### ISSUE TITLE
useSetAtom doc search can't find description

### ISSUE THREAD

**Issue by AjaxSolutions** [pmndrs/jotai#1019]
When I search `useSetAtom`, no doc page is found.  Searching `useAtomValue` finds a doc page.

**Comment by dai-shi** [comment]
We are still working on docs.
Meanwhile, please see `useUpdateAtom` doc. `useSetAtom` from `jotai` and `useUpdateAtom` from `jotai/utils` is 100% the same.

**Comment by dai-shi** [comment]
> see `useUpdateAtom` doc

which has almost nothing...

**Comment by Aslemammad** [comment]
@sajad-sharhani This can also be a good take for you!

**Comment by Nsttt** [comment]
Hello! Writing this at the moment. What should I add as a `Ref:` link ?

**Comment by dai-shi** [comment]
Thanks for your help! I don't think `Ref:` is necessary in this case.

**Comment by Nsttt** [comment]
Just made a PR. If anything else is needed ping me. 

Pretty much one of my firsts PRs. 😄
