### ISSUE TITLE
Documentation : Dark Mode for Docs?

### ISSUE THREAD

**Issue by ajstrand** [pmndrs/jotai#1026]
Is someone already working on something like this?

I'd be happy to work on a basic PR if no one currently is.

**Comment by dai-shi** [comment]
@sandren what's your plan?

**Comment by sandren** [comment]
> Is someone already working on something like this?
> 
> I'd be happy to work on a basic PR if no one currently is.

Dark mode for the website/docs is already a work-in-progress. Thank you for the offer though, @ajstrand! 🙂

**Comment by sandren** [comment]
@ajstrand [Dark mode](https://github.com/pmndrs/jotai/pull/1048) has been merged. 🙂
