### ISSUE TITLE
How to use provider and useContext in jatai?

### ISSUE THREAD

**Issue by hxse** [pmndrs/jotai#1033]
I didn't find any examples in the documentation.
Any examples?

**Comment by hxse** [comment]
Use it like the normal React program? Nothing special? Sorry, I am too new.

**Comment by DennisSmolek** [comment]
Hey @hxse A good place to start is the main web-page: https://jotai.org/
If you go to this projects main page readme you'll see two demo links: [Demo 1](https://codesandbox.io/s/jotai-demo-47wvh) and [Demo 2](https://codesandbox.io/s/jotai-demo-forked-x2g5d)

Those go to a site called [CodeSandBox](https://codesandbox.io/) (CSB for Short) which will show you a live example. 

There is also the [examples folder](https://github.com/pmndrs/jotai/tree/main/examples) `/examples` right on the main page

A cool trick with codesandbox is if you change the website address:
 "https://github.com" to "https://githubbox.com" **(NOTE THE ADDITION OF THE WORD "box")**

So the URL to the todo demo: https://github.com/pmndrs/jotai/tree/main/examples/todos
Becomes: &emsp; &emsp;  &emsp;  &emsp;  &emsp;  &emsp;&emsp;   &ensp;https://githubbox.com/pmndrs/jotai/tree/main/examples/todos

That will AUTOMATICALLY create a sandbox for you running that page as an example.

Another cool thing you can do, is go to the [Codesandbox.io search page](https://codesandbox.io/search): https://codesandbox.io/search

And on the sidebar is many options, the one I like the most is **"Dependencies"** By typing **"Jotai"** [and checking it you get This Page](https://codesandbox.io/search?refinementList%5Bnpm_dependencies.dependency%5D%5B0%5D=jotai&page=1&configure%5BhitsPerPage%5D=12)

Which has almost 10,000 public projects sorted by popularity that you can view **(AND FORK)** absolutely for free.

What I do, is open a bunch in new tabs, then go into them and hit the "Fork" button. If you cant see it in the top right, click the github logo in the left sidebar and there should be a fork this button. 

An even easier way to fork a project is to type in the editor, even a comment, and hit "Save" either with Cmd+s, or the toolbar. 

CodeSandBox(CSB) is easy to connect with your github account too and again, is totally free. 

Spend some time with those resources, if you still have issues, come to the discord: https://discord.com/invite/poimandres

Where you can talk directly with other users as well as the main dev team folks.

**Comment by hxse** [comment]
Thank you very much, I will try it.
