### ISSUE TITLE
Atoms created via atomWithReset do not have debugLabel by default

### ISSUE THREAD

**Issue by jeannnemelanie** [pmndrs/jotai#1038]
Hi community 👋 

I setup my project with `useAtomsDevtools()` and `jotai/babel/preset` as describe [here](https://jotai.org/docs/api/devtools) and [here](https://jotai.org/docs/api/babel). 

Everything is working fine. I do not need to specify `debugLabel` for my atoms except for the ones created with `atomWithReset()`. 

See screenshot below, `atom1` is created with `atomWithReset()` and `atom26` with `atom()`.

![screenshot-jotai-dev-tools](https://user-images.githubusercontent.com/10764355/156648021-b92d0f24-f0e3-4097-b6aa-dc0c679d9cf9.png)

**Comment by dai-shi** [comment]
I guess this is just not supported yet. Not just `atomWithReset` but for all `atomWith*` from `jotai/utils`, right?

@Thisen How hard would it be to support them? (We can probably assume the naming convention like `import { atomWithFoo } from 'jotai/utlis'`.)

**Comment by jeannnemelanie** [comment]
I guess, I did not try the others `atomWith*`.

**Comment by Thisen** [comment]
Thanks for the issue! I'll look into it.
