### ISSUE TITLE
Create a setup local environment tutorial

### ISSUE THREAD

**Issue by LuckyPigeon** [pmndrs/jotai#104]
## Description

I've encountered a few error when I setting up at both LINUX & Windows environment. 

The reason of my linux environment is I use `npm install` instead `yarn install`, while windows couldn't execute the command like `mv`, `cp` and `rm`

To avoid other new-to-jotai contributor and users who want to build jotai at their local environment, I suggest we update a setup tutorial at the bottom of README.md, and create a simple script to classify user's environment and assign appropriate query to execute.

I've already create the os classify script and the tutorial at my local environment, and I hope I can send these files as a Pull Request.
 
## Step to Reproduce

```shell=bash
git clone https://github.com/pmndrs/jotai.git
cd ./jotai
npm install
```

**Comment by dai-shi** [comment]
Thanks for raising this up.
How about using https://github.com/shelljs/shx ?

**Comment by LuckyPigeon** [comment]
@dai-shi 
It works! Could I send the PR for this? Just update the copy command in package.json from `mv` to `shx mv`, `rm` to `shx rm` and `cp` to `shx cp`.

**Comment by dai-shi** [comment]
Sure, please!
Could you try if `shx rm -rf` can replace `rimraf`? Then, we can remove it.

**Comment by LuckyPigeon** [comment]
@dai-shi 
After I tried, `shx rm -rf` is equivalent to `rimraf`

**Comment by dai-shi** [comment]
Nice. Would you replace it and remove it in the PR?
