### ISSUE TITLE
[docs] refactor docs

### ISSUE THREAD

**Issue by LuckyPigeon** [pmndrs/jotai#1041]
Docs current have different typesetting with different pages. It will increase a lot of reading experience if we set a typesetting, 
I think the typesetting of [freezeAtom](https://jotai.org/docs/utils/freeze-atom) would be nice, we can start by refactor `utils` typesetting.

**Comment by dai-shi** [comment]
@sandren is working on refactoring docs. Let's see what we can do after some progress.

**Comment by sandren** [comment]
> @sandren Need some help on this?

@TwistedMinda I'm currently working on writing a new introduction doc and reorganizing the utils section. If you would like to continue copyediting some of the other docs, that would be really helpful. Thanks! 🙂

**Comment by TwistedMinda** [comment]
@sandren No prob'

**Comment by TwistedMinda** [comment]
@sandren Just for you to know, we're gonna add `loadable` util very soon to the utils page. Maybe that changes something in your rework of utils page :p

**Comment by TwistedMinda** [comment]
@sandren What's the state of this issue? The issue here is mostly about code blocks typings.
Now that you did set up the Table of contents, I think it can be a good time to clear that up.

- when there is a component
   - if typescript matters in the example : use "tsx"
   - if typescript doesn't really matter: use "jsx"
- when there is no component
  - if typescript matters in the example: use "ts"
  - if typescript matters in the example: use "js"

I understood the issue correctly, right?
I can make a deep check of all pages if you confirm ;)

**Comment by dai-shi** [comment]
Is the OP about providing code snippet in TS?
Your pattern seem to be about how to write markdowns, which is the same pattern of mine.

**Comment by TwistedMinda** [comment]
@dai-shi OP "typechecking" means the codesandbox at the end of the doc in freezeAtom? I'm confused

**Comment by TwistedMinda** [comment]
@sandren @dai-shi Let's break down the possibilities:
a) Make sure all markdown are using the correct typing depending on the context
b) Make sure all markdown are "tsx"
c) Make sure all pages contain a CodeSandBox at the end to demonstrate

What do you think we have to do for this issue?
Seems like a simple issue but we just need to understand each other :p!

**Comment by dai-shi** [comment]
> we just need to understand each other

well said.

While I don't understand what OP suggests, I think we should do a) for this issue, and close it once done.

**Comment by TwistedMinda** [comment]
@dai-shi Good. I'll do it then

**Comment by TwistedMinda** [comment]
Closing it in favor of the PR.

**Comment by dai-shi** [comment]
Notes to anyone, feel free to open new issues for b), c) and possibly others about improving docs.
