### ISSUE TITLE
[website] redirect to hash tag link after search

### ISSUE THREAD

**Issue by LuckyPigeon** [pmndrs/jotai#1043]
At current website, we can only go to the link after search, and scroll down to the keyword page by our own.
I think it would be convenience if we add hash tag redirect link.
Such as, `https://jotai.org/docs/advanced-recipes/large-objects#focus-atom`, if we search the tag `Focus Atom` of `Large Object`

**Comment by sandren** [comment]
This highlights an important issue. I think we should include both individual sections as well as entire pages in search results to help users get to the right place. Thanks for the suggestion, @LuckyPigeon.
