### ISSUE TITLE
[testing] Can we seed atoms with a value for tests?

### ISSUE THREAD

**Issue by hellos3b** [pmndrs/jotai#1052]
I've looked at the [Testing Documentation](https://github.com/pmndrs/jotai/blob/main/docs/guides/testing.mdx) and completely understand the idea of testing components and not implementation. But I think more often than not we will want to test component  functionality when it has some state

For example in the Counter sample from the docs, imagine if the counter maxes out at 99. Is there a way to inject a `countAtom` that's set to 99, so you can test that clicking the button doesn't change the text?

In a more realistic example, testing a filtered todo list component who's todos are stored in a centralized atom that's initialized from a separate component. We'd need to prefill that atom with a list of todos in order to see that toggling filters are applied correctly, otherwise the component would just be an empty list.

Are there any utils or recommended practices to fill some atoms with data before rendering components?

**Comment by dai-shi** [comment]
Provider's `initialValues` prop is designed for such test cases.
The testing guide docs should include that use case.

**Comment by Aslemammad** [comment]
Hey @Sajad-Sharhani, This may be a good take for you! It'd give you an overview of `initialValues` in providers

**Comment by TwistedMinda** [comment]
Closing this in favor of the PR.
