### ISSUE TITLE
Derived atom getting stuck in suspense when initial value is a Promise that does not resolve

### ISSUE THREAD

**Issue by carlos-marchal** [pmndrs/jotai#1054]
We are starting to use jotai for state management on an existing codebase. One pattern we currently use for data loading is to have a state be null when loading, and hold the data when loaded. So we check if `state === null` to display loading components, and display the data itself (`state`) if the state is not null.

With jotai, we want to start using suspense, so what we do in these cases is as follows:
1. Use an atom to store the original nullable state
1. Derive a read only atom from the step 1 atom, where we return the data if not null, or a promise that never resolves otherwise (`new Promise(() => {})`). 

This makes any component reading the value of atom 2 suspend while the value of the atom 1 is null, and render the data when there atom 1 is not null. So far so good. But the issue appears when the initial state for atom 1 is null, then even after changing it to some other value any component rendering atom 2 remains suspended, and the read function of the atom 2 is not executed.

This sandbox shows the issue: https://codesandbox.io/s/keen-snowflake-cy88ek?file=/src/App.js. Try changing the `INITIAL_VALUE` between a number or null, and see the difference in behavior when fetching new values.

I suspect there must be something that changes with how suspend and jotai interact, depending on whether the component that used the atom has been able to render at least once or is suspended before the first render. I don't really know what the proper expected behavior would be here, as I am not an expert on suspense or jotai, I'm afraid I can't provide more information.

**Comment by dai-shi** [comment]
The infinite promise `new Promise(() => {})` is really hard to deal with. We do support some cases (with tricky implementation), but this one is not covered.
It would be nice if this can be supported, but I'm not sure if it's possible/how easy at this point.

On the other hand, I don't think this pattern will be common (or recommended) as the use case of Suspense. We don't know yet. Will see.

**Comment by carlos-marchal** [comment]
Sounds good, thanks for the response. I've been taking a look at jotai's implementation of SuspensePromise, and even though it's quite elegant, I can see how you'd run into dangerous edge cases.

As I said, I'm not an expert on jotai or suspense, so maybe I'm taking the wrong approach. But can I ask, in your opinion, how you would handle a case such as mine? Refactoring the whole fetching library would be just too much work right now, and I can't find any other incremental approach to handle my use case with suspense.

**Comment by dai-shi** [comment]
I think the original `state` should return (or throw) a promise, because that's where we know when it becomes non-null. If we have a solution with useState, then we might be able to model it in jotai. Otherwise, maybe it doesn't fit well with Suspense. After all, the point of Suspense is to avoid `=== null` check.

**Comment by dai-shi** [comment]
> This sandbox shows the issue: https://codesandbox.io/s/keen-snowflake-cy88ek?file=/src/App.js. Try changing the `INITIAL_VALUE` between a number or null, and see the difference in behavior when fetching new values.

Did you modify the sandbox? I was going to look into this issue, but I don't remember if this is what I saw before.

**Comment by carlos-marchal** [comment]
Oops, you are right, I modified the sandbox to run some different tests with another issue. It has now been restored to the original sandbox and I will leave it like that for future reference.

You were right by the way, it was an issue with our approach. We actually had two different scenarios, one where we were waiting for the user to select what ID to load, and one where we were waiting for the associated data to load. Both were represented by a null data value without suspense.

Now we have a synchronous ID atom that tracks what data the user has selected to load, or null if they haven't yet done it (handle first scenario). Then in case they have selected it, we generate and query an async atom for data fetching using the ID atom and an atom family that takes the selected ID as its parameter, and use suspense for that (handle second scenario). This allows child components to access a data value that will never be null.

We have found that switching to suspense and error boundaries requires a change of mental paradigm and many times will not map 1 to 1 with existing implementations. Your library has been great and allowed us to simplify and reason more cleanly about data flow, so thank you!

The original issue of atoms getting stuck in suspense when on their first render they return a promise that never resolves still persists though. It can be seen in the sandbox. As we have found a cleaner way around that, I leave it up to you to decide what to do with the issue and what other use cases it might / might not support.

**Comment by dai-shi** [comment]
Thanks for restoring it.
Hmm, I think this is something nice if we can support it.
Let me see if there's a reasonable way.

**Comment by dai-shi** [comment]
It was fairly reasonable.
Please check the fixed behavior: https://codesandbox.io/s/nervous-fermi-j89jhw

**Comment by dai-shi** [comment]
We will revert #1089 with #1118, meaning this pattern is not technically possible.

@riemonyamada suggested a workaround. See: https://github.com/pmndrs/jotai/issues/1114#issuecomment-1109059418
