### ISSUE TITLE
can't modify atom in a loop, can't access newest state without re-render

### ISSUE THREAD

**Issue by likon416** [pmndrs/jotai#1064]
If we have an atom and we want to for example do something like
const [myAtom, setMyAtom] = atom(defaultValue);

for(let i=0; i < 10; i++) {
setMyAtom(myAtom + 1);
}

It will not increase the atom's number by 10 but by 1. Because on write, atom refreshes, the next loop iteration, doesn't see the new atom state (because component didn't re-render yet with new atom value).

I know you can write the code differently and just do setAtom(myAtom + 10) but this prevent us from writing code like
removeItemFromList();
addItemFromList();

Because removing and adding would use setMyAtom inside and they are executed one after another, just one operation will be written(because between executing those methods, component didn't re-render). This really limits how we can write the code, it's not flexible. You can do such operations in Redux but not in atoms.

Atom should always see the newest state, regardless of how many times we will do write on it, it can always notify to refresh with some delay if needed.
Atom should always have 1 singleton instance so whenever you will do write or read it always has the newest state.
Atom newest state should always be accessible without need to re-render. Re-render should be just for notifying that state changed.
Is it currently possible to achieve the above?

Thanks :)

**Comment by Aslemammad** [comment]
Updating in general, in react, is not synchronous, it means!
```ts
setCount(count + 1)
setCount(count + 1)
setCount(count + 1)
```
won't make your `count` equal to 3!
for updating values, react needs to re-render (re-runs the component), so you can access the new value!

This is a general concept with react, and not with jotai or any other state management library!


https://reactjs.org/docs/faq-state.html#what-does-setstate-do reading this will help you so much! 

Thank you for using jotai!

**Comment by likon416** [comment]
@Aslemammad thanks for getting back to me. You can do that with redux store. Since it is also global state management, I would expect same with atom.

**Comment by Aslemammad** [comment]
I'm not familiar with redux, but I think you mean a different case, could you share the code you mean?

**Comment by likon416** [comment]
I dont have a code to share. Just want to be able to do chained operation on the state without needing it to be rerendered.

**Comment by likon416** [comment]
it doesn't need to be state, I just need global variable like atom, which doesn't need rerender

**Comment by Aslemammad** [comment]
It's not possible (doing such in a component) in jotai! one way is possible, and it is to write to an atom externally, which we do not have plans for it!

**Comment by likon416** [comment]
@Aslemammad ok, so can I somehow use atom for situation like described in ticket #1065

**Comment by Aslemammad** [comment]
Sure!

**Comment by Aslemammad** [comment]
Since this is how reactjs works and we cannot change it! let's close it!
