### ISSUE TITLE
not able to sync atom without re-render, or not be able to access always the newest state

### ISSUE THREAD

**Issue by likon416** [pmndrs/jotai#1065]
Hello,

I have a problem syncing an atom state across my app.

I want to use atoms inside a callback function beyond react component. I'm using react native with IAP plugin where there is a function setPurchaseListener that is initialized at the start of the app.

The problem is once this listener will get fired (after an IAP purchase) it has the OLD state of an atom. So I can't pass updated data there. Because this is not a react component and it does not re-render to update the atom so the state of the atom is old.

How I can:

Be able to sync state with all same atom instances regardless of re-rendering
Be able to grab manually the newest state even if atom was not refreshed/re-rendered
Would be good that whenever I'm reading atom it always have the newest state regardless of re-rendering.

How I can achieve any of the above?

Thanks :)

**Comment by Aslemammad** [comment]
Hey Likon!
I don't know if I understand your use case, but for syncing, you can use `atomWithStorage`, in react native! and see if it's enough for you!

**Comment by Aslemammad** [comment]
syncing without re-render is not possible at least in the way you mean, you may want to check out SolidJS!
A component needs to re-render so it can access the new value!
