### ISSUE TITLE
[atomWithQuery | atomWithInfiniteQuery]: return all react query state.

### ISSUE THREAD

**Issue by sondh0127** [pmndrs/jotai#1068]
Currently query atom only return the {data} from useQuery hooks.
It would be better to return all other states as well. 
![image](https://user-images.githubusercontent.com/62163604/159172388-32fc3f28-5423-4926-8220-24d9bb9122c4.png)
https://react-query.tanstack.com/reference/useQuery

**Comment by dai-shi** [comment]
Hi, thanks for the suggestion.
The point of `jotai/query` is to make RQ as jotai atoms, and jotai atoms are based on Suspense for async operations.
That means, we shouldn't return loading/pending states with properties, and not for errors which are handled with ErrorBoundary. Also, actions are for `write` function, and we can `refetch`.
That will leave only a few properties out of listed ones, and I would rather like to hear some real use cases, because some of them are already covered by jotai methods.

Hope it makes sense!

**Comment by sondh0127** [comment]
Thank you for your explanation. @dai-shi 
I'm facing a real use-case here with atomWithInfiniteQuery, that I need to get `hasNextPage` to display loadmore button.
```ts
infiniteMetaData.onMount = (update) => {
	  setInfiniteData = update
	  if (options.enabled !== false) {
	    return observer.subscribe(listener2)
	  }
}
```
I tried to add second atom and listen to the same observer of infiniteData does. and return it from wrapper atom.

```ts
const queryAtom = atom<
    { data: InfiniteData<TData | TQueryData> | undefined } & InfiniteMetaData,
    AtomWithInfiniteQueryAction<TQueryFnData>
  >(
    (get) => {
      const { dataAtom, infiniteMetaData } = get(queryDataAtom)
      return { data: get(dataAtom), ...get(infiniteMetaData) }
    },
    (_get, set, action) => set(queryDataAtom, action) // delegate action
  )
```
It's work but I still got some trouble with nextjs ssr. 
I would like to ask the author (you) for an official solution

**Comment by sondh0127** [comment]
> Thank you for your explanation. @dai-shi I'm facing a real use-case here with atomWithInfiniteQuery, that I need to get `hasNextPage` to display loadmore button.
> 
> ```ts
> infiniteMetaData.onMount = (update) => {
> 	  setInfiniteData = update
> 	  if (options.enabled !== false) {
> 	    return observer.subscribe(listener2)
> 	  }
> }
> ```
> 
> I tried to add second atom and listen to the same observer of infiniteData does. and return it from wrapper atom.
> 
> ```ts
> const queryAtom = atom<
>     { data: InfiniteData<TData | TQueryData> | undefined } & InfiniteMetaData,
>     AtomWithInfiniteQueryAction<TQueryFnData>
>   >(
>     (get) => {
>       const { dataAtom, infiniteMetaData } = get(queryDataAtom)
>       return { data: get(dataAtom), ...get(infiniteMetaData) }
>     },
>     (_get, set, action) => set(queryDataAtom, action) // delegate action
>   )
> ```
> 
> It's work but I still got some trouble with nextjs ssr. I would like to ask the author (you) for an official solution

here is my the listener

```ts
const infiniteMetaData = atom<InfiniteMetaData>({})

  let setInfiniteData: (data: InfiniteMetaData) => void = () => {
    throw new Error('atomWithInfiniteQuery: setting infinite data without mount')
  }

  const listener2 = (result: InfiniteQueryObserverResult<TData, TError>) => {
    if (result.error && !isCancelledError(result.error)) {
      setInfiniteData({ hasNextPage: false })
      return
    }
    if (result.data === undefined) {
      return
    }
    setInfiniteData({ hasNextPage: result.hasNextPage })
  }
```

**Comment by dai-shi** [comment]
Okay, `hasNextPage` in atomWithInfiniteQuery sounds somewhat valid. I understand your use case.
Our current atom data type is `InfiniteData<TData>`, and it's from RQ types. Hm, it would be nice if the type includes `hasNextPage`. It's unfortunate that only `InfiniteQueryObserverBaseResult` has it.

@aulneau Do you have any ideas for this?

**Comment by aulneau** [comment]
Yeah, this is all important data to use. Part of why I started working on [jotai-query-toolkit](https://github.com/fungible-systems/jotai-query-toolkit). 

Here is an example hook I made to gain access to some of the data: https://github.com/fungible-systems/jotai-query-toolkit/blob/main/src/hooks/use-infinite-query-atom.ts

and an example atom that gets some of the status of a given query atom: https://github.com/fungible-systems/jotai-query-toolkit/blob/main/src/atoms/react-query/query-key-status-atom.ts

I would recommend making use of the `QueryObserver` that react-query exports to make use of some of these features. Happy to add more docs to jotai-query-toolkit if there is interest in it.

**Comment by dai-shi** [comment]
Thanks for the idea! Having a new separate atom for such status sounds reasonable.

```ts
type InfiniteQueryStatus = {
  isFetchingPreviousPage: boolean
  isFetchingNextPage: boolean
  hasNextPage: boolean
  hasPreviousPage: boolean
}
export function atomWithInfiniteQueryStatus(queryKey: QueryKey): Atom<InfiniteQueryStatus>

**Comment by dai-shi** [comment]
@Aslemammad 's work #1402 revealed that my idea doesn't work, as we can't get an observer from a query key.

My current idea is to export two atoms.
```js
export function atomWithInfiniteQueryObserver(createQuery, getClient) {
  ...
}
export function atomWithInfiniteQuery(createQury, getClient) {
  const baseAtom = atomWithInfiniteQueryObserver(createQuery, getClient)
  return atom(
    (get) => ...,
    (get, set, action) => ...
  )
}
// Hmm, the implementation will be pretty tricky to support Suspense.
```
But, let's wait for a moment. We want to consider this from various aspects.
