### ISSUE TITLE
Write tests for immutableMap

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#107]
immutableMap is an internal module. It's an abstract module.
I wonder if anyone would be interested in writing tests for it.
Note that we want to test the api, not the implementation (the type `ImmutableMap` is representing implementation), because the goal is to come up with better implementation with same functionality.

**Comment by Aslemammad** [comment]
@dai-shi What we should do? Could you explain more? or what we need to learn?

**Comment by dai-shi** [comment]
> What we should do?

It is going to be something like this:

- Read ./src/core/immutableMap.ts
- Ask questions if something is not clear
- Create ./tests/core/immutableMap.test.ts
- Send a PR and discuss

> Could you explain more?

Jotai uses a single provider component to store all atom states (values) in its component tree.
It is important that the provider works with good performance, because it can be a bottleneck.
One of the challenges is immutable map. It's something like `Map` but has to be updated immutably for React Concurrent Mode.
So, I abstract out that part in the file and created a naive (but should work fairly well) implementation.
We'd like to know if we can handle thousands or millions of atoms.

> or what we need to learn?

If you are not familiar with the standard `Map`. Check some docs:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

Learning about testing & benchmarking in general should also help.

**Comment by Aslemammad** [comment]
@dai-shi I appreciate this, thanks.

**Comment by dominictwlee** [comment]
@Aslemammad Are you still working on this?

**Comment by Aslemammad** [comment]
@dominictwlee Hey, yes I'm working on it.

**Comment by dominictwlee** [comment]
Cool, I'll have a look at it.

**Comment by Aslemammad** [comment]
if u need any help, tell me, I'd love to work on it.

**Comment by dominictwlee** [comment]
@dai-shi So given that the api for immutableMap methods are dependent on the implementation detail of receiving an immutable map type, I'm not entirely sure we can avoid writing tests that avoid its implementation details.

Could you clarify what you had in mind for this? Thanks!

**Comment by dai-shi** [comment]
@dominictwlee Glad you start investigating it.
So, the background of this work is to improve performance.
If we have many atoms, our immutableMap becomes big which can cause bad performance of the entire library.

Originally, the code is embedded in Provider.ts, but as we move it to immutableMap.ts,
we can compare different implementations.
To compare different implementations, we need to test it (this issue) and measure peformance (#108).

As an example, the original implementation of immutable map is just a map which is copied on set.

```js
const mCreate = () => new Map()
const mGet = (m, k) => m.get(k)
const mSet = (m, k, v) => new Map(m).set(k, v)
...
```

I still wonder if this is fairly performant.

So, the test would be something like this.
```js
m1 = mCreate()
m2 = mSet(m1, 1, 'a')
mGet(m2, 1) === 'a'
mGet(m1, 1) === undefined // or == null? or !== 'a'
m1 !== m2
m3 = mSet(m2, 1, 'b')
mGet(m2, 1) === 'a'
...
```

Does it clarify the idea?

**Comment by dominictwlee** [comment]
> @dominictwlee Glad you start investigating it.
> So, the background of this work is to improve performance.
> If we have many atoms, our immutableMap becomes big which can cause bad performance of the entire library.
> 
> Originally, the code is embedded in Provider.ts, but as we move it to immutableMap.ts,
> we can compare different implementations.
> To compare different implementations, we need to test it (this issue) and measure peformance (#108).
> 
> As an example, the original implementation of immutable map is just a map which is copied on set.
> 
> ```js
> const mCreate = () => new Map()
> const mGet = (m, k) => m.get(k)
> const mSet = (m, k, v) => new Map(m).set(k, v)
> ...
> ```
> 
> I still wonder if this is fairly performant.
> 
> So, the test would be something like this.
> 
> ```js
> m1 = mCreate()
> m2 = mSet(m1, 1, 'a')
> mGet(m2, 1) === 'a'
> mGet(m1, 1) === undefined // or == null? or !== 'a'
> m1 !== m2
> m3 = mSet(m2, 1, 'b')
> mGet(m2, 1) === 'a'
> ...
> ```
> 
> Does it clarify the idea?

Yep makes sense, looks similar to some of the test cases I drafted out. K I know where to take this from here.
