### ISSUE TITLE
Does jotai also adopt the flux architecture idea?

### ISSUE THREAD

**Issue by PachVerb** [pmndrs/jotai#1072]

**Comment by dai-shi** [comment]
Does this help? https://twitter.com/dai_shi/status/1477593623156105217

**Comment by PachVerb** [comment]
> Does this help? https://twitter.com/dai_shi/status/1477593623156105217

Yes, that's a good example, thanks. Can be used as the basis for applying flux. But sometimes, as the initial involvement of the application, I always get confused whether to use flux.
