### ISSUE TITLE
Benchmark immutableMap (create a benchmark tool)

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#108]
After #107, or in parallel with it, we would want to create a benchmark tool for immutableMap.
It would allow us to evaluate the current implementation, compare possible alternative implementations, and improve the entire performance of jotai.

Anybody keen about performance?

**Comment by dai-shi** [comment]
btw, benchmarking of jotai itself would also be interesting and important.

**Comment by Aslemammad** [comment]
@dai-shi  How we write it? and what to learn? suggestions? ...

**Comment by dai-shi** [comment]
First of all, this is not a trivial issue. It requires some general knowledge for benchmarking and understanding how it would be used in jotai (we need to design benchmark scenario.) I don't have a full answer.

That said, if I were to do this, I'd use [benchmark](https://www.npmjs.com/package/benchmark) and start with a simple scenario.

You might want to start with #107 before working on benchmarking.

**Comment by Aslemammad** [comment]
Got it, I'm just learning and I love challenges. Thanks.

**Comment by dai-shi** [comment]
New implementation might be based on different abstractions. Closing this for now.
