### ISSUE TITLE
deno.land/x module is not working

### ISSUE THREAD

**Issue by TomokiMiyauci** [pmndrs/jotai#1081]
Deno asks for import extensions, so [deno.land/x/jotai](https://deno.land/x/jotai) will not work unless import maps are used.

Module for Deno from the Node.js code base is a bit of a challenge, but [denoify](https://github.com/garronej/denoify) is a good reference.

**Comment by dai-shi** [comment]
Hi, thanks for reporting. Our hope was it works with no changes, so it's unfortunate.
I assume, lately, Deno tries to increase Node.js compatibility and users will be able to use NPM, hopefully eventually?

**Comment by TomokiMiyauci** [comment]
> Deno tries to increase Node.js compatibility and users will be able to use NPM, hopefully eventually?

Yes. But deno 1.20.4 currently limited to CommonJS.

As for compat, perhaps the most practical is to use the [esm.sh](https://esm.sh/) registry.

In fact, https://esm.sh/jotai@1.6.1?pin=v74 seems to do module resolution correctly. 
(Unfortunately, `process` converts to [std/node](https://deno.land/std@0.133.0/node/_process/process.ts) , so it won't work in the browser as is, but that's another issue...)

I think the deno.land/x module should be "Deno native", what do you think?

**Comment by dai-shi** [comment]
Well, I think we should consider taking down from deno.land/x. I don't think it works without building now because our source code use `__DEV__` internally. Or, do you have any idea? I looked at denoify, but feels too much for us. (Would be nice if it works outside this repo.)

**Comment by TomokiMiyauci** [comment]
> our source code use `__DEV__` internally.

You can deploy to deno.land/x with a Subdirectory specified. 
Not sure how to change the current deno.land/x/jotai configuration though...

<img width="1740" alt="スクリーンショット 2022-04-04 12 56 31" src="https://user-images.githubusercontent.com/46842642/161473695-615b259e-2014-4aaa-a995-0abed25219ba.png">


That is, by building the module for deno, you can deploy to that directory only. (But you will need to include it in git.)

> I looked at denoify, but feels too much for us.(Would be nice if it works outside this repo.)

Sure. With jotai's codebase, there are probably two things you need to do:

- Add file extensions to the import path
- Universalization of `process`

If this is all that is needed, rollup may be able to handle this.

**Comment by dai-shi** [comment]
> * Add file extensions to the import path

Yeah, that should be possible if we configure rollup to remove them.

> * Universalization of `process`

We no longer have `process` except for one place which is inside try-catch.

> If this is all that is needed, rollup may be able to handle this.

But, we are not sure if these are everything?

**Comment by TwistedMinda** [comment]
@dai-shi I totally agree with your 2 points:
- denoify is a bit too much for jotai
- deno could improve node-compatibility for better adoption, and jotai being a fairly light library could easily benefit from it

I would also add that, now and for a good time still, deno will be used on back-end. Whereas in the opposite, jotai is meant to be used with react...

In overall I think it's a bit early to worry about this. I would vote to close instead of "on hold" for now ;)
What do you think?

**Comment by dai-shi** [comment]
> * Add file extensions to the import path

> If this is all that is needed, rollup may be able to handle this.

Hi @TomokiMiyauci , do you actually know how to configure rollup? We would like to remove file extensions from import/export path on build, right?

**Comment by TomokiMiyauci** [comment]
@dai-shi It seems that you can change it with `resolveId`. https://rollupjs.org/plugin-development/#resolveid

**Comment by dai-shi** [comment]
> It seems that you can change it with `resolveId`. https://rollupjs.org/plugin-development/#resolveid

Thanks for the hint! I went and tried it. But then noticed, my problem is different. It's about TypeScript only. So, the workaround is a patch script...
See: https://github.com/pmndrs/valtio/pull/644
Also: https://github.com/pmndrs/valtio/pull/643
If both are applied, I think it's Deno compatible. What do you think?
(ah, as for valtio, import maps will be required for `proxy-compare`.)

If it works as expected, we apply the same change to jotai and zustand.

**Comment by TomokiMiyauci** [comment]
@dai-shi 
For compatibility with Deno, the following items must be satisfied.

- The module specifier of a relative path must basically have an extension. (Strictly speaking, import map can also be used.)
- Modules must be `js`, `ts`, `jsx`, `tsx`, `json`(import assertions) only
- URI schemes are `file`, `http`, `https`, `data`, `npm`, `node`
- No `process`.

Also, import map is supported, so all specifiers can be overridden.

Deno now supports the new `node` scheme. So if you are using node.js built-in modules, both environments can be supported seamlessly. eg. `node:fs`.

It would be really nice to add an extension to specifier in anticipation of TypeScript 5.0.

> If both are applied, I think it's Deno compatible. What do you think? (ah, as for valtio, import maps will be required for `proxy-compare`.)

It probably won't be a problem, but please make sure it meets the section above.

**Comment by JacobWeisenburger** [comment]
How are we supposed to use Jotai with Deno? Is there something in the docs to explain it? I can't find anything and it doesn't seem to just work out of the box.

```ts
import { atom } from 'https://deno.land/x/jotai@v2.0.3/src/index.ts'
//       ^^^^
// Module '"https://deno.land/x/jotai@v2.0.3/src/index.ts"' has no exported member 'atom'.
```

```
error: Uncaught TypeError: Module not found "https://deno.land/x/jotai@v2.0.3/src/vanilla".
    at https://deno.land/x/jotai@v2.0.3/src/index.ts:1:15
  await import(entrypoint);
  ^
    at async dev (https://deno.land/x/fresh@1.1.4/src/dev/mod.ts:187:3)
```

**Comment by dai-shi** [comment]
My hope is #1742 and #1823 will fix deno support.

Does deno.land allow specifying the git commit??

**Comment by dai-shi** [comment]
#1742 and #1823 are merged. Hope it works. If there's still an issue, please open a new discussion.

**Comment by JacobWeisenburger** [comment]
> #1742 and #1823 are merged. Hope it works. If there's still an issue, please open a new discussion.

https://github.com/pmndrs/jotai/issues/1874

**Comment by dai-shi** [comment]
#2040
