### ISSUE TITLE
atomWithStorage seems to be broken with 1.6.2

### ISSUE THREAD

**Issue by gunters63** [pmndrs/jotai#1086]
I updated Jotai to 1.6.2 just now and I noticed this seems to have broken code in my current project which uses atomWithStorage.

I can't give you a minimal reproduction now (might later). All I can say now that I have several useAtoms() of atomWithStorage in different React components and suddenly at least one started to return the local storage value of a completely different key. 

I reverted to 1.6.1 and everything is working fine.

**Comment by dai-shi** [comment]
Thanks for reporting, and sorry for the regression.
#1080 is the related PR.
I hope you help creating a test for your use case, and let's find a solution.
We can consider reverting #1080 if that makes sense.

**Comment by gunters63** [comment]
I had some problems writing a test to reproduce the problem. I even thought for a while this was a bogus bug report because I could not reproduce the problem anymore. Now the problem resurfaced and it seems it happens when you try to get a non-existing item from local storage (after previously successfully retrieving one with a different key). Somehow this will (sometimes) return the cached lastValue.
From looking at the current source (createJSONStorage) I still don't know how this can happen, though. Which makes writing a test case difficult :).

**Comment by dai-shi** [comment]
> Somehow this will (sometimes) return the cached lastValue.

Sounds interesting. Does this only happen in v1.6.2 and not in v1.6.1?

**Comment by Dreamacro** [comment]
@dai-shi 

a demo broken on 1.6.2 https://codesandbox.io/s/jotai-1-6-2-broken-1ku45o

**Comment by gunters63** [comment]
Interesting. So getting atomWithStorage with a non-existing key does not work except when some previous get on an existing key seeded lastValue (which then results the wrong result of course)

**Comment by gunters63** [comment]
> > Somehow this will (sometimes) return the cached lastValue.
> 
> Sounds interesting. Does this only happen in v1.6.2 and not in v1.6.1?

Yes

**Comment by gunters63** [comment]
I also made some experiments: https://codesandbox.io/s/stoic-jepsen-845wmb?file=/src/App.tsx

With
````
// localStorage.removeItem("foo");
// localStorage.removeItem("bar");
localStorage.setItem("foo", "3");
localStorage.setItem("bar", "4");
````
you get the render output 3 and 4.
Interestingly, the component gets rendered 4 times (console outputs 3 and 4 four times).

With 
````
localStorage.removeItem("foo");
localStorage.removeItem("bar");
// localStorage.setItem("foo", "3");
// localStorage.setItem("bar", "4");
````
you get empty render. The console says 1, undefined two times.

**Comment by Thebarda** [comment]
I have exactly the same issue on my projects. When the key is not defined in the local storage, atomWithStorage returns `undefined` instead of the initial value.

Downgraded to 1.6.1 and it's working fine :)

**Comment by Moshyfawn** [comment]
Same issue with
```json
{
  "jotai": "^1.6.2"
}
```

Reproduction CSB [here](https://codesandbox.io/s/strange-lewin-5no4hx?file=%2Fsrc%2FApp.tsx%3A787-801)

**Comment by dai-shi** [comment]
Thanks guys! I think I finally got how it's happening. Will work on it.

**Comment by dai-shi** [comment]
https://ci.codesandbox.io/status/pmndrs/jotai/pr/1088
Please try this. Look for "Local Install Instructions" ☝️

**Comment by Moshyfawn** [comment]
> https://ci.codesandbox.io/status/pmndrs/jotai/pr/1088 Please try this. Look for "Local Install Instructions" ☝️

Looks like it's working now. Here's [a CSB](https://codesandbox.io/s/strange-lewin-5no4hx?file=%2Fsrc%2FApp.tsx)

**Comment by Thebarda** [comment]
Yep, it works fine on my side
