### ISSUE TITLE
How to start the development of the project

### ISSUE THREAD

**Issue by Aslemammad** [pmndrs/jotai#109]
Hey @dai-shi, I don't have any clue how to start the development of the project, Could you explain how to start the project as watch mode and ... for development, and how to see the result.

**Comment by dai-shi** [comment]
If someone has a suggestion, I'd like to hear too!

For me, if I were to fix a bug, I'd firstly create a failing test. After that, fix code to pass the test. Finally, build the package and install it in an example app to confirm.
If I were to develop a new util, I'd simply do it in codesandbox. 😉

**Comment by Aslemammad** [comment]
Aha, Thanks for the suggestions.

**Comment by Aslemammad** [comment]
Hey @dai-shi, do you have a ready codesandbox for development? (for fork)

**Comment by dai-shi** [comment]
Do you mean an example app to fork? Please check docs/showcase.md.

**Comment by Aslemammad** [comment]
Thanks, I found them.

**Comment by Aslemammad** [comment]
@dai-shi Hey, Sorry for the lateness, these days I can't contribute because of some reasons, I'll continue soon, Sorry.

**Comment by dai-shi** [comment]
Closing this as the original question is answered.
