### ISSUE TITLE
Enhancement optional pretty-printing of JSON for createJSONStorage

### ISSUE THREAD

**Issue by gunters63** [pmndrs/jotai#1092]
I have implemented a custom atom with the help of atomWithStorage and createJSONStorage (AsyncStringStorage) to load and persist configuration values to a backend. Those strings will be held in a simple filesystem backed key/value store,

For troubleshooting people will look into this files in the key/value stores quite often. So it would be nice if the JSON would be pretty-printed. Currently I cloned the code of createJSONStorage (and the types AsyncStorage and AsyncStringStorage) just to replace 

````
JSON.stringify(newValue)
````
with
````
JSON.stringify(newValue, null, 2)
````

in createJSONStorage.setItem but of course an option like prettyPrint for createJSONStorage would be much nicer :).

Alternatively generic serialize and deserialize functions like atomWithHash would also be nice, turning createJSONStorage into a generic createSerializedStorage.

**Comment by dai-shi** [comment]
In such cases, I'd suggest creating your own `createJSONStorage` or creating `AsyncStorage` directly.

`createJSONStorage` is not meant for customization. But, if you like you can override properties after creating.

```js
const storage = createJSONStorage(() => strStorage)
storage.setItem = (key, newValue) => strStorage.setItem(key, JSON.stringify(newValue, null, 2))
```

**Comment by gunters63** [comment]
Yes, thank you. I think I can live with the overridden property :)
