### ISSUE TITLE
Commonize useAtomValue 

### ISSUE THREAD

**Issue by always-awake** [pmndrs/jotai#1093]
In Mono repo project, I want to commonize `useNumber` hook in "common" package and use that `useNumber` hook in "my" package(other package). 

but commonized `useNumber` in common package return initialvalue `null` not 100(expected).
I think there is no Provider in common package, so `useNumber` in common package return default value(null). 

is there anyting solution to solve this problem? 

> we have two node_modules (common/node_modules, my/node_modules), and both node_modules have `jotai`.

```js
// packages/common/atom/number.js
export const numberAtom = atom(null)

// packages/common/hooks/useNumber.js

import { useAtomValue } from 'jotai'
import { numberAtom } from '../atom/number'

export const useNumber= () => {
  const calculated = useAtomValue(numberAtom) // initialvalue: null, expect: 100(calculated value)
  return calculated
}
```

```js

// packages/my/hooks/useNumber.js
import { useAtomValue } from 'jotai'
import { numberAtom } from '../../../common/atom/number'

export const useNumber = () => {
  const calculated = useAtomValue(numberAtom) // initialvalue: null, expect: 100(calculated value)
  return calculated
}

// packages/my/components/App.jsx
import { useNumber as commonPackageHook } from '../../../common/hooks/useNumber'
import { useNumber as myPackageHook  } from '../hooks/useNumber'
...

const Component = () => {
  const commonNumber = commonPackageHook(); 
  console.log(commonNumber); // print: null

  const myNumber =  myPackageHook(); 
  console.log(myNumber); // print: 100
  
  ...
}


const App = () => (
  <ProviderinitialValues={[[numberAtom, 100]]}>
    <Component />
  </Provider>
);
```

**Comment by dai-shi** [comment]
my guess is, in the common package, `numberAtom` points to a different reference. It may be related with your build tools. There would be some solutions, but for example, defining an atom in a separate package may or may not help.

**Comment by always-awake** [comment]
@dai-shi

thank you for your comment.

> It may be related with your build tools.

can you explain it in more detail? I wonder why you think so.. 

> There would be some solutions, but for example, defining an atom in a separate package may or may not help

i already define atom in common package. (example code has been modified..) is this what you're saying?

**Comment by dai-shi** [comment]
> can you explain it in more detail?

Just to make sure, it doesn't cause any issues without monorepo, right? Could you try it?

> I wonder why you think so..

Because I have an experience in valtio about such a behavior. But, it's just a guess. So, please try to reproduce the issue without monorepo to confirm.

**Comment by dai-shi** [comment]
Yes, your guess sounds correct. jotai (as well as valtio) uses module variables (like `ScopeContextMap`), so the library has to be loaded into the memory from the single package. I'm not familiar with how monorepo solves module variable issues.

**Comment by always-awake** [comment]
@dai-shi 

we solved our problem!

The `jotai version` of the common package was different from my package.
so the jotai package was installed in the node_modules of each package. (two ScopeContextMap)

we solved our problem by `setting the jotai version of each package all the same.`

Thank you for your comment.
