### ISSUE TITLE
Error in esbuild build (using remix)

### ISSUE THREAD

**Issue by qhnu** [pmndrs/jotai#1094]
I get an error when starting with the basic template in Remix.

Error: `SyntaxError: Cannot use 'import.meta' outside a module`

The following `import` key seems to be the problem.
[package.json](https://github.com/pmndrs/jotai/blob/b0df01c4eb0a38f783bfb612f4d359db41ca3f8b/package.json#L23)

---

In the past,  the import key was deleted once and reinstated again.

1. [deleted](https://github.com/pmndrs/jotai/pull/359/files)
2. [reinstated](https://github.com/pmndrs/jotai/pull/583)

It seems to have been fine in `swc(next.js)`, but `esbuild` gives me an error.
If possible, would it be possible to delete the import key again?

It is unlikely that the esbuild side behavior can be changed.
[How conditions work](https://esbuild.github.io/api/#how-conditions-work)

---

error process:
1. `npx create-remix@latest` > `deployment targets` > `Cloudflare Workers`
2. add `jotai` code
3. `npm run dev` > `SyntaxError: Cannot use 'import.meta' outside a module`

repo:
[remix-template-cloudflare-workers-with-jotai](https://github.com/qhnu/remix-template-cloudflare-workers-with-jotai)

**Comment by dai-shi** [comment]
It’s important to have import in package.json. When removed, would esbuild use cjs? I don’t think it’s what you want. So, the question is where/who complains import.meta.

**Comment by qhnu** [comment]
It looks like an esbuild priority issue.

- Set esbuild options to `format: 'cjs'`
- If `exports.import` key into package.json of the node_modules package, takes precedence over format option
- As a result, `mjs` syntax is mixed in the `cjs` build

This case was here.
It appears to be a problem on the esbuild side, so we will close it.
Thanks for your reply.

**Comment by acusti** [comment]
@qhnu do you know if there is an existing issue i can follow to see when this will be resolved? for now i had to downgrade/pin  jotai to v1.5.3, but i’d love to know if/when i can eventually upgrade to the latest version of jotai.
