### ISSUE TITLE
[Tips] How to use with immer

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#11]
@gsimone suggested useImmerAtom:

```js
const useImmerAtom = (anAtom) => {
  const [state, setState] = useAtom(anAtom)
  const setStateWithImmer = useCallback((fn) => {
    setState(produce((draft) => fn(draft)))
  }, [setState])
  return [state, setStateWithImmer]
}
```

Or, we could create a writable atom:
```js
const countAtom = atom(0)

const countWithImmerAtom = atom(
  (get) => get(countAtom),
  (get, set, fn) => set(countAtom, produce((draft) => fn(draft)))
)
```

We might be able to create a helper function.
```js
const warpWithImmer = (anAtom) => atom(
  (get) => get(anAtom),
  (get, set, fn) => set(anAtom, produce(get(anAtom), (draft) => fn(draft)))
)
```

**Comment by gauravkumar37** [comment]
TypeScript version for `NonPromise` values:
```ts
const withImmer = <Value extends any>(anAtom: WritableAtom<Value, NonPromise<Value>>) => atom(
  (get) => get(anAtom) as NonPromise<Value>,
  (get, set, fn: (draft: Draft<NonPromise<Value>>) => void) => set(anAtom, produce(get(anAtom) as NonPromise<Value>, draft => fn(draft)))
);

const dataAtomImmer = withImmer(atom({count: {actual: 0, other: true}}));
const [data, setData] = useAtom(dataAtomImmer);
setData(draft => {
  draft.count.actual++;
})
```

**Comment by dai-shi** [comment]
Looks nice! Can you avoid `any`?

**Comment by gauravkumar37** [comment]
When using function syntax, we can just specify `<Value>`.
If present in .ts file, we can specify `<Value>` as well.
But if present in .tsx file, we either need to specify `<Value, >` or `<Value extends `something`>`
So, `<Value, >` works in both .ts and .tsx files, I have edited the code above.

**Comment by dai-shi** [comment]
I see. It was for *.tsx. I sometimes use `<Value extends unknown>`. Didn't know `<Value, >` works. Weird, but nice workaround.

**Comment by dai-shi** [comment]
Since v0.5.0, we have `jotai/utils`. See #35 
I'd like to have both `useImmerAtom` and `withImmer` in "utils".
Would you like to draft a PR?

**Comment by dai-shi** [comment]
Hm, but that requires immer as a (peer) dependency. That's not really acceptable. How can we deal with it?

**Comment by dai-shi** [comment]
We could use `peerDependenciesMeta`, and put immer helpers in `jotai/immer` instead of `jotai/utils`.

**Comment by JLarky** [comment]
Here's ready to go example, it doesn't use `NonPromise` and has an example of using generic type instead of just inferring type from the initial value 

```ts
import produce, { Draft } from "immer";
import { atom, useAtom, WritableAtom } from "jotai";

export const withImmer = <Value,>(anAtom: WritableAtom<Value, Value>) =>
  atom(
    get => get(anAtom),
    (get, set, fn: (draft: Draft<Value>) => void) =>
      set(
        anAtom,
        produce(get(anAtom), draft => fn(draft))
      )
  );

const callbacksAtomImmer = withImmer(atom<{ [id: string]: () => void }>({}));
const [callbacks, setCallbacks] = useAtom(callbacksAtomImmer);
setCallbacks(draft => {
  draft["id"] = () => {};
});
```

**Comment by cbioley** [comment]
> Here's ready to go example, it doesn't use `NonPromise` and has an example of using generic type instead of just inferring type from the initial value
> 
> ```ts
> import produce, { Draft } from "immer";
> import { atom, useAtom, WritableAtom } from "jotai";
> 
> export const withImmer = <Value,>(anAtom: WritableAtom<Value, Value>) =>
>   atom(
>     get => get(anAtom),
>     (get, set, fn: (draft: Draft<Value>) => void) =>
>       set(
>         anAtom,
>         produce(get(anAtom), draft => fn(draft))
>       )
>   );
> 
> const callbacksAtomImmer = withImmer(atom<{ [id: string]: () => void }>({}));
> const [callbacks, setCallbacks] = useAtom(callbacksAtomImmer);
> setCallbacks(draft => {
>   draft["id"] = () => {};
> });
> ```

@JLarky I can't make TS happy. I've got the following error:

```
No overload matches this call.
  Overload 1 of 6, '(read: (get: Getter) => NonPromise<Value>, write: (get: Getter, set: Setter, update: (draft: Draft<Value>) => void) => void | Promise<...>): WritableAtom<...>', gave the following error.
    Type 'Value' is not assignable to type 'NonPromise<Value>'.
  Overload 2 of 6, '(read: never, write: (get: Getter, set: Setter, update: (draft: Draft<Value>) => void) => void | Promise<void>): WritableAtom<(get: Getter) => Value, (draft: Draft<...>) => void>', gave the following error.
    Argument of type '(get: Getter) => Value' is not assignable to parameter of type 'never'.
  Overload 3 of 6, '(read: (get: Getter) => Promise<unknown>, write: (get: Getter, set: Setter, update: (draft: Draft<Value>) => void) => void | Promise<void>): WritableAtom<...>', gave the following error.
    Type 'Value' is not assignable to type 'Promise<unknown>'.
````

(TypeScript 4.0.3, jotai 0.6.2, immer 7.0.9)

**Comment by dai-shi** [comment]
@cbioley Would you try jotai v0.7.2 please?

**Comment by cbioley** [comment]
@dai-shi It works perfectly. Thank you 👍

**Comment by dai-shi** [comment]
Action item is to create a new `'jotai/immer'` bundle like `'jotai/utils'`.
I was thinking of putting `useImmerAtom`, `withImmer`, and `atomWithImmer`.
It's open for discussion.

Would anybody want to work on it?

**Comment by Aslemammad** [comment]
Hey @dai-shi, These days, I'm going to read the docs and the source, because I loved the idea of jotai, and I wanted to work on this, no problem with that?

**Comment by dai-shi** [comment]
@Aslemammad Yes, please go ahead.

It's basically like utils:

1. create ./src/immer.ts
2. add two lines in ./rollup.config.
3. create ./docs/immer.md

You can add `immer` in devDependencies, but I'd like to avoid adding it in peerDependencies if `yarn build` works fine.

**Comment by Aslemammad** [comment]
@dai-shi, That's cool, I'm going to work on it.

**Comment by dai-shi** [comment]
Notice #95 changed the src folder structure. Now, it'd be like:
- ./src/immer.ts
- ./src/immer/useImmerAtom.ts
- ...

**Comment by Aslemammad** [comment]
@dai-shi Ok. thanks.

**Comment by Aslemammad** [comment]
@dai-shi Hey, I'm working on immer support, and I wanted to know, what is atomWithImmer and what should it do? Could you explain?

**Comment by dai-shi** [comment]
Sure, we haven't discussed about it. It will create a primitive atom and apply withImmer.

```js
export const atomWithImmer = (initialValue) => {
  const anAtom = atom(
    initialValue,
    (get, set, fn) => set(anAtom, produce(get(anAtom), draft => fn(draft)))
  )
  return anAtom
}
```

Something like this ☝️ in JS. Refer `atomWithReducer` for proper typing.

**Comment by Aslemammad** [comment]
Haha, @dai-shi I wrote the same thing, but IDK why, but I felt bad about it. Thanks.

**Comment by dai-shi** [comment]
@Aslemammad Maybe because the typing is tricky. Also, please note I didn't test it at all, and count on you.

**Comment by Aslemammad** [comment]
Hey @dai-shi, I implemeted the functions, Check it, any suggestion or problem? If it's ok I'll send the PR.
[codesandbox](https://codesandbox.io/s/jotai-immer-typescript-7s1fp?file=/src/App.tsx).
should I write the tests and ....?

And I wanted to say thanks for the oppertunity.

**Comment by dai-shi** [comment]
Looks good. I want to make the return type of atomWithImmer stricter.
```ts
export const atomWithImmer = <Value>(initialValue: Value) => {
  const anAtom: WritableAtom<
    Value,
    Function
  > = atom(initialValue, (get, set, fn) =>
    set(anAtom, produce(get(anAtom), (draft) => fn(draft)))
  );
  return anAtom as WritableAtom<
    Value,
    (draft: Draft<Value>) => void
  >;
};
```

tests would be nice, but we could do it separately.

**Comment by Aslemammad** [comment]
@dai-shi I think now it's ready, is it the time to send the PR?

**Comment by dai-shi** [comment]
@Aslemammad Sure!

**Comment by Aslemammad** [comment]
@dai-shi .
