### ISSUE TITLE
Imperatively & synchronously read atoms (`useAtomCallback` only supports `Promise`s)

### ISSUE THREAD

**Issue by lucaslcode** [pmndrs/jotai#1100]
I am in one of those weird edge cases where I am forced to be un-Reacty as I am using the Leaflet map library which requires a lot of imperative code. Thus I have something like the following:

```typescript
const markersLayer = useRef<L.MarkerClusterGroup>();
useQuery("markersKey", () => fetchMarkers(), {
    onSuccess: (data) => {
      if (!markersLayer.current) {
        markersLayer.current = L.markerClusterGroup({
          iconCreateFunction: (cluster) => {
            const highlightedMarkerIds = valueFromMyAtom;
            // ... create markers based on highlight
```

Unfortunately, the `iconCreateFunction` is triggered later and `valueFromMyAtom` is stale. It seems that I need an imperative getter function to put there instead.
`useAtomCallback` is perhaps what I need, but it only supports asynchronous reading which Leaflet doesn't accept. I investigated implementing a synchronous version but couldn't seem to work it out.

For now I have the following workaround but it feels like awful code smell:

```typescript
export const useAtomGetter = () => {
  const getter = useRef<Getter | null>(null);
  const derived = useMemo(
    () =>
      atom((get) => {
        getter.current = get;
      }),
    []
  );
  useAtomValue(derived);
  return getter.current;
};

//in my component
const atomGetter = useAtomGetter();

//...as above
const highlightedMarkerIds = atomGetter(myAtom);
```

Love the library so far! <3

**Comment by dai-shi** [comment]
Thanks for the real use case.

Now, this is a bit tricky. It's designed to be async at the beginning, but since some point, it work mostly in sync if atoms are sync. While we are not sure if we will be able to keep the behavior for the future, what we can do at the moment is a best effort. Let me try.

Alternatively, we have an experimental api #922 for un-Reacty usage.

**Comment by dai-shi** [comment]
You can try: https://ci.codesandbox.io/status/pmndrs/jotai/pr/1101
Find "Local Install Instructions" in ☝️ .
