### ISSUE TITLE
[atomWithQuery] Queries are not displayed inside react-query devtools

### ISSUE THREAD

**Issue by Nsttt** [pmndrs/jotai#1105]
Currently when using `atomWithQuery` the react-query devtools does not notice anything from the Query.

I believe this should be looked into, since the react-query devtools are really useful.

**Comment by aulneau** [comment]
You can use the query dev tools. You need to make sure to use the same queryClient between the atoms and what is fed into the dev tools. This is a bit of a different example, but the pattern is the same: https://github.com/fungible-systems/micro-stacks-examples/blob/main/nextjs/components/devtools.tsx#L10

**Comment by dai-shi** [comment]
So, it sounds like a documentation issue then.

**Comment by Jawad-sawari** [comment]
hey dai-shi, i wanted to work on this for hacktoberfest but i don't know which file to write the docs in. please let me know, thanks.

**Comment by Jawad-sawari** [comment]
hey dai-shi, I worked on an example and it worked fine, I just wanted to know how to write documentation, and here is the example link, thanks.
https://codesandbox.io/s/elegant-dan-ve7n19?file=/src/App.tsx

**Comment by dai-shi** [comment]
@Jawad-sawari Feel free to open a PR to fix the doc file. We'll review it then.

**Comment by jakkku** [comment]
hi, if no one is working on this, can i do this?

https://github.com/jakkku/jotai/blob/5b950ea38d0e4617c2a921f110160a97f6e8c782/src/query/atomWithQuery.ts#L73-L89
Looking at atomWithQuery, staleTime is fixed to 200.  
Would it be a problem if I allowed the staleTime to be set? Is it okay if the minimum settable value is 200?

**Comment by dai-shi** [comment]
yeah, please go ahead.
