### ISSUE TITLE
Jotai not compiling with Typescript

### ISSUE THREAD

**Issue by tarngerine** [pmndrs/jotai#111]
Hi all,

I'm getting this error as soon as I import `useAtom` from jotai

```
Failed to compile

/Users/tarng/Code/playspace/node_modules/jotai/index.d.ts
TypeScript error in /Users/tarng/Code/playspace/node_modules/jotai/index.d.ts(4,1):
Declaration or statement expected.  TS1128

    2 | export { atom } from './atom';
    3 | export { useAtom } from './useAtom';
  > 4 | export type { Atom, WritableAtom, PrimitiveAtom } from './types';
      | ^
    5 | export { useBridge, Bridge } from './Bridge';
    6 | 

This error occurred during the build time and cannot be dismissed.
```

I've tried to clear node_modules and yarn install again. Pretty new to Typescript and React so maybe I'm missing something obvious. Thanks for your assistance!

**Comment by dai-shi** [comment]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export
Seems like it's supported since 3.8. Which version of typescript do you use?

**Comment by tarngerine** [comment]
ah, that'll likely be the issue! thank you! i was on 3.7.2
