### ISSUE TITLE
Rendering suspense callback while running async actions

### ISSUE THREAD

**Issue by goncy** [pmndrs/jotai#112]
Probably this was a decission, not a bug, but wanted to be sure. I have an async actions that updates the status in different phases:

```typescript
export const shuffle = atom(null, async (_get, set) => {
  try {
    set(status, "pending");
    const _pokemon = await api.shuffle();

    set(status, "resolved");
    set(pokemon, _pokemon);
  } catch (_error) {
    set(status, "failed");
    set(error, "Failed to get pokemon");
  }
});
```
And in my code I want to show a spinner for a certain part if status includes "init" or "pending". Instead of that, I always get the suspense fallback in the root of my app.

Repro: https://codesandbox.io/s/practical-bouman-b3r9v

**Comment by dai-shi** [comment]
While in general, we still have room for discussion about how suspense should work (esp, for `write`), I think your use case can be solved with the current impl.
If I understand correctly, you just want to control loading status by yourself without `<Suspense>`. If that's the case, `write` shouldn't return a promise.

```js
export const shuffle = atom(null, (_get, set) => {
  const runFetch = async () => {
    try {
      set(status, "pending");
      const _pokemon = await api.shuffle();

      set(status, "resolved");
      set(pokemon, _pokemon);
    } catch (_error) {
      set(status, "failed");
      set(error, "Failed to get pokemon");
    }
  }
  runFetch();
});
```

How does that sound?

**Comment by goncy** [comment]
That sounds good, similar to not using async await or wrap the execution in a function in useEffect, thanks!
