### ISSUE TITLE
useAtom with Ref

### ISSUE THREAD

**Issue by michalkleiner** [pmndrs/jotai#1123]
Firstly — thanks for a great library and all your work on Jotai!

Question — I found this module for the normal `useState` hook — would there be something similar for `useAtom`?

https://www.npmjs.com/package/react-usestateref

My use case is abstracting some functionality within react components into methods that work with atom values. The issue is they get created when the component renders and at that point the atoms have their initial values. Subsequent changes to the values of the atoms don't update the value within the methods so I'm getting stale data. Using the reference seems like a nice solution to the problem.

A similar issue was https://github.com/pmndrs/jotai/issues/406, but I didn't want to piggyback there, so opening a new one.

**Comment by dai-shi** [comment]
> My use case is abstracting some functionality within react components into methods that work with atom values.

I'm not confident if I understand the use case, so let me start with an option. Does `useAtomCallback` help your case?

**Comment by michalkleiner** [comment]
I don't think `useAtomCallback` does what I need.

A simple use case would be something like this (pseudo-code):

```
const atom1 = atom(0);

function componentA {
   const [val, setVal] = useAtom(atom1);
   
   const reusableMethod() {
      ... some longer code that would otherwise be duplicated, using val
      // THIS code always reads val as 0 regardess of subsequent updates
   }
   
   useEffect(() => {
     some code setting val via setVal
   }, [deps]}
   
   useEffect(() => {
      some code calling reusableMethod()
   }, [dependency 1]}

   useEffect(() => {
      some other code calling reusableMethod() as well
   }, [dependency 2]}
}

**Comment by dai-shi** [comment]
From the code snippet, I think `useAtomCallback` works.

```js
function componentA {
  const [val, setVal] = useAtom(atom1);
  const readVal = useAtomCallback(useCallback((get) => get(atom1), [])); 
   
  const reusableMethod() {
     const val = readVal(); // this returns the latest value
      ... some longer code that would otherwise be duplicated, using val
   }
```

**Comment by michalkleiner** [comment]
Ah, right. I probably didn't understand well how to use the `useAtomCallback` in my use case. Will give that a go!

**Comment by michalkleiner** [comment]
Cool, that works! Thanks for the hint!
