### ISSUE TITLE
multi atom instance and batch update 

### ISSUE THREAD

**Issue by mainhanu** [pmndrs/jotai#1124]
when I have 1000 atom instance and I want to update all the atom value during one event, how to batch all changes, so the React view only rerender once?

code example:

https://codesandbox.io/s/mystifying-bell-cni04v?file=/src/App.tsx

you can see when button clicked, react rerender rerender a lot and cost more than 1 secounds despite the update logic is inside `ReactDOM.unstable_batchedUpdates`

**Comment by mainhanu** [comment]
updated the [demo](https://codesandbox.io/s/mystifying-bell-cni04v?file=/src/App.tsx) and some results are as follows

1. After removing redux, the problem disappeared
2. if I bind each atom with indepent redux store, the problem disappeared

since the problem is the invoke num of `flushPending`, with 1000 node update:

pure atom，**32 times**
![image](https://user-images.githubusercontent.com/48398913/165669153-211bfc35-b6af-434c-840d-ec39f545fa89.png)

1000 redux store, **48 times**
![image](https://user-images.githubusercontent.com/48398913/165669205-62956e50-1a9a-4e0d-a308-96eb4d169897.png)

single redux store, **1000 times**
![image](https://user-images.githubusercontent.com/48398913/165670257-1d7686cf-fd48-4fb8-992b-f2b464b8a5c9.png)

**Comment by mainhanu** [comment]
> Hmm, flushPending will still be batched by React.
> 
> Here's the example with an atom. How does it behave? https://codesandbox.io/s/hopeful-elbakyan-gwzc1j

it's still very slow due to the invoke time of flushPending

![image](https://user-images.githubusercontent.com/48398913/166132534-b8bcb625-c113-49b9-af3a-efb1c25783ec.png)

**Comment by mainhanu** [comment]
I think there is something todo with the derived atom, I changed the pure Atom to derived atom, it then become extramly slow due to the same reason.

1. pure atom: https://codesandbox.io/s/white-worker-m0pjyz?file=/src/pureAtom.tsx
![image](https://user-images.githubusercontent.com/48398913/166132599-30217bb9-3402-4e13-8409-cb9badbedf68.png)


2. derived atom: https://codesandbox.io/s/white-worker-m0pjyz?file=/src/pureAtomDerived.tsx

![image](https://user-images.githubusercontent.com/48398913/166132618-e00b6956-92e9-43a8-86ce-de13b8a420b7.png)

**Comment by dai-shi** [comment]
How about this? I expect it not slow:

```js
const baseAtom = atomFamily((id: string) => atom(0));
const getCountAtom = atomFamily((id: string) =>
  atom(
    (get) => get(baseAtom[id]),
    (get, set, update) => {
      const base = get(baseAtom[id]);
      set(baseAtom, update);
    }
  )
);
```
That ☝️ is more atomic.

In such a case, I guess there's possibly the room for improvement for updating derived atoms and then bailing out (because of the same atom value). Maybe skipping flushPending somehow.
