### ISSUE TITLE
(react 18) Extra commit with useTransition

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#1125]
https://codesandbox.io/s/bold-antonelli-04z766?file=/src/App.js

Initial log:
```
commit {isLoading: false, resolvedThree: 3}
```

After clicking the button:
```
commit {isLoading: true, resolvedThree: 3}
commit {isLoading: true, resolvedThree: 4}
commit {isLoading: false, resolvedThree: 4}
```

The second commit with `{isLoading: true, resolvedThree: 4}` should not exist, and it's how `useState` behaves.

**Comment by MohanadOO** [comment]
If you pass the `isLoading` as an array dependency to the `useEffect` it should not allow the `console.log` to execute until there is a change in the IsLoading.

```js

useEffect(() => {
    console.log("commit", { isLoading, resolvedThree });
  }, [isLoading]);
```

Console Log: 

```
commit {isLoading: false, resolvedThree: 3}
commit {isLoading: true, resolvedThree: 3}
commit {isLoading: false, resolvedThree: 4}
```

**Comment by mattbdc** [comment]
This masks an extra console.log call, but doesn't fix the real issue that the component is committing an unnecessary  time  (the 2nd one)
