### ISSUE TITLE
Second useAtom call returns old data

### ISSUE THREAD

**Issue by nikparo** [pmndrs/jotai#1127]
When getting the value from the same atom twice in the same component, the second value is sometimes out of date. Granted, this is not something you would normally want to do, it's just something I discovered while testing and playing around to get a feel for how atoms work.

```ts
const testAtom = atom("foo");

// Somewhere in code
const setValue = useSetAtom(testAtom);
setValue("bar");

// In component
const [value] = useAtom(testAtom);
const [value2] = useAtom(testAtom);
// foo, foo
// bar, foo
// bar, bar
```

Working example that displays this behaviour:
https://codesandbox.io/s/jovial-wozniak-bv8oqk

**Comment by dai-shi** [comment]
That sounds bad. Thanks for reporting.

I will work on #1125. maybe it's slightly related? will see.

**Comment by Aslemammad** [comment]
This issue only happens with React versions that are not 18, and as I said, it's because the batching system of React 18 was improved so much! I found a workaround, you can see it in the PR, but I don't think it's worth it! (it may break jotai in react-native and ...)

**Comment by Aslemammad** [comment]
@nikparo We decided to close this issue as we think the solution is not worth it (jotai's store does not depend only on react, and batchedUpdates in the core is a bad move in the long run for using in core in jotai)! 
So feel free to use the batchedUpdates workaround!
