### ISSUE TITLE
Suspense does not work

### ISSUE THREAD

**Issue by hxse** [pmndrs/jotai#1131]
I create a codesandbox: 
https://codesandbox.io/s/optimistic-night-qbgsy1?file=/src/App.js
When i fetch data, Suspense did not show "loading" as expected.
How should I do to let it work on React18?

**Comment by mattbdc** [comment]
Suspense boundary will show the fallback if a child component throws a promise (i.e. the promise in the atom hasn't yet resolved)

Your suspense boundary is after the call to useAtom

This is expected (and applies to non Jotai too)

**Comment by Thisen** [comment]
Sounds like it was resolved 🙏🏼
