### ISSUE TITLE
using `unstable_createStore` gives `act()` warnings in tests

### ISSUE THREAD

**Issue by dwelle** [pmndrs/jotai#1132]
At least I'm pretty sure it relates to the `unstable_createStore`. Removing it from the provider (and using the default store) and adding a declarative `setAtomValue` instead of an imperative `store.set()` removes the warnings.

```
 Warning: An update to Provider inside a test was not wrapped in act(...).
 
 When testing, code that causes React state updates should be wrapped into act(...):
 
 act(() => {
   /* fire events that update state */
 });
 /* assert on the output */
```

**Comment by dai-shi** [comment]
Wouldn't
```js
act(() => {
  store.set(...)
})
```
solve it?

**Comment by dwelle** [comment]
In the test code it's not immediately obvious what to wrap in `act()` (tried wrapping most of the test code logic to no results). Especially considering that react-testing-library should already be doing that for us (Excalidraw).

Could it be that the unstable stores don't play well with the `useDebugState`?

**Comment by dai-shi** [comment]
> Could it be that the unstable stores don't play well with the `useDebugState`

Hmm, not sure why they can't play well with it. Would you be able to try the following patch?

```diff
diff --git a/src/core/Provider.ts b/src/core/Provider.ts
index c806e9d..f14d501 100644
--- a/src/core/Provider.ts
+++ b/src/core/Provider.ts
@@ -59,7 +59,8 @@ export const Provider = ({
   }
 
   // LIMITATION: useDebugState prevents to work versioned write properly
-  if (__DEV__ && !unstable_enableVersionedWrite) {
+  // LIMITATION: unstable_createStore doesn't play well?
+  if (__DEV__ && !unstable_enableVersionedWrite && !unstable_createStore) {
     // eslint-disable-next-line react-hooks/rules-of-hooks
     useDebugState(scopeContainerRef.current)
   }
```

**Comment by TwistedMinda** [comment]
@dai-shi I tested, and as expected, the warning pops when not wrapping state changes with "act" and disappear when using "act" as you mentioned.

Tried to provide a [CodeSandBox](https://codesandbox.io/s/jest-testing-react-forked-xxfoo3?file=/src/components/App.test.js) But i can't manage to make it build due to dependencies....

Do you think we should close it?

@dwelle You mentioned `act()` from `react-testing-library` but there's no such function! Did you mean `@testing-library/react`, or maybe `react-testing-renderer` ? I feel confused.
Anyway, with `@testing-library/react` it wors as expected for me.

**Comment by dai-shi** [comment]
Note that, since v1.7.0, useDebugState is not included in Provider.
https://github.com/pmndrs/jotai/releases/tag/v1.7.0

**Comment by TwistedMinda** [comment]
@dai-shi Ah, good to know. For my tests, i was using `"jotai": "^1.6.6"`, so it looks okay even before 1.7.0.

So anyway this is issue can't happen starting from 1.7.0, right?

**Comment by dwelle** [comment]
Oops, I missed your reply @dai-shi — will try it out, or better yet just bump to 1.7.0. If still causing issues then, will dig deeper. Thanks for the help so far!

**Comment by dwelle** [comment]
> @dwelle You mentioned `act()` from `react-testing-library` but there's no such function! Did you mean `@testing-library/react`, or maybe `react-testing-renderer` ? I feel confused.

React testing library doesn't expose `act()`, that comes from React. From what I understand you should be wrapping the state updates yourself, but react-testing-library does that for us, hence why most users haven't ever encountered the `act()` API, myself included.

**Comment by TwistedMinda** [comment]
I'm closing it since this shouldn't be an issue anymore

**Comment by dai-shi** [comment]
Note to anyone: if such an issue with `useAtomsDebugValue` is found, please open a new issue.
