### ISSUE TITLE
`atomFamily.remove` does not trigger component update

### ISSUE THREAD

**Issue by niyan-ly** [pmndrs/jotai#1134]
As the title, it seems like a bug. I'm currently using react@18.
And here is the minimum representable code.

### What i expected
- when the `reset lisa` clicked, lisa should be remove from personAtom. And because it is being referenced from an index list, it should automatically re-created with brand new `age`.

### What actually happened
- the page doesn't update

```tsx
import { atom, useAtomValue } from "jotai";
import { atomFamily } from "jotai/utils";

const familyIndex = atom<string[]>(["lisa", "papa", "mama"]);
const personAtom = atomFamily((name: string) =>
  atom({ name, age: Math.random() })
);
const wholeFamilyAtom = atom((get) => {
  const indexes = get(familyIndex);

  return indexes.map((ind) => get(personAtom(ind)));
});

export default function App() {
  const family = useAtomValue(wholeFamilyAtom);

  return (
    <div className="App">
      <button
        onClick={() => {
          personAtom.remove("lisa");
        }}
      >
        reset lisa
      </button>
      {family.map((person) => (
        <p key={person.name}>
          {person.name}: {person.age}
        </p>
      ))}
    </div>
  );
}
```

**Comment by dai-shi** [comment]
While I understand where your expectation comes from, it's working as expected.
atomFamily is an atom cache, and removing it doesn't trigger re-render.

Closing this, but I guess the question remains what we should do. In your case, as you want to reset the value, I think `atomWithReset` would work.
Please feel free to continue discussion here or create [a new discussion](https://github.com/pmndrs/jotai/discussions/new).
