### ISSUE TITLE
Bridge example throws "useContextSelector requires special context"

### ISSUE THREAD

**Issue by elav000** [pmndrs/jotai#114]
Repro steps:
* Open up the example in the [useBridge/Bridge](https://github.com/pmndrs/jotai/blob/master/docs/core.md#usebridgebridge) docs at [https://codesandbox.io/s/jotai-r3f-fri9d](https://codesandbox.io/s/jotai-r3f-fri9d)
* Click on `Add`
* View the error raised from `use-context-selector` :
![image](https://user-images.githubusercontent.com/12959403/95385055-4dec7b80-08a2-11eb-963a-7e28b9432d10.png)

**Comment by dai-shi** [comment]
Thanks for reporting. The issue confirmed. 🤔

**Comment by dai-shi** [comment]
https://codesandbox.io/s/jotai-r3f-fri9d
Fixed!

**Comment by elav000** [comment]
Thank you!!!
