### ISSUE TITLE
Wrong values during render

### ISSUE THREAD

**Issue by iscekic** [pmndrs/jotai#1149]
Hello,

Thanks for creating an awesome library! I've encountered an issue and I need some help debugging.

Given the following definition of atoms:
```js
export const firebaseUserInfoAtom = atomWithReset({
  token: "",
  uid: "",
});

export const firebaseUidAtom = selectAtom(
  firebaseUserInfoAtom,
  (firebaseUserInfo) => firebaseUserInfo.uid
);

export const firebaseTokenAtom = selectAtom(
  firebaseUserInfoAtom,
  (firebaseUserInfo) => firebaseUserInfo.token
);

export const anonymousUidAtom = atom("");
export const userUidAtom = atom(
  (get) => get(firebaseUidAtom) || get(anonymousUidAtom)
);

export const userLoggedInAtom = selectAtom(firebaseUserInfoAtom, (userInfo) =>
  Boolean(userInfo.uid)
);
```

For these steps:
1. initial render ✅ 
2. anonymous id gets set ✅ 
3. firebase boots and sets user info 🟥 
4. subsequent correct render ✅ 

This component:
```js
const uid = useAtomValue(userUidAtom);
const userLoggedIn = useAtomValue(userLoggedInAtom);

useEffect(() => {
  console.log({ uid, userLoggedIn });
}, [uid, userLoggedIn]);
```

Logs the following:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/4062236/167697257-3fe5b8d6-cbc3-4837-945f-72c2218b9757.png">

My expectation is that render 3 doesn't exist.

CodeSandbox repro: https://codesandbox.io/s/cool-glade-vl2om8?file=%2Fsrc%2FApp.js

Versions I'm using:
```
"next": "12.1.5"
"react": "17.0.2"
"jotai": "1.6.5"
```

Please let me know if you need any more info. 🙇‍♂️

**Comment by iscekic** [comment]
A weird thing I noticed is that, in dev tools, the atom is dependant on itself:
<img width="307" alt="image" src="https://user-images.githubusercontent.com/4062236/167698390-0514aa27-b8c7-425f-a4de-a0cecf12ac55.png">

Not sure if that's normal or not.

**Comment by dai-shi** [comment]
https://codesandbox.io/s/nervous-lamport-xio5gk?file=/src/App.js
Hmm, this is even reproducible without `atomWithReset` and `selectAtom`.

@riemonyamada Would you like to give a shot???

---

> the atom is dependant on itself:

It's correct. some atoms may not depend on themselves.

**Comment by iscekic** [comment]
The issue isn't reproducible in react 18 - I think it has to do with state updates batching being automatic in 18 vs manual in 17.

I think a potential solution might be to wrap all updates of an atom and its dependants with `ReactDOM.unstable_batchedUpdates`.

**Comment by dai-shi** [comment]
Oh, great finding!!!
https://codesandbox.io/s/strange-driscoll-8f8jrn
Yeah, `unstable_batchedUpdates` fixes it.

Okay, this is working as expected.
If one needs to fix it in react 17, it's their responsibility to use `batchedUpdates` on their end.
(We don't do it in the library for various reasons.)

Closing as not an issue.

(btw, if we have a better solution without `batchedUpdates`, we may consider it.)

**Comment by iscekic** [comment]
A note somewhere in the docs might be benefitial - there are still lots of react 17 users out there. 😄 

Thanks for the help!

**Comment by dai-shi** [comment]
good point. where do you think we should add such a note?

**Comment by iscekic** [comment]
Somewhere in the derived atoms section? 🤷

**Comment by dai-shi** [comment]
Hmm, it's not only about derived atoms.
If anyone has suggestions, please feel free to open PRs. 😅

**Comment by dai-shi** [comment]
maybe, `./guides/react-17.mdx`..
