### ISSUE TITLE
Transition with `useTransition` is broken by re-render

### ISSUE THREAD

**Issue by riemonyamada** [pmndrs/jotai#1151]
If a re-render occurs on a component during a transition with `useTransition`, the transition is broken.

https://codesandbox.io/s/jotai-x-usetransition-4qrsdh
If you click `update id atom with startTransition` and then click `update some atom` before it is resolved, it suspends.

When I use `unstable_enableVersionedWrite` it works but I am getting errors.

https://codesandbox.io/s/jotai-x-usetransition-versioned-write-b94ge2

I have also experienced other unstable behavior with `unstable_enableVersionedWrite`, although I have not been able to reproduce it. I don't have time right now, so I will look into it again later.

**Comment by dai-shi** [comment]
Hi, thanks for digging into it.
Just a basic question, if we use useContext and useState (for each atom) without jotai, the behavior is different, right?

**Comment by riemonyamada** [comment]
Do you mean something like this? Not exactly the same as the first example, but it would be helpful. And yes, it appears to be working well.

https://codesandbox.io/s/usetransition-x-context-forked-gokrtl?file=/src/App.js

The `count` uses `useState` and `useContext` and the `derivedData` is derived from `count`. The `derivedData` is stored in module scope and does not even use `useState`. 

Concurrent Mode seems to be more than I had imagined. I would like to dig a little deeper, but I don't have time right now and don't think I will get around to it for a while.

**Comment by dai-shi** [comment]
Thanks so much for the investigation.
I will look into it later. This might be a bit related to what I'm trying in another project.

**Comment by dai-shi** [comment]
@riemonyamada #1154 is ready to play with. Wanna try your example?
https://ci.codesandbox.io/status/pmndrs/jotai/pr/1154 👈 "Local Install Instructions"

**Comment by riemonyamada** [comment]
Hi, Thanks for letting me know. I've used it briefly and it looks good to me!
