### ISSUE TITLE
atomWithImmer doesn't work

### ISSUE THREAD

**Issue by lgwebdream** [pmndrs/jotai#1155]
object value doesn't change, but component is rendered repeatedly~
demo link
https://codesandbox.io/s/atomwithimmer-demo-u4pw0u?file=/src/App.js

**Comment by dai-shi** [comment]
If you wrap `console.log` with `useEffect` and the result is something expected, then it's not an issue, but an intentional behavior to make it better work with concurrent react.

https://codesandbox.io/s/atomwithimmer-demo-forked-th8820

**Comment by lgwebdream** [comment]
> If you wrap `console.log` with `useEffect` and the result is something expected, then it's not an issue, but an intentional behavior to make it better work with concurrent react.
> 
> https://codesandbox.io/s/atomwithimmer-demo-forked-th8820
I probably understand, thanks~

**Comment by dai-shi** [comment]
I understand the different behavior in React 18 and 17. https://github.com/pmndrs/jotai/issues/1158#issuecomment-1126848920

#1159 will improve the behavior, it doesn't re-render on updates. (on mount, it's double render with one commit.)

https://codesandbox.io/s/atomwithimmer-demo-forked-2cg03z?file=/src/App.js
