### ISSUE TITLE
[useAtomDevtools]: documentation for `DevtoolOptions`

### ISSUE THREAD

**Issue by Pondorasti** [pmndrs/jotai#1178]
[PR#1095](https://github.com/pmndrs/jotai/pull/1095) introduced a new way to call `useAtomDevtools` hook and label atoms using `DevtoolOptions` object. From that point forward, making debug labels the old fashioned way `useAtomDevtools(atom, "name")` started throwing console warnings.

What's the timeline for fully deprecating and removing old method? I would also love to see updated docs for usage, which I could help with 🙃 👀 .

![CleanShot 2022-05-23 at 17 20 12](https://user-images.githubusercontent.com/32957606/169924786-3e5e7b10-5047-41a7-bd4d-1ba360207e69.png)

**Comment by dai-shi** [comment]
> [PR#1095](https://github.com/pmndrs/jotai/pull/1095) introduced a new way to call `useAtomDevtools` hook and label atoms using `DevtoolOptions` object. From that point forward, making debug labels the old fashioned way `useAtomDevtools(atom, "name")` started throwing console warnings.

Right. Sorry about the confusion.

> What's the timeline for fully deprecating and removing old method?

No planned timeline, but we should eventually remove deprecated method.

> I would also love to see updated docs for usage, which I could help with 🙃 👀 .

That's very appreciated.
One of the biggest things to improve currently is docs. There are some work going on. If you can take the `devtools` part, it's more than welcomed.

**Comment by Pondorasti** [comment]
Cool cool, I will try to find some time this week and submit a draft for `/devtools` page.

**Comment by dai-shi** [comment]
Is it stalled?

**Comment by Pondorasti** [comment]
Some minors clarifications have been already made to devtools docs. Unfortunately, as jotai couldn't satisfy some project requirements, I had to move away to a different framework and lost familiarity/context :/

**Comment by dai-shi** [comment]
No problem. Closing.
