### ISSUE TITLE
(DEV-only) re-renders caused by `<Provider />`

### ISSUE THREAD

**Issue by Pondorasti** [pmndrs/jotai#1180]
Following up on the `unstable_createStore` introduced in [#861](https://github.com/pmndrs/jotai/issues/861).  

I've noticed that wrapping a react tree under `<Provider />` it trigger a re-render whenever an atom changes. From what I could gather the Provider re-render has minimal performance impact, especially when memoizing children (profiled in a large application). However, it does introduce a lot of noise when trying to do performance debugging & profiling (ex: highlighting renders, browser paint flashing).

Shouldn't the provider treat each change as transient and let hooks like `useAtomValue` trigger a re-render inside child components?

### [CodeSanbox](https://codesandbox.io/s/xenodochial-margulis-bbd854?file=/src/App.js)

I'm using react dev tools profiler and turned on `Highlight updates when components render`.

https://user-images.githubusercontent.com/32957606/169950911-70747041-75d5-4579-a77d-032afb19e84e.mp4

**Comment by dai-shi** [comment]
Is it correct that this issue is about any `<Provider>`s, not just one with `unstable_createStore`?

**Comment by Pondorasti** [comment]
Oh yeah, you are right. I've updated issue description and CodeSandbox. The `unstable_createStore` feature was the motivation to use a `<Provider />` for the first time.

**Comment by dai-shi** [comment]
Thanks. This is because we have `useDebugValue` in Provider. It's DEV only behavior. It's for improving debugging ironically. We might consider making it an option to control by users.

**Comment by Pondorasti** [comment]
That makes sense, thanks for clarifying. Could I open a PR and add a new prop to the `<Provider />`, something like `disableDebugValue`?

**Comment by dai-shi** [comment]
I'd like to fix some tests as well, so I'll be working on it. Thanks for your suggestion. You are very welcome to contribute to some issues!

**Comment by dai-shi** [comment]
Hmm, I'm super confident if making it a prop is appropriate. `DebugProvider` might be cleaner. Or, disable it globally. I wonder if we need to enable/disable it selectively for some Providers.

**Comment by dai-shi** [comment]
I think it's far better to have a separate component  or hook to provider the debug state feature. Then, it works for provider-less mode too. In such a case, we'd want to put it in `jotai/devtools`.

**Comment by Pondorasti** [comment]
Took a look at your PR, and exposing `useDebugState` is much nicer. What I do find confusing is the naming between `useDebugState` and `useAtomsDevtools`. It makes the latter sounds like a "general" devtooling hook. Might be worth considering using `useReactDevtools` and `useReduxDevtools`, or maybe just renaming the redux one? What do you think?

**Comment by dai-shi** [comment]
Yeah, I'm not comfortable with the name.
We don't want to change `useAtomsDevtools`.

I too thought about `useReactDevtools`, but if we don't change `useAtomsDevtools`, it's still confusing. And, it's not really like "using" react devtools. `useDebugState` makes sense if people are familiar with [`useDebugValue`](https://reactjs.org/docs/hooks-reference.html#usedebugvalue), but it's hopeless.

Hmm, I'm not sure if I can come up with better naming. `useAtomsDebugValue` can be an option.

**Comment by Pondorasti** [comment]
This is a tough one, I like `useAtomsDebugValue` the most since it's inline with `useAtomsDevtools` and you can infer from the name that it applies to all atoms.

**Comment by dai-shi** [comment]
Yeah, `useAtomsDebugValue` seems better and we should educate people it's a wrapper around `useDebugValue`. Thanks.
