### ISSUE TITLE
(DEV-only) react profiling doesn't show `DebugState`

### ISSUE THREAD

**Issue by Pondorasti** [pmndrs/jotai#1183]
Atom labels for react devtooling don't seem to work. The `DebugState` hook doesn't show up anymore as per [documentation](https://jotai.org/docs/guides/debugging#provider). I've tried it both in personal project and an older Jotai [example](https://codesandbox.io/s/react-typescript-forked-cvfeh?file=/src/App.tsx), without any success. For [reference](https://github.com/pmndrs/jotai/pull/93#issuecomment-704175560), this is what I'm looking for.

![CleanShot 2022-05-24 at 21 26 40](https://user-images.githubusercontent.com/32957606/170179701-7bb236bb-e3fc-4939-8077-faf12a7000a9.png)

**Comment by dai-shi** [comment]
<img width="294" alt="image" src="https://user-images.githubusercontent.com/490574/170220712-a9b4a0fd-ef1b-48a2-ace0-4c0ad94e82e6.png">

It's in the React "Components" tab, not "Profiler".

**Comment by Pondorasti** [comment]
Ah, I see. It would be amazing if you could see those debug states for any given snapshot when profiling. Although, not sure what's the technical limitation here. Closing issue for time being.

**Comment by dai-shi** [comment]
Yeah, it's probably not possible unless some APIs are exposed from React. Would be nice though.
