### ISSUE TITLE
Question on atom init

### ISSUE THREAD

**Issue by aliakakis** [pmndrs/jotai#1186]
Is it bad practice instead of the code below: 

```code
export const usersAtom = atom([]):

export const fetchUsersAtom = atom(
  (get) => get(usersAtom),
  (get, set, update) => {
    set(result.data); // await fetch code here for users
  }
```

to use the code like this:

```code
export const usersAtom = atom(
  (get) => [] ?? get(usersAtom),
  (get, set, update) => {
    set(usersAtom, result.data); // await fetch code here for users
  }
```

**Comment by TwistedMinda** [comment]
@aliakakis What is your use-case ?

```js
export const fetchUsers = atom(
  [],
  async (get, set, update) => {
    set(fetchUsers, result.data); // await fetch code here for users
  }
)

const [users, fetchUsers] = useAtom(fetchUsers)
```

Seems to be the most compact and readable, but I prefer like this:

```js
export const usersAtom = atom([])
export const fetchUsers = atom(
  get => get(usersAtom),
  async (get, set, update) => {
    set(usersAtom, result.data); // await fetch code here for users
  }
)

const users = useAtomValue()
const fetchUsers = useSetAtom(fetchUsers)
```

But I'm a newbie too!

**Comment by aliakakis** [comment]
Strictly readability and compact code. I will use your compact code. Thought the getter was mandatory. Thank you for your answer 🙂

**Comment by TwistedMinda** [comment]
@aliakakis Don't forget to set as resolved if that fits your needs ;)

**Comment by aliakakis** [comment]
Question answered 🙂

**Comment by dai-shi** [comment]
Thanks guys.

Some follow-ups:

```js
export const usersAtom = atom(
  (get) => [] ?? get(usersAtom),
  (get, set, update) => {
    set(usersAtom, result.data); // await fetch code here for users
  }
```
That ☝️ is prohibited and an error will be thrown on write.

```js
export const fetchUsersAtom = atom(
  [],
  async (get, set, update) => {
    set(fetchUsersAtom, result.data); // await fetch code here for users
  }
)
```
That ☝️ works and is totally fine in JS. But, we can't infer types in TS. So, this pattern is not documented and thus sort-of unrecommended. `atomWithReducer` is a util for this pattern.

Using two atoms is good and jotai way. You can export both atoms or just the second derived atom.

**Comment by aliakakis** [comment]
@dai-shi thank you for the answers. 
I was using codesandbox through my mobile therefore didn't see any error for the code below

```code
export const usersAtom = atom(
  (get) => [] ?? get(usersAtom),
  (get, set, update) => {
    set(usersAtom, result.data); // await fetch code here for users
  }
```
It wrote properly when calling for example setUsers([1,2]). Again, will check when I am on my PC.

**Comment by TwistedMinda** [comment]
@dai-shi Well, you can infer type this way, without another atom!

```ts
const users: any[] = []
export const fetchUsersAtom = atom(
  users,
  async (get, set, update) => {
    set(fetchUsersAtom, result.data); // await fetch code here for users
  }
)
```

 I feel like it's a decent pattern for atoms that only need 1 attached action.
What do you think?

**Comment by dai-shi** [comment]
Maybe I wasn't clear enough about type inference, but `any` is not a solution for us.
Again, `atomWithReducer` is designed to be a solution to this.

**Comment by TwistedMinda** [comment]
@dai-shi Sorry to insist, but I'm not sure you understood my point:
- could be an interesting pattern for atoms that require 1 action only, which happen a lot in my experience (while `atomWithReducer` is kinda meant for atoms that need two or more actions.
- I was using `any` as an example, but I tested it and this works:
```ts
type User = { id: string } 
const users: User[] = []
export const fetchUsersAtom = atom(
  users,
  async (get, set, update) => {
    set(fetchUsersAtom, result.data); // await fetch code here for users
  }
)
// Usage in components
const users = useAtomValue(fetchUsersAtom) // type User[] is inferred correctly
```
Did I miss something? :p
Sorry to bother!

**Comment by dai-shi** [comment]
> could be an interesting pattern for atoms that require 1 action only, which happen a lot in my experience

This is totally valid. Feel free to use the pattern. It's just not TS friendly.
Out of curiosity, do you prefer 1 atom to 2 atoms, because of performance, readability or something else?

> (while `atomWithReducer` is kinda meant for atoms that need two or more actions)

It's limited for just one atom, but not necessarily meant for multiple actions. If you felt so, it's unfortunate, but naming is always hard. Feel free to rename it on your end.

>  Did I miss something? :p

We want to make type error if we do like `set(fetchUsersAtom, null)`.
https://tsplay.dev/WKqdKN

Now, I noticed `atomWithReducer` doesn't support async write. So, there could be another util with a better name that supports async write.

**Comment by TwistedMinda** [comment]
@dai-shi
> Out of curiosity, do you prefer 1 atom to 2 atoms, because of performance, readability or something else?

I think same as the author, I suppose we all know it can't hurt the performance, but it's more like "I prefer to have only 1 variable that acts as set/get then a setter and getter separately."
If there is more than 1 action, I will not use this pattern, for sure.

> It's limited for just one atom, but not necessarily meant for multiple actions. If you felt so, it's unfortunate, but naming is always hard. Feel free to rename it on your end.

Yeah, it could be used for 1 action only, of course. What I meant is more that I was interested in finding a specific pattern for 1 and only 1 :p 

> Now, I noticed atomWithReducer doesn't support async write. So, there could be another util with a better name that supports async write.

Didn't know it doesn't work with async, but yeah, being async wouldn't feel like a redux reducer at all.

> We want to make type error if we do like set(fetchUsersAtom, null).
https://tsplay.dev/WKqdKN

Oh, indeed, I did not realize that the typing of the setter was not correctly inferred! Thanks for enlightening me!
However, I can't make it work with your option either :/

```ts
type User = { id: string } 
const usersAtom = atom<User[]>([])
export const fetchUsersAtom3 = atom(
  get => get(usersAtom),
  async (get, set, update) => {
    const old = get(fetchUsersAtom);
    set(fetchUsersAtom, null) // No error triggered here
  }
)
```

**Comment by dai-shi** [comment]
> ```js
> set(fetchUsersAtom3, null) // Therefore, no TS type error here either
> ```

btw, this will throw a runtime error, we can't `set` derived atoms.

What I meant is this:
```js
type User = { id: string } 
const usersAtom = atom<User[]>([])
export const fetchUsersAtom3 = atom(
  get => get(usersAtom),
  async (get, set, update) => {
    const old = get(usersAtom)
    set(usersAtom, null)
  }
)```

**Comment by TwistedMinda** [comment]
@dai-shi oh yeah sure! Thanks for clarifying!!!

**Comment by aliakakis** [comment]
@dai-shi strictly for readability I prefer the one atom get/set for some people not front end oriented, trying to make the code as easy to understand as possible. I follow the less is more concept a lot.

**Comment by TwistedMinda** [comment]
@aliakakis however this only works if your project doesn't use typescript. Therefore it's a valid pattern, but use it "at your own risk"

So to conclude, if question is: is it good/bad practice?
Answer is: no, it's not a good practice because you lose the Typescript typing on your setter inside the write function or your atom.

**Comment by aliakakis** [comment]
@TwistedMinda we don't use TS and there is no plan of us going that route 🙂
