### ISSUE TITLE
One atom to manage multiple components?

### ISSUE THREAD

**Issue by dani-z** [pmndrs/jotai#1196]
Hi, 

I am very new to Jotai but I really like its philosophy and the bottom-up approach. I am trying to implement it in a React Native app and I am struggling to understand a bit the mental model. 

My use case is that I have a Dialog and a Drawer component wrapper. I have an atom for each (and derive from the `atomWithToggle`) of them but I can have more than one drawer or dialog, ie Error dialog, Success dialog. 

Is it possible to explicitly instruct what type of modal to show at certain times?
The code I have is
``` js
// Component
const [isVisible, setIsVisible] = useAtom(dialogAtom);
```

``` js
// Atom
export const dialogAtom = atomWithToggle(false);
```

``` js
// atomWithToggle
function atomWithToggle(initialValue?: boolean): WritableAtom<boolean, boolean | undefined> {
  const anAtom = atom(initialValue, (get, set, nextValue?: boolean) => {
    const update = nextValue ?? !get(anAtom);
    set(anAtom, update);
  });

  return anAtom as WritableAtom<boolean, boolean | undefined>;
}
```

Thank you.

**Comment by dai-shi** [comment]
> I am struggling to understand a bit the mental model.

If you ever used useState and useContext to share state between components, useAtom basically works like that. useAtom will encourage smaller states, so the mental model is a little different though.

> I can have more than one drawer or dialog, ie Error dialog, Success dialog.

We basically have two options:
1. Create multiple atoms for dialogs. `atomFamily` may work (but not necessary).
2. Use one atom and use `Provider` to provider separate values for different subtrees.

The first one is probably easier to understand.

> Is it possible to explicitly instruct what type of modal to show at certain times?

I'm not exactly sure if I understand the question. `atomWithToggle` doesn't seem to have anything to do with this issue, does it?

**Comment by TwistedMinda** [comment]
@dani-z Hello! You don't "need" the toggle util to toggle thinks :p It's just a nice pattern. But for your case I suppose you just want to store a "type" instead of a "boolean". For example, we could use a string for the type, or an enum.

So something like:
```tsx
// Atom
type DialogType = "error" | "success" | null
export const dialogAtom = atom<DialogType>(null);

// Component
const Component = () => {
  const [type, setType] = useAtom(dialogAtom);
  const onClose = () => setType(null)
  if (!type)
    return (null);
  switch (type) {
    case "error":
      return <Error onClose={onClose} />
      break
  }
}
```

**Comment by TwistedMinda** [comment]
That issue looks more like a Discussion than an issue. I think we can close it.
@dani-z Don't hesitate to ask any question about the mental modal, patterns and common usage in the Discussion section ;)

**Comment by dani-z** [comment]
Hi both, this is great, thanks so much for the explanations. @TwistedMinda I think that's exactly what I was looking for, not multiple modals visible at the same time, but one at a time. I agree this could be better in the Discussions sections, apologies I haven't checked that first before posting here. Happy to move it there if you feel it adds value.

Thanks again for the help. 🙏

**Comment by dani-z** [comment]
@TwistedMinda sorry to post it again here, I think it may be useful for continuity. What is `atomSetValue` in your example? I think the flow is clearer, I just don't know what the function looks like.
Thanks again

**Comment by TwistedMinda** [comment]
@dani-z Hello! No problem!
It's a mistake! I meant to write `useSetAtom`, to [retrieve the setter](https://jotai.org/docs/api/core#use-set-atom)
Sorry for the confusion :)

**Comment by dani-z** [comment]
Ah! I thought that was it, I was just not sure if there's anything internal not documented 😄 
Thanks for confirming this!
