### ISSUE TITLE
Validating atoms

### ISSUE THREAD

**Issue by BenBeattieHood** [pmndrs/jotai#1198]
Thanks for your superb work on this package! I'm enjoying using it.

Where an atom reads from an API (local storage, react query response, form input) rather than an in-memory value, we can't guarantee the value matches the expected type. 

An example of this can be seen here: [https://d5kn6.csb.app/#count=%22stored+value+may+not+match+your+expected+type%2C+if+it+has+been+written+by+previously+deployed+code%22](https://d5kn6.csb.app/#count=%22stored+value+may+not+match+your+expected+type%2C+if+it+has+been+written+by+previously+deployed+code%22)

(Pressing the `+1` button on the above example shows how the business logic will fail with an invalid input type)

The current implementation of atomWithValidate is written to apply validation on write, with a synchronous initialValue; but could we instead have validation nested into atoms (eg atomWithValidate's initialValue is an atom, therefore requiring `onMount` to provide a getter as well as a setter), and in this way perhaps compose the validation atom so that API responses could be validated during load?

**Comment by dai-shi** [comment]
Thanks for opening this up.

In terms of `atomWithStorage`, I have thought about validation/type guard and custom `storage` is a solution. While I agree that docs are missing, so far nobody seems interested. https://github.com/pmndrs/jotai/issues/805#issuecomment-1133607794
So, let's improve docs on this.

`atomWithHash` is a sub util based on `atomWithStorage`, and `deserialize` option is the place to validate.

I'm not sure about `jotai/query`. I assume react-query should be responsible about it?

For forms, we have an experimental project [jotai-form](https://github.com/jotai-labs/jotai-form), FYI.

**Comment by BenBeattieHood** [comment]
Thanks @dai-shi 👍I'll try out the custom storage solution, as well as adding react-query validation.

As to [jotai-form](https://github.com/jotai-labs/jotai-form), I was hoping its [atomWithValidate could be adjusted here](https://github.com/jotai-labs/jotai-form/blob/main/src/atomWithValidate.ts#L42) to accept either initialValue _OR_ another atom, similar to how [focusAtom](https://github.com/pmndrs/jotai/blob/main/src/optics/focusAtom.ts#L14) or [atom.ts does it](https://github.com/pmndrs/jotai/blob/main/src/core/atom.ts#L107-L108)

**Comment by dai-shi** [comment]
https://github.com/jotai-labs/jotai-form/pull/4 is a new function related it. I don't think deriving atoms is very easy, and it may overlap with other native functions. Though, I' might be missing something. Would be great if you open a new issue there with some use cases.

**Comment by dai-shi** [comment]
I think what's remaining in this issue is documentation for `atomWithStorage` and `atomWithHash`. Not sure about `jotai/query`, but maybe.

**Comment by dai-shi** [comment]
Closing this as it's a bit stale now.

**Comment by KutnerUri** [comment]
@dai-shi - this seems very necessary, there's no way to drop old values when changing data structure. This is storage agnostic.

Should be something like:
```
export const atom = atomWithStorage("cat", ["meow"], undefined, {
  getOnInit: true,
  validateStorage: value => Array.isArray(value) // return false to skip storage and use default value
});
```

**Comment by dai-shi** [comment]
> This is storage agnostic.

Yeah, that's convincing. But, I'm not convinced to add an option. Let's add a util, which is less comfortable, but more flexible.
