### ISSUE TITLE
Jotai with React Query, how to handle errors?

### ISSUE THREAD

**Issue by AlsDevShack** [pmndrs/jotai#1199]
I have a simple jotai atom with query. It's doing a fetch for some data:
```
export const state = atomWithQuery(() => ({
    queryKey: ['stateKey'],
    initialData: {date: "someData"} ,
    queryFn: async () => {
        const res = await fetch('/api/endpoint')
        const {data} = await res.json();
        return {data}
    },
}))
```

what do I do if there is an error while fetching? How to I notify the user? Currently nothing happens on the component level, and initialData just carries on being used. 

Ideally I thought I'd be able to have some kind of an error atom that I could set, upon catching the exception here. But I don't think it's possible to set a different item from within the queryFn.

**Comment by dai-shi** [comment]
https://github.com/pmndrs/jotai/blob/14540988e665a574b8aa49dde37b233f817afcbd/src/query/atomWithQuery.ts#L135

Looks like it sends the error to ErrorBoundary. But, I've never tried. It should work to catch errors, but not sure how easy it is to recover from the error.
@aulneau Do you have any experience with handling errors?

**Comment by TwistedMinda** [comment]
@AlsDevShack Just use [Error Boundary](https://reactjs.org/docs/error-boundaries.html) (just a simple copy paste from the docs), wrap the component that does the query with it, and u're good to go :)

If for some reason you don't wanna use Suspense & ErrorBoundary, you can also use the [loadable API](https://jotai.org/docs/utils/loadable) on your atom :)

@dai-shi I just tried it and both ways work like a charm

**Comment by dai-shi** [comment]
Okay, I'd admit we haven't worked on this case very well yet. So, contributions are welcome.
I think the issues are a) error log from react-query, and b) a way to recover from error.

**Comment by AlsDevShack** [comment]
> @AlsDevShack Yep, just use [Error Boundary](https://reactjs.org/docs/error-boundaries.html) (just a simple copy paste from the docs), wrap the component that does the query with it, and u're good to go :)
> 
> If for some reason you don't wanna use Suspense & ErrorBoundary, you can also use the [loadable API](https://jotai.org/docs/utils/loadable) on your atom :)
> 
> @dai-shi I just tried it and both ways work like a charm
> 
> EDIT: BUT, I still got a **warning log** when using either loadable or Suspense
> 
> ```
> err
> at node_modules/react-query/lib/core/query.js:367:10 in onError
> at node_modules/react-query/lib/core/retryer.js:81:40 in reject
> at node_modules/react-query/lib/core/retryer.js:146:14 in Promise.resolve.then._catch$argument_0
> ```
> 
> ... and a little bonus **error log** that only Suspense has
> 
> ```
> err
> This error is located at:
>     in Content (created by Root)
>     in Suspense (created by Root)
>     in ErrorBoundary (created by Root)
>     in RCTView (created by View)
>     in View (created by Root)
>     in Root (created by App)
>     in Suspense (created by App)
>     in App (created by ExpoRoot)
>     in ExpoRoot
>     in RCTView (created by View)
>     in View (created by AppContainer)
>     in DevAppContainer (created by AppContainer)
>     in RCTView (created by View)
>     in View (created by AppContainer)
>     in AppContainer
>     in main(RootComponent)
> at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
> at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
> at node_modules/react-native/Libraries/Core/ReactFiberErrorDialog.js:52:4 in showErrorDialog
> ```
> 
> Note: "err" is what was thrown in the `atomWithQuery` request Note2: I'm on React-native

ahh, the loadable api would have been a decent solution in my case.  Thank you.

**Comment by dai-shi** [comment]
> a) error log from react-query

This seems unavoidable. If anyone knows any solution (even with `useQuery`), please let us know.

**Comment by lemind** [comment]
Hello there.
Trying to catch 404. But can not do it. What I do wrong with that?

https://codesandbox.io/s/jotai-query-error-boundary-forked-qtudfw

Thank you
PS in case my API does not work the request should return 404 with any data

**Comment by dai-shi** [comment]
I think you need to check the http status: https://codesandbox.io/s/jotai-query-error-boundary-forked-esppkh?file=/src/App.tsx
