### ISSUE TITLE
Add docs and test for jotai/immer

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#122]
This is a follow up task for #120.

**Comment by Aslemammad** [comment]
Which part should I edit? And how it works?

**Comment by dai-shi** [comment]
For docs: Create a new file `./docs/immer.md`

For tests: Create three new files `./tests/immer/atomWithImmer.d.ts` `./tests/immer/useImmerAtom.d.ts` `./tests/immer/withImmer.d.ts`

`yarn test` should run all tests.

**Comment by Aslemammad** [comment]
@dai-shi I did the same thing for the test, yesterday. I'll work on them. thanks

**Comment by Aslemammad** [comment]
People, if you have any idea about immer docs in jotai, share with us here.

**Comment by dai-shi** [comment]
(Should we keep this issue open for a while?

**Comment by Aslemammad** [comment]
@dai-shi Choose the best. I think we shall close it because if someone wanted to edit the docs, he/she would create a new issue, so do the best.

**Comment by dai-shi** [comment]
Closing this as the initial work is done with #125. Please file a new issue/PR for any improvements.
