### ISSUE TITLE
Does Jotail have poor performance?

### ISSUE THREAD

**Issue by meotimdihia** [pmndrs/jotai#1243]
Hi, I am using Next.js. And the simple snippet, added 400 ms to initial render for local development.
```typescript
import { useUpdateAtom, useAtomValue } from "jotai/utils"

function Layout(props) {
  const updateBreakpoint = useUpdateAtom(breakpointAtom)
```

I don't have exp with other state management libraries but Jotai.

**Comment by dai-shi** [comment]
Hi, thanks for reporting.

Would you like to create a minimal reproduction? It would help the investigation. Also, can use measure it in production mode too?

Would anyone like to investigate the issue?

**Comment by meotimdihia** [comment]
Sorry, I can't reproduce the issue on a new project. I close the issue.

**Comment by meotimdihia** [comment]
do we have a way to lazyload atoms?

**Comment by dai-shi** [comment]
Creating atoms should be extremely fast. 50 atoms shouldn't be a problem.
https://twitter.com/dai_shi/status/1480083292884172801

Maybe `jotai/query` can be slow. It creates a default RQ client at the module level.

> do we have a way to lazyload atoms?

That's the important point of atoms. you can lazy load atoms, just like any functions and components.

**Comment by meotimdihia** [comment]
Thanks for the help. My application uses a lot of atomWithStorage.
This is the benchmark after when I removed atomWithInfiniteQuery:

![WindowsTerminal_2022-06-21_16-44-06](https://user-images.githubusercontent.com/300961/174770483-5c6b40ee-1f0d-42e2-ab18-ef236990370c.png)

I'll report futher if I find other problems. 🙂
