### ISSUE TITLE
AtomFamily recursion: too much recursion

### ISSUE THREAD

**Issue by MrHeer** [pmndrs/jotai#1248]
Steps to reproduce:
1. open [CodeSandbox](https://codesandbox.io/s/atomfamily-recursion-se8p31?file=/src/App.js)
2. click `n` times `Swap` button (sometime `n` > 10, some time `n` > 5)
3. you will see the `too much recursion`

**Comment by thomaszdxsn** [comment]
+1

**Comment by thomaszdxsn** [comment]
+1， same issue here

**Comment by dai-shi** [comment]
Thanks for reporting!
Would anyone help investigating this?

Can either of you try to create the reproduction smaller to reveal the issue?

**Comment by thomaszdxsn** [comment]
> Thanks for reporting! Would anyone help investigating this?
> 
> Can either of you try to create the reproduction smaller to reveal the issue?

Can you give some hint? I want investigating but don't know many internal details.

Looks like readAtomState call many times exceed call stack limit

**Comment by dai-shi** [comment]
> Can you give some hint? I want investigating but don't know many internal details.

Yes, without understanding the details, you could still make the reproduction smaller.
And, if you know the atomFamily implementation (which is much easier to understand than core), then you should be able to reproduce the issue without atomFamily.

And, then, we can make a test case.

**Comment by dai-shi** [comment]
https://codesandbox.io/s/atomfamily-recursion-forked-mji6pw
Looks like v1.7.5 already fixed the issue.

If anyone can reproduce the behavior in tests, please submit a PR.
