### ISSUE TITLE
`templateBuilder is not a function` in plugin-react-refresh.mjs

### ISSUE THREAD

**Issue by whitetrefoil** [pmndrs/jotai#1251]
When using `'jotai/babel/plugin-react-refresh'` w/ vite it throws `templateBuilder is not a function` at `/node_modules/jotai/esm/babel/plugin-react-refresh.mjs`.

According to [@babel/template #13719](https://github.com/babel/babel/issues/13719#issuecomment-910252622), when using native mjs, it requires
```
import _template from "@babel/template";
const templateBuilder = _template.default;
```
instead of normal
```
import templateBuilder from "@babel/template";
```

**Comment by dai-shi** [comment]
Yeah, I know this kind of issue is tricky. We have one in zustand: https://github.com/pmndrs/zustand/pull/953

We might need to support both:
```js
import babelTemplate from "@babel/template";
const templateBuilder = babelTemplate.default || babelTemplate;
```

What do you think? @Thisen
