### ISSUE TITLE
async write atom not waiting

### ISSUE THREAD

**Issue by dave10101010** [pmndrs/jotai#1253]
I'm using jotai v1.7.2 with react native and in my onPress event handler I am navigating back after setting the state. 

```
const storage = {
  ...createJSONStorage<string>(() => AsyncStorage),
  delayInit: true,
};

export const itemAtom = atomWithStorage("item", "", storage);
```

In component
```
const setItem = useSetAtom(itemAtom);

onPress={async () => {
  await setItem(item.id);
  props.navigation.goBack();
}}
```

I get a warning in the console when the event handler runs.

`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.`

setItem doesn't seem to be waiting and removing it fixes the warning.

**Comment by dai-shi** [comment]
I'm not sure if this behavior is specific to `atomWithStorage`.
Does it reproduce if you use a normal atom?
```js
export const itemAtom = atom("");
```

**Comment by dave10101010** [comment]
No. When using a normal atom the warning doesn't appear.

Also this doesn't show the warning either.

```
onPress={async () => {
  const longPromise = () =>
    new Promise((res) => {
      setTimeout(() => {
        res("");
      }, 5000);
    });
               
   await longPromise();
   props.navigation.goBack();
}}
```

**Comment by dai-shi** [comment]
So, does this seem an issue only with `atomWithStorage` only with AsyncStorage?

Just to confirm, does this 👇 show the error?
```js
onPress={async () => {
  const longPromise = () =>
    new Promise((res) => {
      setTimeout(() => {
        res("");
      }, 5000);
    });
 longPromise();
 props.navigation.goBack();
}}
```

**Comment by dave10101010** [comment]
```
onPress={async () => {
  const longPromise = () =>
    new Promise((res) => {
      setTimeout(() => {
        res("");
      }, 5000);
    });
 longPromise();
 props.navigation.goBack();
}}
```
There is no error or warning with this.

**Comment by dai-shi** [comment]
Oops, I should ask something different.
How about this? 👇 
```js
const setItem = useSetAtom(itemAtom);

onPress={() => {
  setItem(item.id);
  props.navigation.goBack();
}}
```

**Comment by dave10101010** [comment]
Ok wow thanks. That seems to work with no warning or error. Any idea why that works?

**Comment by dai-shi** [comment]
Hmm, I'm not totally sure how it happens.

If you need further investigation, the best is to provide a **minimal** reproduction with codesandbox with react-dom (not sure what's `goBack` equivalent).
Or, maybe expo snack, if it's only reproducible with react-native.

**Comment by dave10101010** [comment]
It's working now so I'll just close this issue. Thanks
