### ISSUE TITLE
SWC plugins for Jotai

### ISSUE THREAD

**Issue by Thisen** [pmndrs/jotai#1258]
As Next.js has support for SWC plugins through WASM, lets mirror the functionality of our Babel plugins for SWC.

**Comment by Pondorasti** [comment]
+1

**Comment by jeannnemelanie** [comment]
+1

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
+1

**Comment by Thisen** [comment]
Follow work here: https://github.com/pmndrs/swc-jotai
