### ISSUE TITLE
[core] can not export atoms

### ISSUE THREAD

**Issue by u3u** [pmndrs/jotai#1261]
```ts
// ts-error:
// Exported variable 'itmeSizeAtom' has or is using name 'WithInitialValue'
// from external module but cannot be named.ts(4023)
export const itmeSizeAtom = atom(16)
```

**Comment by dai-shi** [comment]
Thanks for reporting.

Confirmed in ts playground: https://tsplay.dev/w8EgdN

<img width="670" alt="image" src="https://user-images.githubusercontent.com/490574/176856387-65e0eaa7-8129-4004-a338-282c25d06ccc.png">

**Comment by emersonlaurentino** [comment]
I'm also having the same problem
<img width="630" alt="Screen Shot 2022-07-01 at 10 07 36" src="https://user-images.githubusercontent.com/10627086/176900667-f775dc69-4967-4c6f-ad71-e9b2a28814df.png">

**Comment by emersonlaurentino** [comment]
I'm also having the same problem
<img width="523" alt="Screen Shot 2022-07-01 at 10 08 37" src="https://user-images.githubusercontent.com/10627086/176900803-e8805696-e3fe-4203-9601-f95f487b8ff1.png">

**Comment by shensven** [comment]
same problem, see here
https://github.com/shensven/Yadds/runs/7123437198

**Comment by emersonlaurentino** [comment]
I downgrade to `jotai@1.7.2` and works well.

**Comment by dai-shi** [comment]
Hi, can anyone (as many as possible) try https://ci.codesandbox.io/status/pmndrs/jotai/pr/1260/builds/267263 build?
Please see "Local Install Instructions".

**Comment by dai-shi** [comment]
Can anyone confirm??

**Comment by u3u** [comment]
<img width="586" alt="image" src="https://user-images.githubusercontent.com/20062482/177903892-ce0a77e3-daec-497e-b0a7-e1c9f1f6e6a0.png">

I confirm it's okay.

**Comment by dai-shi** [comment]
Thanks!
