### ISSUE TITLE
Next.JS example is not wrapped with a Provider - is it intended?

### ISSUE THREAD

**Issue by TenkoSpirit** [pmndrs/jotai#1272]
Hello! I was switching from Vue and had a need for some state management, so I tried Jotai and really enjoy it so far :heart: 

The only thing that is a little bit unclear for me is the use of `Provider`. I have read  the discussion in #1207 and related issues, and it seems like `Provider` is extremely necessarily for SSR / SSG (correct me if I am wrong about it actually). 

So I thought if the `Provider` wrapper component that important, then maybe [NextJS example](https://github.com/vercel/next.js/blob/6b4b0373969bc6810954e95db110829deb557847/examples/with-jotai/pages/_app.tsx) should be updated as well? The example's app isn't wrapped with `Provider` and it's index page seems to be using SSR, which is a little bit confusing then :sweat_smile:

**Comment by dai-shi** [comment]
Yeah, it's better to have it for SSR. It's why jotai is Context based.
@Thisen Will you confirm and update the example?

**Comment by Thisen** [comment]
I'll update the example 👍🏼

**Comment by Thisen** [comment]
https://github.com/vercel/next.js/pull/38398

**Comment by TenkoSpirit** [comment]
> Yeah, it's better to have it for SSR. It's why jotai is Context based. @Thisen Will you confirm and update the example?

Alright, thanks for the clarification!  By the way. [documentation examples](https://jotai.org/docs/guides/nextjs#examples)  might need an update as well 😄

**Comment by MihailPertsev** [comment]
> Yeah, it's better to have it for SSR. It's why jotai is Context based. @Thisen Will you confirm and update the example?

Isn't there already an example with `useHydrateAtoms` and **without** provider?

https://github.com/pmndrs/jotai/issues/340#issuecomment-894239341

Is it too old and outdated?

**Comment by Thisen** [comment]
No, `useHydrateAtoms` behavior hasn't changed 😄

**Comment by MihailPertsev** [comment]
> No, `useHydrateAtoms` behavior hasn't changed 😄

So, what is the "recommended" way then? `useHydrateAtoms` or `Provider` (or both) inside `_app.tsx`?

**Comment by TenkoSpirit** [comment]
> > No, `useHydrateAtoms` behavior hasn't changed smile
> 
> So, what is the "recommended" way then? `useHydrateAtoms` or `Provider` (or both) inside `_app.tsx`?
> 
> @Thisen

Yeah, actually the more I try to understand the more confused I am :smile: 

I have noticed we can provide `initialValues` to the `Provider` component, is it essentially the same as if I were to apply `useHydrateAtoms` and the `Provider` but without passing anything to `initialValues` of the `Provider`? Currently I am hydrating all my atoms inside `_app.tsx` and I am also wrapping root element with `Provider`. So from my understanding it's possible to avoid use of `useHydrateAtoms` completely with `Provider` by passing `initialValues` to it, is it correct?

If it's possible, then I wonder if passing `initialValues` to the `Provider` make some conflict with `useHydrateAtoms` hook? :thinking:

**Comment by Thisen** [comment]
> > No, `useHydrateAtoms` behavior hasn't changed 😄
> 
> So, what is the "recommended" way then? `useHydrateAtoms` or `Provider` (or both) inside `_app.tsx`?
> 
> @Thisen

I'd say that wrapping your app in a `Provider` is recommended for the reasons stated in https://github.com/pmndrs/jotai/pull/1207. `useHydrateAtoms` is optional, however very convenient, because it allows you to keep atoms module specific.

Lets say you have a `CounterPage` in a Next.js app, where you get the `initialCount` from the server, then this allows you to do this:

```ts
import { atom, useAtom } from 'jotai'
import { useHydrateAtoms } from 'jotai/utils'

const countAtom = atom(0)
const CounterPage = ({ countFromServer }) => {
  useHydrateAtoms([[countAtom, countFromServer]])
  const [count] = useAtom(countAtom)
  // count would be the value of `countFromServer`, not 0.
}
```

This has the following benefits:
- It allows the atom to stay module-specific and you don't need to export it and see `initialValues` in `app.tsx`
- `useHydrateAtoms` makes sure the atom only hydrates once.

I hope this is helpful @MihailPertsev and @TenkoSpirit.

**Comment by MihailPertsev** [comment]
@Thisen 

Ok, so we still need to wrap our `_app.tsx` in `Provider`.
If I also have `QueryClientProvider` from `react-query` there then should `Provider` from jotai be the first one or the second one?

**Comment by Thisen** [comment]
> @Thisen
> 
> Ok, so we still need to wrap our `_app.tsx` in `Provider`. If I also have `QueryClientProvider` from `react-query` there, then should `Provider` from jotai be the first one or the second one?
> 
> Is this one correct?
> 
> ```ts
> const MyApp = function MyApp({ Component, pageProps }) {
>     const [queryClient] = useState(() => new QueryClient());
> 
> 
>     return (
>         <QueryClientProvider client={queryClient}>
>             <Hydrate state={pageProps.dehydratedState}>
>              <JotaiProvider>
>                   <Component {...pageProps} />  
>               </JotaiProvider>
>             </Hydrate>
>             <ReactQueryDevtools initialIsOpen={false} />
>         </QueryClientProvider>
>     );
> };
> ```
> 
> Or that one:
> 
> ```ts
> const MyApp = function MyApp({ Component, pageProps }) {
>     const [queryClient] = useState(() => new QueryClient());
> 
> 
>     return (
>     <JotaiProvider>
>         <QueryClientProvider client={queryClient}>
>             <Hydrate state={pageProps.dehydratedState}>
>           
>                   <Component {...pageProps} />  
>          
>             </Hydrate>
>             <ReactQueryDevtools initialIsOpen={false} />
>         </QueryClientProvider>
>      </JotaiProvider>
>     );
> };
> ```

The first one. Then you can use the common `queryClient` if you choose to use `atomWithQuery`.

**Comment by TenkoSpirit** [comment]
> > > No, `useHydrateAtoms` behavior hasn't changed 😄
> > 
> > 
> > So, what is the "recommended" way then? `useHydrateAtoms` or `Provider` (or both) inside `_app.tsx`?
> > @Thisen
> 
> I'd say that wrapping your app in a `Provider` is recommended for the reasons stated in #1207. `useHydrateAtoms` is optional, however very convenient, because it allows you to keep atoms module specific.
> 
> Lets say you have a `CounterPage` in a Next.js app, where you get the `initialCount` from the server, then this allows you to do this:
> 
> ```ts
> import { atom, useAtom } from 'jotai'
> import { useHydrateAtoms } from 'jotai/utils'
> 
> const countAtom = atom(0)
> const CounterPage = ({ countFromServer }) => {
>   useHydrateAtoms([[countAtom, countFromServer]])
>   const [count] = useAtom(countAtom)
>   // count would be the value of `countFromServer`, not 0.
> }
> ```
> 
> This has the following benefits:
> 
> * It allows the atom to stay module-specific and you don't need to export it and see `initialValues` in `app.tsx`
> * `useHydrateAtoms` makes sure the atom only hydrates once.
> 
> I hope this is helpful @MihailPertsev and @TenkoSpirit.

Alright, so basically the hydration hook isn't exactly required but can be very useful. I actually have a good use case for this hook in my project then! Thanks a lot for the explanation and your time ❤️

**Comment by Thisen** [comment]
No problem! Closing this :)
