### ISSUE TITLE
Derived atom inconsistency?

### ISSUE THREAD

**Issue by s-r-x** [pmndrs/jotai#1295]
Hello.

Let's say we have a modal which displays some user data.

```tsx
const Modal = ({ isOpen, info }) => {
  if(!isOpen) return null;
  if(!info) throw new Error("oops, info shouldn't be nil");
  return <div class="modal">{info}</div>;
}
```

corresponding atom
```ts
const userInfoModalAtom = atom({
  isOpen: false,
  user: null
});
const userInfoAtom = atom(get => get(userInfoModalAtom).user?.info);

const openUserInfoModalAtom = atom(null, (_, set, user) => set(userInfoModalAtom({ isOpen: true, user })));
```

parent component
```tsx
const Component = () => {
  const open = useUpdateAtom(openUserInfoModalAtom);
  const { isOpen } = useAtomValue(userInfoModalAtom);
  const info = useAtomValue(userInfoAtom);
  return (
    <>
      <button onClick={() => open({ user: { info: 'i' }})>Show</button>
      <Modal isOpen={isOpen} info={info}/>
    </>
  )
}
```
after the "Show" button has been clicked isOpen is true, but info is still nil, so the app will crash (because info will be commited only after userInfoModalAtom, so there will be a second render). is it expected behavior? i just caught a really unpleasant bug in my app because of this one :(

**Comment by dai-shi** [comment]
`openUserInfoModalAtom` accepts a user object as an argument, so it should be used as `open({ info: "i" })`.

Check this fixed version:
https://codesandbox.io/s/reverent-hertz-zesfql?file=/src/App.js

I find the bug using TypeScript:
https://codesandbox.io/s/great-glitter-cq6jkq?file=/src/App.tsx

Alternative solution is to change `openUserInfoModalAtom`:
```js
const openUserInfoModalAtom = atom(null, (_, set, { user }) => set(userInfoModalAtom({ isOpen: true, user })));
```

**Comment by s-r-x** [comment]
@dai-shi yep, there is a typo in the example, but that's not the point.

i've experimented a little with my code, and it turns out that jotai works just fine. but i'm using react wrapper around fullcalendar, and there is definetely some problems when using jotai write only atoms as callbacks. unfortunately, this one is pretty hard to reproduce with a small example. thanks for your time anyways 👍

**Comment by dai-shi** [comment]
Hope you can make a small reproduction!
