### ISSUE TITLE
[useAtomSelect]: more performant alternative to selectAtom

### ISSUE THREAD

**Issue by eolme** [pmndrs/jotai#1300]
After using splitAtom together with atomFamily, it felt too complicated.

```ts
const selectedNameAtom = atom('');
const isSelected = atomFamily((name: string) => selectAtom(selectedNameAtom, (selected) => selected === name));
```

My suggestion is to implement new hook like this:

```ts
export function useAtomSelect<Value, Selected>(
  atom: Atom<Value>,
  selector: (value: Awaited<Value>) => Selected,
  scope?: Scope
): Selected => {
  // Same as useAtomValue but the value is returned from `getAtomValue` wrapped in the selector function
}
```

**Comment by dai-shi** [comment]
`jotai/utils` provides atom functions as much as possible, not hook functions, with some exceptions (for example, `useAtomCallback`).

I feel like `useAtomSelect` should be in docs (advanced-recipes?).
```js
export function useAtomSelect(a, selector, scope) {
  return useAtomValue(useMemo(() => atom((get) => selector(get(a))), [a, selector]), scope)
}
```

**Comment by eolme** [comment]
But in fact, it's the same thing, additional atoms are also created

**Comment by Nazzanuk** [comment]
@eolme can you give an example with params, what would a selector look like?

**Comment by dai-shi** [comment]
Oh, so you want to avoid creating additional atoms in the hook implementation? How would you do it? Is it for performance, or something else?

**Comment by dai-shi** [comment]
Oops, so I missed the title "more performant"...
(I got confused with "felt too complicated".)

The code in https://github.com/pmndrs/jotai/issues/1300#issuecomment-1193007950 should be performant enough. Creating a new atom is very lightweight. If there's a performance issue, we should fix it entirely. It's not the issue of hook implementation. So, please open an issue if you find a performance hit.

That said, temporary atoms (defined in hooks) are technically less efficient than permanent atoms (defined at module level). So, if the performance is your concern, I think you approach with `atomFamily` is good.
A small nit: `selectAtom` is not very efficient for your need. So, it would be this:
```js
const selectedNameAtom = atom('');
const isSelected = atomFamily((name) => atom((get) => get(selectedNameAtom) === name));
```
