### ISSUE TITLE
Using loadable hangs the tab in some cases.

### ISSUE THREAD

**Issue by levidrain** [pmndrs/jotai#1330]
If an atom in a dependency graph throws, the browser tab freezes when using a derived atom wrapped in a loadable.

https://codesandbox.io/s/jotai-forked-f72bbx?file=/src/App.js

**Comment by dai-shi** [comment]
Thanks for reporting. Please try #1332.

Find "Local Install Instructions" 👇 
https://ci.codesandbox.io/status/pmndrs/jotai/pr/1332
