### ISSUE TITLE
scheduler not mentioned as peerDependency in documentation

### ISSUE THREAD

**Issue by PutziSan** [pmndrs/jotai#134]
When using this package with yarn v2 (yarn berry), it throws while building:

```
Module not found: Error: jotai tried to access scheduler (a peer dependency) but it isn't provided by your application; this makes the require call ambiguous and unsound.
```

I can resolve it by adding [scheduler](https://www.npmjs.com/package/scheduler) to my dependencies.

To solve the problem from your side, I see 2 possibilities:
- You could add an installation instruction, that mentions the need to install react and scheduler or 
- you could define scheduler as a dependency
- (or remove the scheduler-dependency if not needed ;-) )

**Comment by dai-shi** [comment]
Hi, thanks for trying. Currently, scheduler is used in core.

I'm not sure if developers need to install scheduler separately because react-dom depends on it. Same for react-native. Is it something different for you? Does yarn v2 repro the error with react-dom? Are there any other ways to solve this issue?

**Comment by PutziSan** [comment]
I have react-dom installed and this error will throw. 

Yarn v2 is changed so that it forces a package to mention all dependencies in its package.json. If you define scheduler as peerDependency, I have to add it to my dependencies, or it will not be available.

So to make this package usable with yarn 2, the 3 points above are the only possibilities which I can think of.

**Comment by dai-shi** [comment]
> Yarn v2 is changed so that it forces a package to mention all dependencies in its package.json. If you define scheduler as peerDependency, I have to add it to my dependencies, or it will not be available.

Ah, I see. I didn't know the behavior. We'd like to support yarn 2. 🤔

**Comment by dai-shi** [comment]
> You could add an installation instruction, that mentions the need to install react and scheduler

This seems like a solution for us.
