### ISSUE TITLE
useAtomCallback not compatible with async atoms

### ISSUE THREAD

**Issue by mwisnicki** [pmndrs/jotai#1345]
Attempting to read async atom within useAtomCallback results in a promise being thrown:

https://codesandbox.io/s/jotai-useatomcallback-async-error-kuj2vb

```ts
const someAsyncAtom = atom(
  async (get): Promise<string> => {
    console.log("started async action");
    await new Promise((r) => setTimeout(r, 1000));
    return "some data";
  }
);
//...
const handleClick = useAtomCallback(
  useCallback((get) => {
    console.log("clicked", get(someAsyncAtom));
  }, [])
);
```

This results in `Reading pending atom state in write operation. We throw a promise for now.`.

I would have expected for callback to succeed once pending reads are resolved.

Alternatively and perhaps more correctly, have a way to await on on pending atoms.

**Comment by mwisnicki** [comment]
So I found `unstable_promise` option that allows me to await atoms and solves problem but...

I find it highly error prone as you have to know which atoms can be potentially async or always await every single one.

I think the only way to improve it is to track whether atom is async in it's type and then prohibit get on async atom in contexts that do not allow it. Perhaps in such contexts get on async atom should return a promise instead of throwing.

**Comment by mwisnicki** [comment]
Something along these lines:

```ts
type SyncAtom<T> = BaseAtom<T>;
type AsyncAtom<T> = BaseAtom<Promise<T>>;
type Atom<T> = SyncAtom<T> | AsyncAtom<T>;
```

**Comment by dai-shi** [comment]
This is hard one, and we don't have any solution yet. `unstable_promise` is the current workaround.

We can't know statically if an atom is sync or async.

```js
const atom1 = atom('foo') // sync
const atom2 = atom(async (get) => get(atom1)) // async

const atom3 = atom((get) => get(atom1)) // sync
const atom4 = atom((get) => get(atom2)) // async 🤯 
```

**Comment by mwisnicki** [comment]
Perhaps async support should be separated? 

```ts
const atom4 = atomAsync((get) => get(atom2))
```

**Comment by dai-shi** [comment]
Well, the whole point of atoms is not to distinguish sync and async, so it's against the api design. Some atoms can even be async conditionally.

**Comment by mwisnicki** [comment]
Idea: change WriteGetter, Write and useAtomCallback to always deal with `(T | Promise<T>)`.
This is in fact the correct signature and will force users to await everywhere where a value is potentially async.
This will force some unnecessary awaits but it's a minor cost for correctness IMHO.

**Comment by dai-shi** [comment]
That's close to what I did originally. But, for users who never use async features, it's very weird, so it's changed afterwards. Maybe we should have two variant hooks of `useAtomCallback`, or a `mode` option.

**Comment by mwisnicki** [comment]
How does one avoid async in web browser? Can't imagine anything more complex than hello world type apps.

**Comment by dai-shi** [comment]
I meant async atoms, not async features in general.

**Comment by mwisnicki** [comment]
Ideally people should have that state inside jotai so isn't it moot?

In any case this is a helper I came up with:

```ts
import { Atom, Setter } from "jotai";
import { Scope } from "jotai/core/atom";
import { useAtomCallback } from "jotai/utils";

type Awaitable<T> = T | PromiseLike<T>;

type AsyncWriteGetter = {
  <Value>(atom: Atom<Value | Promise<Value>>): Awaitable<Value>;
  <Value>(atom: Atom<Promise<Value>>): Awaitable<Value>;
  <Value>(atom: Atom<Value>): Awaitable<Awaited<Value>>;
};

type Callback<Result, Arg> = undefined extends Arg
  ? (arg?: Arg) => Result
  : (arg: Arg) => Result;

export function useAtomCallbackSafe<Result, Arg>(
  callback: (get: AsyncWriteGetter, set: Setter, arg: Arg) => Promise<Result>,
  scope?: Scope
): Callback<Promise<Result>, Arg> {
  return useAtomCallback(
    (get, set, arg) =>
      callback((atom) => get(atom, { unstable_promise: true }), set, arg),
    scope
  );
}
```

https://codesandbox.io/s/jotai-useatomcallbacksafe-yjb1gq?file=/src/useAtomCallbackSafe.ts

**Comment by dai-shi** [comment]
Not quite sure if we are on the same page, but your workaround would be good for `useAtomCallback` alternative.
(a nit: please don't depend on internal types in `jotai/core/atom` which will be changed without notice.)

In general, I still think `unstable_promise` feature is `unstable` and would like to get more feedbacks (and also see how React will become.)

**Comment by dai-shi** [comment]
This is the limitation in v1, and v2 API fixes it. This is one of the big requests for pushing v2. So, thanks for the feedback.
