### ISSUE TITLE
(atomWithStorage): Exceptions from Storage providers should not be silenced

### ISSUE THREAD

**Issue by mwisnicki** [pmndrs/jotai#1347]
At the moment if anything throws inside StorageSync the error will be swallowed and not even logged in console.
This behavior is very unfriendly.

```ts
const storage = createJSONStorage(() => localStorage);
const prefsAtom = atomWithStorage(
  "prefs",
  { x: 1 },
  {
    ...storage,
    getItem: (key) => {
      console.log("loading", key);
      throw new Error("Cannot load prefs");
      return storage.getItem(key);
    }
  }
);
```

https://codesandbox.io/s/jotai-useatomcallback-async-error-forked-zr737n?file=/src/App.tsx:187-470

I had a bug where zod couldn't parse data but took me a while to figure out because of suppressed exceptions.

IMHO exceptions should be at the very least logged with `console.error` if not made fatal.

**Comment by dai-shi** [comment]
Good point. We should only catch if (a) storage doesn't have an item or (b) if JSON.parse files with defaultStorage.

I can work on it unless anyone else would like to take it.

**Comment by joshmkennedy** [comment]
Would the solution to this be something like this, or is there a better way?

```ts
  const handleErr = ()=>{
    //Logic for deciding if return initialValue or not
  }
  const getInitialValue = () => {
    try {
      const value = storage.getItem(key)
      if (value instanceof Promise) {
        return value.catch(handleErr)
      }
      return value
    } catch (e) {
      return handleErr(e)
    }
  }
  ```

**Comment by dai-shi** [comment]
It's close. We should return initial value if (a) or (b), otherwise _throw_ the error.

**Comment by dai-shi** [comment]
I'll work on it.

**Comment by dai-shi** [comment]
Could you try #1363?
https://ci.codesandbox.io/status/pmndrs/jotai/pr/1363
Find "Local Install Instruction" ☝️

**Comment by joshmkennedy** [comment]
Yeah, that works!
https://codesandbox.io/s/jotai-useatomcallback-async-error-forked-bgpmet
