### ISSUE TITLE
loadable states need to be enum, not strings

### ISSUE THREAD

**Issue by mschipperheyn** [pmndrs/jotai#1352]
'loading' | 'hasData' | 'hasError' should be an enum, not strings. Strings lead to typos, typos lead to unnecessary errors.

enum LoadableState {
   loading = 'loading',
   error = 'error',
   hasData = 'hasData'
}

**Comment by dai-shi** [comment]
I believe union type should help to some extent.
Using string enums may have pros and cons. I prefer union types.
Thanks for suggestion anyway.

**Comment by dai-shi** [comment]
Closing this, but feel free to have some discussions here.
