### ISSUE TITLE
devtools: using useAtomsSnapshot in useAtomsDevtools

### ISSUE THREAD

**Issue by Aslemammad** [pmndrs/jotai#1356]
From @dai-shi:

> As you notice, we have common code in useAtomsDevtools and useAtomsSnapshot. We may want to try refactoring to use useAtomsSnapshot inside useAtomsDevtools. What do you think? Let's tackle it later.

I guess this would be possible, although we haven't investigated it properly!

**Comment by dai-shi** [comment]
(btw, we don't usually create utils with utils. so, this is an exception with historical reasons.)
