### ISSUE TITLE
jotai/urql errors suspends forever and cannot be caught

### ISSUE THREAD

**Issue by lukechu10** [pmndrs/jotai#1359]
When the graphql request errors, suspense is never resolved but no error is visible. There doesn't seem to be any way of detecting for error and for recovering.

Example: https://codesandbox.io/s/jotai-urql-graphql-error-rrt80o

Possibly related to #1358

**Comment by dai-shi** [comment]
Error handling isn't simply supported.
As #1239 is done, I'm planning to apply the same technique for jotai/urql, which might introduce some big changes. Will see.

Note that you should have the component tree in this order.
```jsx
<Provider>
  <ErrorBoundary>
    <Suspense>
```

**Comment by dai-shi** [comment]
#1381 is ready to play with atomWithQuery.
https://ci.codesandbox.io/status/pmndrs/jotai/pr/1381
Find "Local Install Insturctions" ☝️

**Comment by dai-shi** [comment]
https://codesandbox.io/s/jotai-urql-graphql-error-forked-pk5co1?file=/src/App.js
