### ISSUE TITLE
Problem with ESM/CJS configuration and Rollup

### ISSUE THREAD

**Issue by DynamicArray** [pmndrs/jotai#136]
Seems your config is sending mixed messages about your package state to Rollup. I don't claim to understand the issue, but the problem arises when using [Snowpack](https://www.snowpack.dev/). @FredKSchott describes here: https://github.com/pikapkg/snowpack/discussions/1321

**Comment by dai-shi** [comment]
Thanks for reporting. I need to understand the problem. Will read the description.

**Comment by dai-shi** [comment]
OK, the issue is in use-context-selector. Let me look for a solution.
