### ISSUE TITLE
React Native (Expo) atomWithStorage error: "window.addEventListener is not a function"

### ISSUE THREAD

**Issue by mkossoris** [pmndrs/jotai#1373]
I'm running into an issue using the `atomWithStorage` util with React Native. Here's the relevant code I'm trying with it:

Creating the atom:
```ts
import { atomWithStorage, createJSONStorage, loadable } from "jotai/utils";
import AsyncStorage from "@react-native-async-storage/async-storage";

const storage = createJSONStorage<boolean>(() => AsyncStorage);
export const walkThroughStatusAtom = atomWithStorage(
  "@walkThroughStatus",
  false,
  storage
);
```

Using the atom:
```ts
const [walkThroughStatus, setWalkThroughStatus] = useAtom(walkThroughStatusAtom);
```

Running this, I get the following error:
```
TypeError: window.addEventListener is not a function. (In 'window.addEventListener('storage', storageEventCallback)', 'window.addEventListener' is undefined)
```

It would appear this is happening at the following line: https://github.com/pmndrs/jotai/blob/main/src/utils/atomWithStorage.ts#L86

There's a check that window is not undefined [here](https://github.com/pmndrs/jotai/blob/main/src/utils/atomWithStorage.ts#L79), but at least when running the app with Expo, window is indeed defined, so the check fails to prevent the `window.addEventListener` from being called. I'm new to React Native, so I'm not sure if window is a global variable once the app is actually built and running on a native environment. This may just be an incompatibility with Expo, but with Expo being a common tool for React Native, it might be something to look into. Perhaps the check could be changed to:

```ts
if (typeof window !== 'undefined' && typeof window.addEventListener === 'function')
```

**Comment by dai-shi** [comment]
Thanks for reporting and sorry for the regression. Your suggestion seems good. Would you be able to open a PR?

**Comment by mkossoris** [comment]
Yeah for sure, I'll do that tonight!
