### ISSUE TITLE
atomWithStorage is broken with Gatsby-SSG in 1.8.1

### ISSUE THREAD

**Issue by jablonski** [pmndrs/jotai#1377]
Jotai 1.8.1 doesn't work in Gatsby (SSG) anymore, caused by latest changes for atomWithStorage (https://github.com/pmndrs/jotai/pull/1363). Project works fine with Jotai 1.8.0.

```
error "location" is not available during Server-Side Rendering. Enable "DEV_SSR" to debug this during "gatsby develop".
 540 |   const hashStorage = {
 541 |     getItem: (key2) => {
 542 |       const searchParams = new URLSearchParams(location.hash.slice(1));
 |   WebpackError: ReferenceError: location is not defined

```

**Comment by dai-shi** [comment]
Thanks for reporting and sorry for the regression. Let me work on it.

**Comment by dai-shi** [comment]
(Hmm, I wonder why `window.addEventListener` hadn't caused any issues before.)

**Comment by dai-shi** [comment]
Can you please try https://ci.codesandbox.io/status/pmndrs/jotai/pr/1378 ?
Find "Local Install Instructions".

**Comment by jablonski** [comment]
Thanks for the updated package, works without problems.

**Comment by jablonski** [comment]
Just deployed 1.8.2, works perfectly. Thanks for the quick update!
