### ISSUE TITLE
Typescript issue with Atoms of different types

### ISSUE THREAD

**Issue by elz5star** [pmndrs/jotai#1387]
Hooks such as useAtom, useAtomValue and useSetAtom have a typescript error when using atoms of different types. As demonstrated in this typescript playground: https://tsplay.dev/N5Lk2w

**Comment by dai-shi** [comment]
Would anyone like to tackle this? I'll take it otherwise. It may require decent TS skills. (Also, note that we don't generally export types.)

**Comment by carlesba** [comment]
I think it's doable if types are exported. Is that an option?

**Comment by dai-shi** [comment]
It doesn't sound like a good option, but if you have an idea, can you please try with typescript playground?

Here's something you can start with: https://tsplay.dev/WKRMgm

**Comment by carlesba** [comment]
Great! Thanks for the playground.

Here's the **solution** I was mentioning https://tsplay.dev/mAQMRm

It works exporting a `AtomUnion` type to infer the values correctly. 
The **issue** I found is that typescript is not inferring  unions of generic values correctly (ie, `Foo<number> | Foo<string>`). 
Curiously,  it does it well for things like functions. Like, if you pass `value: (() => string) | (()=> number)` it will infer `() => string | number`.

A generic `AtomUnion` repackages the types converting things like `Atom<number> | Atom<string>` into `Atom<number | string>`.

Now, despite this is possible **I'm not sure this is something we should encourage**. There're some side effects to take into account. 
Users could find issues when setting values into the atoms as the new types are wider.  
Say,
```ts
const a = atom(0); 
const b = atom('');
function run(a: Atom<string|number>){
  const setA = useSetAtom(a)
  // ...
  setA("bad") // would break atom a
  setA(1) // would break atom b
```
Here, both cases are valid for the type-checker but can break in runtime. 

I'd love to know your opinion here @dai-shi

**Comment by dai-shi** [comment]
Here's the solution I had in mind (but didn't confirm until now): https://tsplay.dev/WJ5MZm
It's a breaking change in types, but I think we'd do with minor version up, if we were to do it.
Do you see any drawbacks other than that?

**Comment by carlesba** [comment]
Nice! way better.

**Comment by dai-shi** [comment]
I did for the core types in #1427. Will continue.

**Comment by dai-shi** [comment]
I'm not quite sure if/how this causes some troubles with existing app code.

**Comment by dai-shi** [comment]
https://tsplay.dev/werx1N
Okay, deprecation works. Let's do that.

**Comment by dai-shi** [comment]
Actually, we don't need to deprecate them. Just overloading seems to work.
