### ISSUE TITLE
Issue: atom get memory leak when using SSR

### ISSUE THREAD

**Issue by leedoopal** [pmndrs/jotai#1388]
Next.js is in use, and the test applied filter() to atom get.
For the test, 600 requests were sent for 1 minute.

**version**
next 12.2.2
react 17.0.2
jotai 1.7.6

testing tool: k6
```
const options = {
  stages: [
    { duration: "1m", target: 600 },
    { duration: "1m", target: 600 },
    { duration: "1m", target: 600 },
    { duration: "1m", target: 600 },
    { duration: "1m", target: 600 },
  ],
};
```

<br/>

### Test
```javascript
// _app.js
return (
  <Provider>
    <Component {...pageProps} />
  </Provider>
)
```

```javascript
// component
const [readData] = useAtom(readDataAtom);

return (
  <div>
    <div>{JSON.stringify(readData)}</div>
   </div>
  );
```

```javascript
// store
export const readDataAtom = atom((get) => {
  return get(dataAtom).modules.filter(({ moduleSeq }, i) => moduleSeq > i + 210);
});
```

### Result

![jotai_get-selector-atom](https://user-images.githubusercontent.com/39582981/187709020-ec371106-a3b8-498f-b435-9dba9303a080.jpeg)

It started at 153 MB, but it is 269 MB even after 5 minutes.
Why is there a memory leak?
I want help. thanks

**Comment by dai-shi** [comment]
Hmmm, not sure. Can you make sure if it doesn't happen if you eliminate `useAtom`?

**Comment by leedoopal** [comment]
Yes I'm sure. 
eliminate useAtom, there is no memory change.

Captured every 30 seconds.
<img width="201" alt="스크린샷 2022-09-01 오전 12 32 56" src="https://user-images.githubusercontent.com/39582981/187719048-7c5321ff-73cf-46c2-858e-6b8c8ed7b1d3.png">

**Comment by dai-shi** [comment]
Thanks. Now, I need someone to help on this. We need to dig into it how this happens. I'm not very good at profiling.

Can you simplify to use just one count atom `const countAtom = atom(0)`, and see if the issue persists?

Another thing to try is around `Provider`. It's the major place to consume memory. I wonder if nextjs unmounts `Provider` clearly for each session. Or, it's using a common `Provider` for all sessions.

**Comment by leedoopal** [comment]
thank you! No memory leak occurs when `atom(0)` or `atom(somethingData)` is used. (next.js and ssr)

When tested, only specific data like code below, a leak occurs.
Do you have any guesses?
```javascript
const readDataAtom = atom((get) => {
  return get(data).filter(
    ({ seq }, i) => seq > i + 210
  );
});
```

I don't know if next.js clearly `Provider` well. I'll look for it and tell you.

**Comment by dai-shi** [comment]
> When tested, only specific data like code below, a leak occurs.

That's interesting.
How about this?

```js
const dataAtom = atom(0)
const readDataAtom = atom((get) => get(dataAtom))
```

**Comment by leedoopal** [comment]
1) only get - no memory change
```javascript
const dataAtom = atom(0)
const readDataAtom = atom((get) => get(dataAtom))
```

2) calculation - no memory change
```javascript
const dataAtom = atom(10);
const readDataAtom = atom((get) => get(dataAtom) * 2);
```

3) filter() on array of length 2 - no memory change
```javascript
const dataAtom = atom([{ seq: 10 }, { seq: 20 }]);
const readDataAtom = atom((get) =>
  get(dataAtom).filter((value) => value.seq > 10)
);
```

---

The dummy data I tested is 28300 lines of json data. Is there a problem if the quantity is large?

**Comment by dai-shi** [comment]
Don't know...
How about this instead? (with large data)
```js
const readDataAtom = atom((get) =>
  get(dataAtom).find((value) => value.seq > 10)
);
```

**Comment by leedoopal** [comment]
ah Sorry, I think I was doing the test wrong. I'll try everything again and let you know the results 😢

**Comment by leedoopal** [comment]
Thank you for waiting. I tested again.

1. only get - no memory change
```javascript
const dataAtom = atom(0)
const readDataAtom = atom((get) => get(dataAtom))
```
![0902_jotai_only-get](https://user-images.githubusercontent.com/39582981/188157623-43f749db-29b1-447f-b868-56860d837a51.jpeg)


2. calculation - no memory change
```javascript
const dataAtom = atom(10);
const readDataAtom = atom((get) => get(dataAtom) * 2);
```
![0902_jotai_calc](https://user-images.githubusercontent.com/39582981/188157696-da9691a9-75d4-4852-8e43-2bde0717aa87.jpg)


3. filter() on array of length 2 - no memory change
```javascript
const dataAtom = atom([{ seq: 10 }, { seq: 20 }]);
const readDataAtom = atom((get) =>
  get(dataAtom).filter((value) => value.seq > 10)
);
```
![0902_jotai_filter](https://user-images.githubusercontent.com/39582981/188157877-a2a5d1ad-9d71-4a77-81a9-9fa4f91ae735.jpeg)

4. large data - no memory change
```javascript
const readDataAtom = atom((get) =>
  get(dataAtom).find((value) => value.seq > 10)
);
```
![0902_jotai_large](https://user-images.githubusercontent.com/39582981/188174908-498b0a88-99cc-41b9-b51c-347871cadf43.jpeg)

---

There was obviously a leak, but when I tried it again it disappeared.
I'll close the issue as there's no problem.

I'll leave an issue if I find it again.

**Comment by dai-shi** [comment]
> large data - no memory change

How about large data with `.filter()`??

**Comment by leedoopal** [comment]
@dai-shi yes! I use .filter()

**Comment by leedoopal** [comment]
Hi! 
The test was conducted again today the same conditions.

#### [test - large data with .filter()]
![0907_jotai_large](https://user-images.githubusercontent.com/39582981/188899964-7c1fab30-819d-48c5-bbcc-35403d31969a.jpg)
Still be found to have in a memory leak.

You'd better do to get any confidence in the results?
Test once a day for 5 days, or Should I try another tool other than k6?

Tell a good idea, please.

**Comment by dai-shi** [comment]
Not sure, but does .filter() return a big array?
How about just returning `.length`? We would need to know what is "large".

**Comment by leedoopal** [comment]
Thanks!

"large" mean a big array, as you said. I ran two test.

1) just return `.length`
<img width="200" alt="jotai_data-get_length" src="https://user-images.githubusercontent.com/39582981/189516884-47728bf5-69c5-4a87-b5ba-e12467d55771.png">

2) return `.filter().length` with big array
```javascript
// example
const readDataAtom = atom((get) =>
  get(dataAtom).filter((value) => value.seq > 10).length
);
```
<img width="198" alt="jotai_data-get_filter_length" src="https://user-images.githubusercontent.com/39582981/189516957-74487522-e23e-4cf8-a651-f2938da52eb7.png">

There was no leak in both cases, and there was a leak when returning a big array.

**Comment by dai-shi** [comment]
Are you sure that you are not storing the big array somewhere else?
Another question: Is this running in production mode?

**Comment by leedoopal** [comment]
Are you saying that the big arrays are coming into the store?
I can be sure of that.

I'm in developer mode, I'll try again production mode!

**Comment by leedoopal** [comment]
no licks in production mode! thank you!! 😃 

test: return `.filter()` with big array
<img width="200" alt="스크린샷 2022-09-11 오후 8 17 43" src="https://user-images.githubusercontent.com/39582981/189524644-75dfd728-e06c-4c30-94ce-9d6003ccfecc.png">

I will test one more day tomorrow and close the issue!!!

**Comment by dai-shi** [comment]
Thanks. Good to know.

I'm still concerned how it can happen.
We have two extra states in dev mode.
https://github.com/pmndrs/jotai/blob/fc96b2c72a057cb00afef0dfbe2ca30cbb7b23c4/src/core/store.ts#L176-L179

Assuming you are not using `'jotai/devtools'`, `mountedAtoms` can only leak. But, it only depends on the number of atoms, not the size of data.

**Comment by leedoopal** [comment]
Testing in production mode again today.

**production mode**
<img width="201" alt="스크린샷 2022-09-12 오후 6 13 16" src="https://user-images.githubusercontent.com/39582981/189616973-2abfd6af-8551-4bed-9933-f9d058eba407.png">
There was no memory leak!


---
Thank you for letting me know! got me thinking again.
I thought, there is large page data in next.js, so I tested it with less than 128kb.
original data: >= 500kb
(docks: https://nextjs.org/docs/messages/large-page-data)

**< 128kb data**
<img width="196" alt="스크린샷 2022-09-12 오후 5 56 40" src="https://user-images.githubusercontent.com/39582981/189613634-4f507a71-9f57-4251-b5cd-79fc8a0025a4.png">

There was no leak.
I think there may be a cause here.

**Comment by dai-shi** [comment]
> < 128kb data
> There was no leak.

Do you mean it's even in DEV mode?

**Comment by leedoopal** [comment]
yes. It's Dev Mode

**Comment by dai-shi** [comment]
In summary: it doesn't sound like there's leak on jotai end, right?

**Comment by leedoopal** [comment]
right! I think it's a problem with next.js.

Thanks for helping with testing, and thanks for making jotai.
I will use it well!
