### ISSUE TITLE
App getting stuck when using loadable async atom in strict mode

### ISSUE THREAD

**Issue by SpringNyan** [pmndrs/jotai#1392]
Repro: https://codesandbox.io/s/8ez0zg

App getting stuck after click the button. If StrictMode component is removed, it works well.

Seems this issue is occurred after 1.7.8.

**Comment by dai-shi** [comment]
Simplified version: https://codesandbox.io/s/dark-currying-uebnpe?file=/src/App.js
Issue confirmed without atomFamily. It doesn't happen without loadable.

Maybe #1091 caused this, but not sure.

Seems like a tough one.
