### ISSUE TITLE
No way to make plugin-react-refresh work with custom atom creators

### ISSUE THREAD

**Issue by hackwaly** [pmndrs/jotai#1414]
It is hardcoded. Can we make it configable? 

https://github.com/pmndrs/jotai/blob/fc96b2c72a057cb00afef0dfbe2ca30cbb7b23c4/src/babel/utils.ts#L20-L42

**Comment by dai-shi** [comment]
Do you know how to do it?

**Comment by hackwaly** [comment]
Yes, I do. I can send PR if i have time.

**Comment by dai-shi** [comment]
sounds great. cc @Thisen

**Comment by Thisen** [comment]
Created a PR for this: https://github.com/pmndrs/jotai/pull/1480
