### ISSUE TITLE
[react-query] Undefined query in QueryCache 

### ISSUE THREAD

**Issue by danielr18** [pmndrs/jotai#1416]
It looks like after https://github.com/pmndrs/jotai/pull/1313 got merged, there's always an empty query in the cache.

This query is added when the QueryObserver is created with just the default options.
https://github.com/pmndrs/jotai/blob/476a3f24cb417257d47c319c155b76198a4f9593/src/query/atomWithQuery.ts#L111

<img width="829" alt="image" src="https://user-images.githubusercontent.com/9046616/190182533-e00f93c7-c7ed-4371-a7de-07ff444d1fc5.png">

This causes a warning to show up when using react query devtools, as it uses the query key as the react key.
<img width="909" alt="image" src="https://user-images.githubusercontent.com/9046616/190182873-41fd132a-c123-4d1b-9577-f1c5b663caaf.png">

**Comment by dai-shi** [comment]
Thanks for reporting! We are kind of still struggling with its implementation.
