### ISSUE TITLE
[jotai/query] atomWithQuery gets stuck in react strict mode

### ISSUE THREAD

**Issue by mwisnicki** [pmndrs/jotai#1418]
https://codesandbox.io/s/jotai-query-stuck-in-strict-8ffrtn?file=/src/App.tsx

If `<React.StrictMode>` is enabled then the query is stuck showing placeholder data.

Also, in bigger application I have this problem even without placeholderData - there the query is forever stuck in loading state with no observers attached. Seems to happen when there are many derived atoms. Hopefully it's the same root cause since I haven't been able to create smaller test case without placeholderData.

**Comment by dai-shi** [comment]
Thanks for reporting. Seems like a bug. We have struggled with StrictMode and something might still be missing.
Actually, we have one test failing with StrictMode.
#1417 may or may not be related.

Can you or anyone create a test case from the codesandbox, and then possibly try to fix it (though, it requires deeper understanding of the current implementation.)

**Comment by mwisnicki** [comment]
I wanted to debug it in context of my project but unfortunately I was unable to make it work.
I've checked out jotai and replaced dependency with workspace however it fails to resolve type.
Unfortunately I have no experience using workspaces and no other idea how to do it.

**Comment by dai-shi** [comment]
#1435 would probably fix it, if it's done.
currently, it seems to work: https://codesandbox.io/s/jotai-query-stuck-in-strict-forked-qr2fzs

**Comment by mwisnicki** [comment]
Thanks, it seems to also work with my full project. Requests are cancelled as before due to unmount but then retried on mount.
