### ISSUE TITLE
Write tests for utils/useAtomCallback

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#143]
Discussed in #60 and created PR #140.
`./tests/utils/useAtomCallback.ts` is still missing.

**Comment by Aslemammad** [comment]
Hey, I'll work on it.

**Comment by dai-shi** [comment]
@Aslemammad That's nice. This hook is a bit difficult to understand. So, feel free to ask me questions for clarification. (BTW, are you in the discord server?)

**Comment by Aslemammad** [comment]
@dai-shi Sure, yes, I am.

**Comment by Aslemammad** [comment]
#182 Close issue.
