### ISSUE TITLE
No type checking of atom setter update value for literal unions 

### ISSUE THREAD

**Issue by AlmostBearded** [pmndrs/jotai#1442]
Hey 👋 

It seems like the wrong generics are derived for the set function used inside atom setters when trying to set an atom that takes a literal union value.

```
type LiteralUnion = 'string-1' | 'string-2';

const atomWithLiteralUnion = atom(null, (get, set, a: LiteralUnion) => console.log(a));

const setAtomWithLiteralUnion = useSetAtom(atomWithLiteralUnion);
setAtomWithLiteralUnion('string-3'); // ✅ type error

const someOtherAtom = atom(null, (get, set) => {
  set(atomWithLiteralUnion, 1); // ✅ type error
  // derived type of set 👇
  // <null, LiteralUnion, void>(atom: WritableAtom<null, LiteralUnion, void>, update: LiteralUnion)

  set(atomWithLiteralUnion, 'string-3'); // ❎ no type error
  // derived type of set 👇
  // <null, LiteralUnion | "string-3", void>(atom: WritableAtom<null, LiteralUnion | "string-3", void>, update: LiteralUnion | "string-3") => void

  // workaround to get type checking is to explicitly type the set function which is easy to forget
  set<null, LiteralUnion, void>(atomWithLiteralUnion, 'string-3'); // ✅ type error
});
```

Is this a limitation of typescript or could the typings of the set function potentially be improved? 🤔 

Thx for the help :)

**Comment by dai-shi** [comment]
I can't reproduce it in TypeScript playground: https://tsplay.dev/wgl4MN

**Comment by AlmostBearded** [comment]
That is really strange. Even with my exact TS and jotai versions this codesandbox correctly reports a type error. https://codesandbox.io/s/typescript-playground-export-forked-bws29t

Seems like some weird problem with my local setup. I'll investigate 🤔 

Thanks for the help. I guess this issue can be closed then. I'll reopen it if it turns out to be a jotai issue after all.
