### ISSUE TITLE
useAtomsDevtools inside React.StrictMode shows twice in Redux Dev Tools

### ISSUE THREAD

**Issue by sazzer** [pmndrs/jotai#1445]
Hi there,

Firstly, it's entirely possible that I've done something wrong here, so apologies if so!

I've noticed that if I'm calling `useAtomsDevtools()` from *inside* of `React.StrictMode` then I get two different stores showing up in the Redix Dev Tools, where the one that is selected by default is not useful:

```
  const AtomsDevtools: React.FC<AtomsDevtoolsProps> = ({ children }) => {
    useAtomsDevtools('linaria');
    return children;
  };

  ReactDOM.createRoot(root).render(
    <JotaiProvider>
      <React.StrictMode>
        <AtomsDevtools>
          <AuthProvider>
            <Suspense fallback={'Loading'}>
              <UI />
            </Suspense>
          </AuthProvider>
        </AtomsDevtools>
      </React.StrictMode>
    </JotaiProvider>
  );
```

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/66072/192097487-0ed14f03-63ec-44f7-a06e-6b14aff7240f.png">

If I move it around so that `useAtomsDevtools` is instead *outside* of the `React.StrictMode` then everything works as expected:
```
  const AtomsDevtools: React.FC<AtomsDevtoolsProps> = ({ children }) => {
    useAtomsDevtools('linaria');
    return children;
  };

  ReactDOM.createRoot(root).render(
    <JotaiProvider>
      <AtomsDevtools>
        <React.StrictMode>
          <AuthProvider>
            <Suspense fallback={'Loading'}>
              <UI />
            </Suspense>
          </AuthProvider>
        </React.StrictMode>
      </AtomsDevtools>
    </JotaiProvider>
  );
```
<img width="821" alt="image" src="https://user-images.githubusercontent.com/66072/192097569-1cd551c2-4c8e-4755-8870-72b8d129b7ed.png">

I *assume* this is because `React.StrictMode` does the double-render trick to catch certain issues, but it seems to have a negative effect in this case.

Cheers

**Comment by dai-shi** [comment]
@Aslemammad Can you investigate this please?

**Comment by dai-shi** [comment]
@sazzer 
#1456 should fix. Can you try it?
https://ci.codesandbox.io/status/pmndrs/jotai/pr/1456
Find "Local Install Instructions" ☝️
