### ISSUE TITLE
Setter always causes a TypeScript error (Expected 1 arguments, but got 2.)

### ISSUE THREAD

**Issue by divmgl** [pmndrs/jotai#1452]
Hi! This piece of code causes a TypeScript compiler error:

```tsx
const _profileAtom = atom<Profile | null>(null)
export const profileAtom = atom<Profile | null>(
  (get) => get(_profileAtom),
  (_get: Getter, set: Setter, newProfile: Profile) => { // Error starts here
    set(_profileAtom, newProfile)
    set(activeTenantAtom, newProfile.tenants[0])
  }
)
export const activeTenantAtom = atom<Tenant | null>(null)
```
```
Expected 1 arguments, but got 2. ts(2554)
```

I'm really unsure what's going on here and how to fix this. It happens with any kind of writable atom.

Here's the CodeSandbox recreating this problem:

https://codesandbox.io/s/bitter-field-647k7t?file=/src/App.tsx

**Comment by divmgl** [comment]
I was able to bypass this for now using `@ts-expect-error`, but not a permanent solution.

**Comment by dai-shi** [comment]
You are defining read only atoms. Better to try `atom(null as Foo | null)`.

**Comment by divmgl** [comment]
Haha oh my gooooodness. Yes, you're right. I'm still glad I asked given that I spent way too much time on this already.

```tsx
export const profileAtom = atom<Profile | null, Profile>(
  (get) => get(_profileAtom),
  (_get: Getter, set: Setter, newProfile: Profile) => {
    set(_profileAtom, newProfile)
    set(activeTenantAtom, newProfile.tenants[0])
  }
)
```

To anyone seeing this in the future, you have to specify a second generic that defines what the setter will be.


```tsx
export const profileAtom = atom<Profile | null, Profile>(
```

**Comment by dai-shi** [comment]
I see. The problem was only the second one.
