### ISSUE TITLE
[jotai/query] atomWithQuery gets stuck when request takes too long

### ISSUE THREAD

**Issue by AlbinAxtelius** [pmndrs/jotai#1454]
https://codesandbox.io/s/long-request-does-not-render-wnpber

When doing a promise inside a `atomWithQuery` that takes longer than 1 second to resolve the atom doesn't trigger a render and gets stuck on the fallback component provided to `<Suspense>`. Methods like `onSettled` doesn't trigger.

When jotai is locked to version `1.8.3` it works and renders when the promise resolves but when updating to `1.8.4` it gets stuck.

**Comment by dai-shi** [comment]
Thanks for reporting. Yeah, I added the 1 sec timeout in the recent refactor. It's not very predictable. So, it's being revisited. #1435 will fix it eventually.
