### ISSUE TITLE
Preact

### ISSUE THREAD

**Issue by prbxr** [pmndrs/jotai#146]
What is the compatibility with Preact?
Currently it seems to be working.
But I saw in the README Jotai requires scheduler dependency...

**Comment by dai-shi** [comment]
Goooood point. Does it work with the latest version v0.10.0?
Yes, it depends on scheduler, which is technically for concurrent mode, so it may not be so important in preact?

**Comment by dai-shi** [comment]
Does it mean preact has a scheduler compat layer?

**Comment by prbxr** [comment]
jotai 0.10.0
preact 10.5.4
I don't know about any scheduler compat layer, at least it is not in the api and not in it's types
I don't know if it is important in preact, don't undestand it. It does not use concurrent yes. It says it is like react 15.

**Comment by dai-shi** [comment]
> jotai 0.10.0
> preact 10.5.4

Cool. If it works, it works. There's no intention to kill the compatibility.
In a longer term, jotai (and many other react state libs) will depend on a new hook useMutableSource once it lands. I assume preact will provide a compat hook then.

**Comment by dai-shi** [comment]
jotai v0.10.2 should work better with preact.
Please give it a try.

In summary:
- we don't intend to kill the compatibility with preact
- the current version should work
- in the future version that depends on uMS, we'd need preact compat layer support.
- feel free to file an issue if someone find any problems with preact.

Having that said, let's close this issue.
