### ISSUE TITLE
Export all types used in exported declarations

### ISSUE THREAD

**Issue by mwisnicki** [pmndrs/jotai#1467]
At the moment jotai is very shy about exposing type declarations however it leads to huge pain when I try to create any sort of wrappers, helpers or abstractions on top of jotai.

Let's say for example I want to provide helper for working with results of `atomWithStorage` then I need `SetStateActionWithReset` which is not exposed.

Right now I have to duplicate this type and I can't even do it fully because RESET symbol is not exported. Sometimes it's possible to extract types with some convoluted use of `Parameters<>` or `ReturnType<>` but that's also not great.

I get you prefer to keep public API surface as small as possible to lower maintenance burden but this drives library consumers to writing more code that is even more brittle across library versions so I would like you to reconsider.

If this was any other language than TypeScript the types would have to be exposed. In fact they are effectively exposed except they are currently anonymous outside the library so the only thing you are keeping private is their names. IMHO this has too many downsides for very little gain.

**Comment by dai-shi** [comment]
I would disagree with "very little gain". It actually was a **huge** pain maintaining a library with exposing too many "internal" types. What we assume public types are "interfaces". Type aliases are internal types.

I understand `SetStateActionWithReset` is a little pain. But, what I'm confused is that `RESET` symbol is not exported. Isn't it exported?

That said, I would consider making some internal types public, if there was too much pain. (Like `AtomFamily` case)

**Comment by mwisnicki** [comment]
You're right about `RESET`. IntelliJ couldn't figure it out and I looked at index.ts but it's exported from utils.ts.

**Comment by mwisnicki** [comment]
What about exporting non-public types in a way that's obvious to come with no stability guarantees? For example via a file called unstableTypes.ts?

You would be free to change them as you see fit but library consumers would have much easier life too.

**Comment by dai-shi** [comment]
Something like this?
https://github.com/pmndrs/valtio/blob/6e58c9d0edc24a2507c69bc2aaf52b03c13786d5/src/vanilla.ts#L20-L24

I would still carefully choose which internal types to export.

**Comment by dai-shi** [comment]
Related: https://github.com/pmndrs/jotai/discussions/1532

Closing this for now. Please open a new discussion if anyone has a pain for specific cases.
