### ISSUE TITLE
State not found v0.10.0 for async atoms

### ISSUE THREAD

**Issue by fkocovski** [pmndrs/jotai#147]
Async `atoms` that have primitive `atoms` as dependents can't find the state if multiple ones are used inside a component.

Repro with `atomFamily`: https://codesandbox.io/s/zen-hellman-plh9w

Repro with `atom`: https://codesandbox.io/s/suspicious-germain-zr0wu

**Comment by garrettmk** [comment]
I had a similar issue, but it doesn't look like it was solved by #148. Here's a [sandbox](https://codesandbox.io/s/crimson-silence-xvg3o) to illustrate. The atom dependencies look like this:

Primitive atom -> async atom (simulated fetch) -> derived atom

Changing the primitive atom causes the async atom to re-fetch, as expected. However the derived atom never resolves.

**Comment by dai-shi** [comment]
@garrettmk Thanks for reporting. The sandbox link has the code yet unchanged? I'll try to repro in test.

**Comment by dai-shi** [comment]
@garrettmk I'll merge #148, and work on the issue reported as a new PR. Would you create a new issue with the correct sandbox link please?
