### ISSUE TITLE
atomWithStorage inside Provider returns wrong initialValue if Android app is destroyed

### ISSUE THREAD

**Issue by sregg** [pmndrs/jotai#1479]
When a React Native Android app is killed (aka destroyed) by the OS to free up memory and is re-opened, `useAtom` will return the wrong initial value of an `atomWithStorage` if it's inside the Provider.

Minimum Reproducible Project: https://github.com/sregg/JotaiAndroidDestroyed

**Comment by dai-shi** [comment]
(Looked at your reproduction, but I don't run it.)

> the wrong initial value

So, does this mean, `<Counter counterName="Inside Provider" />` and `<Counter counterName="Outside Provider" />` show different values?

I'm not sure how that could happen. Can you dig it deeper to reveal a bug?
Does it happen with iOS?

**Comment by sregg** [comment]
> So, does this mean, <Counter counterName="Inside Provider" /> and <Counter counterName="Outside Provider" /> show different values?

That's right.

> I'm not sure how that could happen. Can you dig it deeper to reveal a bug?
Does it happen with iOS?

I'll do some more digging (mostly inside the Provider I'm guessing).

> Does it happen with iOS?

Not that I know of.

The thing I noticed was that when the app is killed by OS, the JS thread is somehow not re-run from scratch. Meaning imports and module global variables are not initialized again, they hold the value since last run. This means in my example that `atomWithStorage` is not called `App` is re-rendered.

**Comment by dai-shi** [comment]
> The thing I noticed was that when the app is killed by OS, the JS thread is somehow not re-run from scratch.

Okay, then, this can be an expected behavior. Provider holds values which is refreshed, but Provider-less uses global state in memory. That's why we have Provider, to be able to reset values. The remaining problem, is why it doesn't re-read from the storage. It keeps showing different value, right?

**Comment by sregg** [comment]
> The remaining problem, is why it doesn't re-read from the storage. It keeps showing different value, right?

Yes, it keeps showing the wrong count until you force close the app and open it again (at which point it will call `atomWithStorage` again and `getInitialValue()` is called again [here](https://github.com/pmndrs/jotai/blob/main/src/utils/atomWithStorage.ts#L142).

**Comment by dai-shi** [comment]
Ah, my misunderstanding. So, it will only sync if `delayInit=true`. Otherwise, the initial value is the one when the module is first loaded.
`subscribe` property in storage will also help if we need to keep in sync.
I think `delayInit` is easier for your case. (We could have made it "default"...)

**Comment by sregg** [comment]
We ended up fixing this issue by removing the `Provider` altogether (we didn't realize it was optional until we investigated this issue).
I just thought I shared our findings in case others are running into it. Feel free to close if you don't think the issue is inside the Provider.
We also tried `delayInit` and it worked even worse for some reason.

**Comment by dai-shi** [comment]
My understanding is this is not an issue in Provider. It's unfortunate behavior of `atomWithStorage`. We can't simply fix it, because it will break some other usages.
