### ISSUE TITLE
bug: promise handling can result in infinite loops

### ISSUE THREAD

**Issue by matthewhuang97** [pmndrs/jotai#1481]
Hi! Thanks for all the great work on Jotai. 

I noticed some pretty severe breaking behavior in using async values in atoms. In particular, `store.ts` has two usages of the same pattern that result in an infinite loop:

In `writeGetter`: https://github.com/pmndrs/jotai/blob/0e610f920d65f18830e5769789ca9682add25c72/src/core/store.ts#L659-L666

In `asyncGet`: https://github.com/pmndrs/jotai/blob/0e610f920d65f18830e5769789ca9682add25c72/src/core/store.ts#L986-L987

In each of these, what happens is that we call the parent function, check if `atomState.p` exists, and then calls `p.then(() => writeGetter(atom))` again to invoke the parent function. The next time around, `atomState.p` still exists, so we end up in an infinite loop.

I'm not sure whether this is an oversight, or whether there is supposed to be code responsible for clearing out `atomState.p`. I think the repro was pretty simple, in that I just tried `get`ing an atom whose value was a pending promise. As far as I can tell from the code, this would result in an infinite loop any time this happens? Let me know how I can help!

**Comment by dai-shi** [comment]
Our contract is when `atomState.p` finalizes, we should either put a new promise or `.v` or `.e`. I may revisit/refactor the code, but the logic should be the same.

Can you create a failing example or a test only using public api?

**Comment by matthewhuang97** [comment]
There's actually something already failing with a really simple repro: https://codesandbox.io/s/young-cloud-9nng6v?file=/src/App.tsx. It's hard to show the infinite loop, but I think if you try to run the sandbox, it pretty much never renders, and after 10s my tab browser would crash.

Here, all that's happening is:
```
function makeAtom() {
  const a = atom<any>(new Promise(() => {}));
  return a;
}

const a = makeAtom();

export default function App() {
  const x = useAtomValue(loadable(a));
  ...
}
```

I have a local, slightly more complex repro where I can see the stack trace in Jotai's internals, and it seems to be an infinite recursive loop calling `writeGetter` -> `aState.p.then` -> `writeGetter`. 

It seems to work properly (i.e. crashes because no Suspense boundary) when I remove the `loadable`, so maybe it is actually an issue with that API?

**Comment by matthewhuang97** [comment]
> Our contract is when atomState.p finalizes, we should either put a new promise or .v or .e. I may revisit/refactor the code, but the logic should be the same.

Can you show me where this code lives? I might be able to dig in a bit and help out if I have spare bandwidth!

**Comment by dai-shi** [comment]
Yeah, it sounds like the issue of `loadable`. It has been producing various bugs.
We should probably add a new test for `loadable`.

The code is in src/core/store.ts and src/utils/loadable.ts. Both are fairly complicated. I hope to refactor them. I will start something next month. (So, having a test and a (workaround) fix would be nice before that.)

**Comment by dai-shi** [comment]
Thanks for the reproduction! That looks pretty basic...
While this can be considered a bug, and anyone interested can challenge,
I think it's pretty tough.
Meanwhile, I would suggest avoiding using infinite promise at all with loadable.

(btw, my recent focus is on a new API #1514, and with it, hopefully loadable will be more stable without hacks.)
