### ISSUE TITLE
Setting atom twice breaks reactivity in some situations

### ISSUE THREAD

**Issue by 11bit** [pmndrs/jotai#1495]
I found a bug when in a very specific situation the component is not updated after setting the value of the derived atom twice with the same value. 

Here is a [sandbox](https://codesandbox.io/s/hungry-fermi-t3k25c?file=/src/App.js)  with reproduction scenario: Input works fine until the "wreck things" button is pressed. After that it stops reacting to some changes

Sorry for the complex setup, this is the minimal reproduction case that I found after some experimenting.

**Comment by dai-shi** [comment]
Very interesting. Thanks for reporting.
It's probably a bug somewhere, but I'm not sure.
Let's make a failing test at first (hope to make it small), and then tackle it.
@Thisen Would you be interested in it?

**Comment by 11bit** [comment]
By the way, I can not reproduce it when using v2 API. So, one more argument to upgrade!

**Comment by dai-shi** [comment]
Nice that v2 API fixes it. We won't be fixing it in v1.
