### ISSUE TITLE
Performance when using in the root of a deeply nested tree

### ISSUE THREAD

**Issue by secretlifeof** [pmndrs/jotai#150]
Hello!

Thanks a lot for this library. It is a joy to use!

I don't know if I am doing things correctly, but I am struggling with a performance issue. Have a DOM tree that is deeply nested and useAtom is located at the root of the tree (opening/closing and information for modals). I know it is an overkill for that.

**If the click event triggers an empty function (not activating jotai) this is the profile**

<img width="462" alt="image" src="https://user-images.githubusercontent.com/38684618/96872341-cb53e680-1473-11eb-8658-b8044091b39e.png">

**If the click event triggers jotai this is the profile**

<img width="556" alt="image" src="https://user-images.githubusercontent.com/38684618/96873447-3baf3780-1475-11eb-8ae1-b2616c16a695.png">

Is this due to the "bottom-up" style from jotai? Is this a wrong use case for jotai?

Tried creating a codesandbox but the long event is not present in a shallow DOM tree.

### Versions:
"jotai": "^0.10.0",
"react": "^16.13.1",
"react-dom": "^16.13.1",
"react-spring": "^9.0.0-rc.3",
"react-use-gesture": "^7.0.16"

**Comment by dai-shi** [comment]
@secretlifeof
Thanks for reporting! We definitely need more work on performance in general.
This seems like a bug. How can I repro?
Would you confirm if this improves with jotai v0.10.1?

**Comment by secretlifeof** [comment]
Hello @dai-shi. Thanks for answering! I have been trying to build a mockup this week. But I am not able to reproduce the flickering. Have also tried to use Zustand, but the same flickering/glitch occurs. I don't really believe this is a performance issue with jotai per se. I use a new UI library and was wondering if that is the cause, but benchmarking shows that it performs better than Chakra-UI/Stitches. So I am kind of clueless at the moment. Will get back to you when I manage to reproduce the problem in a code sandbox. I wish you a wonderful weekend.

**Comment by dai-shi** [comment]
Closing as stale.
