### ISSUE TITLE
Declaration or statement expected "export type"

### ISSUE THREAD

**Issue by italodeandra** [pmndrs/jotai#151]
https://github.com/pmndrs/jotai/blob/9bd3ea476d1a69f6f967a42a587c9bf8b0d16e41/src/index.ts#L4

`import type`/`export type` construct started being supported on TypeScript 3.8 and I just wanted to point that out because CRA still ships with `3.7.2` and this syntax won't work if you don't update TypeScript. It might be nice to add that on the documentation or use a different syntax for exporting types.

**Comment by italodeandra** [comment]
I'm not familiar with releasing a new Jotai version but maybe there's a babel for translation TypeScript 3.8> for <3.7 that might also solve that. Not sure which is the best approach.

**Comment by dai-shi** [comment]
Hi, thanks for reporting. Yeah, I'm aware of the issue at certain point.
Now that CRA v4 is (will be) released just today, we don't have to worry too much about it?

**Comment by italodeandra** [comment]
Sure. With CRA v4 this won't happen anymore, but just for new projects. For old projects, TypeScript 3.8> will still be a requirement.

**Comment by dai-shi** [comment]
When I was trying CRA before, I updated typescript, which wasn't a big deal. (I'm not sure if that holds now, because CRA v3 had some issues with typescript+eslint even without jotai.)

Would you like to add some notes in `./docs/typescript.md`? PR appreciated.

**Comment by italodeandra** [comment]
Yeah, I didn't mean to create a big of a deal with that, sorry. I'll add the note and keep this issue as a reference. I'll add the error to the title so people will find it when searching for it.
