### ISSUE TITLE
atomWithReset does not work correctly with initial object and update function

### ISSUE THREAD

**Issue by gunters63** [pmndrs/jotai#1525]
This test here fails:

````
it('atomWithReset resets to its first object', async () => {
  const countAtom = atomWithReset({ a: 0 })

  const Parent = () => {
    const [count, setValue] = useAtom(countAtom)
    return (
      <>
        <div>count: {count.a}</div>
        <button onClick={() => setValue(RESET)}>reset</button>
        <button onClick={() => setValue((old) => ({ a: ++old.a }))}>
          increment
        </button>
      </>
    )
  }

  const { findByText, getByText } = render(
    <StrictMode>
      <Provider>
        <Parent />
      </Provider>
    </StrictMode>
  )

  await findByText('count: 0')

  fireEvent.click(getByText('increment'))
  await findByText('count: 1')

  fireEvent.click(getByText('reset'))
  await findByText('count: 0')
})
````

because it expects count to be 0 after the reset but it is 1.

If I replace atomWithReset({ a: 0 }) with atomWithReset(0) (and change the rest of the test accordingly) the test works.

I guess the problem is that the passed initialValue is directly modified through the update function.

**Comment by gunters63** [comment]
Using a modified implementation of atomWithReset where the initialValue is retrieved by a delegate makes the error go away:

````
export function atomWithReset2<Value>(initialValueGetter: () => Value) {
  type Update = SetStateActionWithReset<Value>
  const anAtom = atom<Value, Update>(
    initialValueGetter(),
    (get, set, update) => {
      const nextValue =
        typeof update === 'function'
          ? (update as (prev: Value) => Value | typeof RESET)(get(anAtom))
          : update

      set(anAtom, nextValue === RESET ? initialValueGetter() : nextValue)
    }
  )
  return anAtom as WritableAtom<Value, Update>
}
````

**Comment by gunters63** [comment]
An alternative would be maybe to make deep copies of the initialValue for both the atom constructor and when a RESET is made.

**Comment by dai-shi** [comment]
This is a wrong usage of updating atom values, not only about atomWithReset but about any atoms.
Atom values must to be immutable.
(To detect such misusage, `freezeAtom` should help.. but, for this case it doesn't work. `freezeAtomCreator` may work.)

Anyway, the solution for you case is not to mutate the object.
```jsx
<button onClick={() => setValue((old) => ({ a: old.a + 1 }))}>
```

Closing as it's intentional behavior.
