### ISSUE TITLE
Issues on initial page load on NextJS v13

### ISSUE THREAD

**Issue by GLips** [pmndrs/jotai#1529]
Not sure exactly what's going on here, but I've created [a minimal repro on CodeSandbox](https://codesandbox.io/s/nextjs-with-jotai-forked-pi6v0c?file=/components/Clock.js) that shows the issue.

The error is `TypeError: Cannot read properties of null (reading 'useContext')`

<img width="562" alt="Cannot read properties of null (reading 'useContext')" src="https://user-images.githubusercontent.com/842883/199370826-eda1769e-c385-4054-979b-0b6f557ccb1a.png">

Commenting out `useAtom()` in `/components/Clock.js` and replacing its variables with hardcoded values causes the page to render correctly:

```
//  const [{ lastUpdate, light }, setClock] = useAtom(clockAtom);
const lastUpdate = 0;
const light = false;
const setClock = (x) => {};
```

Once you've loaded the page, you can add the `useAtom()` call again and remove the hardcoded definitions and the page will work as expected. Possibly something related to SSR or hydration?

**Comment by dai-shi** [comment]
Sounds like related with https://github.com/pmndrs/zustand/issues/1395 in zustand.

**Comment by GLips** [comment]
> Sounds like related with https://github.com/pmndrs/zustand/issues/1395 in zustand.

I think you're right—I neglected to mention this only occurs when you add `experimental: { appDir: true }` in `next.config.js`, as described in https://github.com/pmndrs/zustand/issues/1395

**Comment by DestroyerXyz** [comment]
![image](https://user-images.githubusercontent.com/70191184/199740075-4c3d34f2-66d2-4b52-93f4-def8036f344c.png)
This is probably because features like useContext required for Jotai are only available in client components. You need to append `'use client';` on the top of the file.

**Comment by Caryyon** [comment]
would it be as easy as adding "use client" to the `Provider.tsx` and maybe a few other client component files? Otherwise maybe a small babel plugin that would parse the file for `"use client"` and throw an error that explains the issue? happy to do the work for either, just new to jotai so would love a nudge in that right direction.

**Comment by Rawnly** [comment]
![CleanShot 2023-02-27 at 16 09 12@2x](https://user-images.githubusercontent.com/16429579/221601075-e193e323-b10b-4c33-96aa-874be121fd27.png)

same here but without `appDir: true` :(

**Comment by thejus-r** [comment]
Jack Herrington made a great video about this I think.. [YouTube Video](https://www.youtube.com/watch?v=OpMAH2hzKi8&t=753s)

We really have to think differently when using React Server Components.

**Comment by dai-shi** [comment]
Closing as a resolution is `"use client"`.
