### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by EduardoLopes** [pmndrs/jotai#1531]
Hi. I'm using jotai in a medium size project and i was experimenting with custom hooks returning atoms values, converting from react context only, to use jotai. Then i got this error:

```
Uncaught RangeError: Maximum call stack size exceeded
    at index.mjs:295:29
    at Map.forEach (<anonymous>)
    at readAtomState (index.mjs:295:21)
    at index.mjs:298:15
    at Map.forEach (<anonymous>)
    at readAtomState (index.mjs:295:21)
    at index.mjs:298:15
    at Map.forEach (<anonymous>)
    at readAtomState (index.mjs:295:21)
    at index.mjs:298:15
```

After a lot of debugging i managed to reproduce it in a smaller project, it doesn't have the same stack trace, but i'm pretty sure is the same issue i'm having on the bigger project. 

Here the reproduction: https://stackblitz.com/edit/vitejs-vite-vcmja2?file=src%2Fstores%2FuseData.ts&terminal=dev

## More info

The structure of hooks i'm using is something like this: 

```js

// custom hook 1, returning actions and atoms values;
function useAdd() {
    const [value] = useAtom(valueAtom);
    
    return {   
      value,
      ...
    }
}

// custom hook 2, returning actions and atoms values;
function useMultiply() {
    const [value] = useAtom(valueAtom);
    
    return {   
      value,
      ...
    }
}

// custom hook 3, returning actions and atoms values! but dependes on one of the stores
function useData() {
   // this call is the main problem here
   const stores = useStores();
   const [data] = useAtom(dataAtom);
    
    return {   
      data,
      ...
    }
}

// hook returning all the custom hooks and 
function useStores() {
    const add = useAdd();
    const multiply = useMultiply();
    const data = useData();
    
    return {   
      add,
      multiply,
      data
    }
}

```

I know there's a circular dependency here, but somethings i was even getting warnings saying that it was possible to be a react bug: 

```
Uncaught Error: Should have a queue. This is likely a bug in React. Please file an issue.
    at updateReducer (chunk-HVRFWYDF.js?v=e54dc11e:11940:19)
    at Object.useReducer (chunk-HVRFWYDF.js?v=e54dc11e:12941:24)
    at useReducer (chunk-S4LFUXEE.js?v=e54dc11e:990:29)
    at useAtomValue (chunk-GD36XXQS.js?v=e54dc11e:767:105)
    at useAtom (chunk-GD36XXQS.js?v=e54dc11e:828:5)
    at useMultiply (useMultiply.ts:15:29)
    at useStores (index.ts?t=1667431226424:16:20)
    at useData (useData.ts?t=1667431226424:30:17)
    at useStores (index.ts?t=1667431226424:17:16)
    at Data (Data.tsx?t=1667431226424:30:18)
```

I fixed the issue by getting the data i need directly from the atom, and not getting it from the store.

Anyways, i don't know if there's a better way to do this. I don't know if i shouldn't use jotai like this. I don't know if it's a jotai bug or this is expected. O even if it's a react bug.

**Comment by dai-shi** [comment]
Can you create the reproduction with codesandbox ( https://react.ts.new ) without using jotai-tanstack-query? Preferably, everything in one file `App.tsx`.

**Comment by EduardoLopes** [comment]
react router and jotai-tanstack-query it's there because i thought it was related. but let's see

**Comment by EduardoLopes** [comment]
here it is: https://codesandbox.io/s/jolly-poincare-hygxpk?file=/src/App.tsx

the eslint is complaining about "'useStores' was used before it was defined.", but i don't think the problem is that

**Comment by dai-shi** [comment]
https://codesandbox.io/s/unruffled-snow-pswktn
I don't think it's related with jotai or even with react.

```js
const f = () => {
  return 0;
};

const g = () => {
  h();
  return 1
};

const h = () => {
  const v1 = f();
  const v2 = g();
  return { v1, v2 };
};

h();
```

**Comment by EduardoLopes** [comment]
Oh my! I'm embarrassed. I didn't noticed that it's a recursion! :upside_down_face:

Sorry. Thanks for your time checking this.
