### ISSUE TITLE
useResetAtom on React17 BUG

### ISSUE THREAD

**Issue by AeolusZane** [pmndrs/jotai#1536]
my react version: 
"react": "^17.0.2",
"react-dom": "^17.0.2",
useResetAtom can't work on this version

**Comment by dai-shi** [comment]
Does it work with `17.0.0`?

We do run tests with multiple versions:
https://github.com/pmndrs/jotai/blob/053b947b38d411378c9fe5e66b517d9868a56c7d/.github/workflows/test-multiple-versions.yml#L38-L44

**Comment by cksal0805** [comment]
me too.. but It's ok now. after version upgrade 17.0.2 -> 18.0.0

**Comment by dai-shi** [comment]
Although very curious, nothing is actionable without a reproduction.
