### ISSUE TITLE
atomFamily caches too aggressively async requests

### ISSUE THREAD

**Issue by fkocovski** [pmndrs/jotai#155]
When using `atomFamily` starting from v0.10.0 the `get` part is cached thus preventing new refetch of data even if initialising parameters change. This behaviour does not happen with 0.9.2.

https://codesandbox.io/s/sharp-oskar-2kmtx?file=/src/atoms.js

In order to check, open the console and try to navigate between components `A` and `B`.

**Comment by dai-shi** [comment]
@fkocovski Hi, this might be controversial.

#131 did this.

> - Provider no longer garbage collect atom values even when all useAtoms' are gone
>   - They will only be garbage collected by JS
>   - https://github.com/pmndrs/jotai/issues/84#issuecomment-703967151

So, it was intentional. Under the `<Provider>`, atom values are kept. If you need to reevaluate `read`, add a dependency or create a new atom.

Now, two questions are: a) isn't it intuitive? b) how should we solve your use case?
