### ISSUE TITLE
Atom updated by a scoped action atom displays old value

### ISSUE THREAD

**Issue by AjaxSolutions** [pmndrs/jotai#1562]
## Summary
Scoped action atom updates an atom, but the updated atom display the initial value.

## Link to reproduction
https://codesandbox.io/s/jotai-provider-example-forked-6723s8?file=/src/App.js

## Check List

Please do not ask questions in issues.

- [x ] I understand this is not a question.

Please include a minimal reproduction.

- [ x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by dai-shi** [comment]
Because you are reading from a different scope (undefined scope).
https://codesandbox.io/s/jotai-provider-example-forked-xge56x
Seems like you have some misconceptions.

**Comment by AjaxSolutions** [comment]
Thanks for the explanation.  It makes sense and it clarifies things for me.
