### ISSUE TITLE
Can atomFamily be called with multiple params?

### ISSUE THREAD

**Issue by DynamicArray** [pmndrs/jotai#157]
``
export const areaState = atomFamily(({ area_id, period, agent_id }) => async get => {
	if (parseInt(area_id) > 0 && parseInt(agent_id) > 0) {
		const r = await getAreaData(area_id, period, agent_id);
		return r.result;
	}
});
``

and then

`	
const [areaStatistics] = useAtom(
		areaState({ area_id: settings.areaid, period: settings.period, agent_id: settings.agentid })
	);
`

causes a perpetual re-run of the atomFamily, presumably since the object in the useAtom statement is re-created during each render and thus is new.

That being the case, what are my options?

**Comment by dai-shi** [comment]
We have the third argument `areEqual` in atomFamily, which defaults to `Object.is`.
You want to pass shallowEqual from some libs, or create your own equality function.

```js
export const areaState = atomFamily(
  ({ area_id, period, agent_id }) => async get => {
    if (parseInt(area_id) > 0 && parseInt(agent_id) > 0) {
      const r = await getAreaData(area_id, period, agent_id);
      return r.result;
    }
  },
  null,
  (a, b) => a.area_id === b.area_id && a.period === b.period && a.agent_id === b.agent_id
);
```

**Comment by DynamicArray** [comment]
Thank you, just what I needed.
