### ISSUE TITLE
Asynchronous writes to atom delay computation of derived atom

### ISSUE THREAD

**Issue by y120sb** [pmndrs/jotai#1572]
## Summary
Writing to an atom using async in useAtomCallback delays the computation of the atom derived from that atom.

This problem seems to occur only when using React18 in React17 compatibility mode, as shown in the following article.
https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis

On the web, this is not a problem because I can just use React18, but with ReactNative, this problem occurs because it runs in React17 compatibility mode unless I opt-in to the Fabric renderer.
https://reactnative.dev/docs/react-18-and-react-native#users-on-react-native-069-not-yet-migrated-to-the-new-architecture

### Code

```typescript
const AsyncWriteTest: React.FC = () => {
    const valueAtom = useMemo(() => atom(0), []);
    const derivedAtom = useMemo(() => atom((get) => get(valueAtom) * 2), [valueAtom]);

    const onClick = useAtomCallback(
        useCallback(
            async (get, set) => {
                console.log("onClick");
                await new Promise((r) => setTimeout(r, 300));
                set(valueAtom, (old) => old + 1);
            },
            [valueAtom]
        )
    );

    console.log('valueAtom: ', useAtomValue(valueAtom));
    console.log('derivedAtom: ', useAtomValue(derivedAtom));
    
    return (
        <button onClick={onClick}>test</button>
    );
};
```

### Expected
```
valueAtom: 0
derivedAtom: 0
onClick
valueAtom: 1
derivedAtom: 2
```

### Actual
```
valueAtom: 0
derivedAtom: 0
onClick
valueAtom: 1
derivedAtom: 0 <-- 
valueAtom: 1
derivedAtom: 2
```

### Environments
- React 18.1.0
- ReactNative 0.70.5

## Link to reproduction
https://codesandbox.io/s/modern-glade-tzm87q

## Check List

Please do not ask questions in issues.

- [x] I understand this is not a question.

Please include a minimal reproduction.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by dai-shi** [comment]
This is a known issue and only workaround I know of is `unstable_batchedUpdates`.
https://codesandbox.io/s/funny-euclid-9ud9nn

I hope RN exposes it too. Otherwise, there's nothing much we can do.
