### ISSUE TITLE
Consider React Native for persistence support

### ISSUE THREAD

**Issue by likern** [pmndrs/jotai#159]
Hello! I now it might not be the issue for right now. 
But if you are going to add persistence support, please, _consider React Native also_. So persistence layer would be optional / configurable.

There is no HTML and DOM in React Native and components (`View`, `Text`, `TextInput`) map to Native Android / iOS components. And **there is no Web API** like https://www.w3.org/TR/IndexedDB or https://dev.w3.org/html5/webdatabase
Also there is several solutions for persistence like SQLite database https://github.com/andpor/react-native-sqlite-storage or AsyncStorage https://github.com/react-native-async-storage/async-storage

**Comment by dai-shi** [comment]
Hi,
Please check `docs/persistence.md` and feel free to suggest improvements (and possibly a PR).

We don't add persistence support in core to keep it premitive, but utils can.
So far, because there are many patterns, we haven't yet come up with a single recommended solution.

btw, have you tried jotai with RN? Would be great to hear your experience.

**Comment by likern** [comment]
> Hi,
> Please check `docs/persistence.md` and feel free to suggest improvements (and possibly a PR).
> 
> We don't add persistence support in core to keep it premitive, but utils can.
> So far, because there are many patterns, we haven't yet come up with a single recommended solution.
> 
> btw, have you tried jotai with RN? Would be great to hear your experience.

I'm going to try and test jotai for my React Native project.
I will share my experience.

**Comment by likern** [comment]
I'm using React Native version `0.62.2` with Hermes JS Engine https://hermesengine.dev `0.4.1` version.
When I wrapped my application into `<Provider>` component from jotai I see white screen / nothing.

There is not error, error logs and indicator that something doesn't work.
But one time error message appeared, as far as I remember it stated `No proxy support`.

For more modern Hermes JS there is Proxy support. But for stated versions jotai doesn't work out-of-the-box.

While doing the same with `RecoilJS` `0.1.2` at least I see application screens.

**Comment by dai-shi** [comment]
@likern Thanks for your trial. That's totally unexpected for me. Let me create a PR to remove Proxy usage. I will ask you for testing it.

**Comment by dai-shi** [comment]
Let's close this. If we have a real issue, please open a new one.

**Comment by Albert-Gao** [comment]
Actually, Proxy support for Hermes just landed with 0.64, But I am perfectly fine. Jotai is my go-to statement for React/React Native now.
