### ISSUE TITLE
queryClientAtom is not exported by vite-optional-peer-dep

### ISSUE THREAD

**Issue by felix-bohlin** [pmndrs/jotai#1610]
First of all, hello and thank you for a great library! :)

## Summary
When I run `npm run build` the console throws this error: 
```
'queryClientAtom' is not exported by __vite-optional-peer-dep:jotai-tanstack-query:jotai, imported by node_modules/jotai
/esm/query.mjs
```

* It only happens if I upgrade Jotai to version `1.8.6` and above. `1.8.5` and below works without errors.
* Running `npm run dev` won't throw any errors regardless of version.

## Link to reproduction
https://github.com/felix-bohlin/jotai-bug

## Other info
vite: 3.2.4
react: 18.2.0

**Comment by dai-shi** [comment]
Thanks for the reproduction.

Since jotai v1.9.0, you need to install the peer dependency `jotai-tanstack-query` to use `jotai/query`.
```bash
npm install jotai-tanstack-query
```

Please also check the new docs: https://github.com/pmndrs/jotai/blob/59f93dc6fe15513bd6a9402face48297ef990f52/docs/integrations/query.mdx

**Comment by felix-bohlin** [comment]
Thanks @dai-shi! Works well 👍

**Comment by dai-shi** [comment]
fyi, `jotai/query` will be deprecated soon and will be removed in v2. `jotai-tanstack-query` has more capabilities.
