### ISSUE TITLE
Mistake in code documentation in core-internals documentation

### ISSUE THREAD

**Issue by segamiken** [pmndrs/jotai#1619]
## Summary

Sorry if I'm wrong, but Perhaps I have found a mistake in the[ documentation about core internals](https://jotai.org/docs/guides/core-internals).

## Link to reproduction

https://github.com/pmndrs/jotai/blob/a598fb223cdf984f327bd98a509924a76b541c92/docs/guides/core-internals.mdx?plain=1#L42

I thinks "keep listening for atom's state change till component is unmounted." is correct.

Before
// keep listening for atom's state change till component is **mounted**. 

After
// keep listening for atom's state change till component is **unmounted**.

This is because `atomState.listeners.delete(callback)` is called and stop listening when component is unmounted.

## Check List

Please do not ask questions in issues.

- [X] I understand this is not a question.

Please include a minimal reproduction.

- [X] I've added a ~~link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.~~ correct documentation I think.

**Comment by dai-shi** [comment]
Sounds right. Can you open a PR to fix?

**Comment by segamiken** [comment]
Sure！I will open a PR.
