### ISSUE TITLE
Atoms value becomes `undefined` after using React.useCallback in useSelector (with atomFamily)

### ISSUE THREAD

**Issue by merisbahti** [pmndrs/jotai#163]
Hey,

This is quite elaborate, but I havent managed to make a smaller example.

Buggy code is here:
https://github.com/merisbahti/jotai-optics/blob/meris/clean-arrayfamily/example/index.tsx

To run it, just clone the repo and `cd example; yarn start`.

The problem appears when removing a field in the form (using the X button), then adding a new field... This resutls in an exception where the value of the atom is undefined!

issue seems to be with `useAtomArrayFamily`, lines here: https://github.com/merisbahti/jotai-optics/blob/meris/clean-arrayfamily/src/index.ts#L92-L103

With the useCallback the bug appears:
```typescript
   // other from useAtomArrayFamily truncated
  return useSelector(
    atom,
    React.useCallback(
      elements => {
        const length = elements.length
        return Array.from(new Array(length)).map(
          (_, key) => [atomFamilyGetter(key), () => removeItem(key)] as const,
        )
      },
      [atomFamilyGetter, removeItem],
    ),
  )
``` 

but without the `React.useCallback`, the bug doesnt appear.

**Comment by merisbahti** [comment]
https://youtu.be/JhjK1T_tO6E

I made more complicated youtube instructions... But recorded it in 4k... so I'm not sure if this will ever be a video that one can watch? Try and wait for the 4k quality to be released... :P

Basically.

1. git clone git@github.com:merisbahti/jotai-optics.git
2. cd jotai-optics
3. git checkout meris/clean-arrayfamily
3. yarn
4. cd example
5. yarn
6. yarn start
7. (follow video instructions, but basically, add a field, then remove one)

**Comment by dai-shi** [comment]
@merisbahti Thanks for reporting this. Could you copy&paste the error stack trace?

**Comment by merisbahti** [comment]
```
Uncaught TypeError: Cannot read property '0' of undefined
    at Field (index.tsx:79)
    at renderWithHooks (react-dom.development.js:14803)
    at mountIndeterminateComponent (react-dom.development.js:17482)
    at beginWork (react-dom.development.js:18596)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22154)
    at workLoopSync (react-dom.development.js:22130) 
```

``` 
react_devtools_backend.js:2450 The above error occurred in the <Field> component:
    in Field (created by Form)
    in ul (created by Form)
    in div (created by Form)
    in Form (created by FormList)
    in div (created by FormList)
    in ul (created by FormList)
    in FormList (created by App)
    in InnerProvider (created by Provider)
    in Unknown (created by Provider)
    in Unknown (created by Provider)
    in Provider (created by App)
    in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

**Comment by dai-shi** [comment]
Thanks. Can you tell what the `field` atom is like? It's a derived atom, correct? Is it async?

**Comment by dai-shi** [comment]
If possible, can you confirm if this issue is caused by this line returning `undefined`?

https://github.com/pmndrs/jotai/blob/4c45660d60f6e72a627e4428f0c41aa964ff803b/src/core/Provider.ts#L220

**Comment by merisbahti** [comment]
currently at work but will check when finished.

**Comment by merisbahti** [comment]
> If possible, can you confirm if this issue is caused by this line returning `undefined`?
> 
> https://github.com/pmndrs/jotai/blob/4c45660d60f6e72a627e4428f0c41aa964ff803b/src/core/Provider.ts#L220

Unfortunately, this did not work. I added a console log right before that line:

``` 
      console.log('value of thing is:', a.init, a.key)
      return a.init // this should not be undefined
``` 

Here's how it looked in the console (I added a console log right before I start clicking)
![Screenshot 2020-11-06 07:51:51](https://user-images.githubusercontent.com/2946728/98335283-f8240400-2004-11eb-89e1-03df3e8cab3f.png)

**Comment by dai-shi** [comment]
I have no clue, so next experiment. What if you use a simplified useSelector?
```ts
export function useSelector<Value, Slice>(
  anAtom: Atom<Value>,
  selector: (v: Value) => Slice
): Slice {
  const sliceAtom = useMemo(() => {
    const derivedAtom = atom((get) => {
      const slice = selector(get(anAtom))
      return slice
    })
    return derivedAtom
  }, [anAtom, selector])
  return useAtom(sliceAtom)[0]
}
```

**Comment by merisbahti** [comment]
Hey, thanks.

Yeah, same behaviour with the simplified selector.

**Comment by merisbahti** [comment]
Actually, dai-shi, it seems like the error is in my side,

I actually took the time to implement the bug in my library on this branch:
https://github.com/merisbahti/klyva/tree/meris/klyva-next

So I'll spend some time to figure out what I'm doing wrong, thanks for your help.

I'll try and keep this issue posted as I find out more, but you can close it if you want. (I'll still write here even if its closed)
