### ISSUE TITLE
Using a provider breaks reactivity for derived async atoms

### ISSUE THREAD

**Issue by pgetta** [pmndrs/jotai#1643]
## Summary

It seems there is an issue with derived async atoms when using a Provider. I have the following:
* primitive atom
* derived async atom which depends on the one above.

When updating the first atom - the value of the second one is getting re-computed in a Provider-less configuration, but with Provider it looks like that this doesn't work anymore. Tried both v1 and v2 APIs.

I hope I didn't miss anything important.

## Link to reproduction

https://codesandbox.io/s/competent-shape-ew6xcn?file=/src/App.js

## Check List

Please do not ask questions in issues.

- [x] I understand this is not a question.

Please include a minimal reproduction.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by dai-shi** [comment]
You don't need an async atom to reproduce it, just a derived atom.
The way it works is that the useAtom hook outside the Provider component refers to Provider-less store.

Here's the fix:
https://codesandbox.io/s/sparkling-shape-dpch6z?file=/src/App.js

**Comment by pgetta** [comment]
I don't know how I've missed that and I'm sorry I've bothered you with such a thing. Thanks a lot for the explanation!
