### ISSUE TITLE
`.sub` callback is not triggered in the second subscription

### ISSUE THREAD

**Issue by tmkx** [pmndrs/jotai#1658]
## Summary
`sub` the same atom twice will not invoke the second callback, is it expected?

## Link to reproduction
```tsx
const store = createStore()
const aAtom = atom(0)

store.sub(aAtom, () => console.log('called'))
store.sub(aAtom, () => console.log('not called'))
```

## Check List

Please do not ask questions in issues.

- [x] I understand this is not a question.

Please include a minimal reproduction.

- [ ] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by dai-shi** [comment]
Nice catch.
We shouldn't invoke the first callback for consistency. Reproduction: https://codesandbox.io/s/morning-sound-1hm42b?file=/src/App.tsx
Will open a PR later.

**Comment by dai-shi** [comment]
Fixed in #1659: https://codesandbox.io/s/inspiring-cray-kkjh0f?file=/src/App.tsx

**Comment by FlatMapIO** [comment]
I happen to be wondering if `store.sub([aAtom, bAtom], () => {})` makes sense?

**Comment by dai-shi** [comment]
We want the library to be minimalistic, so it's out of the scope. One can create a util function easily.

Fun fact: You could probably do:
```js
store.sub(atom((get) => [get(aAtom), get(bAtom)]), () => {})
```
