### ISSUE TITLE
Typescript "This expression is not callable. Type 'never' has no call signatures."

### ISSUE THREAD

**Issue by etaracsaocnarf** [pmndrs/jotai#1660]
Can you open a new discussion with a reproduction?

_Originally posted by @dai-shi in https://github.com/pmndrs/jotai/issues/802#issuecomment-1367165717_
   
I wanted to create an abstract store in case I move to another library in the future, but the `set` function of `useAtom` is not working, here is the link to the playground:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgQRhEAaOBDNm4CuAzgKarpwC+cAZlBQOQBWEM2wDA3AFDckAekWLQIA7AMYxgEUXHFQSuEgGU0CgDwAVAHwAKYKOBTsAG1VKAXHE0BKRNzhwFMAlFm50WvQaPBT5mBIbHkpeASF4GjFJaVliFTUSL10iRKtyEC87BAcnEhc3QlIMlMTg7lC+QWh4cRlUopIoDLgAXjkFJVVoJNSoAwBzOAAfWlNSPRpxoJ5eOtEGgG14qCxSGABVUigAXTbG7oVdFYybXnWtpt0GFdFsEBIGGyA

**Comment by colindjk** [comment]
Can you explain how this was fixed? Running into a similar issue.
