### ISSUE TITLE
atomWithStorage not updated server-side (NextJS)

### ISSUE THREAD

**Issue by rtritto** [pmndrs/jotai#1689]
## Summary
Using NextJS and Material UI, value of the atom (`atomWithStorage`) is not correctly loaded server side.

### Example:
Save theme mode to localStorage (_darkMode_ local storage variable is true or false).
Page background is yellow with light theme and grey with dark one.

## Link to reproduction
[CodeSandbox](https://codesandbox.io/s/nextjs-with-jotai-forked-6qufy0)

Template used:
- [Next.js + Jotai](https://github.com/vercel/next.js/tree/canary/examples/with-jotai)
- [Next.js + Material UI](https://github.com/mui/material-ui/tree/master/examples/nextjs)

## Step to reproduce
- Click on `Change` button and theme is change to light (yellow background)
- Reload page
- Theme is light in localStorage but background is yellow (_darkModeAtom_ is true in server-side, is false in client-side) and there is a log with class missmatch:

<details><summary>Console output</summary>

```console
Warning: Prop `className` did not match. Server: "MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium mui-style-1o011v7-MuiButtonBase-root-MuiButton-root" Client: "MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium mui-style-1e6y48t-MuiButtonBase-root-MuiButton-root"
    at button
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at ButtonBase (webpack-internal:///./node_modules/@mui/material/ButtonBase/ButtonBase.js:107:82)
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Button (webpack-internal:///./node_modules/@mui/material/Button/Button.js:240:59)
    at IndexPage (webpack-internal:///./pages/index.js:14:83)
    at InnerThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:21:70)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:43:5)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:40:5)
    at MyThemeProvider (webpack-internal:///./components/ThemeProvider.js:20:11)
    at Provider (webpack-internal:///./node_modules/jotai/esm/index.mjs:703:3)
    at MyApp (webpack-internal:///./pages/_app.js:27:13)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:62:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:301:63)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:850:919)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:61:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:171:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:346:11)
```
</details>

Note:
After changing from light to dark and page reload, there are no problems

**Comment by dai-shi** [comment]
(Without looking into details) Can you try `delayInit: true`? It will be default in v2.

**Comment by rtritto** [comment]
Get this error:
```console
Error: Text content does not match server-rendered HTML.

See more info here: https://nextjs.org/docs/messages/react-hydration-error
```

**Comment by dai-shi** [comment]
Are these errors with `delayInit: true`?
Also, please try replacing `atomWithStorage` with `atom` and see how those errors change.

**Comment by rtritto** [comment]
> Are these errors with delayInit: true?

Yes

> Also, please try replacing atomWithStorage with atom and see how those errors change.

With `atom`, after 1 setAtom, there are no errors because, on page reload, the atom value is always the default one.

**Comment by dai-shi** [comment]
I just downloaded the codesandbox and confirmed that I failed to explain `delayInit: true` properly.

You need to do this:
```js
// import { atom } from "jotai";                              
import { atomWithStorage, createJSONStorage } from "jotai/utils";              
                                                                               
// export const darkModeAtom = atom(false);                                    
export const darkModeAtom = atomWithStorage("darkMode", true, {                
  ...createJSONStorage(() => localStorage),                                    
  delayInit: true                                                              
});                                                                            
```

**Comment by rtritto** [comment]
Work like a charm, thank you so much!

**Comment by electroheadfx** [comment]
> ```js
> delayInit: true 
> ```

it it work same in 1.13.1 ? I can't add it.

**Comment by electroheadfx** [comment]
it works from, look at this code, maybe it may help you:

```typescript
import { atomWithStorage, createJSONStorage } from 'jotai/utils'

export type IContext = 'catenary' | 'track' | 'all'

const cookieStorage = createJSONStorage<IContext>(() => {
  return {
    getItem: () => Cookies.get('contextRail') as IContext,
    setItem: (ctx, value) => Cookies.set(ctx, value, { sameSite: 'lax' }),
    removeItem: (ctx) => Cookies.remove(ctx),
  }
})

export const contextRailAtom = atomWithStorage<IContext>('contextRail', 'all', { ...cookieStorage })

```

**Comment by mickdewald** [comment]
> it works from, look at this code, maybe it may help you:
> 
> ```ts
> import { atomWithStorage, createJSONStorage } from 'jotai/utils'
> 
> export type IContext = 'catenary' | 'track' | 'all'
> 
> const cookieStorage = createJSONStorage<IContext>(() => {
>   return {
>     getItem: () => Cookies.get('contextRail') as IContext,
>     setItem: (ctx, value) => Cookies.set(ctx, value, { sameSite: 'lax' }),
>     removeItem: (ctx) => Cookies.remove(ctx),
>   }
> })
> 
> export const contextRailAtom = atomWithStorage<IContext>('contextRail', 'all', { ...cookieStorage })
> ```

Ill give it a try, but shouldnt you suppose to create the store provider in the layout.js to have the stores only available on a request base?

```javascript
// app/layout.tsx
import { Provider as JotaiProvider, createStore } from "jotai";

export const store = createStore();

export default function RootLayout({ children }: RootLayoutProps) {
  // console.log("[RootLayout]");

    <html lang="en" suppressHydrationWarning>
      <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
        <div className="flex-1">    
          <JotaiProvider store={store}>
            {children}
          </JotaiProvider></div>
      </body>
    </html>
  );
}
```

Once I use it like this (the recommended way), I run into the hydration errors on page reload (cmd+r or F5).
