### ISSUE TITLE
[website] Replace 'useSetValue' with 'useSetAtom'

### ISSUE THREAD

**Issue by naixy28** [pmndrs/jotai#1739]
Hi guys I really appreciate your work on the new doc, enjoyed it a lot!
And I may have found a possible typo in the "Getting started" section. Should `useSetValue` be `useSetAtom`? 

https://github.com/pmndrs/jotai/blob/202b140b2af017f038fa81c3b0c9a44636a91a67/website/src/pages/index.js#L266

**Comment by dai-shi** [comment]
Nice catch. Can you please open a PR?
