### ISSUE TITLE
RFC: jotai/optics

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#175]
@merisbahti originally filed the issue #44.
As I wasn't familiar with optics then, a separate package `jotai-optics` made sense.
I'm not yet very familiar with it, but I start getting to know its power and suitability with jotai api.
So, it would be a good option to provide `jotai/optics` officially.

Just yesterday, @c0d3t3k announced [an article](https://dev.to/c0d3t3k/jotai-now-with-optics-29ld) with a good example using jotai and optics, thought it's a good chance to start a discussion.

**Comment by merisbahti** [comment]
Really interesting and fun to hear, I can make a PR for this. 👍
