### ISSUE TITLE
Discussion: atomFamily better alternative

### ISSUE THREAD

**Issue by likern** [pmndrs/jotai#180]
I've tried to use `atomFamily` or implement my own alternative. But looks like I had no succeess, so I decided to discuss my vision and ideas.

## atomFamily drawback
As I understand `atomFamily` was copied from RecoilJS. While at first glance it might look good, trying to implement this pattern in real life fails shortly. That's the problems I found.

### Can't fetch or load data to `atomFamily`
Most often in real life before starting managing `atoms` we need to fetch data from somewhere - from local database or server.
We don't want to do multiple requests for each atom from `atomFamily`. While our strategy is to do the least requests returning most data, these requests will be highly specialized.

For example I have sqlite `tags` table
| id                                   | label     | iconName              | iconColor              | isSelected |
|--------------------------------------|-----------|-----------------------|------------------------|------------|
| e8a63d19-ae64-44df-b3a8-0adbf7df1155 | Family    | users                 | rgba(227, 95, 166, 1)  | 1          |
| 7d3bfd19-3c88-4d12-8665-ddd405af5aee | Health    | heartbeat             | rgba(242, 108, 108, 1) | 0          |
| 6f07bc4e-79b1-44d2-b65e-460422ba137a | Home      | home                  | rgba(89, 212, 220, 1)  | 0          |
| 18efd821-9088-48a1-9bf7-2db589e69621 | Shopping  | shopping-basket       | rgba(114, 180, 31, 1)  | 0          |
| eb6a269b-66c7-4a6e-a588-ebff855800d1 | Friends   | user-friends          | rgba(236, 122, 86, 1)  | 0          |
| 8d9d7cd1-12a9-4d60-90be-7c028bbcfc18 | Grooming  | cut                   | rgba(217, 110, 117, 1) | 0          |

and I want to make one request to load data
```ts
const tagRepository = getTagRepository();
return tagRepository.find()
```

`atomFamily` do not allow to do that

### atomFamily requires separate atom to manage ids
`atomFamily` requires to manage separate `atom` with list of ids. But most entities from server or local database already have `id` as part of its data.

- additional request to load ids is required 
- separate atom with ids requires additonal coordination which complicates code

```ts
@Entity({ name: 'tags' })
export class Tag {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column('text')
  label!: string;
  ...
}
```

### atomFamily doesn't give performance advantage
If we add new `todo` to `todoList` https://github.com/jacques-blom/recoil-todo-list/blob/ccbec84f3a438b8707f235263bf079fab4bbd987/src/components/Input.tsx#L31
```ts
    const insertTask = useRecoilCallback(({set}) => {
        return (label: string) => {
            const newTaskId = tasks.length
            set(tasksState, [...tasks, newTaskId])
            set(taskState(newTaskId), {
                label: label,
                complete: false,
            })
        }
    })
```
this updates `tasksState`  atom with ids.
```ts
export const tasksState = atom<number[]>({
    key: 'tasks',
    default: [],
})

const tasks = useRecoilValue(tasksState)

    return (
        <div>
            {tasks.map((id) => (
                <Task id={id} key={id} />
            ))}
        </div>
    )
```
so all `<Task />` components will be rerendered again (but reconcilation - real DOM update - should happen only for updated task). I think there is no difference then just updating one big atom with list of todos.

The only advantage for `atomFamily` is when we **update** one `atom` - that should lead to updating only one component.
But `atomFamily` **doesn't solve** `insert / delete` use-cases.

Also, if we have example with **filtered todo-list**
```ts
const filteredTasksAtom = atom(
  get => {
    const allTasks = get(allTasksAtom)
    return allTasks.filter(<some condition>)
  }
)
```
this is more like a toy example. We might not have all tasks in memory. In real code we will have to load filtered tasks from server / database using query.

```ts
const filteredTasksAtom = atom(
  get => {
    return fetch('/tasks?isCompleted=0&isTracked=1')
  }
)
```
How to coordinate `allTasksAtom` and `filteredTasksAtom` because they might overlap?
Since `fetch('/tasks?isCompleted=0&isTracked=1')` might return updated data we want to update existing atoms with this updated information from request, add new atoms and delete old ones. So we want to sync them.

**Comment by dai-shi** [comment]
I agree atomFamily is only useful when we have id (=param) in advance.

I'd like to solve each item one by one without using utils, and in the end, we could hopefully propose new utils.

> We don't want to do multiple requests for each atom

The first one. Hm, this already sounds hard.
I'm not sure if atoms should be used for server caching, but let's see how far we can go.

It needs to be one big atom.

```js
const fetchData = async () => ...

const dbAtom = atom(fetchData())
```

Now, to get one item, can we use id?

```js
const getItemAtom = (id) => atom(
  get => get(dbAtom)[id],
  (get, set, newValue) => set(dbAtom, { ...get(dbAtom), [id]: newValue }),
)
```

How does it look so far?
My question is how should we get the `id`.

**Comment by youknowriad** [comment]
@dai-shi 

```
const getItemAtom = (id) => atom(
  get => get(dbAtom)[id],
  (get, set, newValue) => set(dbAtom, { ...get(dbAtom), [id]: newValue }),
)
```

On that example, is it true to assume that since `getItemAtom( id )` atoms depend on `dbAtom` which means if I have a list of items, all the components will rerender each time I add or delete an item even if the rendered component only cares about an unchanged item?

**Comment by dai-shi** [comment]
@youknowriad 
It will re-run all read functions of the dependent atoms, but only components in which the read results are changed (`!==`) re-render. Does it make sense?

**Comment by youknowriad** [comment]
It does yes, but personally for me, one of the selling point of recoil/jotai (compared to state solution like redux where they run selectors and check immutability) is that it shouldn't need to call the functions of the dependent atoms. At scale (rendering thousands of components), even these function calls can become costly. 

Granted it's not important in all situations but I wonder if there are techniques that can be used to only subscribe to the particular atoms we're interested in.

**Comment by youknowriad** [comment]
Actually, now that I think about it. It's probably not a big concern though because this function will only run once for each of these items without calling its potential child atoms. This is probably good enough. (Don't mind me :P)

**Comment by dai-shi** [comment]
Note for anyone: This is not avoidable, not because of jotai/recoil design, but JS.

```js
const arr1 = [1, 2, 3]
const arr2 = [1, 9, 3]
arr1[0] === arr2[0] // changed? no
arr1[1] === arr2[1] // changed? yes
arr1[2] === arr2[2] // changed? no
```

So, you need `get(dbAtom)[id]` to check is it's changed.

----
Now, 

> even these function calls can become costly.

in this case, it's bad design to create `dbAtom` top-down.
We should take bottom-up approach.

```js
const atom0 = atom(1)
const atom1 = atom(2)
const atom2 = atom(3)
const arrArom = atom(get => [get(atom0), get(atom1), get(atom2)])

const [, update] = useAtom(atom1)
update(9)
```

**Comment by dai-shi** [comment]
@likern I think we need your input.

**Comment by likern** [comment]
> @likern I think we need your input.

I've switched to Recoil for my application. It has exactly the same requirements.

I'm still investigating. But looks like soon I can provide my experience of solving these mentioned problems.

**Comment by likern** [comment]
@dai-shi I've got some experience and it looks like it's working. But I'm short on time. As soon as I will have more time I'll fill in more information. Close for now.
