### ISSUE TITLE
createJSONStorage does not properly subscribe to updates caused by RESET

### ISSUE THREAD

**Issue by nderscore** [pmndrs/jotai#1815]
## Summary

When an item is removed from storage, a `storage` event fires with `null` as the incoming value. The storage event handler in `createJSONStorage` ignores `null` values from incoming `storage` events. 

This is caused by a check for a non-falsy `e.newValue` here:
https://github.com/pmndrs/jotai/blob/main/src/vanilla/utils/atomWithStorage.ts#L83

When `setAtom(RESET)` is called on an `atomWithStorage`, subscribers in other windows do not get the reset update.

## Link to reproduction

I've created a minimal reproduction of the issue on codesandbox here:

https://codesandbox.io/s/jotai-storage-bug-reset-u9doo3?file=/src/App.tsx

Like with #1812 you might have to open the preview iframe itself (https://u9doo3.csb.app/) in separate windows to avoid permissions errors.

## Fix discussion

I think that in order to fix this, the interface of the `(Sync/Async)Storage.subscribe` argument `callback` needs to be updated to accept `NO_STORAGE_VALUE`, so that the Storage can inform `atomWithStorage` that a reset occurred in another window.

```diff
--- a/src/vanilla/utils/atomWithStorage.ts
+++ b/src/vanilla/utils/atomWithStorage.ts
@@ -15,14 +15,14 @@ export interface AsyncStorage<Value> {
   getItem: (key: string) => Promise<Value | typeof NO_STORAGE_VALUE>
   setItem: (key: string, newValue: Value) => Promise<void>
   removeItem: (key: string) => Promise<void>
-  subscribe?: (key: string, callback: (value: Value) => void) => Unsubscribe
+  subscribe?: (key: string, callback: (value: Value | typeof NO_STORAGE_VALUE) => void) => Unsubscribe
 }
 
 export interface SyncStorage<Value> {
   getItem: (key: string) => Value | typeof NO_STORAGE_VALUE
   setItem: (key: string, newValue: Value) => void
   removeItem: (key: string) => void
-  subscribe?: (key: string, callback: (value: Value) => void) => Unsubscribe
+  subscribe?: (key: string, callback: (value: Value | typeof NO_STORAGE_VALUE) => void) => Unsubscribe
 }
 
 export interface AsyncStringStorage {
@@ -83,10 +83,13 @@ export function createJSONStorage<Value>(
       const storageEventCallback = (e: StorageEvent) => {
         if (
           e.storageArea === getStringStorage() &&
-          e.key === key &&
-          e.newValue
+          e.key === key
         ) {
-          callback(JSON.parse(e.newValue))
+          try {
+            callback(JSON.parse(e.newValue ?? ''))
+          } catch (e) {
+            callback(NO_STORAGE_VALUE)
+          }
         }
       }
       window.addEventListener('storage', storageEventCallback)
@@ -126,7 +129,9 @@ export function atomWithStorage<Value>(
     }
     let unsub: Unsubscribe | undefined
     if (storage.subscribe) {
-      unsub = storage.subscribe(key, setAtom)
+      unsub = storage.subscribe(key, (nextValue) => {
+        setAtom(nextValue === NO_STORAGE_VALUE ? initialValue : nextValue)
+      })
     }
     return unsub
   }
```

Currently, the only place the `NO_STORAGE_VALUE` symbol is exposed to consumers is with an `unstable_` prefix. 

That change would technically leak `NO_STORAGE_VALUE` as part of the exposed types for `Sync/AsyncStorage`.

It might make sense to remove the unstable prefix from the exported `NO_STORAGE_VALUE` symbol because of that? 

**Semi-related:** Another reason it might make sense to expose `NO_STORAGE_VALUE` is because I don't think you can create a custom storage (one that doesn't use `createJSONStorage`, such as would be required to make a validated storage - #1198) without using that symbol either.

## Check List

Please do not ask questions in issues.

- [x] I've already opened a [discussion](https://github.com/pmndrs/jotai/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by dai-shi** [comment]
I haven't looked into detail, but it sounds like you have pretty good understanding.
Your solution might be the only one, but may I ask?

> It might make sense to remove the unstable prefix from the exported NO_STORAGE_VALUE symbol because of that?

Do you have any idea to avoid depending on this symbol completely? I wish there were simpler solution... even with some breaking change.

**Comment by nderscore** [comment]
I have some ideas:

1. It doesn't make a big difference, but the simplest way to avoid `NO_STORAGE_VALUE` might be to replace its usages with the `RESET` symbol.

2. Another alternative might be to allow storage to throw an error when there is no stored value instead of returning a special Symbol. This method might actually make it easier to implement custom validated storage, since validation libraries like `zod` or `yup` provide parsers which throw an error on invalid inputs. See: zod's [parse](https://github.com/colinhacks/zod#parse) & yup's [validateSync](https://github.com/jquense/yup#schemavalidatesyncvalue-any-options-object-infertypeschema). The default `getItem` from `createJSONStorage` could also surface the error from `JSON.parse` here instead of catching it: https://github.com/pmndrs/jotai/blob/fed8d807a0a1a4c6361f6b30356e58895a26b9a3/src/vanilla/utils/atomWithStorage.ts#L58-L62

  This approach does have a downside though. If some _other_ error occurs in `getItem`, one which we don't expect as a result of parsing the stored data, then that error would get swallowed by the try/catch (or `.catch()` for an async storage) and treated as if it was an empty value.
  
  
3. Another approach might be to return a wrapper object from the storage instead of the value directly. The return type of `getItem` could by updated from: `value: Value` -> `{ hasValue: true; value: Value; } | { hasValue: false; }`

The updated `parse` method in `createJSONStorage` might look something like this afterwards:

```ts
const parse = (str: string | null) => {
  str = str || ''
  if (lastStr !== str) {
    try {
      lastValue = JSON.parse(str)
    } catch {
      return { hasValue: false }
    }
    lastStr = str
  }
  return { hasValue: true, value: lastValue }
}
```

**Comment by dai-shi** [comment]
Thanks for your ideas!!

1: `RESET` is for action. I don't prefer reusing it.
2(first): I think throwing is once done, but someone reported issue that catching everything caused a problem (parse error shouldn't be hidden). Maybe we can revisit it.
2(second): createJSONStorage is a method to avoid separating getItem and parseItem. So, negative.
3: I don't dislike it. I would do `{ value?: Value }`. It's breaking for users who create custom storage though. (we don't do major bump for utils.)

> I'll try to think of some more alternatives.

👍

**Comment by nderscore** [comment]
> I would do { value?: Value }

My only concern with this shape was that it might make it stranger to distinguish explicit `undefined` values from non-values (`{ value: undefined }` vs `{}`) It could be checked with `("value" in result)` but treating them differently could be a source of confusion for consumers.

---

4. Another option could be to make the storage aware of the default value, so that it only ever sends valid values back up to the atom.

    It could be an additional argument for both the `getItem` and `subscribe` methods of storage.
    
    ```ts
    storage.getItem('key', fallbackValue);
    storage.subscribe('key', callback, fallbackValue)
    ```

    It kind of mixes concerns though, since the write function of the `atomWithStorage` still needs probably to handle incoming `RESET` values.

**Comment by nderscore** [comment]
> Maybe, we don't need it for `subscribe` assuming there should always be a value.

That's actually the bug that happens right now with `createJSONStorage` subscriptions. 😅

When we call `setAtom(RESET)` on an atom with storage, the storage performs a `removeItem`. This triggers a `storage` event in other tabs/windows where the new incoming value is `null`. 

Right now there's no way for storage to handle those resets and tell the atom to set the default value.

**Comment by dai-shi** [comment]
> That's actually the bug that happens right now with `createJSONStorage` subscriptions. 😅

Oh! Now, I'm getting what this issue is about. Thanks for your patience.

Is `e.newValue` equal to `null` after `removeItem`? That sounds easy to fix.

**Comment by nderscore** [comment]
> Is e.newValue equal to null after removeItem? That sounds easy to fix.

Yep! That's what occurs.

**Comment by dai-shi** [comment]
My current idea:
```js
storage.getItem(key, fallbackValue)
storage.subscribe(key, callback) // don't call callback if newValue is null, and reset value in the atom.
```

**Comment by nderscore** [comment]
> storage.subscribe(key, callback) // don't call callback if newValue is null, and reset value in the atom.

But then how does the storage perform the reset? 

---

Maybe the storage `subscribe` method could take two callbacks?

```ts
storage.subscribe(key, setAtomCallback, resetAtomCallback)
```

**Comment by nderscore** [comment]
Or maybe the callback could accept different arguments? Such the nested object syntax from the earlier idea:

```ts
storage.subscribe(key, callback as ({ value?: Value } => void)
```

**Comment by dai-shi** [comment]
I might still be missing something, but it calls removeItem, so the item is removed from the storage, right? Maybe, I can draft a PR.

**Comment by dai-shi** [comment]
> subscribers in other windows do not get the reset update.

oops, I missed that part.

Yeah, this would only work:
```js
storage.getItem(key, fallbackValue)
storage.subscribe(key, callback, fallbackValue)
```

**Comment by dai-shi** [comment]
> Yeah, this would only work:
> 
> ```js
> storage.getItem(key, fallbackValue)
> storage.subscribe(key, callback, fallbackValue)
> ```

@nderscore Would you like to draft a PR?
