### ISSUE TITLE
TypeError: Invalid value used as weak map key

### ISSUE THREAD

**Issue by seeatend** [pmndrs/jotai#1817]
## Summary
I got this issue when I defined an atom in typescript outside the component file and imported it to component

![image](https://user-images.githubusercontent.com/29393733/222933452-d73a0fa9-4822-4f5c-8cf7-1adef3287f01.png)

```
const interface User {
  firstName: string;
  lastName: string;
}
const userAtom = atom<{
  [key: string]: User;
}>({});
```

**Comment by dai-shi** [comment]
Please continue discussion in #1816.
