### ISSUE TITLE
Updating an atom dependency without having the dependent in the same component doesn't update the dependent

### ISSUE THREAD

**Issue by mdingena** [pmndrs/jotai#184]
## Context

I have an `attackerSkillSetAtom` atom:

```jsx
import { atom } from 'jotai';

export const attackerSkillSetAtom = atom({
  someExampleSkill: 3,
  anotherSkill: 2
});
```

I have a component with a `skillSetAtom` prop that accepts an atom:

```jsx
import { useAtom } from 'jotai';

export const UpdateSkill = ({ skillSetAtom, skill }) => {
  const [skillSet, setSkills] = useAtom(skillSetAtom);

  const handleChange = change => {
    setSkills({
      ...skillSet,
      [skill]: skillSet[skill] + change
    });
  };

  return (
    <>
      <button onClick={() => handleChange(-1)}>-</button>
      <input type='text' value={skillSet[skill]} disabled />
      <button onClick={() => handleChange(1)}>+</button>
    </>
  );
};
```

I have a page in my app that displays skills (for a game) in a list with these `UpdateSkill` components on it. The route for this page is `/skills/:party` because I'd like to show a different skill set for the attacking player and the defending player. My routing component feeds the `party` prop, and the component selects the appropriate atom based on that. To keep it simple, here is a simplified example of that page component `SkillsScreen` that feeds one single `UpdateSkill` component:

```jsx
import { attackerSkillSetAtom, defenderSkillSetAtom } from '../atoms';

const skillSetAtom = {
  attacker: attackerSkillSetAtom,
  defender: defenderSkillSetAtom
};

export const SkillsScreen = ({ party }) => {
  return (
    <>
      <h2>Some Example Skill</h2>
      <UpdateSkill skillSetAtom={skillSetAtom[party]} skill='someExampleSkill' />
    </>
  );
};
```

However, users of the app aren't mainly interested in setting skills. They are interested in the effects their skills have. So I have another atom that keeps track of skill effects: `attackerSkillEffectsAtom`:

```jsx
const getSkillEffects = skillSetAtom => get => {
  const skillSet = get(skillSetAtom);

  // for simplicity of the example, I'm just adding up whatever their skill values are
  return Object.keys(skillSet).reduce((sum, skill) => sum + skillSet[skill], 0);
};

export const attackerSkillEffectsAtom = atom(getSkillEffects(attackerSkillSetAtom));
```

The reason I provide a curried function to `atom()` is that I do the same for `defenderSkillEffectsAtom` and I don't want to duplicate code.

I have a "homepage" component that lists a player's skill effects:

```jsx
import { useAtom } from 'jotai';
import { attackerSkillEffectsAtom } from '../atoms';

export const HomeScreen = () => {
  const [skillEffects] = useAtom(attackerSkillEffectsAtom);

  return (
    <pre>
      Attacker skill effects are: {JSON.stringify(skillEffects, null, 2)}
    </pre>
  );
};
```

## Problem

When navigating to `/skills/attacker` and changing the skill value, then navigating back to `/`, the derived atom doesn't appear to have updated.

However, if I use my derived atom in `SkillsScreen`, the same place where the dependency atom is imported, it will update immediately as expected:

```diff
- import { attackerSkillSetAtom, defenderSkillSetAtom } from '../atoms';
+ import { attackerSkillSetAtom, defenderSkillSetAtom, attackerSkillEffectsAtom, defenderSkillEffectsAtom } from '../atoms';

  const skillSetAtom = {
    attacker: attackerSkillSetAtom,
    defender: defenderSkillSetAtom
  };

+ const skillEffectsAtom = {
+   attacker: attackerSkillEffectsAtom,
+   defender: defenderSkillEffectsAtom
+ };
+
  export const SkillsScreen = ({ party }) => {
+ const [skillEffects] = useAtom(skillEffectsAtom[atom]);
+
    return (
      <>
        <h2>Some Example Skill</h2>
        <UpdateSkill skillSetAtom={skillSetAtom[party]} skill='someExampleSkill' />
+       <pre>{skillEffects}</pre>
      </>
    );
  };
```

Now when navigating back to `/`, the value remains updated.

**Is this designed behaviour of jotai?**

**Comment by dai-shi** [comment]
Hey! Thanks for trying. Looks like an interesting use case.

I will look at your description more in detail later, but one question out of my head is where you place `<Provider>`. It needs to be outside of your router if you need to keep values across routes.

> The reason I provide a curried function to atom() is that I do the same for defenderSkillEffectsAtom and I don't want to duplicate code.

Yes, this is a valid usage.

**Comment by mdingena** [comment]
> where you place `<Provider>`. It needs to be outside of your router if you need to keep values across routes.

```jsx
import { AtomProvider } from './Atoms';
import { RouterProvider } from './Router';
import { ResizeObserverProvider } from './ResizeObserver';

const Providers = ({ children }) => (
  <AtomProvider>
    <ResizeObserverProvider>
      <RouterProvider>{children}</RouterProvider>
    </ResizeObserverProvider>
  </AtomProvider>
);

export default Providers;
```

**Comment by dai-shi** [comment]
Thanks.

I read the description again. It seems like a bug. We started supporting keeping atom values across routes since v0.10, and there might still be some cases not covered.

I'll investigate it further as it's important if it's really a bug, but if you are willing to help the project, a *small* reproduction with codesandbox would be so much helpful. I suppose one route with a primitive atom and another route with a derived atom should repro. Otherwise, we'd actually need your help to repro.

**Comment by mdingena** [comment]
Here is a reproduction: https://codesandbox.io/s/late-smoke-2z91z

* Observe the derived values on the home page: `42` and `1337`.
* Navigate to Key 1 page.
* Observe the primitive values on the Key 1 page: `42` and `1337`.
* Click the button, observe that `key1` value becomes `43`.
* Navigate to home page.
* **Observe that derived value has not updated.**

To see it working:
* **remove the `<Switch>` wrap at lines `19` and `25`** in `src/index.js`.
* Navigate to Key 1 page.
* Observe both primitive and derived values.
* Click the button.
* Observe that both primitive and derived values change.
* Navigate to home page.
* Observe that derived values are updated there.

**Comment by dai-shi** [comment]
@mdingena Thanks for the small reproduction! This is very helpful. I know what's happening underneath. Now, thinking how to solve this.

FYI, if you use React DevTools, you can check the Provider state.

<img width="621" alt="image" src="https://user-images.githubusercontent.com/490574/98747268-8b40ad80-23fa-11eb-9200-d14c8b9b562d.png">

Find `DebugState` in `hooks`.

**Comment by dai-shi** [comment]
@magom001 This is relatively an old issue and it was fixed back then.
If you find a weird behavior, it can be a new bug.

Your code snippet looks good at a glance. Except that I'm not sure how `ComponentType` works.
Would you please open a new issue with a codesandbox reproduction? Would be nice if it can repro without `ComponentType` but just a primitive value like `number`.

**Comment by magom001** [comment]
ComponentType is just a string enum. Unable to reproduce it in a sandbox...
