### ISSUE TITLE
atomWithHash not loading initially using Next/Router

### ISSUE THREAD

**Issue by lloydrichards** [pmndrs/jotai#1845]
## Summary

There seems to be a bug when navigating using next/link on the loading of atomWithHash().  All in all the url deep links work correctly when copying and pasting the url into another browser, but when the same link is created through a `<Link />` component then the initial load is empty and when a rerender is triggered then the hash data loads in correctly.

### To Reproduce
1. Create a Link with a url including hash data (eg. `<link href="/about#topic='sports'" />`)
2. Click the link and see that the hash data is not loaded in the page component.
3. Trigger a rerender using some kind of update
4. Then see the hash data load in correctly
5. Copy the URL and open in a new tab or browser
6. See the hash data load in on initial render this time.

### In [Codesandbox](https://codesandbox.io/p/github/t6adev/DeepLinks-in-Nextjs) with a minimal reproduction.
1. Click the "About:Sport" nav link
2. See nothing in the "[ ]"
3. Toggle the switch
4. See "Sport" now in the "[ ]"

## Link to reproduction

[Github Repo](https://github.com/lloydrichards/DeepLinks-in-Nextjs)

## Check List

Please do not ask questions in issues.

- [x] I've already opened a [discussion](https://github.com/pmndrs/jotai/discussions/1836) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [x] I've added a link to a [codesandbox](https://codesandbox.io/p/github/t6adev/DeepLinks-in-Nextjs) with a minimal reproduction.

**Comment by dai-shi** [comment]
You don't need to create a new issue, while still under discussion. (unless you are ready to tackle the problem.)
Besides, we should create the issue in `jotai-location` repo.
Let's continue discussion in #1836 meanwhile.
Closing.
