### ISSUE TITLE
Showcase are broken

### ISSUE THREAD

**Issue by JulioJu** [pmndrs/jotai#1890]
## Summary

Some shocases are broken .

## Link to reproduction

Follow README.md of

- https://github.com/pmndrs/jotai/tree/1313a9d2fd07689e30a771ad5516d3de0e91f0a8/examples/hacker_news
- https://github.com/pmndrs/jotai/tree/1313a9d2fd07689e30a771ad5516d3de0e91f0a8/examples/todos

We have error in browser
```
Failed to compile

./src/App.tsx
Attempted import error: 'useSetAtom' is not exported from 'jotai'.

This error occurred during the build time and cannot be dismissed.
```
When we download this sample from https://jotai.org/docs/basics/showcase we have the same problem. Same problem with Yarn and Npm.

I notice that is Jotai 1.x that is used in this examples.

## Check List

Please do not ask questions in issues.

- [X] I've already opened a [discussion](https://github.com/pmndrs/jotai/discussions) before opening this issue, or already discussed in other media. See https://github.com/pmndrs/jotai/discussions/1889

Please include a minimal reproduction.

- [X] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by milhamm** [comment]
Hey @dai-shi, I want to fix this issue. Should the example be updated to Jotai v2, or should I keep it and just minor upgrade the v1?

**Comment by dai-shi** [comment]
I think just updating v2 latest is fine. Thanks!
