### ISSUE TITLE
Unnecessary reference to Facebook in the comparison between Jotai and Recoil

### ISSUE THREAD

**Issue by vasco3** [pmndrs/jotai#190]
In the comparison [jotai vs. recoil](https://github.com/pmndrs/jotai/blob/master/docs/comparison.md#how-is-jotai-different-from-recoil), it seems to me like the mentioning of Facebook product is unnecessary.

> If you want a Facebook product, choose Recoil obviously.

People using Jotai are already using code by Facebook, such as React. So I don't see why it matters if Recoil is made by Facebook or not. I wonder which was the intention of this mention. I got mixed feelings about it (like a bit of a bummer that it was mentioned). Personally, I would get rid of that sentence.

**Comment by dai-shi** [comment]
Thanks for the notice. Yeah, that was careless. Let me remove it in a second.
