### ISSUE TITLE
Thread blocking with 100,000+ nodes. What does jotai do *after* retrieving an atom value?

### ISSUE THREAD

**Issue by nganbread** [pmndrs/jotai#1902]
My application follows a tree like structure with over 100,000 nodes, where each node is an atom:

* A
  * B1
    * C1
    * C2
    * ...
    * C* 
  * B2   
    * C1
    * C2
    * ...
    * C*
  * ...  
  * B*

<sup>(the tree is actually a couple levels deeper than this)</sup>

Each `C` node can be marked as completed, and I need to display the completion % at levels `A` and `B` in real-time. To do this, I have a `DerivedAtomB` which calculates the completion stats for its `C` children. I then have a `DerivedAtomA` which performs the same, but on its `DerivedAtomB` children

The calculation of `DerivedAtomA` takes around 800ms and blocks the main thread, which is fine for me. However, after calculating the value of `DerivedAtomA` and returning it to the component, it takes an extra 2-3s for the main thread to be unblocked and the results of `useAtomValue` to be rendered. Furthermore, when I hide the component and then re-render it, the cached value is instantly returned, however the main thread still takes the same 2-3s to be freed again

My questions are;
 - What is Jotai doing ("asynchronously") after returning the atom value from `useAtomValue`? 
 - Is there a way to mitigate this post-`useAtomValue`  thread blocking?

---

Here's some sample code if it helps at all
```
  const aProgressAtom = atom<Progress>((get) => {
    const bProgress = get(a).bs.map((x) =>get(bProgressAtom(x))); // bs is a string[]. bProgressAtom is an atomFamily

    return {
      completed: bProgress.reduce((sum, { completed }) => sum + completed, 0),
      total: bProgress.reduce((sum, { total }) => sum + total, 0),
    };
  });
```

**Comment by dai-shi** [comment]
Please use #1901 for discussion.
