### ISSUE TITLE
Import error on stackbliz

### ISSUE THREAD

**Issue by himself65** [pmndrs/jotai#1908]
## Summary

```
Error in /turbo_modules/jotai@2.0.4/index.js (3:15)
Cannot use 'import.meta' outside a module
```

## Link to reproduction

https://stackblitz.com/edit/react-ts-ecbyx8?file=App.tsx

## Check List

Please do not ask questions in issues.

- [x] I've already opened a [discussion](https://github.com/pmndrs/jotai/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by Himself65** [comment]
Related: https://github.com/pmndrs/valtio/issues/448

**Comment by dai-shi** [comment]
FYI

`import { atom } from 'https://unpkg.com/jotai@2.0.4/umd/vanilla.development.js';` does a trick.
But, `import { useAtom } from 'https://unpkg.com/jotai@2.0.4/umd/react.development.js';` doesn't.
(I think our umd builds for zustand/jotai/valtio are suboptimal.)

**Comment by milang** [comment]
@Himself65 @dai-shi

Please note that StackBlitz ViteJS project running in [WebContainers environment](https://developer.stackblitz.com/guides/user-guide/available-environments) can import and use Jotai just fine:

https://stackblitz.com/edit/vitejs-vite-lwnsd3?file=src/App.tsx

**Comment by dai-shi** [comment]
https://github.com/pmndrs/jotai/issues/1908#issuecomment-1530527165

> (I think our umd builds for zustand/jotai/valtio are suboptimal.)

Hm, I don't think our umd builds are bad. We can't simply use it for `import`.

**Comment by dai-shi** [comment]
Closing until someone comes in with an idea.
