### ISSUE TITLE
wrong type signature for useAtomDevtools

### ISSUE THREAD

**Issue by JLarky** [pmndrs/jotai#191]
`WritableAtom<Value, Value>` will only work for simple atoms, and will fail if a custom updater is used.

Codesandbox example: https://codesandbox.io/s/jotai-issue-191-44wy3?file=/src/App.tsx

**Comment by dai-shi** [comment]
Yeah, but it's intentional for now. Your atom needs to accept `Value` for updating to time travel.

Maybe, it'd be good to support `Atom<Value>` too and disable time traveling somehow.
cc @c0d3t3k

**Comment by JLarky** [comment]
to be honest I tried simple boolean atom (for checkbox) and I couldn't make it work with time travel :)

anyway, good to know that this is not a bug, but maybe `useReadonlyAtomDevtools` could be added :)

**Comment by dai-shi** [comment]
> to be honest I tried simple boolean atom (for checkbox) and I couldn't make it work with time travel :)

Nice catch. I wasn't aware. Maybe it only works with an object. If that's the case, we'd need to wrap primitive values in the hook?

> maybe useReadonlyAtomDevtools could be added :)

Sounds nice and easy.

> having a redux debugger for reducer style atom is kind of on the nose :)

I hadn't thought about it, but totally agreeable as we have atomWithReducer. But, it's very difficult. Maybe impossible without any workaround.

**Comment by c0d3t3k** [comment]
My Thoughts:
- The atom state is sent to the [devtools extension](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/README.md#1-for-chrome) as a raw value ([useAtomDevtools#L90](https://github.com/pmndrs/jotai/blob/a92c82ba92d49e5bb7e4aa51c83d9df8d6344fb3/src/devtools/useAtomDevtools.ts#L90)). When Time Travel events come back from the extension, they are returned as a string, necessitating a call to `JSON.parse` ([useAtomDevtools#L68](https://github.com/pmndrs/jotai/blob/a92c82ba92d49e5bb7e4aa51c83d9df8d6344fb3/src/devtools/useAtomDevtools.ts#L68)). Thus, it may be better to wrap the value sent to the devtools in an object (i.e. `devtools.send(..., { value: atomValue })`).
- For the typing of atoms, maybe we could have something like:
```typescript
useAtomDevtools<ReadValue, WriteValue = ReadValue>(
  anAtom: WritableAtom<ReadValue, WriteValue> | Atom<ReadValue>,
  name?: string
)
```
Then, we could add a check to ignore time travel events if the atom is not writable. Also, maybe we could have:
```typescript
useAtomDevtools<ReadValue, WriteValue = ReadValue>(
  anAtom: WritableAtom<ReadValue, WriteValue> | Atom<ReadValue>,
  name?: string,
  devtoolsUpdateStateCallback?: (value: WriteValue) => void
)
```
and allow the user to handle time travel manually.
- I'm not extremely familiar with the Redux pattern, but it seems like possibly the reducer for an atom could be composed directly with the devtools enhancer as described [here](https://github.com/pmndrs/jotai/blob/a92c82ba92d49e5bb7e4aa51c83d9df8d6344fb3/src/devtools/useAtomDevtools.ts#L68).

**Comment by dai-shi** [comment]
> we could add a check to ignore time travel events if the atom is not writable.

If you think it's not too confusing users, it sounds good.

There's a small issue, though. A writable atom doesn't always mean you can write the same type back.
So, the typing should be:
```ts
useAtomDevtools<ReadValue>(
  anAtom: WritableAtom<ReadValue, ReadValue> | Atom<ReadValue>,
  name?: string
)
```

> devtoolsUpdateStateCallback?: (value: WriteValue) => void

How can this be used?

**Comment by dai-shi** [comment]
BTW, if we have a read-only atom and would like to use devtools, we can wrap it to create a writable atom and discard updates.

```ts
const countAtom = atom(0)
const readOnlyAtom = atom(get => get(countAtom))

useAtomDevtools(useMemo(() => atom(
  get => get(readOnlyAtom),
  (_get, _set, _argIgnored: number) => {} // dummy write function
), [readOnlyAtom]))
```

cc @JLarky

**Comment by c0d3t3k** [comment]
> There's a small issue, though. A writable atom doesn't always mean you can write the same type back.
> So, the typing should be:
> 
> ```ts
> useAtomDevtools<ReadValue>(
>   anAtom: WritableAtom<ReadValue, ReadValue> | Atom<ReadValue>,
>   name?: string
> )
> ```
Well, the `WriteValue = ReadValue` was just supposed to be a default, if the atom should have a separate write value this is allowed. In my experience with TS >3.8.0 the type params are automatically inferred from the atom.

Also, the shadow write-discarding atom could be created by a helper function added to `jotai/utils`.

**Comment by dai-shi** [comment]
It's not about TS capability.
How could devtools allow time traveling for `WritableAtom<{ x: number }, { y: string }>`?

Yeah > could be created by a helper function

**Comment by c0d3t3k** [comment]
Yes, I agree that time traveling will not affect every atom. I don't think it matters that the write function actually does anything, it just has to be handled/callable somehow. At that point, the update can either be acted upon or ignored.

**Comment by dai-shi** [comment]
Yeah, based on that, I still think `WritableAtom<Value, Value>` is the precise atom typing because that's how useAtomDevtools calls `set`.

**Comment by c0d3t3k** [comment]
> How could devtools allow time traveling for `WritableAtom<{ x: number }, { y: string }>`?

I was thinking about this and came up with the following case:
```typescript

// Atom for storing Raw Value
const storageAtom = atom(1)

// Shadow atom with custom read/write handlers
const readWriteAtom: WritableAtom<{ x: number }, { y: string }> = atom(
    (get) => ({ x: get(storageAtom) }),
    (get, set, update) => set(storageAtom, update.y)
)

const TheComponent: React.FC<any> = () => {
...
    // Use the shadow atom
    const [atomValue, setAtomValue] = useAtom(readWriteAtom);

    // With useAtomDevtools<ReadValue, WriteValue = ReadValue>, the following should support time travel.
    useAtomDevtools<{ x: number }, { y: string }>(readWriteAtom)
...
}
```

Since the shadow atom transforms the value read from (or written to) the raw value atom, these values should be consistent when the atom is updated from a time travel event.

> Yeah, based on that, I still think `WritableAtom<Value, Value>` is the precise atom typing because that's how useAtomDevtools calls set.

With the previous example in mind, I think that the [`setValue` call](https://github.com/pmndrs/jotai/blob/master/src/devtools/useAtomDevtools.ts#L68) in the devtools would still work for atoms with separate types for `ReadValue` and `WriteValue`. 
That said, I think it is worth considering that allowing separate read and write types could provide more precise typing.

**Comment by dai-shi** [comment]
> useAtomDevtools<{ x: number }, { y: string }>(readWriteAtom)

If you send `{ x: 0 }` to Redux DevTools Extension, it will send back to you `'{"x":0}'` in JSON, right? It doesn't know anything about `y`.

Consider another example:

```js
const countAtom = atom(0)
const derivedAtom = atom(
  get => get(countAtom),
  (_get, set, arg: number) => set(countAtom, arg * 2)
)

  useAtomDevtools(derivedAtom) // this doesn't work as expected?
```

**Comment by c0d3t3k** [comment]
> If you send `{ x: 0 }` to Redux DevTools Extension, it will send back to you `'{"x":0}'` in JSON, right? It doesn't know anything about `y`.

Ok, my mistake. I think I understand now. This is an interesting paradox, since the the devtools cannot be assured of the backing state of a derived atom. 

So if you have a derived atom with separate read/write types, you have to wrap that atom with another derived atom that converts back to the raw value and has identical read/write types. 

With that in mind, I now agree that `WritableAtom<Value, Value>` is the best typing.

**Comment by dai-shi** [comment]
OK, let's close this issue then.

----

A remaining issue (maybe create a new issue?) is how to support `Atom<Value>` without time traveling.

Option A:
- `useAtomDevTools<Value>(anAtom: WritableAtom<Value, Value> | Atom <Value>, name? string)`
- If the atom is not writable, just ignore updates from Redux DevTools Extension.

Option B:
- new `useReadOnlyAtomDevtools<Value>(anAtom: Atom<Value>, name?: string)`
- Throws an error if it receives updates from Redux DevTools Extension.
