### ISSUE TITLE
Remove/update `jest` references

### ISSUE THREAD

**Issue by rtritto** [pmndrs/jotai#1918]
## Summary

`jest` is removed in #1839.

[/.vscode/launch.json](https://github.com/pmndrs/jotai/blob/main/.vscode/launch.json) should be updated with `vitest` or removed.

Other _jest_ references: https://github.com/pmndrs/jotai/search?q=jest

## Check List

Please do not ask questions in issues.

- [x] I've already opened a [discussion](https://github.com/pmndrs/jotai/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by dai-shi** [comment]
Nice catch. I'm not a VSCode user, so hope someone can help on it.

@Aslemammad @arjunvegda We should take care all of Zustand/Jotai/Valtio.

**Comment by arjunvegda** [comment]
Nice catch indeed!

I'm not too familiar with VSCode's debugger. Do we want to remove it for now? 

There are other references in `examples/`, they don't seem to be used, should we remove those too?

**Comment by dai-shi** [comment]
> I'm not too familiar with VSCode's debugger. Do we want to remove it for now?

Yeah, if nobody can maintain it, let's remove it.

> There are other references in `examples/`, they don't seem to be used, should we remove those too?

If they are unused, we can remove. Note that, examples use CRA, and CRA uses jest.

**Comment by arjunvegda** [comment]
> If they are unused, we can remove. Note that, examples use CRA, and CRA uses jest.

Nice! I tested it locally and it works as expected without `react-app/jest`. 

However, come to think of it, there might be some value in keeping them around 🤔 Especially if users would like to play around with atoms and unit testing.
