### ISSUE TITLE
Turning atom value into promise does not suspend

### ISSUE THREAD

**Issue by shulcsm** [pmndrs/jotai#1923]
## Summary
Turning atom value into promise does not re-suspend but returns promise as value.

## Link to reproduction
https://codesandbox.io/s/holy-wood-4pljne

Confirmation in discord:  
> daishi:
Interesting. I didn't know that issue. It's not related with #1851 because v2.0.3 can repro.
This works: 
https://codesandbox.io/s/vigorous-babycat-urzrn7?file=/src/App.tsx 

Originally encountered the issue when trying to re-suspend atom that was initialized as promise. And got promises in get values of derived atoms.

**Comment by dai-shi** [comment]
On second thought, this is working as expected in v2.

Notice the type error:
<img width="601" alt="image" src="https://user-images.githubusercontent.com/490574/236822258-1658112f-3aef-4761-b627-b34982437df7.png">

We need to make the atom type `number | Promise<number>`. But, that will show another type error:
<img width="604" alt="image" src="https://user-images.githubusercontent.com/490574/236822486-a39cd70e-98de-44f0-847e-61d9b311475e.png">

That means, `c` can be a promise. So, here's the right fix:
<img width="743" alt="image" src="https://user-images.githubusercontent.com/490574/236822659-33a96284-19ce-4ed5-b30a-600a49a98d72.png">

Link: https://codesandbox.io/s/amazing-golick-mcudeq
