### ISSUE TITLE
Weird behaviours when using atomWithDefault with async atom

### ISSUE THREAD

**Issue by TeaBough** [pmndrs/jotai#1937]
Following the discussion https://github.com/pmndrs/jotai/discussions/1935
In this piece of code, every time we increase `field1` it renders the whole component (it starts by displaying `LOADING` then the components).

Updating the `atomWithDefault` first display the fallback component thus reload the entire component...

```ts
const anAtom = atom((get) =>
  Promise.resolve({
    field1: 1,
    field2: 1
  })
);

export const testAtom = atomWithDefault(async (get) => {
  const res = await get(anAtom);
  return res;
});

const field1Atom = selectAtom(testAtom, (p) => p.field1);
const field2Atom = selectAtom(testAtom, (p) => p.field2);

function Field1Display() {
  const field1 = useAtomValue(field1Atom);
  console.log('RENDER DISPLAY 1')
  return <div>VALUE FIELD 1 : {field1}</div>;
}

function Field2Display() {
  const field2 = useAtomValue(field2Atom);
  console.log('RENDER DISPLAY 2')
  return <div>VALUE FIELD 2 : {field2}</div>;
}

function IncreaseButtons() {
  const setTestAtom = useSetAtom(testAtom);
  return (
    <>
      <button
        onClick={() =>
          setTestAtom((prev) => ({ ...prev, field1: prev.field1 + 1 }))
        }
      >
        Increase field 1
      </button>
      <button
        onClick={() =>
          setTestAtom((prev) => ({ ...prev, field2: prev.field2 + 1 }))
        }
      >
        Increase field 2
      </button>
    </>
  );
}
const App = () => (
  <React.Suspense fallback={<div>LOADING</div>}>
    <Field1Display />
    <Field2Display />
    <IncreaseButtons />
  </React.Suspense>
);
```

Here is the sandbox to reproduce : 
https://codesandbox.io/s/with-jotai-2-forked-leejy2?file=/src/App.js

**Comment by dai-shi** [comment]
#1939 alone doesn't solve it, but it fixes the signature and now we can use undocumented `unstable_unwrap`. https://codesandbox.io/s/with-jotai-2-forked-g403sz?file=/src/App.js

**Comment by TeaBough** [comment]
Using #1939 , I'm still experiencing a rendering problem when using `focus` and `split`. 
Here is the sandbox : https://codesandbox.io/s/with-jotai-2-forked-566jed?file=/src/App.js
Everytime I increase the counter it renders the fields whereas it should not since the field `items` is focused and not impacted by the increment...

**Comment by dai-shi** [comment]
That's because `items` isn't stable.
Here's the fixed version: https://codesandbox.io/s/with-jotai-2-forked-tmdpqd?file=/src/App.js

So, what #1939 means is it allows to use _undocumented_ `unstable_unwrap` to cover this #1937 cases.

**Comment by TeaBough** [comment]
Thx for the fix. But how do you handle the type ?
`focus` needs a `WritableAtom`, but `unwrap` returns and `Atom`...

**Comment by dai-shi** [comment]
> So basically what I'm trying to do is : `atomsWithQuery` => `focus` => `split`

In that case, you don't need focusAtom, because you don't have a writable atom. Just a derived atom will do.



> `focus` needs a `WritableAtom`, but `unwrap` returns and `Atom`...

Good catch. In that case, we need to create a writable atom after unwrap. It's probably over-complicated for most cases.

**Comment by TeaBough** [comment]
> In that case, you don't need focusAtom, because you don't have a writable atom. Just a derived atom will do.
Oh my... You're right... It didn't crossed my mind that `focus` is only useful if you want to write that specific atom down the road...

**Comment by dai-shi** [comment]
I guess names of focusAtom and selectAtom are mis-guiding. Docs could be improved.
