### ISSUE TITLE
TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by ha-sante** [pmndrs/jotai#1953]
## Summary
- On installing and using Jotai in a nextjs app, I keep getting this error. In isolation, from other app components, and still got the same error.
- TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))

## Link to reproduction
https://codesandbox.io/s/jotai-error-reproduction-wj2wp4

## CheckList

Please do not ask questions in issues.

- [X] I've already opened a [discussion](https://github.com/pmndrs/jotai/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [X] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by arjunvegda** [comment]
Jotai store does not accept state values as params. We'll need to create an atom and use it in our component. 

See fixed CSB: https://codesandbox.io/s/jotai-issue-1953-wiby6q?file=/src/App.tsx

Learn more about [atoms](https://jotai.org/docs/core/atom) and store [here](https://jotai.org/docs/core/store) 🙌

**Comment by ha-sante** [comment]
Sandbox not found/working

I reckon from linked, you mean, I need to use

`
myStore.set(countAtom, 1)
`

**Comment by arjunvegda** [comment]
Sorry about that, I fixed the sandbox link. Please try again

And yes!

**Comment by ha-sante** [comment]
Okay, that fixed the issue. 

Thank you very much.
