### ISSUE TITLE
Discussion: How to cancel derived async atom?

### ISSUE THREAD

**Issue by AjaxSolutions** [pmndrs/jotai#197]
This question is very similar to this Recoil issue.

https://github.com/facebookexperimental/Recoil/issues/51

**Comment by dai-shi** [comment]
JS doesn't have a cancellation api, so let's see how AbortController works.

```js
import { atom } from 'jotai'

const abortableAtom = () => {
  const { signal, abort } = new AbortController()
  return atom(async (get) => {
    abort()
    const url = get(urlAtom)
    const response = await fetch(url, { signal })
    cont data = await response.json()
    return data
  })
}
```

Assuming this works, the question is how to generalize the `read` function. I'm not also 100% sure if we can re-use AbortController. `abort()` let the previous fetch throw an error, so we may need to catch it.

**Comment by AjaxSolutions** [comment]
Thanks, but how would I abort the request when the component unmounts?

**Comment by dai-shi** [comment]
Good point... If we used the atom directly we could do something like,

```js
const abortMap = new WeakMap()

const abortableAtom = () => {
  const { signal, abort } = new AbortController()
  const anAtom = atom(async (get) => {
    abort()
    const url = get(urlAtom)
    const response = await fetch(url, { signal })
    cont data = await response.json()
    return data
  })
  abortMap.set(anAtom, abort)
  return anAtom
}

const useAbortableAtom = (anAtom) => {
  useEffect(() => {
    return () => {
      const abort = abortMap.get(anAtom)
      if (abort) abort()
    }
  }, [anAtom])
  return useAtom(anAtom)
}
```

but, this would not be very nice because other components (and dependency atoms) could be still using the same atom.

**Comment by dai-shi** [comment]
Another idea:
```js
const urlAtom = atom('https://...')

const abortableAtom = () => {
  const { signal, abort } = new AbortController()
  return atom(async (get) => {
    abort()
    const url = get(urlAtom)
    if (!url) return null
    try {
      const response = await fetch(url, { signal })
      cont data = await response.json()
      return data
    } catch (e) {
      return null
    }
  })
}

const Component = () => {
  const [, setUrl] = useAtom(urlAtom)
  useEffect(() => {
    return () => {
      setUrl('') // clear url and it leads to abort (but we need to confirm, can be race condition)
    }
  }, [setUrl])
  return ...
}
```

Hmm, this doesn't look very intuitive.

----

Actually, I have concerned such situation and would like to tackle the problem.
https://github.com/pmndrs/jotai/blob/b6ada607bd928e54214ebb00c5ef0838f53dfe2e/src/core/Provider.ts#L432-L435

So, maybe we attach a cancel function to a promise, and call it before discarding it (or just discard the promise if no `cancel`)

```js
          if (atomState.readP) {
            if (atomState.readP.cancel) {
              atomState.readP.cancel()
            }
            atomStateCache.set(atom, { ...atomState, readP: undefined })
          } else {
            atomStateCache.set(atom, atomState)
          }
```

(On second thought, this may discard promises too aggressively. We need to collect more use cases and test specs.)

**Comment by AjaxSolutions** [comment]
> I'm not also 100% sure if we can re-use AbortController

AbortController can't be reused or reset.  Thanks for taking time to answer my question.  This Recoil issue is still being discussed.

**Comment by dai-shi** [comment]
> AbortController can't be reused or reset. 

So, it has to be something like this:
```js
const abortableAtom = () => {
  let abort = () => {}
  return atom(async (get) => {
    abort()
    const controller = new AbortController()
    abort = controller.abort
    const url = get(urlAtom)
    const response = await fetch(url, { signal: controller.signal })
    cont data = await response.json()
    return data
  })
}
```

There's a caveat though. We can technically reuse atoms for multiple Providers. So, the singleton for an atom might not work as expected. It think it's better to abort fetch outside of atoms.

For unmount use case, I think it's better not to cancel promises. The mental model of Jotai is a big WeakMap. So, as long as an atom exists, its value should be available. It means even if it's unmounted, it will be remounted keeping the value (it does not re-evaluate `read`.)

**Comment by tarngerine** [comment]
hi, i have a similar need but rather than aborting i was thinking if it's possible for a (get) => {} to provide the previous atom value so i can just return that, e.g.

const atom = atom(...)

const derived = atom((get, previous) => {
  if(someCondition) return previous
  return newValue
})

although i dont know if this would prevent a rerender

**Comment by Aslemammad** [comment]
@tarngerine Check this:
```ts
const previousAtom = atom(null)
const derived = atom((get) => {
  if(condition) return get(previousAtom)
    return get(derived)
}, (get,set,update) => {
  set(previousAtom, get(derived))
  set(derived,update)
})

```
I didn't check this, but maybe the idea solves your problem.

**Comment by dai-shi** [comment]
If the `condition` is only from the atom (previous) value, equalityFn in selectAtom might help.

**Comment by dai-shi** [comment]
I think it's mostly answered. Please open a new discussion if necessary.

**Comment by dai-shi** [comment]
More than one year passed, I've got an actual implementation. #1091 
It's not about manual cancellation, but cancellation on overwriting and on unmount.
The previous discussion is not valid because we didn't have `onUnmount` back then, but the discussion context seems valid, so let's re-open.

**Comment by riemonyamada** [comment]
I like this pattern which uses `onMount` and `atoms in atom`. This pattern is useful not only for abortable cases but also for unsubscribe-able cases (like Firestore) or any other cancelable cases.

I don’t think it’s possible to implement this pattern with Recoil, because Recoil Effect is different from Jotai’s `onMount`.

```
const urlAtom = atom('https://...');

function createAbortableAtom(url) {
  const abortableAtom = atom(null);
  abortableAtom.onMount = (setAtom) => {
    const controller = new AbortController();
    const data = fetch(url, { signal: controller.signal }).then(({ json }) => json);
    setAtom(data);
    return controller.abort;
  };
  return abortableAtom;
}

const wrapperAtom = atom((get) => {
  const url = get(urlAtom);
  if (!url) return atom(null);
  return createAbortableAtom(url);
});

const dataAtom = atom((get) => get(wrapperAtom));
```

**Comment by dai-shi** [comment]
Looks nice.

Just a small nit: `return () => controller.abort();`

**Comment by riemonyamada** [comment]
Oops. Thanks, I'll fix that.

**Comment by dai-shi** [comment]
I think it is too technical to document for now.
We should actually document more about `onMount` first and its typical use cases.
Then, `createAbortableAtom` is going to be one of various advanced use cases.

The reason I reopened this issue is that I'm working on #1091. This should going to be a recommended method.
