### ISSUE TITLE
Error: Atom state not found. Weirdness with async derived atom loading depending on where atom is used.

### ISSUE THREAD

**Issue by tarngerine** [pmndrs/jotai#201]
Hi there, I am running into an issue using async atoms. Here is the repro code sandbox: https://codesandbox.io/s/suspicious-nobel-bgzce

Expected:
- `roomClientAtom` should properly load after `currentSpaceAtom` and `roomServiceAtom` are configured.

Actual:
- `roomClientAtom` errors out
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/1629901/99716849-38a46880-2a6e-11eb-8180-c368cea23d7a.png">

Some interesting behavior — if I lift `const [room] = useAtom(roomClientAtom)` from `<Room>` into `<Loader>`, the `roomClientAtom` is now properly loaded. Curious why behavior of derived atom depends on where it is called with `useAtom`? 

Repro this by uncommenting line 44

<img width="768" alt="image" src="https://user-images.githubusercontent.com/1629901/99716823-3215f100-2a6e-11eb-8ede-e2293907a4f9.png">

**Comment by dai-shi** [comment]
Hi! Thanks for reporting. This is a bug. There are still some cases not implemented well, especially around async derived atoms.

I plan to revise the implementation and overhaul, and this kind of reproductions for unexpected behavior is very helpful.

I would like to create a failing test to start with. Would you help me a bit? Could you shave your example further to reproduce the issue at minimal? I wonder if this happens with just one primitive atom. Or does it only happen with two primitive atoms?

Dependency graph:
![image](https://user-images.githubusercontent.com/490574/99752529-d9a32a00-2b27-11eb-8bc7-7a52c2e955a2.png)
https://excalidraw.com/#json=5194287503376384,PTiI18H8n99OLxn254_xJw

Looks correct? If we remove `currentSpaceAtom`, does the problem persist?

**Comment by tarngerine** [comment]
## Removing currentSpaceAtom
still reproduces
https://codesandbox.io/s/recursing-nobel-xi24g?file=/src/App.tsx
<img width="327" alt="image" src="https://user-images.githubusercontent.com/1629901/99754462-0a467d80-2aae-11eb-86c2-5bb9d686c748.png">


## Removing roomServiceAtom
still reproduces, but one less warning message
https://codesandbox.io/s/magical-ives-9fo2x?file=/src/App.tsx
<img width="328" alt="image" src="https://user-images.githubusercontent.com/1629901/99754485-13cfe580-2aae-11eb-9e1a-bdafb36a586e.png">
<img width="258" alt="image" src="https://user-images.githubusercontent.com/1629901/99754517-25b18880-2aae-11eb-8ffb-81200be19f4a.png">

**Comment by dai-shi** [comment]
Thanks!

> still reproduces, but one less warning message

This sounds like there are two separate bugs to produce this issue.
