### ISSUE TITLE
Declare `@types/react` as peerDeps to avoid phantom dep

### ISSUE THREAD

**Issue by wjw99830** [pmndrs/jotai#2047]
## Summary

`jotai` imports `@types/react` but doesn't declare it in `package.json`, so in some monorepos there will be a 'phantom dep' problem that caused by two `@types/react` which has different major.

## Link to reproduction

https://github.com/wjw99830/phantom-dep

### Steps
- run `pnpm i`
- run `cd packages/react-18 && pnpm remove @types/react && pnpm i @types/react@18`, **in order to hoist `@types/react@18` to `.pnpm/node_modules`**
- restart ts server, then look at the definition of `JSX.Element` in `packages/react-17/src/index.tsx`. There are two definitions.

## Check List

Please do not ask questions in issues.

- [ ] I've already opened a [discussion](https://github.com/pmndrs/jotai/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [ ] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by dai-shi** [comment]
Does it work if it's optional peer dependency? Yeah, I think so.
It's interesting as I thought peerDeps are only for JS.
If adding it to peerDeps fixes the issue, it makes sense anyway. Can you please open a PR? Oh actually we need three PRs for zustand, jotai and valtio.
