### ISSUE TITLE
Component Exception ( Please use <Provider>)

### ISSUE THREAD

**Issue by ralphievolt** [pmndrs/jotai#205]
The component is a child component where Jotai Provider is set. If  I removed this declaration 
`  const [, setKeyValue] = useAtom(KEY_VALUE);` 
 everything is fine however if I declare it I'll get an error 
**Component Exception  Please use  Provider**

I am running React Native.

This is the code.

```
import { useAtom } from "jotai";
import commaNumber from "comma-number";

import { KEY_VALUE } from "./atom/atoms.js";

export default function Pricing() {
  const [text, setText] = React.useState("");
  const [, setKeyValue] = useAtom(KEY_VALUE);

  return (
    <>
```

**Comment by dai-shi** [comment]
There are several cases. Here's some notes:
- Are you using r3f or some other custom reconcilers?
- Do you think you can repro the issue in Web? 
- Could you create a codesandbox to repro?
- If it only happens in RN, there can be a bug.

**Comment by ralphievolt** [comment]
The problem exist in react-native web as well however I think it originated when the component is encapsulated by this modal component 
[https://callstack.github.io/react-native-paper/portal.html](url)

I'll be closing this issue since its not related with Jotai but a little idea what's the work around will be great =)

**Comment by dai-shi** [comment]
@ralphievolt I'm not very familiar with portal, but it looks like a separate react tree.
In such a case, useBridge/Bridge should help
https://github.com/pmndrs/jotai/blob/master/docs/core.md#usebridgebridge
