### ISSUE TITLE
Read function of atom keeps running even after the component unmounts

### ISSUE THREAD

**Issue by sunniejai** [pmndrs/jotai#2076]
## Summary
I'm running into a really weird issue where each time a component mounts and creates a new atom via useMemo(), I can see that the read function keeps running for atoms that should have been unmounted already

If you look at the code from the codesandbox, everytime the component unmounts, i can see that it will log "Unmounting atom 1" etc.

But when the component remounts, I can see it still logging running atom read function 1 and also running atom read function 2, and it keeps going from like 1-N where N is the amount of times the component has mounted and unmounted. This is causing some issues in our app where it slows down overtime as the amount of work jotai is doing seems to be increasing 

I know in this code is a bit trivial in that we didn't need to create the atom in a useMemo (can just define it outside of the scope) but sometimes we do need to pass parameters to the atoms

Link to conversation on discord: https://discord.com/channels/740090768164651008/752920140483526677/1140738335640408074

## Link to reproduction
https://codesandbox.io/s/upbeat-noether-xf8j7c?file=/src/App.tsx

## Check List

Please do not ask questions in issues.

- [x] I've already opened a [discussion](https://github.com/pmndrs/jotai/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by dai-shi** [comment]
A simplified version:
https://codesandbox.io/s/musing-pare-pntjrw?file=/src/App.tsx

**Comment by dai-shi** [comment]
Added a failing test in #2078

**Comment by dai-shi** [comment]
fbe82d1 removing useEffect still reproduces the error.

**Comment by dai-shi** [comment]
#2078 will fix it: https://codesandbox.io/s/awesome-northcutt-n5yz2r
