### ISSUE TITLE
Accessing derived atoms from a write only atom can lead to atoms that never get cleaned up and degrade performance over time

### ISSUE THREAD

**Issue by sunniejai** [pmndrs/jotai#2077]
## Summary
If a write only atom reads from a derived atom and that derived atom doesn't have a subscription via useAtomValue then that derived atom stays mounted and doesn't get cleaned up. This leads to an increasing number of atoms and starts to slow down `recomputeDependents` after a while

## Link to reproduction
https://codesandbox.io/s/xenodochial-worker-zwnspm?file=/src/App.tsx

Clicking the initialize button here will increase the mounted.t.size in vanilla.js (line 343) by 1 each time. Looks like onMount and unmount is never triggered though (which makes sense since there's no subscription to that new atom)

I debugged this by putting a breakpoint on vanilla.js on line 343 with this condition `mounted != null && mounted.t.size > 0`

## Link to convo
https://discord.com/channels/740090768164651008/752920140483526677/1141131076115378257

## Check List

Please do not ask questions in issues.

- [x] I've already opened a [discussion](https://github.com/pmndrs/jotai/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by dai-shi** [comment]
>   //Read from the new derived atom. This atom never gets cleaned up now.
>   get(newDerivedAtom);

I don't think this atom will be mounted. Hence it doesn't get unmounted.

> `mounted != null && mounted.t.size > 0`

I'm not sure where this code comes from. L343 looks something different.

---
That said, I'm afraid there can be some bugs around `canUnmountAtom` and `mountDependencies`.

**Comment by sunniejai** [comment]
```mounted != null && mounted.t.size > 0``` 
I was referring to the breakpoint condition that I would put in the debugger because that loop goes through a lot of different atoms.

I would set the breakpoint on L464 here in the actual code: https://github.com/pmndrs/jotai/blob/144a6b5177e96c9ef1fd221e013c576dfdbe26a5/src/vanilla/store.ts#L464

**Comment by dai-shi** [comment]
If the atom is mounted or unmounted atoms are in dependents (="t"), it seems a bug. In the second case, it feels like related with #2076.

**Comment by sunniejai** [comment]
Debugging through this. There's definitely unmounted atoms in `mounted.t`. 

Have a tweaked version here: https://codesandbox.io/s/vibrant-water-wyl4xp?file=/src/App.tsx Basically if you click `show/hide` before you click the Initialize button (no derived atoms created yet via a write-only atom) then the baseAtom mounts/unmounts fine.

Once you click initialize once, the baseAtom is no longer able to unmount

**Comment by sunniejai** [comment]
It's happening on https://github.com/pmndrs/jotai/blob/144a6b5177e96c9ef1fd221e013c576dfdbe26a5/src/vanilla/store.ts#L649

though i'm not sure what the proper fix would be here since I'm not super familiar with the timing of these functions. Possibly it's something like we shouldn't add to `mounted.t` if there's no subscription to that dependent?

**Comment by dai-shi** [comment]
We should add to `mounted.t` if its dependency is mounted. This is one of the trickiest things and as I said there can be a bug.

> https://codesandbox.io/s/vibrant-water-wyl4xp?file=/src/App.tsx

I don't think `newDerivedAtom` should be mounted. Sounds like a separate bug.

**Comment by dai-shi** [comment]
While digging into #2076, I noticed that the first atom isn't mounted during double effects in strict mode. So, probably it's the same issue at the root.

**Comment by dai-shi** [comment]
Okay, I was right. #2078 will fix it: https://codesandbox.io/s/eager-spence-tgtd9m
