### ISSUE TITLE
useEffect not called with latest atom value

### ISSUE THREAD

**Issue by dwelle** [pmndrs/jotai#208]
In a very specific case, a `useEffect` isn't triggered on state update (render) despite dependencies being changed.

(**EDIT:** actually, the two atoms aren't necessary as updating a single one, twice, is enough to reproduce. See sandbox in [comment below](https://github.com/pmndrs/jotai/issues/208#issuecomment-733280403)) After stripping down the whole app into the smallest reproducible example I was able to narrow it down to this: when you update two atoms where the second atom is updated right in the next frame of the previous atom, and you also update the state (in the given `useEffect`) of the component that consumes those atoms, the `useEffect` isn't triggered for the 2nd atom's value.

It's possible the conditions can be simplified even further but this is what I came up with.

Note: this isn't an academic exercise. It came up in a production code and resulted in an app-breaking bug because the state didn't resolve (i.e. the `useEffect` wasn't called with updated, final value).

Reproducible example: https://codesandbox.io/s/frosty-field-tgduk?file=/src/index.js&expanddevtools=1

You should see something like this (you'll probably need to refresh the page via the in-app browser refresh button):

![image](https://user-images.githubusercontent.com/5153846/100140285-0a20f600-2e91-11eb-938d-e6cbd129dd87.png)

Does not reproduce 100%, but often enough.

Note: plain Context [isn't affected by this bug](https://codesandbox.io/s/agitated-glitter-yvroi?file=/src/index.js&expanddevtools=1).

- **Jotai version:** `0.6.2`, `0.11.1`
- **React versions:** `16.14.0`, `17.0.0`
- **Reproduces in strict mode:** yes (both strict and non-strict)

**Comment by dwelle** [comment]
Indeed, it turns out it can be simplified to just use one atom: https://codesandbox.io/s/infallible-engelbart-qmvrv?file=/src/index.js

**Comment by dai-shi** [comment]
This is very helpful. Thanks for the repro. (for me, it's 100% of time)
I guess I know what's happening underneath.
Not sure yet how to fix it, but let me start working on local tests.
