### ISSUE TITLE
Weird behavior with write-only atoms referencing atomWithStorage atoms internally.

### ISSUE THREAD

**Issue by juanhenriquez** [pmndrs/jotai#2080]
Hey 👋🏻! Not sure if this is the right place to ask this, but I'm facing some issues with write-only atoms that internally use atoms created with `atomWithStorage`.

Let's say we have the following atoms:
```tsx
const songsAtom = atomWithStorage("songs", []);
const playlistAtom = atomWithStorage("playlist", []);

const addSongsToPlaylistAtom = atom(null, (get, set) => {
  const songs = get(songsAtom); // <- this will always be the initial value ([]) if I don't render `songsAtom` somewhere
  set(playlistAtom, songs);
});

const saveSongsAtom = atom(null, (get, set, songs) => {
  set(songsAtom, songs);
});
```

If I call `addSongsToPlaylistAtom()`, the `get(songsAtom)` will always return the initial value of the atom (`[]` in this case) If I don't render `songsAtom` somewhere in the app.

I guess this happens because `unstable_getOnInit` is `false` by default, which makes sense for next.js applications and that's why this always return the initial data:
https://github.com/pmndrs/jotai/blob/144a6b5177e96c9ef1fd221e013c576dfdbe26a5/src/vanilla/utils/atomWithStorage.ts#L147-L150

And if I don't render the atom created with `atomWithStorage` at least once, this never gets called either:
https://github.com/pmndrs/jotai/blob/144a6b5177e96c9ef1fd221e013c576dfdbe26a5/src/vanilla/utils/atomWithStorage.ts#L157-L166

Do you guys know any workaround for this? How can I create atoms with `atomWithStorage` that are not intended to be rendered in the UI while still be able to use them inside write-only atoms and always get the latest value stored in LocalStorage?

_Originally posted by @juanhenriquez in https://github.com/pmndrs/jotai/discussions/1999#discussioncomment-6748608_

**Comment by dai-shi** [comment]
Please keep using the original thread or create a new discussion if you think is more appropriate. Thanks.
