### ISSUE TITLE
Split atom creators recipe in docs into multiple markdown files

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#2082]
It's a single file for now and it's fairly big.

**Comment by gerzonc** [comment]
Can I help with this?

**Comment by KrzysztofMoch** [comment]
Hey, I can do it
Would you like to separate each function into single file or group them somehow ?

**Comment by dai-shi** [comment]
Thanks guys! Let's assign @gerzonc and see how it goes.
