### ISSUE TITLE
invalidation / re-evaluation of atoms is broken

### ISSUE THREAD

**Issue by tux21b** [pmndrs/jotai#2084]
## Summary

This example creates two primitive boolean atoms f1 and f2 as well as a derived atom which is set to `f1 && f2`. Selecting and deselecting the checkboxes leads to a state with `f1 == true`, `f2 == true` and `f1 && f2 == false` which should not be possible.

This seems to be a regression in Jotai 2.x.

## Link to reproduction

```
const f1 = atom(false);
const f2 = atom(false);
const f3 = atom(
  (get) => {
    // subscribing to f1 and f2 fixes the problem...
    // console.log(get(f1), get(f2))
    return get(f1) && get(f2);
  },
  (get, set, val: boolean) => {
    set(f1, val);
    set(f2, val);
  }
);

function Field(props: { atom: WritableAtom<boolean, [boolean], void> }) {
  const [checked, setChecked] = useAtom(props.atom);
  return (
    <input
      type="checkbox"
      checked={checked}
      onChange={(ev) => setChecked(ev.target.checked)}
    />
  );
}

const App = () => (
    <div className="App">
        f1: <Field atom={f1} />
        f2: <Field atom={f2} />
        f1 AND f2: <Field atom={f3} />
    </div>
)
```

https://codesandbox.io/s/crazy-kare-5d4xm9?file=/src/App.tsx:0-1082

**Comment by dai-shi** [comment]
> I'm afraid we need completely different logic.

On second thought, this can be a simple bug in recomputeDependents. 🤔

**Comment by dai-shi** [comment]
#2086 should fix it.
Please try it with your actual app.
https://ci.codesandbox.io/status/pmndrs/jotai/pr/2086
☝️ Find "Local Install Instructions"

**Comment by tux21b** [comment]
You are my personal hero! Everything in my project now works again as expected.

Thanks for your quick and friendly reply and the fast bugfix!

**Comment by tux21b** [comment]
Ups, I accidently closed the issue. I am happy with the MR, but the issue should be probably closed when the MR was merged.
