### ISSUE TITLE
atomWithStorage issue since 2.3.0+

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#2098]
This is a tracking issue for #2095. See discussions there.

Reproduction: https://codesandbox.io/s/sharp-lamport-k9s8mp?file=/src/App.tsx

I think it's a bug in https://github.com/pmndrs/jotai/pull/2029 and it's not specific to atomWithStorage.

Tasks:
1. Create a failing test (without atomWithStorage, hopefully only with store api)
2. Fix it

**Comment by dai-shi** [comment]
Would anyone like to work on Task 1?

**Comment by gerzonc** [comment]
> Would anyone like to work on Task 1?

Would like to get into it if it's okay :)
