### ISSUE TITLE
Derived dependent atoms not updating during multiple sets

### ISSUE THREAD

**Issue by jsheely** [pmndrs/jotai#2107]
## Summary
I am seeing a change from 2.3.1 to 2.4.1 where atoms that are updated that have derived values using that atom are not updated

I commonly use `backing` fields for my atoms with custom setters that set the backing field and may set multiple other atoms.

The change between the versions is that when doing a set() on the backing field and then another set() for another atom() that uses that backing field. It is fine. But if that atom() uses another atom that uses the backing field it has not been updated yet.

Here is my quick psuedo code of the issue

```typescript
const testingArray = [];
const _selectedItemIdAtom = atom<string>("")
const selectedItemIdAtom = atom(
    (get) => get(_selectedItemIdAtom),
    (get, set, id: string) => {
        set(_selectedItemIdAtom, id);
        if (id === '')
            set(stateAtom, null)
    }
)

const selectedItem = atom((get)=> {
    const id = get(selectedItemIdAtom);
    return testingArray.find(item => item.id === id);
})

const _stateAtom = atom({});
const stateAtom = atom((get) => { }, (get, set) => { 
    const item = get(selectedItem); 
    const itemId = get(_selectedItemIdAtom)
    console.log(itemId, item?.id) // itemId !== item?.id in 2.4.1. Correct in 2.3.1
    if (item) {
        set(_stateAtom, item.state);
    }
});
```

## Link to reproduction
https://codesandbox.io/s/jotai-2-4-1-regression-kmclx3?file=/src/App.tsx

**Comment by dai-shi** [comment]
Thanks for reporting.
I hope you can create a small reproduction with https://csb.jotai.org.

Meanwhile, if this is a regression from 2.3.1, can you try and see which causes it?
- 2.4.0
- #2078 
- #2086 

You can install the codesandbox build in those PRs.

**Comment by jsheely** [comment]
Attached a repo. Changing from 2.4.1 to 2.3.1 in the package.json will change the behavior of this button

(2.4.1) Missmatch 1 undefined
(2.3.1) Missmatch 1 1
Console.log

I believe that it might be related to the work on https://github.com/pmndrs/jotai/pull/2086 which was my initial hunch. I will try and test them individually

**Comment by jsheely** [comment]
Confirmed that it is #2086 that introduces the behavior change

https://codesandbox.io/s/react-typescript-forked-57q86k

**Comment by dai-shi** [comment]
Thanks. Is it possible for you to try it with Jotai v1.13.1? #2086 was to fix a regression from v1.

**Comment by dai-shi** [comment]
Thanks. Yeah, this seems a regression with fixing another regression from v1...

**Comment by dai-shi** [comment]
#2111 fixes it: https://codesandbox.io/s/jotai-2-4-1-regression-95584g

**Comment by jsheely** [comment]
Confirmed #2111 resolves issue. Nice work on the PR. That looks like a non trivial update.
