### ISSUE TITLE
useAtomValue util

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#212]
Analogous to recoil's `useRecoilValue`, it'd be nice to have an equivalent hook.

This should be in `jotai/utils` along with `useUpdateAtom`.

The implementation in JS is as simple as this.
```js
const useAtomValue = (anAtom) => useAtom(anAtom)[0]
```

So, all we need would be:
- [ ] implement in TS
- [ ] add docs
- [ ] write test

**Comment by Aslemammad** [comment]
@dai-shi I'm gonna work on it. Thanks.

**Comment by Aslemammad** [comment]
#213 Merged.
