### ISSUE TITLE
Type Error while using useHydrateAtoms

### ISSUE THREAD

**Issue by meotimdihia** [pmndrs/jotai#2124]
## Summary
I copied the code in the documentation https://jotai.org/docs/integrations/query, but it looks like there are bugs:
```ts
const HydrateAtoms = ({ children }) => {
  useHydrateAtoms([[queryClientAtom, queryClient]]); <-- TypeError
  return children;
};
```

```ts
(alias) const queryClientAtom: PrimitiveAtom<QueryClient> & {
    init: QueryClient;
}
import queryClientAtom
Argument of type '(QueryClient | (PrimitiveAtom<QueryClient> & { init: QueryClient; }))[][]' is not assignable to parameter of type 'Iterable<readonly [AnyWritableAtom, unknown]>'.
  The types returned by '[Symbol.iterator]().next(...)' are incompatible between these types.
    Type 'IteratorResult<(QueryClient | (PrimitiveAtom<QueryClient> & { init: QueryClient; }))[], any>' is not assignable to type 'IteratorResult<readonly [AnyWritableAtom, unknown], any>'.
      Type 'IteratorYieldResult<(QueryClient | (PrimitiveAtom<QueryClient> & { init: QueryClient; }))[]>' is not assignable to type 'IteratorResult<readonly [AnyWritableAtom, unknown], any>'.
        Type 'IteratorYieldResult<(QueryClient | (PrimitiveAtom<QueryClient> & { init: QueryClient; }))[]>' is not assignable to type 'IteratorYieldResult<readonly [AnyWritableAtom, unknown]>'.
          Type '(QueryClient | (PrimitiveAtom<QueryClient> & { init: QueryClient; }))[]' is not assignable to type 'readonly [AnyWritableAtom, unknown]'.
            Target requires 2 element(s) but source may have fewer.ts(2345)
```

## Link to reproduction

https://codesandbox.io/s/jotai-query-demo-forked-jvhqhl?file=/src/App.tsx

## Check List

Please do not ask questions in issues.

- [x] I've already opened a [discussion](https://github.com/pmndrs/jotai/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by dai-shi** [comment]
It doesn't repro with latest versions: https://codesandbox.io/s/jotai-query-demo-forked-85pzh7

There might be something missing. Please open [a new discussion](https://github.com/pmndrs/jotai/discussions/new) if you need to discuss further.
