### ISSUE TITLE
Jotai async atom not working with expo-router

### ISSUE THREAD

**Issue by smontlouis** [pmndrs/jotai#2131]
## Summary
It looks like async read atoms are not working well with expo-router
No issue using classic expo with App.js.
When using expo-router, page is blank.

```jsx
const countAtom = atomWithAsyncStorage('countAtom', 0)
const count2Atom = atom(async (get) => (await get(countAtom)) * 2)

export const Component = () => {
  const [count] = useAtom(count2Atom)
  console.log(count)
  return <Text>Component {count}</Text>
}
```

## Link to reproduction
https://github.com/smontlouis/jotai-async

Replace package.json "main" entry with either "expo-router/entry" or "node_modules/expo/AppEntry.js" to see jotai not working with expo-router

**Comment by dai-shi** [comment]
Are there any error logs or something?
Does it work with sync atoms?

**Comment by smontlouis** [comment]
Working with sync atoms, no error logs unfortunately

**Comment by dai-shi** [comment]
Is the blank screen because of `<Suspense fallback={null}>`?
Can you try to put something? `<Suspense fallback="Got you!">`

**Comment by dai-shi** [comment]
Also, can you confirm that `atomWithAsyncStorage` has nothing to do with it?
Like:
```js
const count2Atom = atom(async () => 0)
```

**Comment by smontlouis** [comment]
Yes. 
The following is failing (just added async)

```
export const currentBookNumAtom = atom(1)

export const currentBookAtom = atom(async (get) => {
  const currentBookNum = get(currentBookNumAtom)
  const currentBook = books[currentBookNum - 1]
  return currentBook
})
```

**Comment by smontlouis** [comment]
> Are you sure? What happens if you remove the Suspense component entirely?

<img width="423" alt="image" src="https://github.com/pmndrs/jotai/assets/3509412/020edc4c-42bd-43af-8d20-da1821af8b0f">

**Comment by dai-shi** [comment]
It looks weird. Can you try this instead?

```js
export const currentBookAtom = atom(async () => {
  const currentBook = books[0]
  return currentBook
})
```

**Comment by smontlouis** [comment]
This is failing 😄 

```jsx
export const currentBookAtom = atom(async (get) => {
  return 1
})
```

**Comment by smontlouis** [comment]
> Re: [#2131 (comment)](https://github.com/pmndrs/jotai/issues/2131#issuecomment-1717560505)
> 
> So, do you see "Got you" if you add `<Suspense fallback="Got you">`?


```jsx
<SafeAreaProvider>
      <Provider>
        <Suspense
          fallback={
            <View style={{ alignItems: 'center', justifyContent: 'center' }}>
              <Text>Got you !!</Text>
            </View>
          }
        >
          <Root />
        </Suspense>
      </Provider>
    </SafeAreaProvider>
```

Nope :( (same picture as https://github.com/pmndrs/jotai/issues/2131#issuecomment-1717543631)

**Comment by dai-shi** [comment]
> This is failing 😄
> 
> ```js
> export const currentBookAtom = atom(async (get) => {
>   return 1
> })
> ```

That's good to know.

At this point, I don't know what's wrong. If it works without expo-router, expo-router does something to cause Suspense failure. You might then need to create a small reproduction (hopefully without Jotai) and report it to them.

**Comment by dai-shi** [comment]
Re https://github.com/pmndrs/jotai/issues/2131#issuecomment-1717568507

Hmm, that's unfortunate. I've never experienced such a behavior. We need some errors.

**Comment by smontlouis** [comment]
> > What would be an equivalent so that I can try with something else (without jotai) for expo ?
> 
> ```js
> const promise = new Promise((r) => setTimeout(r, 10 * 1000));
> let resolved = false;
> promise.then(() => { resolved = true; });
> 
> const usePromise = () => {
>   if (!resolved) { throw promise; }
> };
> ```
> 
> It should give you the blank screen, if my understanding is correct. But, then expo-router team may say that they don't support Suspense yet.

Omg it's failing ! 
Thank you for your time I'll report to them !
