### ISSUE TITLE
When working with async atoms in TypeScript, cannot import `Loadable` type from `utils`

### ISSUE THREAD

**Issue by jeerbl** [pmndrs/jotai#2134]
## Summary
When import `loadable` from `jotai/utils`, I can't import the type `Loadable` at the same time. This will fail:
```javascript
import { loadable, Loadable } from 'jotai/utils';
```

Instead, I have to find the `Loadable` type manually in `/vanilla` like this:
```javascript
import { loadable } from 'jotai/utils';
import { Loadable } from 'jotai/vanilla/utils/loadable';
```

## Link to reproduction
[Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgGwgQwCZoEbIKYA0cAMulrnnAL5wBmUEIcA5AFYQxrAD0ArjMGQBnZgG4AUOO7c4AdTzIAxo0owIcGAAtKAFQCeYPAGVFUYGHgAFZGj0BzBrwB2GIluBC4HuGjgB3PGwhYBg8KRk-TWBFTTg7YAA3PE89CF4fOBi0J0VVdT8zUKIhTTQoSmyMFDwypzh9QxMzCwA6SWk4AE00zLTkKvcnAGs4CFoveGA6rXLKP1shAC5w8Lg4AFo4AEEUCEU0AQhp9Xxa+oNjU3N4SLxyuCcOKKc7TOy4bHK0IdWN7bgwDZchp1HgAB6GMwgPBOG4hWINS7NeBCPSwtBgoiVOAlMqqbRwACqACViJ4-PDRlo7kJfpsdkJKtgIGCQXBwZDQDC4Vo4BhgLRaHdub1wII7nQajBeOVPGNzo0rhZJMonEJ4NkAKJgtDgfAANTKwBw+DgAF44AAiAASClQcmg-Ut4lVQgg+BaqDsAAotTq9XhDWYTXgAJTtGQ6E41KB1EDQCrM-gaAk2F68NB2QiZZDREY4CBJLx1S3a3WA5KW0ZQK2yUowZieAByeD8lraHQA8tSoBShNmsyjOLA8FVsHo4OV4wkpq9qf3RdDYZ5sdT-I6qt5UjKATZ7I4XG01kA)

## Check List

Please do not ask questions in issues.

- [ ] I've already opened a [discussion](https://github.com/pmndrs/jotai/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by dai-shi** [comment]
It's intentional not to export `Loadable` type from the utils bundle as usually it's not needed/recommended. It's exported in the source to cover some edge cases.
Please provide a real example if you need help.

Closing, but feel free to comment here or open a new discussion.

**Comment by emccorson** [comment]
How about the case of an atom creator which returns a loadable? Below is one example am I using.

In my case, importing from `jotai/vanilla/utils/loadable` works fine; it was just tricky to find the correct import.

```typescript
export const createRefreshableAtom = <T>(
  fn: (get: Getter) => Promise<T>
): [Atom<Loadable<T>>, Atom<Promise<T>>] => {
  const baseAtom = atom(new Promise<T>(() => {}));
  const loadableAtom = loadable(baseAtom);

  const refreshAtom = atom(
    get => get(loadableAtom),
    async (get, set) => {
      const promise = fn(get);
      try {
        await promise;
      } finally {
        set(baseAtom, promise);
      }
    }
  );

  return [refreshAtom, baseAtom];
}
```

**Comment by dai-shi** [comment]
Yeah, for generics, it's unavoidable.

If you don't mind, I'd do this:
https://tsplay.dev/mZBo9m
<img width="681" alt="image" src="https://github.com/pmndrs/jotai/assets/490574/80bea06a-e759-4891-bf4c-03f73d3dafd1">

**Comment by emccorson** [comment]
Thanks! I think this works well!

**Comment by bolinfest** [comment]
@dai-shi when trying to use ESLint checks such as:

https://typescript-eslint.io/rules/explicit-module-boundary-types/

It is important to be able to explicitly name `Loadable` as part of a type when used as part of a contract/`export`. Is it not OK to do this:

```
const userAtom: Atom<Promise<User | null>> = atom(async (get) => {
  /* async logic to produce a User */
});

/**
 * Do not export userAtom, only loadableUser.
 * Here I would like to declare the type as `Atom<Loadable<Promise<User | null>>>`
 */
export const loadableUser = loadable(userAtom);
```

**Comment by bolinfest** [comment]
To be clear, my goal in exporting `loadableUser` is to force callers to consider the async behavior so they can't do `useAtom(userAtom)` and inadvertently trigger a `<Suspend>`.

**Comment by dai-shi** [comment]
Yes, we know it's limited with explicit typing (also called no "slow types"?).

For now, please define it on your end:
```ts
type Loadable<Value> =
  | { state: 'loading' }
  | { state: 'hasError'; error: unknown }
  | { state: 'hasData'; data: Awaited<Value> }
```
or import from deep path:
```ts
import type { Loadable } from 'jotai/vanilla/utils/loadable'
```
We may change out mind in the future, but for now, it's the only solution.
