### ISSUE TITLE
jotai-recoil issue since 2.3.0+

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#2168]
This is a tracking issue for #2164. See discussions there.

Reproduction: https://codesandbox.io/s/flamboyant-sanderson-kp8k3q?file=/src/App.tsx

I think it's a bug in https://github.com/pmndrs/jotai/pull/2029 and it's not specific to jotai-recoil.

Tasks:
1. Create a failing test (without jotai-recoil, hopefully only with store api)
2. Fix it

**Comment by dai-shi** [comment]
I wonder why we didn't have such tests until now.

**Comment by dai-shi** [comment]
Here's the failing test. It passes on v2.2.3.

```diff
diff --git a/tests/vanilla/store.test.tsx b/tests/vanilla/store.test.tsx
index a95d35b..6093439 100644
--- a/tests/vanilla/store.test.tsx
+++ b/tests/vanilla/store.test.tsx
@@ -423,3 +423,15 @@ it('should update derived atoms during write (#2107)', async () => {
   store.set(countAtom, 2)
   expect(store.get(countAtom)).toBe(2)
 })
+
+it('should not recompute a derived atom value if unchanged (#2168)', async () => {
+  const store = createStore()
+  const countAtom = atom(1)
+  const derived1Atom = atom((get) => get(countAtom) * 0)
+  const derive2Fn = vi.fn((get: Getter) => get(derived1Atom))
+  const derived2Atom = atom(derive2Fn)
+  expect(store.get(derived2Atom)).toBe(0)
+  store.set(countAtom, (c) => c + 1)
+  expect(store.get(derived2Atom)).toBe(0)
+  expect(derive2Fn).toHaveBeenCalledTimes(1)
+})
```

**Comment by dai-shi** [comment]
Sure!

**Comment by dai-shi** [comment]
@eryue0220 Any progress?
Should I work on it, or does anyone else want to try?

**Comment by eryue0220** [comment]
> @eryue0220 Any progress? 有什么进展吗？ Should I work on it, or does anyone else want to try?我应该努力，还是其他人想尝试？

I'm still working on it. Maybe more some time.

**Comment by eryue0220** [comment]
@dai-shi Hello，I have some doubts about this. I found the bug occurred because the `hasPromiseAtomValue` call was omitted in this [line](https://github.com/pmndrs/jotai/blob/main/src/vanilla/store.ts#L356). But I don't have much context to know why.

**Comment by dai-shi** [comment]
This line?

https://github.com/pmndrs/jotai/blob/cdbfcdf7a6549c96117b2479cf6fb994800a6b69/src/vanilla/store.ts#L356

Can you open a PR? I will see if it makes sense or not.

**Comment by eryue0220** [comment]
Sorry, I marked a wrong line. It's [here](https://github.com/pmndrs/jotai/blob/main/src/vanilla/store.ts#L372), and I committed the PR, but I'm still working on it. The current code still exists bugs.

**Comment by dai-shi** [comment]
Ah, I see. It doesn't seem ideal, because it recomputes for all promise dependencies (some tests may fail, or such tests are missing.)

btw, we have another issue related with promise handling. https://github.com/pmndrs/jotai/discussions/2192#discussioncomment-7314439
It's not the same issue as it doesn't fix with v2.2.3, but it might be somehow related.
Hopefully, we have a single solution to cover both.

**Comment by dai-shi** [comment]
> Hopefully, we have a single solution to cover both.

It's unlikely as I investigated #2199.

**Comment by dai-shi** [comment]
I think it was our intentional behavioral change in v2.3.0.

So, https://github.com/pmndrs/jotai/issues/2168#issuecomment-1757519869 the test doesn't take that into account.

It should subscribe to `derived2Atom`.

Let me see if we can work around in `jotai-recoil`.

**Comment by dai-shi** [comment]
Ooops, that's my oversight again. It's not solvable on `jotai-recoil`...
So, I guess we should give up the idea in #2029 unless we find a better solution.

**Comment by stevemolitor** [comment]
> I guess we should give up the idea in #2029 unless we find a better solution.

Does this mean #2029 will get reverted in the next Jotai release?

My current project (migrating a big app from Recoil to Jotai) is blocked in some areas. No hurries - I'm just trying to decide if we should downgrade to Jotai v2.2.3 for now, or wait for this bug to get fixed.

Happy to help in any fashion also. 

Thanks!

**Comment by dai-shi** [comment]
Sorry for the confusion. I was confused too. I will merge #2197 soon, which should fix the issue. Let me try your reproduction.
