### ISSUE TITLE
README in dark mode

### ISSUE THREAD

**Issue by dferber90** [pmndrs/jotai#232]
I noticed you've got a highly polished README, which looks quite impressive! Well done :)

I noticed it uses images as headlines. GitHub recently introduced dark mode. Unfortunately the images-approach doesn't work well with dark mode as pictured below.

![image](https://user-images.githubusercontent.com/1765075/101905308-ec0d0280-3bbf-11eb-9f2b-300dbd3079e9.png)

I don't use jotai and I just stumbled upon your README by chance (in dark mode), but I thought I'd share an alternative approach that might work for you (in both, dark mode and regular mode) in case you're not familiar with it.

The repo [sindresorhus/css-in-readme-like-wat](https://github.com/sindresorhus/css-in-readme-like-wat) shows how you can embed CSS into SVGs using `foreignObject`. A PR using that technique can be seen here: https://github.com/sindresorhus/sindresorhus/pull/9.

I think this might help resolve the approach coming from using images only. Not sure how well it would work with READMEs displayed on npm.

In any case, I only opened this issue to let you know about a cool potential solution. This is only meant as a "hey, check this out, this might be useful". Feel free to close the issue.

**Comment by dai-shi** [comment]
Hey, thanks for dropping by. Hope you eventually try jotai too!
We are discussing about the dark mode including `foreignObject`. Will see how it goes.
In the long term, we would eventually migrate to a new web site.
