### ISSUE TITLE
"Primitive" vs. "primitive" atoms

### ISSUE THREAD

**Issue by mhcoffin** [pmndrs/jotai#235]
I'm not sure if this is a bug. Even if it is, I'm not sure it's worth fixing---it may be the best you can manage with typescript. But it did confuse me for a bit. 

The documentation talks about "primitive" atoms, which are atoms created with an initial value:
```
const anAtom = atom('foo')
```
There is also a public type `PrimitiveAtom<T>`. All "primitive" atoms are of type `Primitive<T>`, but you can create a derived atom and give it type PrimitiveAtom<T> without it actually being  "primitive". E.g.,
```
const pAtom: PrimitiveAtom<string> = atom(
  (get) => get(someOtherAtom)
  (get, set, update: SetStateAction<string>) => {set(someOtherAtom, update)}
)
```
I got confused because I knew I needed a "primitive" atom for some purpose, and thought that any object with type `PrimitiveAtom` would work. But that wasn't the case. Everything type-checked okay, but it didn't actually work at run time.

**Comment by dai-shi** [comment]
Good point. 🤔 

```ts
export type PrimitiveAtom<Value> = WritableAtom<Value, SetStateAction<Value>>
```
PrimitiveAtom type is defined as a restricted WritableAtom, but it doesn't say anything about the behavior. It's just a convenient type for `atom('foo')`.

> I got confused because I knew I needed a "primitive" atom for some purpose

I'm not sure about the purpose, but wouldn't it expect `WritableAtom<Value, Value>`, which is stricter than `PrimitiveAtom<Value>`?

> Everything type-checked okay, but it didn't actually work at run time.

I'd like to learn about the concrete case, as it seems very important.
Can you elaborate it please, possibly with code snippets or codesandbox?

**Comment by mhcoffin** [comment]
I was playing around with focusAtom, which requires a "primitive atom" as a base atom. In my ignorance, I poked around and found PrimitiveAtom<T> and then I created an atom that satisfied that type and tried to use it as a base for focusAtom. That didn't work, as you can see in the [sandbox](https://codesandbox.io/s/focusatom-with-non-primitive-atoms-dyxqv). Currently, at least, focusAtom actually requires an atom that is just created with an initial value. If you provide get and set, it just doesn't work. 

This is tangentially related to [issue 231](https://github.com/pmndrs/jotai/issues/231), which is why I conveniently have a sandbox illustrating my confusion. :-)

**Comment by dai-shi** [comment]
Thanks for the example.

```ts
const personAtom: PrimitiveAtom<Person> = atom(
  (get) => Promise.resolve({ name: "Barney", age: 23 }),
  (get, set, update) => set(personAtom, update)
);
```

OK, this is not desirable. Let me see if we can create better typing.

**Comment by dai-shi** [comment]
With #233, this will be fixed.
https://codesandbox.io/s/focusatom-with-non-primitive-atoms-forked-p2tjq?file=/src/App.tsx
<img width="606" alt="image" src="https://user-images.githubusercontent.com/490574/101974101-79faf300-3c7d-11eb-9313-6829c9d6d52c.png">

**Comment by merisbahti** [comment]
I really like the name `Primitive`... But not sure we should keep it.

In klyva, I'm considering naming the primtiive constructor `atom(5)` as a base atom constructor. And derived constructors, like this: `atom(get => get(baseAtom))`, I call derived atom constructors.

But what do we do about the `PrimitiveAtom` type?

Not sure, maybe we could name it `MutableAtom` atom? It's not really the truth, is it? But somehow it still encapsulates that it can be read and written from, it's just leaving out the detail that a callback can be sent in the write-direction.

**Comment by dai-shi** [comment]
Maybe `BaseAtom`? My only concern is `PrimitiveAtom` is not for primitive values, it's primitive atoms.

**Comment by merisbahti** [comment]
Ooh, I like it!

**Comment by dai-shi** [comment]
Are you sure? It's a bit of work. Code and docs. Would you like to work on it??

**Comment by merisbahti** [comment]
I can maybe do it, I have free time soon, but when we agree! Maybe BasicAtom is good too??

**Comment by dai-shi** [comment]
Let me ask it in discord. BaseAtom sounds better than BasicAtom.
