### ISSUE TITLE
RFC: Add `atomWithRefresh` in `jotai/utils`

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#2379]
`atomWithRefresh` has been a recipe, not a util.
We wanted to understand various use cases and thought the naive implementation was somewhat limited. My hesitation is also it can be overused, but that's probably a doc issue.

It's been a while and it seems the basic `atomWithRefresh` seems valuable. https://github.com/pmndrs/jotai/discussions/849#discussioncomment-8359658

There might be several implementation ideas, like using a symbol like `atomWithReset` if that helps.

So, here's an RFC. Should we have `atomWithRefresh` in `jotai/utils`? 👍  / 👎

**Comment by AjaxSolutions** [comment]
How could we incorporate debouncing or throttling into [atomWithRefresh](https://jotai.org/docs/recipes/atom-with-refresh)?

**Comment by dai-shi** [comment]
I think it's the out of the scope of atomWithRefresh or even Jotai library, which means it's a good opportunity for [Jotai Labs](https://github.com/jotaijs) and Jotai ecosystem.

**Comment by dmaskasky** [comment]
> How could we incorporate debouncing or throttling into [atomWithRefresh](https://jotai.org/docs/recipes/atom-with-refresh)?

Should debounce / throttle be applied at the producer side
```ts
function useDebouncedSetAtom<T, A extends any[], R>(atom: Atom<T, A, R>, timeoutMs: number) {
  const setAtom = useSetAtom(atom)
  return useCallback(debounce(setState, timeoutMs), [])
}
```

or the consumer side?
```ts
function useDebouncedAtomValue<T, A extends any[], R>(atom: Atom<T, A, R>, timeoutMs: number) {
  const store = useStore()
  const [state, setState] = useState(store.get(atom))
  useEffect(() => {
    store.sub(debounce(() => {
      setState(store.get(atom))
    }, timeoutMs)
  }, [store, atom])
  return state
}```

**Comment by dai-shi** [comment]
#2393 supports `write` too.

**Comment by dai-shi** [comment]
Accepted and #2393 is ready.
