### ISSUE TITLE
testing with create react app - warning "Atom State not found"

### ISSUE THREAD

**Issue by jcane86** [pmndrs/jotai#243]
Hello,

Thanks again for the great library, and sorry for spamming with so many issues.

I am seeing a pretty weird thing in my tests. My app runs fine, and I don't see any warnings, but when I try to test some components that use jotai, I am seeing the "atom state not defined" warning.

I am using create-react-app, so the tests are run through react-scripts.

I made a repro by copying one test case from your test suite that is similar to my use case (setting an atom from useEffect), and I get the warning. I tried the same test in your original test suite (cloning your repo and running the tests) and I get no warnings.

It looks like this isn't directly an issue with your library, but maybe an incompatibility with something react-scripts does, but maybe you have some ideas of where to look at?

The repro is here: https://codesandbox.io/s/jotai-testing-with-react-scripts-ytd89
If you open a new terminal there and do "yarn test" you should see the warning.
(I made it in js instead of ts to get the most minimalist reproduction I could)

Thanks!

**Comment by dai-shi** [comment]
Thanks for reporting. Tried it locally and got the warning.
I don't have any clue. Can anyone help?

**Comment by Aslemammad** [comment]
I'm gonna debug it and see what is the problem.

**Comment by jcane86** [comment]
thanks @Aslemammad, let me know if I can help in any way

**Comment by dai-shi** [comment]
@Aslemammad found that the difference in CRA is it's using the cjs build. 👏

**Comment by Aslemammad** [comment]
@dai-shi Great solution!
