### ISSUE TITLE
Fix Support Page 

### ISSUE THREAD

**Issue by amanr-dev** [pmndrs/jotai#2433]
The support page is stocked at the Bottom.

screenshot:
![Screenshot 2024-03-02 211614](https://github.com/pmndrs/jotai/assets/124811276/5e2c6d78-5a2c-4671-a6c7-72f57520cf3b)

**Comment by dai-shi** [comment]
Yeah, I notice it happens with small screens.
Would anyone like to fix it please?

**Comment by amanr-dev** [comment]
Assign it to me

**Comment by amanr-dev** [comment]
> Assign it to me 

I would like to work on it.

**Comment by dai-shi** [comment]
@sandren might be already work on it, but I'm not sure.
