### ISSUE TITLE
Investigate and fix possible memory leaks in `store2`

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#2477]
https://github.com/pmndrs/jotai/pull/2463#discussion_r1550772929

**Comment by dai-shi** [comment]
@backbone87 Do you have any idea for the scenario where only `store2` fails with https://github.com/pmndrs/jotai/pull/2463#discussion_r1550772929 ?

**Comment by backbone87** [comment]
the downstream deps (`t`) must only be tracked for mounted downstream deps

**Comment by dai-shi** [comment]
because it leaks memory, or any other reason?

**Comment by backbone87** [comment]
yes because it leaks memory. you could keep the non-mounted downstream in weakrefs but I think that is more expensive than just always "pulling" unmounted atoms on read

**Comment by dai-shi** [comment]
Do you think you can write a test that passes with `store.ts` and fails with `store2.ts`?

**Comment by dai-shi** [comment]
> Do you think you can write a test that passes with `store.ts` and fails with `store2.ts`?

I was able to do it and am working on it: #2533
