### ISSUE TITLE
useUpdateAtom scope

### ISSUE THREAD

**Issue by Aslemammad** [pmndrs/jotai#249]
After @JLarky created this [sandbox](https://codesandbox.io/s/admiring-pascal-hsnuk?file=/src/library/jotaiProvider.tsx)(L10,jotaiProvider) I found out that useUpdateAtom doesn't set the original atom scope on the new derived-writable atom. it just needs one line to fix I think.

**Comment by JLarky** [comment]
Also in some sense, it might be useful to limit the scope of scope (:bowtie:) to just `core` bundle. If library is using jotai internally than maybe it doesn't want or need to bring all other jotai bundles, in that case it needs to be documented.

**Comment by dai-shi** [comment]
Ah, nice catch.
I understand both opinions.
Hmm. 🤔

**Comment by dai-shi** [comment]
Two options are:
1. fix everything for lib usage (scope)
2. only core supports scope (as is) and document so

🤔 🤔 🤔 🤔 🤔 

I'd vote for 1. because scope is one of appealing points compared to say recoiljs
and for better DX, utils and other non-core functions would be important.

**Comment by Aslemammad** [comment]
I vote 1 too as I created the issue for that.
