### ISSUE TITLE
[React Native] Sharing context/state with multiple screens (multiple roots, wix/react-native-navigation) 

### ISSUE THREAD

**Issue by a-eid** [pmndrs/jotai#253]
this same exact issue is happening with `jotai` is there any way around it ? 

https://github.com/facebookexperimental/Recoil/issues/719

**Comment by dai-shi** [comment]
Probably, create a dummy root somewhere and bridge from there to all screens (roots). Can you create an example with expo snack?

**Comment by a-eid** [comment]
expo doesn't support RNN unfortunately.

**Comment by dai-shi** [comment]
Oh, I see. I know the issue itself is reproducible. So, if you would be interested in the possible workaround.

**Comment by chj-damon** [comment]
so what do I have to do exactly to make it work?

**Comment by dai-shi** [comment]
@chj-damon Actually, since v0.15.0, we have provider-less mode.
So, if you **don't** wrap each screen with Provider, it can just work.
Would you give it a try?

**Comment by chj-damon** [comment]
@dai-shi yes it works! thank you

**Comment by dai-shi** [comment]
Good to know. Closing this as resolved.
