### ISSUE TITLE
Possible regression of 2.6.4 with derived atoms

### ISSUE THREAD

**Issue by geril2207** [pmndrs/jotai#2559]
## Summary
Here is a problem, where `moduleInputParamsAtom` in `Node` component returns `null` after promise has resolved, but should return an object. But another derived atom `isSomeModuleAtom` returns correct value. 
`2.6.3` and lower returns correct value for `moduleInputParamsAtom`. With regression you can swap `useAtomValue` calls to fix the issue or enable strict mode also(but not in production) works.

## Link to reproduction
https://codesandbox.io/p/devbox/tl7gkn

**Comment by dai-shi** [comment]
> `2.6.3` and lower returns correct value

Does v2.6.4 break it?

**Comment by dai-shi** [comment]
> Possible regression of 2.6.4 with derived atoms

Oh, the title says that.

**Comment by dai-shi** [comment]
https://github.com/pmndrs/jotai/releases/tag/v2.6.4

The related PR is #2363.

So, probably duplicated with #2532.

We are working on it: #2534
