### ISSUE TITLE
useInitialValue util

### ISSUE THREAD

**Issue by Noitidart** [pmndrs/jotai#257]
I'm trying to learn jotai, it's great. I'm trying to write a custom hook that will only get the initial value and not re-render on consquent updates. I tried this which obviously doesn't work. Any tips on how I can accomplish this? Just a learning thing.

```
function useInitialValueAtom(atom) {
  const [value] = useAtom(atom);
  const savedValue = useRef(value);
  return savedValue.current;
}
```

**Comment by merisbahti** [comment]
Hey,

Just gonna comment a first suggestion to solution to the problem at hand.

```typescript
const useInitialValueOfAtom = <T>(myAtom) => {
  const valueRef = useRef({hasBeenSet: false, value: undefined})

  const initialValueAtom = React.useMemo(() => {
    return atom((get) => {
      if (valueRef.current.hasBeenSet) return valueRef.current.value
      valueRef.current.hasBeenSet = true
      valueRef.current.value = get(myAtom)
      return value
    })
  }, [atom])
  return useAtom(initialValueAtom)[0]
}
```

I haven't tried the code, but this is roughly how it would need to work.

**Comment by merisbahti** [comment]
Here's a sandbox:

https://codesandbox.io/s/jotai-demo-forked-fgvgi

**Comment by Noitidart** [comment]
Oh this is so fun thank you! I'm learning a ton!

**Comment by Aslemammad** [comment]
@Noitidart I don't think so, I loved your idea + @merisbahti solution, @dai-shi What's your opinion about adding something like this to the utils?

**Comment by Noitidart** [comment]
Thank you! :)

**Comment by dai-shi** [comment]
@Aslemammad I'd like to know what is the use case. At this point, adding such a util seems to me only to confuse or misuse things...

What I would do would be at the atom level.

```js
const someValue = atom(123)

const oneTimeValue = atom(null)

const someConditon = atom(true)

const getValueOnce = atom(
  (get) => get(oneTimeValue),
  (get, set, _action) => {
    if (get(someCondition)) {
      set(oneTimeValue, get(someValue))
    }
)
```

It depends on requirements / use cases.

**Comment by Noitidart** [comment]
Where I got the idea from was for this demo from the docs - https://codesandbox.io/s/jotai-demo-47wvh

I wanted to make the "Input" component and uncontrolled component so as to not re-render every key stroke. So I did this with the `useUpdateAtom` but I then needed to set `defaultValue` of the input to that of the atom. As seen in this gif - https://gfycat.com/dependablecarefulhorseshoecrab

**Comment by dai-shi** [comment]
@Noitidart Thanks for the use case. RHF is nice for uncontrolled forms.

So, conceptually, the default value and the current value have different values. How about something like this?
```js
const defaultTextAtom = atom("hello")

const currentTextAtom = atom("hello")
```

I think having atom values in ref out of sync is not React-ish, and better to avoid it.

**Comment by Noitidart** [comment]
True nice point. I totally see both ways. :) Thanks for the educational discussion all!

**Comment by dai-shi** [comment]
👍 
Closing this. Feel free to continue on this topic, or create a new one for a new topic.
