### ISSUE TITLE
Package jotai has been ignored because it contains invalid configuration.

### ISSUE THREAD

**Issue by sreeraj-wd** [pmndrs/jotai#258]
After installing jotai into my react native project and running npm start I get the following error:

_"warn Package jotai has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /project_root/node_modules/jotai/package.json"_

 **"react-native": "~0.63.3"
 "jotai": "^0.12.4",
 "expo": "~39.0.2"**,

tried removing and installing jotai but did not help.

**Comment by dai-shi** [comment]
Oh, no. That's probably caused by what I experimentally added (assuming it's mostly ignored.)
Thanks for reporting. I'll do some search. Please be patient.
