### ISSUE TITLE
Atoms aborted due to unmount are unrecoverable

### ISSUE THREAD

**Issue by Pinpickle** [pmndrs/jotai#2625]
## Summary

The signal passed to read functions is aborted when an atom is unmounted. When the atom is read again (even after mounting again), the behaviour from the aborted signal remains (which is usually a thrown AbortError).

This is similar to #2610 (and may in fact be the same bug)

I can think of two solutions:

- Unmounted atoms shouldn't abort (but atoms that have their dependencies change should abort); or
- Unmounted atoms that haven't resolved should have their values discarded (this sounds like a breaking change)

## Reproduction

Here's a test case:

```js
import { createStore, atom } from 'jotai/vanilla';
const store = createStore();

let resolve = () => {};

const a = atom(1);

const b = atom(async (get, { signal }) => {
  await new Promise((r) => (resolve = r));

  signal.throwIfAborted();

  // This also breaks
  // if (signal.aborted) {
  //   return new Promise<never>(() => {})
  // }

  return get(a);
});

let unsub = store.sub(b, () => {});

// triggers an abort
unsub();
resolve();

// we've re-mounted, the aborted error should be irrelevant
unsub = store.sub(b, () => {});

// Should be 1, instead throws "Error: This operation was aborted"
console.log(await store.get(b));
```

Stackblitz reproduction: https://stackblitz.com/edit/stackblitz-starters-tzmn59

## Check List

Please do not ask questions in issues.

- [x] I've already opened a [discussion](https://github.com/pmndrs/jotai/discussions) before opening this issue, or already discussed in other media -- given #2610 I didn't see the need to open a discussion

Please include a minimal reproduction.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by dai-shi** [comment]
Nice catch.

Unless we have other solutions, we need to pick one. 🤔 
Both sound somewhat correct to me. I wonder what others think.

----

A side note:

> given https://github.com/pmndrs/jotai/discussions/2610 I didn't see the need to open a discussion

I think I prefer to keep everything under discussions (I know there are trade-offs). It's been changed since I wrote it. I will update the issue template.

**Comment by Pinpickle** [comment]
@dai-shi sorry for mis-understanding the discussion point! I'm happy for this to be converted to a discussion and open discussions in the future for bug reports.

Personally, I think that the first option (don't abort on unmount) is the most straightforward. 

The second may be more useful, but I can't think of a way to do it that won't cause more confusing edge-cases. It could be a special case for only instances of `AbortError`. So if an atom has errored with `AbortError`, discard the result.

**Comment by Pinpickle** [comment]
If anyone is interested, I came up with this as a workaround...

```ts
const isMountedAtom = jotaiAtom(false);
const isMountedTrackerAtom = jotaiAtom(null, (_, set, value: boolean) => {
  set(isMountedAtom, value);
});
isMountedTrackerAtom.onMount = (setSelf) => {
  setSelf(true);

  return () => {
    setSelf(false);
  };
};

const abortableAtom = atom((get, { signal }) => {
  if (signal.aborted) {
    // Putting this in a nested block to make it abundantly clear that
    // this `get` call should only be made if the signal has been aborted.
    // Otherwise, we'll have a dependency on the isMountedAtom at all times and
    // all atoms will re-evaluate when they're mounted.
    // Why do we even need to check if the atom is mounted? Jotai has a bug
    // where aborted, unmounted atoms don't ever re-evaluate.
    // https://github.com/pmndrs/jotai/issues/2625
    if (get(isMountedAtom)) {
      throw new DOMException("The operation was aborted.", "AbortError");
    }
  }
})
```

The abort check can go anywhere you want to respond to an abort. In my case, this is in an atom wrapper, so all atoms get the behaviour I want.

**Comment by dai-shi** [comment]
> Personally, I think that the first option (don't abort on unmount) is the most straightforward.

Yeah, the first one seems like a safer solution. Would you be able to draft a PR? Can you add a test for it?

**Comment by Pinpickle** [comment]
@dai-shi done! #2627
