### ISSUE TITLE
[Question] How to read/set from outside of react tree

### ISSUE THREAD

**Issue by Noitidart** [pmndrs/jotai#263]
I know this is specifically to use with react tree. However I'm using this in react-native and I have a background task that needs to update the latitude/longitude as my users travel around. So the app starts up in background mode, none of the react tree is mounted, the task is started in background.

For this use case any ideas on how to read/write atom's from outside the react tree?

**Comment by dai-shi** [comment]
You should use `useEffect` for read/set from outside. It's the same idea with `useState`.

Now, in case you have the background task to update values before react is ready, you might need to have a store outside react anyway. But unless that values are used anywhere outside react, you could only subscribe to the source in useEffect. I'm not sure if I understand the full requirement.

**Comment by Noitidart** [comment]
Thanks so much for your fast reply. I was creating persisted atoms - https://github.com/pmndrs/jotai/blob/master/docs/persistence.md - for lattitude/longitude.

My background job needs to update the latitude/longigude of these persisted atoms. If the app is launched in background, nothing from react fired up, so its ok to update the file on disk. But if app is launched by user, then I wanted to show the atom values in the UI. But the job continues to update the files on disk, which doesn't trigger re-renders in react components. 

If curious here is what I'm doing - https://docs.expo.io/versions/v40.0.0/sdk/task-manager/#example

**Comment by dai-shi** [comment]
So, the background task keeps writing locations to disk, and
only if the react app is running, you want to show the location real-time.

Maybe, you want an external store and then subscribe from useEffect.

```js
const store = {
  latitude: 0,
  longitude: 0,
  listeners: new Set(),
  update: (nextLatitude, nextLongitude) => {
     store.latitude = nextLatitude
     store.longitude = nextLongitude
     listeners.forEach(listener => listener())
  },
}

const Component = () => {
  const [location, setLocation] = useAtom(locationAtom)
  useEffect(() => {
    const callback = () => {
      setLocation({
        latitude: store.latitude,
        longitude: store.longitude,
      })
    }
    store.listners.add(callback)
    callback()
    return () => store.listeners.delete(callback)
  }, [setLocation])
  return (
    <>{location.latitude} {location.longitude}</>
  )
}
```

Notice, there's nothing special for jotai. The same thing for useState, if you change the line:
```diff
-  const [location, setLocation] = useAtom(locationAtom)
+  const [location, setLocation] = useState({ latitude: 0, longitude: 0 })
```

**Comment by Noitidart** [comment]
Thanks so much for your attention here to write something like this. Really appreciate the effort you put to help us learn! I'll do that way thank you!

**Comment by Noitidart** [comment]
Alright haha I worked on making the atom readable/writeable from outside of react. May you please see this code and see if its stable and won't break due to implementation, specifically the `useEffect` where i save the `setAtomValue` and then reuse that. I do this so that if react is mounted then it will properly show "Loading..." fallback when written from external.

https://codesandbox.io/s/jotai-external-stroage-atom-vfjfp?file=/src/App.js

## Usage
### Usage inside of react

```
const enabledAtom = atomWithExternalStorage(
function Value() {
const [enabled, setEnabled] = enabledAtom.useAtom();

return String(enabled);
}
```


### Usage outside of react

```
const enabled = await enabledAtom.storageRead();
// do not await storageWrite
enabledAtom.storageWrite(true);
```


## The `atomWithExternalStorage` method

```
atomWithStorage.storageCache = {};
atomWithStorage.isCached = (key) =>
  atomWithStorage.storageCache.hasOwnProperty(key);
function atomWithStorage(key, initialValue) {
  if (atomWithStorage.isCached(key)) {
    throw new Error(
      `An atom with storage key "${key}" has already been created.`
    );
  }
  let savedSetAtomValue;
  const cacheAtom = atom();
  const asyncAtom = atom(
    (get) => {
      const cachedValue = get(cacheAtom);
      if (atomWithStorage.isCached(key)) {
        console.log("asyncAtom.read: is chaced so returned that");
        return cachedValue;
      } else {
        console.log("asyncAtom.read: is not cached so read");
        return asyncAtom.storageRead();
      }
    },
    async (_get, set, nextValue) => {
      console.log("asyncAtom.write: nextValue:", nextValue);
      await asyncAtom.storageWrite(nextValue, set);
      console.log("asyncAtom.write: done");
    }
  );
  asyncAtom.saveSetAtomValue = (setAtom) => {
    console.log("asyncAtom.saveSetAtom: saving setAtomValue");
    savedSetAtomValue = setAtom;
  };

  asyncAtom.storageRead = async function () {
    if (!atomWithStorage.isCached(key)) {
      console.log("asyncAtom.storageRead: reading from disk");
      const storedValue = await new Promise((resolve) =>
        setTimeout(
          () => resolve(atomWithStorage.storageCache[key] || initialValue),
          2000
        )
      );
      atomWithStorage.storageCache[key] = storedValue;
    }
    return atomWithStorage.storageCache[key];
  };

  // caveat: do not await this method. it does not return properly if react has mounted. if nothing in react has useAtom'ed this atom then it will return early before writing is complete. after react useAtom'ed on this, then use <ErrorBoundary> to catch error in writing.
  asyncAtom.storageWrite = async function (nextValue, set) {
    if (!set && savedSetAtomValue) {
      console.log(
        "asyncAtom.storageWrite: abort because savedSetAtom exists, so route through that"
      );
      savedSetAtomValue(nextValue);
      return;
    }
    console.log("asyncAtom.storageWrite: writing");
    await new Promise((resolve) => setTimeout(resolve, 2000));
    atomWithStorage.storageCache[key] = nextValue;
    if (set) {
      console.log(
        "asyncAtom.storageWrite: written to disk, so will do saved set"
      );
      set(cacheAtom, atomWithStorage.storageCache[key]);
    }
    console.log("asyncAtom.storageWrite: wrote");
  };

  asyncAtom.useAtom = () => {
    const [value, setValue] = useAtom(asyncAtom);
    useEffect(() => {
      console.log("Value.useEffect.saveSetAtomValue");
      enabledAtom.saveSetAtomValue(setValue);
    }, []);
    return [value, setValue];
  };
  return asyncAtom;
}
```

**Comment by dai-shi** [comment]
It looks tricky but it seems to work.

I wouldn't recommend the savedSetAtomValue pattern though.
If you need to show "Loading..." you can probably `set` a promise in `cacheAtom`.
If that works, you can isolate useAtom, which is much cleaner.

There's a problem. We can only get `set` if atom is updated from react. I'm considering adding something new: https://github.com/pmndrs/jotai/issues/211#issuecomment-761947028

Another little concern is the timing issue. setValue from react can be executed async, so there's a potential race condition. But that's the concern in general, not specific to this implementation.

Another concern in some edge use cases is we can have two or more Providers for a single atom. atom values are isolated, but we have only one `set`. We need subscription (multiple listeners) mechanism for this to work.

**Comment by Noitidart** [comment]
Thank you @dai-shi for your extensive review. I really appreciate it. I was trying to come up with a unified interface to avoid multi sources of truth. I don't understand all those comments but will try to think and apply as I learn this. I will for sure make `set` optional.

That RFC for effect looks awesome. To make it callable from without react would I have to do something like this below?


```diff
let savedGet;
let savedSet;
dataAtom.effects = [
  (get, set) => {
+   savedGet = get;
+   savedSet = set;
    const unsubscribe = someStore.subscribe((nextData) => {
      set(dataAtom, nextData)
    })
    return unsubscribe
  }
]
```

**Comment by dai-shi** [comment]
sorry, if I made comments too complicated. Wanted to technically clear.
In short, it works but we want a better way (no hook, atom only).

> That RFC for effect looks awesome. To make it callable from without react would I have to do something like this below?

Yes, but two caveats in your code.
1. you need to clean up the side effect. that's what the returning function is for.
2. atom config is not a singleton. If you have two providers effects are invoked twice. (and your `savedGet` is overwritten.)

So, subscription model is more recommended.

**Comment by Noitidart** [comment]
No sorries at all brother, I really appreciate it. Thanks for your amazing working and helping us to help you!

**Comment by Noitidart** [comment]
Super appreciate your deep code review on this. Posting the corrected code for others to peak at too if they want to. I know its ugly so sorry all haha. And updated code sandbox - https://codesandbox.io/s/jotai-external-stroage-atom-vfjfp

Regarding these two points:
>If you need to show "Loading..." you can probably set a promise in cacheAtom.
> If that works, you can isolate useAtom, which is much cleaner.

I didn't understand them. :( Please no worries to reply, unless you have time. I know this code is so messy.

```
atomWithStorage.storageCache = {};
atomWithStorage.isCached = (key) =>
  atomWithStorage.storageCache.hasOwnProperty(key);
function atomWithStorage(key, initialValue) {
  if (atomWithStorage.isCached(key)) {
    throw new Error(
      `An atom with storage key "${key}" has already been created.`
    );
  }
  const savedSetAtomValues = new Set();
  const cacheAtom = atom(null);
  const asyncAtom = atom(
    (get) => {
      const cachedValue = get(cacheAtom);
      if (atomWithStorage.isCached(key)) {
        console.log("asyncAtom.read: is chaced so returned that");
        return cachedValue;
      } else {
        console.log("asyncAtom.read: is not cached so read");
        return asyncAtom.storageRead();
      }
    },
    async (_get, set, nextValue) => {
      console.log("asyncAtom.write: nextValue:", nextValue);
      await asyncAtom.storageWrite(nextValue, set);
      console.log("asyncAtom.write: done");
    }
  );

  asyncAtom.storageRead = async function () {
    if (!atomWithStorage.isCached(key)) {
      console.log("asyncAtom.storageRead: reading from disk");
      const storedValue = await new Promise((resolve) =>
        setTimeout(
          () => resolve(atomWithStorage.storageCache[key] || initialValue),
          2000
        )
      );
      atomWithStorage.storageCache[key] = storedValue;
    }
    return atomWithStorage.storageCache[key];
  };

  // caveat: do not await this method. it does not return properly if react has mounted. if nothing in react has useAtom'ed this atom then it will return early before writing is complete. after react useAtom'ed on this, then use <ErrorBoundary> to catch error in writing.
  asyncAtom.storageWrite = async function (nextValue, set) {
    if (!set && savedSetAtomValues.size) {
      console.log(
        "asyncAtom.storageWrite: abort because savedSetAtom exists, so route through that"
      );
      savedSetAtomValues.values().next().value(nextValue);
      return;
    }
    console.log("asyncAtom.storageWrite: writing");
    await new Promise((resolve) => setTimeout(resolve, 2000));
    // support nextValue being a functional updater like `setState(prevValue => prevValue + 1)`
    if (typeof nextValue === "function") {
      const prevValue = await asyncAtom.storageRead();
      atomWithStorage.storageCache[key] = nextValue(prevValue);
    } else {
      atomWithStorage.storageCache[key] = nextValue;
    }
    if (set) {
      console.log(
        "asyncAtom.storageWrite: written to disk, so will do saved set"
      );
      set(cacheAtom, atomWithStorage.storageCache[key]);
    }
    console.log("asyncAtom.storageWrite: wrote");
  };

  asyncAtom.useAtom = () => {
    const [value, setValue] = useAtom(asyncAtom);
    useEffect(() => {
      console.log("Value.useEffect.saveSetAtomValue");
      savedSetAtomValues.add(setValue);
      return () => {
        savedSetAtomValues.delete(setValue);
      };
    }, []);
    return [value, setValue];
  };
  return asyncAtom;
}
```

**Comment by Noitidart** [comment]
I found an issue with the observer method. If the atom useEffect which updates the atom value is not mounted, during an external write, then the atom value is not updated. So solution to this is, on mount always use cached value (create in memory cache on every write and first read so its available for this use case). The useAtom atom's value will only become in sync with cache value once a write is done while the useEffect is mounted.

**Comment by dai-shi** [comment]
I guess, you need to read from the external source on mount. (if I understand your statement correctly)

**Comment by norswap** [comment]
Answering since I stumbled on this. Seems like reading and setting from outside of react is now supported via `createStore` ([see here](https://jotai.org/docs/guides/migrating-to-v2-api)).

**Comment by rodrigocfd** [comment]
> Answering since I stumbled on this. Seems like reading and setting from outside of react is now supported via `createStore` ([see here](https://jotai.org/docs/guides/migrating-to-v2-api)).

Well, this is huge news to me. That's the very single reason that made me chose other library over Jotai, but now it seems [possible](https://jotai.org/docs/guides/migrating-to-v2-api#store-api). Please @dai-shi, consider documenting this feature in the main [README](https://github.com/pmndrs/jotai/blob/main/readme.md).

**Comment by rodrigocfd** [comment]
My use case is a large enterprise application, but in a simplified view, I have global objects like these:

```ts
import {atom} from 'jotai';

const warningsAtom = atom([] as string[]);
const errorsAtom = atom([] as string[]);
```

And a component, at the top of the page, which displays them:

```ts
import {useAtom} from 'jotai';
import {errorsAtom, warningsAtom} from './atoms';

function GlobalMessages() {
	const [warnings] = useAtom(warningsAtom);
	const [errors] = useAtom(errorsAtom);

	return <>
		{warnings.length > 0 && 
			<div>
				<h2>Warnings</h2>
				{warnings.map((w, i) =>
					<div key={i}>{w}</div>
				)}
			</div>
		}

		{errors.length > 0 &&
			<div>
				<h2>Errors</h2>
				{errors.map((e, i) =>
					<div key={i}>{e}</div>
				)}
			</div>
		}
	</>;
}
```

Now some components can send/receive server data, according to user actions. There is a `serverPost()` function which fetches data from the back-end, and depending on the returned data, can add messages to `warnings` or `errors`.

Then it comes the problem: `serverPost()` must access the global object to write to `warnings` and `errors`.

As far as I could see, now I can have something like:

```ts
import {createStore} from 'jotai';
import {warningsAtom} from './atoms';

async function serverPost<T>(url: string): Promise<T> {
	
	/// fetch() ...
	
	const store = createStore();
	const warnings = store.get(warningsAtom);
	store.set(warningsAtom, [...warnings, 'New warning']);
	
}
```

Is this correct?

**Comment by dai-shi** [comment]
`createStore()` in a function doesn't seem good.

Maybe you want to open a new discussion, because this is a good topic.

**Comment by rodrigocfd** [comment]
Sure, here we go:

https://github.com/pmndrs/jotai/discussions/1752

**Comment by 07akioni** [comment]
```
import "./styles.css";
import { atom, useAtomValue, createStore, Provider } from "jotai";

const timeAtom = atom(0);
const store = createStore();

setInterval(() => {
  console.log("gigigi");
  store.set(timeAtom, store.get(timeAtom) + 1);
}, 1000);

function Component() {
  const time = useAtomValue(timeAtom);
  return (
    <div className="App">
      <h1>{time}</h1>
    </div>
  );
}

export default function App() {
  return (
    <Provider store={store}>
      <Component />
    </Provider>
  );
}
```

**Comment by ashuvssut** [comment]
@07akioni's example of using `createStore` seems to work nicely. 

I would be interested in contributing a CodeSandbox for `createStore` docs page. If this is something desirable, let me know

**Comment by dai-shi** [comment]
Maybe not in createStore API docs, but a new guide? Like `./docs/guides/using-store-outside-react.mdx`?
