### ISSUE TITLE
jotai breaks ie11 on nextjs with arrow function

### ISSUE THREAD

**Issue by lanyusan** [pmndrs/jotai#265]
Hi, I am testing this great lib and found out it breaks ie11 on next js with the arrow function.

ie 11 reports this error:

```
SCRIPT1002: Syntax error

_app.js (11916,31)
```

And it points to this line of code:

```
const hasInitialValue = atom => 'init' in atom;
```

I understand jotai supports ie11. It seems its standard dist output doesn't transpire arrow function.

Any idea how to transpire it to work with nextjs on ie11?  Sorry if it is a naive issue. Couldn't find an issue addressing this.

**Comment by Aslemammad** [comment]
@dai-shi I think we just need to configure babel to compile things to ES5.

**Comment by dai-shi** [comment]
currently, the cjs build is targeting ie11.
https://github.com/pmndrs/jotai/blob/4ef6cfb06d6400080cd1de6dcb68a5d51dbfb4c5/rollup.config.js#L50

Does it work with ie11 if it's not on nextjs? I'm not sure how nextjs build the bundle.

**Comment by lanyusan** [comment]
My understanding is that Nextjs doesn't transpire use imported node modules.

I just use `import { atom ... } from 'jotai'` with no other nextjs configration.

I have tried `const { atom ... }  = require('jotai')` , still the same problem.

So do I need to specifically ask nextjs/webpack to use the `cjs` build? Any idea how to do so with nextjs or webpack? Did a search but couldn't find a straight answer.  Sorry if it is naive.

**Comment by dai-shi** [comment]
@lanyusan 
Could you try this?
```js
import { atom } from 'jotai/index.cjs'
```
to explicitly use cjs build.

**Comment by lanyusan** [comment]
Got this compile error:

`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './index.cjs' is not defined by "exports" in /.../node_modules/jotai/package.json`

**Comment by dai-shi** [comment]
Oh, I see. ie11 is traditional, but nextjs (node14?) is very new. Let me see what we can do.

**Comment by dai-shi** [comment]
Unfortunately, I couldn't come up with a good solution.

if `const { atom } = require('jotai')` doesn't work, I would like you to try transpiling module at your end.

https://nextjs.org/docs/advanced-features/customizing-babel-config
Seems like you can customize the babel config.

https://github.com/martpie/next-transpile-modules
This package might help easing the work.

**Comment by lanyusan** [comment]
busy recently. Would twist nextjs config later. thanks anyway.

**Comment by dai-shi** [comment]
when you got time, please try the build in #282 to see if it fixes.

**Comment by lanyusan** [comment]
Have you pushed the chage to NPM? I tried it with the latest version @npm 0.12.7. Still the same problem

**Comment by dai-shi** [comment]
@lanyusan No, but it's in codesandbox ci build. https://github.com/pmndrs/jotai/pull/282#issuecomment-767924946
```
yarn add https://pkg.csb.dev/pmndrs/jotai/commit/43d50637/jotai
npm i https://pkg.csb.dev/pmndrs/jotai/commit/43d50637/jotai
```

**Comment by lanyusan** [comment]
Used `yarn add https://pkg.csb.dev/pmndrs/jotai/commit/43d50637/jotai` to tryit and got this error 

```
error - ../node_modules/jotai/index.mjs
Can't import the named export 'BridgeProvider' from non EcmaScript module (only default export is available)
event - build page: /next/dist/pages/_error
wait  - compiling...
error - ../node_modules/jotai/index.mjs
Can't import the named export 'BridgeProvider' from non EcmaScript module (only default export is available)
```

**Comment by dai-shi** [comment]
@lanyusan Sorry, it turns out that was a wrong one. Please try v0.13.2 now.

**Comment by lanyusan** [comment]
Tried the latest version with nextjs still doesn't work but it looks not Jotai's problem. I created a naked nextjs app with nextjs standard `yarn create next-app`, which doesn't work with ie 11, which nextjs claims it works with ie11 out of box.
I will create an issue there.

**Comment by larswittenberg** [comment]
I have the same problem. But without jotai the Create Next app works in IE11. I have to say that `next dev` also has a problem in IE11, but with `next build && next start` the Create Next App runs in IE11. Ok, the grid layout is displayed incorrectly, but no syntax error appears.


Node: 14.16.0
next.js: 10.0.8
jotai: 0.15.3

**Comment by larswittenberg** [comment]
> I have the same problem. But without jotai the Create Next app works in IE11. I have to say that `next dev` also has a problem in IE11, but with `next build && next start` the Create Next App runs in IE11. Ok, the grid layout is displayed incorrectly, but no syntax error appears.
> 
> Node: 14.16.0
> next.js: 10.0.8
> jotai: 0.15.3

Using [https://github.com/martpie/next-transpile-modules](https://github.com/martpie/next-transpile-modules) I got it to run in IE11.

```
// next.config.js
const withTM = require('next-transpile-modules')(['jotai']);
module.exports = withTM();
```

**Comment by dai-shi** [comment]
> Using https://github.com/martpie/next-transpile-modules I got it to run in IE11.
> 
> ```
> // next.config.js
> const withTM = require('next-transpile-modules')(['jotai']);
> module.exports = withTM();
> ```

Thanks for confirming. I guess this is a recommended solution at the moment.
