### ISSUE TITLE
🛠️ Repo: ESLint is running TypeScript rules on .json files

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [pmndrs/jotai#2699]
👋 Coming over from https://x.com/dai_shi/status/1821338388957388859 -> #2698, I see you're running ESLint on all `.js`, `.json`, and `.ts` files:

https://github.com/pmndrs/jotai/blob/20e0cde354c77dd7a9aee7bee4f54f83ea56ebb4/package.json#L77

...which means you're running all sorts of JavaScript- and TypeScript-specific rules on `.json` files like `tsconfig.json`. Was this intentional?

The applying JS/TS rules when linting `.json` files is why #2698 has a [`plugin:@typescript-eslint-no-unused-expressions`](https://typescript-eslint.io/rules/no-unused-expressions) failures in the `tsconfig.json` file:

```plaintext
/home/runner/work/jotai/jotai/tsconfig.json
Error:   1:1  error  Expected an assignment or function call and instead saw an expression  @typescript-eslint/no-unused-expressions
```

---

Posting some suggested next steps in case it's useful, sorry if you already know all this 😅 ...

If you _don't_ want to lint `.json` files, you can remove the `json` from the linting scripts.

If you _do_ want to lint `.json` files, I'd suggest:

1. Switching all JS- and TS-related plugins to be in [eslintrc `overrides`](https://eslint.org/docs/latest/use/configure/configuration-files-deprecated#configuration-based-on-glob-patterns) that apply to `.js` and `.ts` files
2. Onboarding `.json`-specific plugins such as [`eslint-plugin-jsonc`](https://github.com/ota-meshi/eslint-plugin-jsonc) in `overrides` for `.json` files

Hope this is helpful - cheers! 💙 

Edit: oh, and if this makes no sense, I can send a draft PR showing suggested changes. 🙂

**Comment by dai-shi** [comment]
> Was this intentional?

It was intentional, but mostly historically. I don't think we need to run lint on json files. I'll remove it and if necessary, we can re-consider it in the future.

Thanks!
