### ISSUE TITLE
[Bug] useAtom(atom) does not re-render when the input atom changes.

### ISSUE THREAD

**Issue by kueychuj** [pmndrs/jotai#273]
Issue updated in https://github.com/pmndrs/jotai/issues/273#issuecomment-765399339

Item Component won't re-render when ```id``` changes.

```ts
import * as React from "react";
import { atomFamily } from "jotai/utils";
import { useAtom } from "jotai";

const todoFamily = atomFamily<number, any>((id) => ({
  id
}));
const Item: React.FC<{ id: number }> = ({ id }) => {
  const todo = useAtom(todoFamily(id));
  return <h1>{JSON.stringify(todo)}</h1>;
};

export default function App() {
  const [a, setA] = React.useState(1);
  return (
    <div className="App">
      <button onClick={() => setA((a) => a + 1)}>+</button>
      <button onClick={() => setA((a) => a - 1)}>-</button>
      <Item id={a} />
    </div>
  );
}

```

Sandbox Example
https://codesandbox.io/s/keen-haslett-cnjz9

any thought?

**Comment by merisbahti** [comment]
what's the definition of todofamily? I think that might give it away :)

**Comment by kueychuj** [comment]
> what's the definition of todofamily? I think that might give it away :)

So fast. :p

Thanks for quick response. I have just created a minified example on this.
https://codesandbox.io/s/react-typescript-forked-8zfrn

**Comment by merisbahti** [comment]
Hey, just 1 thing (and we might need to improve our typings to fix this), but `atomFamily` should return an `Atom<T>` and not `T`, take a look at the tests here: https://github.com/pmndrs/jotai/blob/master/tests/utils/atomFamily.test.ts

I haven't found how to reproduce your error in the UI yet, I keep checking.

**Comment by dai-shi** [comment]
Wow, nice catch. Thanks for the sandbox. I confirmed that this is broken since v0.12.0.

**Comment by dai-shi** [comment]
OK, I added a failing spec: 033b2e8
Not sure yet where the bug is...

**Comment by kueychuj** [comment]
Thank Both, look forward to the bug fix :-)

**Comment by kueychuj** [comment]
It appears unrelated to atomFamily but the useAtom hook.

The example below shows that useAtom(atom) did not resolve the correct value after the input atom is changed.
It is broken since v0.12.0.

Example: https://codesandbox.io/s/zen-snyder-rwqx9

```ts
import * as React from "react";
import { atom, useAtom } from "jotai";

const atomA = atom({ id: "a" });

atomA.debugLabel = "atomA";

const atomB = atom({ id: "b" });

atomB.debugLabel = "atomB";

const Item: React.FC<{ id: string }> = ({ id }) => {
  const atom = React.useMemo(() => (id === "a" ? atomA : atomB), [id]);
  const [atomValue] = useAtom(atom);
  return (
    <h1>
      Atom Label: {atom.debugLabel}
      <br />
      Atom Id: {atomValue.id}
    </h1>
  );
};

export default function App() {
  const [id, setId] = React.useState("a");
  return (
    <div className="App">
      <button onClick={() => setId("a")}>atom A</button>
      <button onClick={() => setId("b")}>btom B</button>
      <Item id={id} />
    </div>
  );
}

```
https://codesandbox.io/s/zen-snyder-rwqx9?file=/src/App.tsx

**Comment by dai-shi** [comment]
Thanks. Yeah, it's not related with atomFamily. It's a very fundamental bug. Thanks for finding this.
We should definitely add a test for this. Your example above is helpful. (Would you be interested in adding a failing test? Just asking.)
I know where the bug is and which commit I introduced it, and i'm still working on a correct solution.

**Comment by dai-shi** [comment]
OK, the upstream PR is ready. Let me work on some more tests.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/jotai/v/0.12.6

@kueychuj Thanks so much for reporting this and digging to create reproductions! All helped!

@merisbahti Just thought, could this be related to your local tests with useAtomSlice thing?

**Comment by merisbahti** [comment]
Hmm, not sure! But might be!

**Comment by kueychuj** [comment]
@dai-shi @merisbahti , thanks for the quick fix.

However, I seemed to find another problem on the re-rendering. 
In v0.12.6, using atom hook causes necessary re-renders and the first render produces wrong atom value.



**Example** ( https://codesandbox.io/s/romantic-forest-lixid?file=/src/App.tsx )
Switch from atomA to atomB will trigger two renders on ItemWithAtomHook component. (which should be one I believe)
The first render of ItemWithAtomHook produces a wrong atom value with correct atom.

```ts
Item render:  atomA 
ItemWithAtomHook render:  atomA b 
ItemWithAtomHook render:  atomA a 
```
