### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by MarkLyck** [pmndrs/jotai#281]
When using Create-react-app with Jest.

Any tests that ends up important a Component using `jotai/utils` fail with the following error:

```
Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/mark/ypm/x/c1-frontend-v4/node_modules/jotai/utils.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { useMemo, useCallback } from 'react';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import React, { useState } from 'react'
      2 | import { useAtom } from 'jotai'
    > 3 | import { useUpdateAtom } from 'jotai/utils'
        | ^
      4 | import { ReactKeycloakProvider } from '@react-keycloak/web'
      5 | import keycloak from 'src/lib/keycloak'
      6 | import { IDP_HINT } from 'src/common/constants'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (src/lib/keycloak/AuthProvider.tsx:3:1)
```

I am using "vanilla" create-react-app. There's no custom babel configuration or anything just the default.

If I switch to just use `useAtom` from 'jotai' it works fine. But I want to be able to use the jotai/utils.

**Comment by dai-shi** [comment]
Thanks for reporting.

> When using Create-react-app with Jest.

This sounds like one of the most popular use cases...

I know what is probably happening, but don't know what's best to fix. If anyone has any ideas, I would like to hear.

Meanwhile, if you changed like this, it would work.
```diff
- import { useUpdateAtom } from 'jotai/utils'
+ import { useUpdateAtom } from 'jotai/utils.cjs'
```

**Comment by MarkLyck** [comment]
@dai-shi indeed that worked! Thanks for the temporary workaround!

No other libraries I'm importing is using or requires using commonJS though.
I don't think it should be necessary to import the commonJS version to make the unit tests work?

Could you elaborate on 

> I know what is probably happening, but don't know what's best to fix.

Maybe some one else that runs into this will know how to fix it 🤞

**Comment by dai-shi** [comment]
> No other libraries I'm importing is using or requires using commonJS though.
> I don't think it should be necessary to import the commonJS version to make the unit tests work?

From the error message, jest doesn't understand "import" in the files in node_modules (because babel exclude them by default.)

The fact is that it actually the same as this in jest env.
```js
import { useAtom } from 'jotai/index.cjs'
```

> Could you elaborate on
> 
> > I know what is probably happening, but don't know what's best to fix.
> 
> Maybe some one else that runs into this will know how to fix it 🤞

yeah, this issue is specific to jotai, or the way it provides bundle files.
This way is not very common but we store a separate bundle `jotai/utils` in `jotai`.
Some might say this is not a best practice, but let's assume we want to keep it for now.

utils files are like this:
```bash
$ ls utils.*
utils.cjs.d.ts
utils.cjs.js
utils.d.ts
utils.js
```

index files are also like this, and jest understand `"main"` / `"module"` fields in package.json and pick the cjs one. I added "exports" field introduced in node14, with the hope that, eventually, jest, typescript, and other toolchains understand it.

**Comment by dai-shi** [comment]
We might change the default to be cjs and add mjs for module files. Yeah, that would solve the nextjs and ie11 issues too.

Let me draft a PR, but I'm not sure about the final decision.

**Comment by dai-shi** [comment]
@omarkhatibco

With the later versions, `jotai/utils` is CJS, and you don't need `.cjs`.

**Comment by omarkhatibco** [comment]
Hi @dai-shi, thank you for your support. 

it seems a Remix compiler Problem, it picks the wrong file.
