### ISSUE TITLE
Can't import the named export 'BridgeProvider' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by n8sabes** [pmndrs/jotai#287]
Upgraded to 0.13.1 and now getting this error:

`Can't import the named export 'BridgeProvider' from non EcmaScript module (only default export is available)`

**Comment by dai-shi** [comment]
Oh, no...

**Comment by dai-shi** [comment]
Okay, I suppose it's too ealy to use `.mjs`.

**Comment by dai-shi** [comment]
@n8sabes Could you try the build by codesandbox ci? https://github.com/pmndrs/jotai/pull/288#issuecomment-770940026

**Comment by n8sabes** [comment]
@dai-shi I've not installed from codesandbox ci before, so not sure if I've done this correctly but, I ran the `yarn` command below and it appears to have solved the issue.

`yarn add https://pkg.csb.dev/pmndrs/jotai/commit/91c266cd/jotai`

BTW -- If there's an easier way to have installed the PR, please let me know.

Thank you for the quick fix!

**Comment by dai-shi** [comment]
Thanks for the confirmation. Yes, that's the correct way. How could it be simpler?

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/jotai/v/0.13.2
