### ISSUE TITLE
Call compute outside of React ? 

### ISSUE THREAD

**Issue by dusanjovanov** [pmndrs/jotai#294]
I have two async action atoms 

```tsx
const doSomething = atom(get => null, async (get, set, args) => ...);

const loadSomething = atom(get => get(someAtom), async (get, set,args) => ...);
```

I would like to call `loadSomething`'s `compute` function when `doSomething` has finished it's work. Is that possible ?

**Comment by dai-shi** [comment]
Hi, I'm not sure if I get how `compute` is defined in `loadSomething`. Can you show a more concrete example?

(There's no magic, so we need to come up with ideas. At this point, I can't say if it's possible or not.)

**Comment by dusanjovanov** [comment]
When I say `compute` i mean `const [loadSomethingResult, compute] = useAtom(loadSomething)`. `loadSomething` would fetch data from the server. I want to call that atom and refetch data once `doSomething` atom has done it's work (also sending some request to the server). I hope It's clearer now.

**Comment by dai-shi** [comment]
yes, thanks. in this case, `compute(arg)` is equivalent to `set(loadSomething, arg)`, so it's an expected use case.

```js
const loadSomething = atom(get => get(someAtom), async (get, set, arg) => {
  // fetch data from server
});

const doSomething = atom(null, async (get, set, arg) => {
  // do some async work
  // and then refetch
  set(loadSomething, ...)
});
```

Does it make sense? `await set(loadSomething, ...)` is also possible.

**Comment by dusanjovanov** [comment]
Thank you, this works. Great library by the way.
