### ISSUE TITLE
Derived async atom cause endless loop

### ISSUE THREAD

**Issue by Jancat** [pmndrs/jotai#306]
```js
// async atom
const atom1 = atom(async () => new Promise(resolve => 
    setTimeout(() => reslove(1001), 1000))
))

const atom2 = atom(async get => {
    const id = get(atom1);
    const response = await fetch(
    `https://hacker-news.firebaseio.com/v0/item/${id}.json`
    );
    return await response.json();
})
```

Then the page is stuck.

HackerNews Examples (modified)
https://codesandbox.io/s/heuristic-haze-h6f86?file=/src/App.js

**Comment by dai-shi** [comment]
Thanks for reporting. Not quite sure what's happening. The codedsandbox shows error for some times, and then after experimenting for a while, it is stuck.

<img width="260" alt="image" src="https://user-images.githubusercontent.com/490574/108365751-e7f20680-723a-11eb-8ec4-2707e05b4feb.png">

---
Will investigate it. 🤔 
Any help from anyone appreciated.

**Comment by aulneau** [comment]
I've found this happens too. I haven't been able to determine why exactly this happens, but typically seems to be when i have an async atom that is used within an async atom family.

**Comment by dai-shi** [comment]
reproduced in a test. 🤔 how to fix.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/jotai/v/0.14.2
