### ISSUE TITLE
[jotai/query] atomWithMutation

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#309]
follow up #248

It would be nice if we can add the mutation support.

**Comment by Aslemammad** [comment]
That's great; I'll research for it.

**Comment by dai-shi** [comment]
@aulneau Any plan for this? If nobody needs such a feature, let's close this issue. I created this issue, just assuming there's a use case.

**Comment by xaun** [comment]
Yea I think this should exist. Especially as it exists for URQL. Definitely should be able to tap into state updates for a mutation response

**Comment by omerman** [comment]
Why is this closed?

**Comment by dai-shi** [comment]
It's implemented in a separate library. #1435 
https://jotai.org/docs/integrations/query
<img width="631" alt="image" src="https://user-images.githubusercontent.com/490574/209657934-db54cec1-84f2-4d2e-a144-c1ce9ed6f1e7.png">

**Comment by omerman** [comment]
Oh that is great, thanks
