### ISSUE TITLE
Can PrimitiveAtom be covariant?

### ISSUE THREAD

**Issue by miyamonz** [pmndrs/jotai#312]
I want to store PrimitiveAtom that can take multiple types.

```ts
const aaa: Atom<number | string> = atom(0); //ok
const bbb: PrimitiveAtom<number | string> = atom(0); // error
```
https://codesandbox.io/s/jotai-playground-forked-qdr1l?file=/src/App.tsx

it seems to be about covariance or contravariance issue in typescript.
If it's impossible in principle, I want to know another way to solve the problem.

**Comment by dai-shi** [comment]
Thanks for reporting. It would be nice if that didn’t raise the error. Anyone who is familiar with TS, please help. 


Meanwhile, the recommended way is this. 
```ts
const a = atom<number | string>(0)
```

**Comment by dai-shi** [comment]
```ts
const bbb: PrimitiveAtom<number | string> = atom<number>(0);
```
Hm, I don't think this is possible because atom is defined as number and can't be overwritten with string.

Closing this unless anybody has other suggestions.

**Comment by miyamonz** [comment]
thanks for your reply!
I'll consider another way to solve my problem.

**Comment by dai-shi** [comment]
```js
const a = atom<number | string>(0)
```
Does this solve your problem?
