### ISSUE TITLE
Error to use splitAtom with read-only atom 

### ISSUE THREAD

**Issue by tell-y** [pmndrs/jotai#313]
Hi, I'm super happy I can use splitAtom util in my project.

## Edited
https://github.com/pmndrs/jotai/issues/313#issuecomment-782818328

## First post
I just noticed a type definition error is occurred when I use splitAtom with read-only atom, so I report it.

### Reproducing
You can see the error to add some lines in https://codesandbox.io/s/react-typescript-forked-8cv79?file=/src/App.tsx

```typescript
const notDoneTodosAtom = atom((get) => {
  const todos = get(todosAtom)
  return todos.filter(todo => !todo.done)
})

const TodoList = () => {
  const [todoAtoms, removeTodoAtom] = useAtom(splitAtom(todosAtom))
  const [notDoneTodoAtoms] = useAtom(splitAtom(notDoneTodosAtom)) // Error here
  return (
    <ul>
      {todoAtoms.map((todoAtom) => (
        <TodoItem todoAtom={todoAtom} remove={() => removeTodoAtom(todoAtom)} />
      ))}
    </ul>
  )
}
```

Not appearing the error, if you add write function.
```typescript
const notDoneTodosAtom = atom(
  (get) => {
    const todos = get(todosAtom)
    return todos.filter(todo => !todo.done)
  },
  () => {
    // write
  }
)
```

**Comment by dai-shi** [comment]
Note, it's not only about typing, we need to prohibit `remove`.

We should also take care of removing from upstream.
https://github.com/pmndrs/jotai/blob/1946081c72548c9b2be868791895476d4cc20f44/src/utils/splitAtom.ts#L11

**Comment by tell-y** [comment]
I posted it as uncompleted information. 
In the first place, it seems that read-only atom with splitAtom is not working.
I created an example here [codesandbox](https://codesandbox.io/s/react-typescript-forked-u60nt?file=/src/App.tsx)

```typescript
const todosAtom = atom(initialState)
const notDoneTodosAtom = atom((get) => {
  const todos = get(todosAtom)
  return todos.filter(todo => !todo.done)
})

const TodoList = () => {
  const [todoAtoms, removeTodoAtom] = useAtom(splitAtom(todosAtom))
  const [notDoneTodoAtoms] = useAtom(splitAtom(notDoneTodosAtom))
  return (
    <ul>
      {todoAtoms.map((todoAtom) => (
        <TodoItem todoAtom={todoAtom} remove={() => removeTodoAtom(todoAtom)} />
      ))}
      // it's not working
      {notDoneTodoAtoms.map((todoAtom) => (
        <TodoItem todoAtom={todoAtom} />
      ))}
    </ul>
  )
}
```

Sorry for bothering you.

**Comment by ddeisadze** [comment]
How would you handle searching in the list?
