### ISSUE TITLE
How to do atomWithReducer + localStorage correctly with Next.Js

### ISSUE THREAD

**Issue by Sparklytical** [pmndrs/jotai#318]
I've been trying to achieve the way of doing that, the logic is the general logic that if its SSR, send true, otherwise send the localStorage value.

This is my code - 
```js

import { atomWithReducer } from "jotai/utils";

const isSSR = typeof window === "undefined";


export const gtAtom = atomWithReducer(
  isSSR ? true : localStorage.getItem("gt"),
  (_prev, newGt: string) => {
    localStorage.setItem("gt", newGt);
    return newGt;
  }
);
```

Then using it like this - 
```js
  const [gt, setGt] = useAtom(gtAtom);
```

But when its always showing value as null whenever i try to load the page. is there something wrong the way I'm doing it?

**Comment by dai-shi** [comment]
https://codesandbox.io/s/zealous-ives-nwirx?file=/src/App.js
It seems to me working as expected on client side.
<img width="787" alt="image" src="https://user-images.githubusercontent.com/490574/109231390-d8aa2480-7809-11eb-81a5-ea089895f33b.png">

**Comment by dai-shi** [comment]
BTW, it would be nice to add a check on write.
```ts
export const gtAtom = atomWithReducer(
  isSSR ? true : localStorage.getItem("gt"),
  (_prev, newGt: string) => {
    if (isSSR) {
      throw new Error("unable to set in SSR");
    }
    localStorage.setItem("gt", newGt);
    return newGt;
  }
);
```

**Comment by Sparklytical** [comment]
Hey @dai-shi , when I open the tab first time, it do correctly shows the value as 'foo' in your sandbox, but when i delete the value from localStorage and reload the page again, it shows null like the screenshot. and this is that null problem that im having.

![null](https://user-images.githubusercontent.com/30311089/109335642-57de3d80-7888-11eb-9922-4195767d0b45.png)

**Comment by dai-shi** [comment]
What is the expected behavior, and how would it be solved with `useState` in native React?

**Comment by Sparklytical** [comment]
I added a recheck with the help of useEffect and my problem got solved. And thanks for creating such a good library.

**Comment by dlindenkreuz** [comment]
@Sparklytical Curious about your solution, I'd love to see it in a codesandbox!

In the meanwhile, I also found a workaround:

```typescript
const useSsrFallback = <T>(fallback: T, value: T) => {
  const [mounted, setMounted] = useState(false)
  useEffect(() => {
    setMounted(true)
  }, [])
  if (!mounted) {
    return fallback
  }
  return value
}

const MyToken = // ... localstorage token ...

const FooComponent = () => {
  const [myToken, setMyToken] = useSsrFallback(
    [undefined, () => {}],
    useAtom(ChallengeToken) // <- this is always called, no issues with hook consistency
  )
  // ...
}
```

**Comment by Sparklytical** [comment]
@dlindenkreuz hey sorry about it, i just did a useEffect that will check if the value is undefined, if it's check again or try to set state again. Sorry I tried finding the exact code where i did it, but it was missing/not able to find it.
