### ISSUE TITLE
[Tips] Updating atom object property

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#32]
Atoms can hold any primitive values, including objects.
Here's an example to updating a property of an object.

```js
const funkyPigAtom = atom({ funkyPig: { glasses: 'stylish', bling: 'golden' }})

const Component = () => {
  const [funkyPig, setFunkyPig] = useAtom(funkyPigAtom)
  const updateBling = (bling) => {
    setFunkcyPig((prev) => ({ ...prev, funkyPig: { ...prev.funkyPig, bling } }))
  }
  // ...
}
```

We could also create an update action atom.

```js
const funkyPigAtom = atom({ funkyPig: { glasses: 'stylish', bling: 'golden' }})
const updateBling = atom(
  null,
  (get, set, bling) => {
    const prev = get(funkyPigAtom)
    set(funkyPigAtom, { ...prev, funkyPig: { ...prev.funkyPig, bling } })
  }
)
```

**Comment by hsw107** [comment]
Using `[immer](https://immerjs.github.io/immer/docs/introduction)` could simplify this, especially with even deeper nesting:
e.g.

```
const updateBling = atom(null, (get, set, bling) => {
  const prev = get(funkyPigAtom);
  const newState = produce(prev, (draft) => {
    draft.funkyPig.bling = bling;
  });
  set(funkyPigAtom, newState);
});

```

**Comment by dai-shi** [comment]
Exactly! See also #11.

**Comment by hsw107** [comment]
@dai-shi You're way ahead of me, thanks! :) Maybe I should spend more time looking through all these issue!

**Comment by NorweskiDrwal** [comment]
Ooooh, you guys are the best!
I am learning about Observer Patterns in JS and wanted to write a state management lib using OP for giggles, so I found [this](https://bennetthardwick.com/blog/recoil-js-clone-from-scratch-in-100-lines/), which led me here (and to Recoil) and now I'm just writing a handler's layer on top of Jotai to learn how stuff works.
@dai-shi thanks a lot for doing all this ;)

**Comment by dai-shi** [comment]
I'm not sure where/how I should write this on in the docs.
Or, is it so obvious that we don't need to describe in docs?

**Comment by dai-shi** [comment]
Let me just close this as explained and resolved. We do now have `jotai/immer` bundle which eases this use case with mutation style.

**Comment by peterje** [comment]
Could you provide an example of how to update an object property using atomWithImmer?

**Comment by dai-shi** [comment]
Something like this?

```js
const fooAtom = atomWithImmer({ foo: 'hello' })

  // in component/hook
  const [foo, setFoo] = useAtom(fooAtom)
  const handleClick = () => {
    setFoo((draft) => {
      draft.foo = 'hello world'
    })
  }
```
