### ISSUE TITLE
Error boundaries don't work in providerless mode

### ISSUE THREAD

**Issue by allforabit** [pmndrs/jotai#323]
I was having an issue where an error in an async read function would cause the app to lock up and show an error in the console but not trigger react error boundaries. I fixed it by adding the provider back in. So it seems as if error boundaries aren't working correctly in providerless mode.

**Comment by dai-shi** [comment]
Thanks for this issue. I wasn't aware of the bug, but it's not too surprising as providerless mode is brand new.
Would you be able to add a failing test in `tests/error.test.tsx`?

**Comment by allforabit** [comment]
Yes will do!

**Comment by allforabit** [comment]
Will get to this before the end of the week...

**Comment by Thisen** [comment]
@allforabit, if you don't get around to do this, just leave a note on the issue and we can take over :)

**Comment by allforabit** [comment]
Hi yes please if you can take over that would be great. I will get the jotai repo setup properly on my machine and will try to contribute for further issues.

**Comment by dai-shi** [comment]
@allforabit Can you repro with codesandbox then?

**Comment by Thisen** [comment]
Yeah, please add a reproduction - I haven't been able to reproduce this. 

Thanks in advance!

**Comment by allforabit** [comment]
Hi @dai-shi @Thisen I'm actually struggling to recreate it myself. It could have been something else in my app that was causing it. Here's the code sandbox that I'm trying to recreate it with: https://codesandbox.io/s/keen-chaum-2rnwm?file=/src/my-component.tsx I will try jotai in providerless mode again in my app and see if it will show up there. Otherwise this issue might not be relevant. Thanks!

**Comment by allforabit** [comment]
I tried it again in my app and it's working as expected. So closing the issue. Sorry for the incorrect report!

**Comment by mdtusz** [comment]
I seem to be encountering this as well - I have a read-write atom that takes an async function for the write argument (for using the "last" value) but the errors seem to be swallowed. A simple example:

```ts
const fooAtom = atom(0, async (get, set, update) => {
  const oldValue = get(fooAtom);
  const newValue = await update(oldValue);
  set(fooAtom, newValue);
}

// Then in some component...
const [foo, setFoo] = useAtom(fooAtom);

const onClick = () => {
  try {
    await setFoo(async (old) => await someFailableAsyncThing()) 
  } catch (e) {
    console.log("This will never be run");
  }
}

return <button onClick={onClick}>Foo</button>
```

Adding `await` in front of the `setFoo` line doesn't make any difference either :thinking:

**Comment by dai-shi** [comment]
@mdtusz 
Nice catch. (Though, this isn't related with the original issue.)

https://github.com/pmndrs/jotai/blob/2c3e3c31a9491ab5032e1d71db6abb5800e2be53/src/core/vanilla.ts#L493

Well, it's not yet implemented. Actually, it was implemented but I removed it during refactoring as the code wasn't maintainable. Let's revisit it again. I think it would be just good to return the error in the promise.

**Comment by mdtusz** [comment]
Should the `setState` write that is provided by `useAtom` not just throw an error as well if one occurs during an update? That seems the most "expected" to me from a dx point of view. I'll open a new issue where we can discuss more.
