### ISSUE TITLE
Are we supposed to use memo wrapping while using jotai ..?

### ISSUE THREAD

**Issue by sahilrajput03** [pmndrs/jotai#324]
since if we don't wrap components around React.memo, react re-renders all child components by default, is there some recommendations for using react.memo around each component for using jotai effectively.?

Jotai is great work, but i also made a similar thing some time ago when i din't know about it then.. https://www.npmjs.com/package/usewhat , but its far different thing from jotai, thanks!!

Loving uisng jotai!!

**Comment by Aslemammad** [comment]
There's nothing bad about re-rendering. It will be bad if it decreases performance. You can use the memo there, and maybe there are other approaches instead of the memo. I recommend you [this](https://overreacted.io/before-you-memo/). But I'd love to see where's the problem in jotai and your performance so that we can help you more.

**Comment by dai-shi** [comment]
@sahilrajput03 
In general, I'm not against using React.memo, it works well in some cases. I'd use it when useState has an array of objects.
With jotai, it's likely that we useAtom in deep in component tree, and it's less likely we need React.memo for performance optimization. If you organize the structure well, you would never need it.
Let me know if you have more specific questions. Happy to help.

**Comment by sahilrajput03** [comment]
> There's nothing bad about re-rendering. It will be bad if it decreases performance. You can use the memo there, and maybe there are other approaches instead of the memo. I recommend you [this](https://overreacted.io/before-you-memo/). But I'd love to see where's the problem in jotai and your performance so that we can help you more.

Gonna read this article and get back to you..., thanks for replying ..:)

**Comment by sahilrajput03** [comment]
> @sahilrajput03 
> In general, I'm not against using React.memo, it works well in some cases. I'd use it when useState has an array of objects.
> With jotai, it's likely that we useAtom in deep in component tree, and it's less likely we need React.memo for performance optimization. If you organize the structure well, you would never need it.
> Let me know if you have more specific questions. Happy to help.

I just came to know about jotai from reading kent'c article about statemanagement.., but i am using this for my curren projects.., i am tired of making all contexts and their providers using usecontext.. 🤣

Thanks a lot for making jotai this good..!
:)

**Comment by dai-shi** [comment]
Check my latest todos example, using memo.
https://codesandbox.io/s/jotai-todos-ijyxm?file=/src/App.tsx:961-998

**Comment by sahilrajput03** [comment]
I saved that codesandbox in my folder in codesandbox account, and will analy it sooner. 
Thanks @dai-shi , i appreciate your work!
