### ISSUE TITLE
Snowpack atomState.d is not defined

### ISSUE THREAD

**Issue by mauricekraus** [pmndrs/jotai#327]
Hey, I bootstrapped my application with snowpack instead of CRA. So far it worked great with jotai, but I wanted to use atoms that get an asynchronous read function (get). Here I encountered a problem that does not occur with apps bootstrapped with CRA. Also, the error doesn't occur when I copy the code in myself and let it transpile through my pipeline.  Apparently atomState.d is not set when iterating over state.w in commitState (atomState is undefined). I have attached a repo to illustrate. Unfortunately, I don't understand the code enough to debug it myself as to why this happens and I also don't understand why this only happens when transpiling through Snowpack.

https://codesandbox.io/s/serene-noether-7ns2i?file=/src/App.tsx

Thanks for your help

**Comment by dai-shi** [comment]
Thanks for reporting! Such an edge case is very helpful.

> I also don't understand why this only happens when transpiling through Snowpack.

Me neither. I would like to see the transpiled code, the difference between snowpack and cra.
I have zero experience in snowpack (would like to learn it!), so suggestions/guides are appreciated.

Meanwhile, can you quickly check if #326 changes the situation? You can simply install the build by codesandbox ci.

**Comment by Aslemammad** [comment]
0.15.0 didn't fix this problem. The error still there.

**Comment by Aslemammad** [comment]
#326 didn't fix that.

**Comment by Aslemammad** [comment]
@mauricekraus  #338 I think it's done now.

**Comment by mauricekraus** [comment]
@Aslemammad good catch. Yep this resolves the issue! Thanks for your help.
