### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by Andrewjeska** [pmndrs/jotai#329]
```
query.js:1007 Uncaught ReferenceError: regeneratorRuntime is not defined
    at query.js:1007
    at atomWithQuery (query.js:1037)
```

I'm getting this error when setting using `jotai/query`. I'm using it as shown below. 

```
const profileAtom = atomWithQuery((get) => ({
  queryKey: [],
  queryFn: async () => {
    return await getProfile();
  },
}));

export const useUserProfile = () => useAtom(profileAtom);
```

`getProfile` simply fetches the user's profile from the backend using the user's auth token. 

Googling the error message cites a few issues people encountered with Babel. 

For what it's worth, we're using `snowpack` for this repo. 

Anyways, I haven't encountered this error before, something to do with `async/await` not being polyfilled correctly but I'm not terribly sure. 

Any ideas would be much appreciated!

**Comment by Aslemammad** [comment]
I think it's related somehow to #327

**Comment by Thisen** [comment]
This could have something to do with `@babel/plugin-transform-regenerator`, which is included in `@babel/preset-env`. The transform is for transpiling generator functions, which async/await statements are turned into.

The `regeneratorRuntime` is probably not included in the snowpack build, which causes it to error in the async scenario.

**Comment by dai-shi** [comment]
```bash
$ ag regeneratorRuntime dist
dist/query.js:134:    var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(get, set, action) {
dist/query.js:137:      return regeneratorRuntime.wrap(function _callee$(_context) {
```

The solution on user end is to install `@babel/plugin-transform-regenerator` or use `query.module.js`.

The solution on lib end is to remove async/await, which is currently only one place and not very meaningful. But, eventually other bundle may use async/await, so this is just a temporary solution. It might be better to explore fixing the rollup config and drop old browser, probably.

**Comment by mauricekraus** [comment]
Including @babel/plugin-transform-regenerator did not fix the issue (I even included regenerator runtime via cdn in the html) everywhere else it is defined but not in jotai. Can you guide me how to use query.module (did not manage to get this to work)

**Comment by dai-shi** [comment]
Please try v0.15.1, which doesn't use regeneratorRuntime. It should just work.

---
> The solution on user end is to install `@babel/plugin-transform-regenerator`

This was wrong. Confused with https://babeljs.io/docs/en/babel-runtime.

> or use `query.module.js`.

It depends on bundlers. It may or **may not** work doing something like this.
```js
import { atomWithQuery } from 'jotai/query.module'
```
