### ISSUE TITLE
Update example on https://jotai.surge.sh/

### ISSUE THREAD

**Issue by mjsarfatti** [pmndrs/jotai#334]
Said example still shows the use of `<Provider>`, which I understand is not necessary anymore (since #308).

I'm using Jotai with react-three-fiber and I couldn't figure out why atoms weren't "synced" between the App and the Canvas root. Went in a small rabbit hole made of READMEs, Docs and Issues and was a little lost when some suggested to use `useBridge`, but I couldn't find the hook in the docs anywhere.

Eventually found out I just had to remove `<Provider>` from my code for everything to magically work 🙌

PS: thanks for this simple amazing library, it makes React state something nice to work with!

**Comment by dai-shi** [comment]
Thanks for reporting this and sorry for the confusion.
So, this falls into both updating the example and fixing docs. I will create a separate issue for docs.

**Comment by Aslemammad** [comment]
#342

**Comment by dai-shi** [comment]
It's deployed on the new site: https://jotai-demo.pmnd.rs/
The last thing is to redirect from the old site.
