### ISSUE TITLE
Dynamic selectAtom or focusAtom?

### ISSUE THREAD

**Issue by tarngerine** [pmndrs/jotai#347]
Hi, curious how I might approach this issue

Given a data structure like:
```
const elementsAtom = atom({
  id1: {
    value: "..."
  },
  id2: {
    value: "..."
  },
  id3: {
    value: "..."
  },
})
```

i want to render an `<Element>` for each `id` which DOES NOT RERENDER whenever any of the other elements update

something like selectAtom or focusAtom or splitAtom would be nice, but splitAtom is only for arrays, and select/focus atom need to be defined outside of a component

how might I be able to do something like

select/focusAtom style

```
// Element.tsx

const Element = (id) => {
  const el = focusAtom(elementsAtom, id, deepEquals)
  return <>
    <div>{el.value}</div>
  </>
}
```

or splitAtom style

```
//ElementList.tsx

const elementsAtom = {...} // shown above
const elementAtoms = splitAtomByKey(elementsAtom) // each key = a new atom

const ElementList = () => {
  const elements = useAtomValue(elementAtoms)
  return elements.map((atom) => <Element atom={atom} />)
}
```

**Comment by Aslemammad** [comment]
Actually, I'm not that much into focus and select utilities, but I refactored an example these days, take a look at [this](https://github.com/pmndrs/jotai/blob/master/examples/mega-form/src/App.tsx).

**Comment by dai-shi** [comment]
> something like selectAtom or focusAtom or splitAtom would be nice, but splitAtom is only for arrays, and select/focus atom need to be defined outside of a component

All of these atom creating utilities have to be used outside components or with useMemo/useRef.

For this case, you could simply create a derived atom in component.

```js
const Component = ({ id }) => {
  const elementAtom = useMemo(() => atom(get => get(elementsAtom)[id]), [id])
  const element = useAtom(elementAtom)
  ...
}
```

We should document this more clearly.

**Comment by dai-shi** [comment]
> We should document this more clearly.

https://docs.pmnd.rs/jotai/basics/primitives

<img width="759" alt="image" src="https://user-images.githubusercontent.com/490574/116847798-40c02100-ac26-11eb-94ea-50f65d3fa631.png">

**Comment by bhushan-patil-official** [comment]
Hey @dai-shi I know this is a closed issue. But, how can we update the value of any single key, suppose we want to update the object of id2. How can we do that? I tried atom Family but I was not able to get it working.

```
export const flatAtomData = atom<{
	dataId: string[],
	dataById: Map<string, any> | {}
}>({dataId: [], dataById: {}});

export const flatAtomFamily = atomFamily((param) =>
	atom(
		// @ts-ignore
		(get) => get(flatAtomData).dataById.get(param.uuid),
		(get, set, arg) => {
			const prevMain = get(flatAtomData);
			const prev = get(flatAtomData).dataById;
			// @ts-ignore
			prev?.set([param.uuid, arg])
			// @ts-ignore
			set(flatAtomData, { ...prevMain, dataById: prev });
		}
	)
)
```

As you can see I have a nested object I just want to update a nested key of the nest object.
So here I want to update an object from dataById which has a Map in it. so trying to update the new values in the atom.

Can you suggest me how we can do that. or guide me to any discussion where it took place, because I was not able to find it.

Thanks

**Comment by dai-shi** [comment]
If you use Map, you have to update it immutably. But, unless you are familiar with Map, maybe you should prefer using plain objects to Maps.

**Comment by bhushan-patil-official** [comment]
@dai-shi Thanks for the quick response. I am using map because I wanted it to be unordered and in object it was not setting as unordered.

The idea is to update the specific key in the object without creating a re-render for component.

**Comment by dai-shi** [comment]
atom is the way to trigger re-render. If you want to avoid re-render, you don't want use atoms in the first place.

**Comment by bhushan-patil-official** [comment]
I want to re-render the component where that specific key is being consumed.

**Comment by dai-shi** [comment]
Mutable Map doesn't sound the right solution then.
Check out atoms-in-atom pattern, which might help.
If you need a help, please create a minimal example with https://codesandbox.io/s/react-new without RN, and open a new discussion.

**Comment by bhushan-patil-official** [comment]
Will do it thanks

**Comment by AjaxSolutions** [comment]
> > something like selectAtom or focusAtom or splitAtom would be nice, but splitAtom is only for arrays, and select/focus atom need to be defined outside of a component
> 
> All of these atom creating utilities have to be used outside components or with useMemo/useRef.
> 
> For this case, you could simply create a derived atom in component.
> 
> ```js
> const Component = ({ id }) => {
>   const elementAtom = useMemo(() => atom(get => get(elementsAtom)[id]), [id])
>   const element = useAtom(elementAtom)
>   ...
> }
> ```
> 
> We should document this more clearly.

```
const Component = ({ id }) => {
  const elementAtom = _.memoize(() => atom(get => get(elementsAtom)[id]), [id])
  const memoizedAtom = _.memoize((id, elementAtom) => atom(get => get(elements)[id]));
  const element = useAtom(elementAtom)
  ...
}
```

> > something like selectAtom or focusAtom or splitAtom would be nice, but splitAtom is only for arrays, and select/focus atom need to be defined outside of a component
> 
> All of these atom creating utilities have to be used outside components or with useMemo/useRef.
> 
> For this case, you could simply create a derived atom in component.
> 
> ```js
> const Component = ({ id }) => {
>   const elementAtom = useMemo(() => atom(get => get(elementsAtom)[id]), [id])
>   const element = useAtom(elementAtom)
>   ...
> }
> ```
> 
> We should document this more clearly.

@dai-shi Can I use lodash memoize to create an equivalent example?

```
const memoizedAtom = _.memoize((id) => atom(get => get(elementsAtom)[id]));

const Component = ({ id }) => {
  const elementAtom = memoizedAtom(id);
  const element = useAtom(elementAtom)
  ...
}
```
