### ISSUE TITLE
`setAtom` doesn't bail on same value if component reads from another atom

### ISSUE THREAD

**Issue by dwelle** [pmndrs/jotai#355]
`setAtom(value)` doesn't bail on same value provided the component also uses another atom (it doesn't behave exactly like I just described in 100% of cases, but I think this is the gist).

csb: https://codesandbox.io/s/setatom-bail-failure-59tcw?file=/src/App.tsx

- jotai: 0.15.2
- strict mode: both strict & non-strict mode

**Comment by dwelle** [comment]
If it'll help in investigation, the default value of the atom also comes into play. If the default value is identical to the one being set, the bailing works: https://codesandbox.io/s/setatom-bail-failure-forked-3b67s?file=/src/App.tsx

**Comment by Aslemammad** [comment]
I'm investigating it; thanks for the report, @dwelle.

**Comment by dwelle** [comment]
Funny enough, if there's a sibling compo using the same atom (as is being updated), it works correctly: https://codesandbox.io/s/quirky-einstein-u9v62?file=/src/App.js

**Comment by dwelle** [comment]
Thank you @Aslemammad and @dai-shi for the fix!
