### ISSUE TITLE
[Tips] useSelector equivalent

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#36]
While the atom model fits with bottom-up approach (composing small atoms), we could create a big atom and select pieces out of it.

```js
const bigAtom = atom({
  num: 0,
  str: 'hi',
  bool: true,
  obj: { a: 1, b: 2, arr: [3, 4, 5] },
})

const numAtom = atom(
  get => get(bigAtom).num,
  (get, set, update) => {
    const prev = get(bigAtom)
    const num = typeof update === 'function' ? update(prev.num) : update
    set(bigAtom, { ...prev, num })
  }
)

  const [num, setNum] = useAtom(numAtom)
```

We can make this a hook. Let's try for a read-only atom.

```js
const useSelector = (anAtom, selector) => {
  const selectedAtom = useMemo(() => atom(get => selector(get(anAtom))), [anAtom, selector])
  return useAtom(selectedAtom)[0]
}
```

**Comment by rattrayalex** [comment]
`useSelector` seems a bit toilsome to write, should it be baked-in?

When I first read the readme, and saw `const sum = atom(get => get(count1) + get(count2) + get(count3))`, I assumed that it would intelligently memoize for me, so that if none of the counts have changed, the sum would not recalculate. In other words, I assumed that a jotai `atom` with a get function was the same as a [recoil selector](https://recoiljs.org/docs/basic-tutorial/selectors). Is that not the case?

**Comment by dai-shi** [comment]
useSelector here is just to show the possibility, and I’m not sure if there’s real use cases. 

Yes, the derived atoms work like recoil’s selector. They are only recalculated if one or more of its dependencies change.

**Comment by rattrayalex** [comment]
Oh okay, great. 

I see, your `useSelector` example there was just to generalize the `useNum` function. So instead of writing `useNum` you would write:
```
const useNumValue = useSelector(bigAtom, (s) => s.num)
```
However, wouldn't this still update every time any item in the tree changes? Sorry if I misunderstand, I am new to many of these concepts

**Comment by dai-shi** [comment]
No, your useNumValue updates only if num is changed. This is because the useSelector creates a new derived atom in it. Happy to help you for better understanding.

**Comment by dai-shi** [comment]
I'm not sure how I should do with this because our basic recommendation is bottom-up approach. Just close it, leave it or write something in docs?

This is kind of top-down approach and jotai-optics by merisbahti seems like a right solution.
https://github.com/merisbahti/jotai-optics

**Comment by dai-shi** [comment]
> useSelector here is just to show the possibility, and I’m not sure if there’re real use cases.

Maybe if we support `equalityFn` too, it might be useful if someone is used to react-redux.

> useSelector seems a bit toilsome to write, should it be baked-in?

Let me try...
