### ISSUE TITLE
Why null data save in "null"?

### ISSUE THREAD

**Issue by tomriddle7** [pmndrs/jotai#372]
https://codesandbox.io/s/gallant-napier-piskp

When I click 'reset localstorage', stringAtom become null.

But I refresh webpage, stringAtom call localstorage data and it become 'null'.

I don't understand why this happens.

How can I fix it?

**Comment by dai-shi** [comment]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/490574/111956750-7acddb80-8b2e-11eb-9094-dfcc89669171.png">

The stringAtom doesn't accept `null`. The easiest fix would be to pass an empty string.
https://codesandbox.io/s/lucid-browser-swchc

Closing this as it doesn't seem to be an issue in the lib, but a usage question. Feel free to continue questions/discussions.
