### ISSUE TITLE
"Too many re-renders." when I set value to atom in useEffect (v0.15.3)

### ISSUE THREAD

**Issue by wancup** [pmndrs/jotai#373]
Thank you for awesome library!

I updated Jotai v0.15.2 to v0.15.3. in my project, and it starts to fall.
The error message is "Too many re-renders. React limits the number of renders to prevent an infinite loop.".

I uploaded the reproduction project to https://github.com/wancup/jotai-re-render-error-test. (It's ok in v0.15.2)
Main file is https://github.com/wancup/jotai-re-render-error-test/blob/main/src/App.js 

I think it's occurred by using an atom derived other derived atom and set a value in useEffect.

Is it a Jotai's bug?

**Comment by dai-shi** [comment]
Yeah, it looks like a bug in v0.15.3.
Thanks for reporting and the reproduction!

I tried commenting out `fourfold2` line, and it seems to work.
https://codesandbox.io/s/heuristic-flower-npuq1?file=/src/App.js

We should fix the bug anyway...
