### ISSUE TITLE
`atomWithQuery` does not respect `react-query` options

### ISSUE THREAD

**Issue by aulneau** [pmndrs/jotai#374]
from discord:
> So i've been digging into the atomWithQuery for one of my projects, and I can't seem to get any of the 'refreshX' options that come along with react-query to work. is it the case that an atomWithQuery should be able to refresh on an interval, without suspending?
>
> I've modified this codesandbox to use the `refreshInterval` option to 1 second, and you'd expect the atom to update behind-the-scenes with the new data -> https://codesandbox.io/s/jotai-query-demo-forked-7kpv1?file=/src/App.tsx (but it does not refetch)

Some of the best features of a tool like `react-query` have to do with its ability to refresh data at different times:
- on an interval
- on mount
- on network change
- on window focus

Currently `atomWithQuery` can take these options but it seems to not apply them.

**Comment by dai-shi** [comment]
Thanks for reporting the issue. Let's investigate how to support them. We want to support them.

For now, I have a question: When should it "suspend" and when shouldn't it? Currently, it suspends for "refetch", but I wasn't so sure if it could be done silently.

**Comment by aulneau** [comment]
> For now, I have a question: When should it "suspend" and when shouldn't it? Currently, it suspends for "refetch", but I wasn't so sure if it could be done silently.

I think it depends on the app. For me, I like that it would suspend at first if there is no data, but then not suspend when the data updates via any of the refresh variables. I don't think it should suspend on every single update.

react-query has an option to enable suspense -> https://react-query.tanstack.com/guides/suspense#_top, maybe we could allow more fine-tune control over suspense, eg `suspenseOnInit` `suspenseOnRefresh`?

**Comment by dai-shi** [comment]
Thanks, good to know. Let's revisit the suspense behavior too after we figure out how to support refreshInterval.

Note, unlike pure react-qurey, atomWithQuery doesn't have a loading flag. It prefers to use suspense for showing loading status.

**Comment by aulneau** [comment]
Looking into this more, I realized for my use case the atom is never firing the `onMount` method, nor subscribing -- I am passing an initial value to the atom via a Provider (as the app is SSR). Would that cause an issue? I saw in a different test app (non-ssr), the refresh options apply correctly and the interval works.

**Comment by dai-shi** [comment]
> passing an initial value to the atom via a Provider

Oh, right. initial values in Provider are to store atom values as if they are already mounted. (It's conceptually different from atom's initial value.)
I'm not sure if this is somewhat solvable or rather intended. 🤔 
In the mean time, we'd need to subscribe in useEffect at the Provider in this use case. (without using onMount...)

**Comment by aulneau** [comment]
I see, that makes sense.

I think for me (and probably others) this would be an ideal experience when using `atomWithQuery` in next.js or any other ssr app.

- fetch data on server
- provide the initial data to the atom from the server
- when the client hydrates, the atom subscribes and respects any react-query options

I know react-query has two patterns for supplying the initial data, with the [`initialData`](https://react-query.tanstack.com/guides/ssr#using-initialdata) option or the [Hydration](https://react-query.tanstack.com/guides/ssr#using-hydration) pattern.

**Comment by aulneau** [comment]
This works, but seems maybe a round about way of fixing it:

```ts
export const dataAtom = atom<DataType | null>(null); // provide initial state via Provider
export const queryAtom = atomWithQuery(get => ({
  queryKey: QUERY_KEY,
  queryFn: fetcher,
  initialData: get(dataAtom),
  refetchInterval: 10000,
  refetchOnReconnect: true,
  refetchOnWindowFocus: true,
  refetchOnMount: true,
  keepPreviousData: true,
}));

export const finalAtom = atom(get => {
  if (typeof document === 'undefined') {
    return get(dataAtom);
  } else {
    return get(queryAtom) || get(dataAtom);
  }
});

```

**Comment by dai-shi** [comment]
> this would be an ideal experience when using atomWithQuery in next.js or any other ssr app.

I agree. We have a separate discussion about nextjs #340 (this is not ssr in general).
I guess some of ssr issues might not be tied to jotai/query.



> Looking into this more, I realized for my use case the atom is never firing the `onMount` method, nor subscribing -- I am passing an initial value to the atom via a Provider (as the app is SSR). Would that cause an issue? I saw in a different test app (non-ssr), the refresh options apply correctly and the interval works.

So, confirming this again, do we have any issues currently in non-ssr?
If not, it would be clearer to close this and open a new one? or change the title/description of this issue.

**Comment by aulneau** [comment]
I'm going to close this -- I've found a solution that allows me to get around the issue. To clarify for anyone coming with similar issues: when you use a provider and set the initial value of a given atom, it will not fire any kind of 'onMount' effects. The query atom respects all (most) of the applicable options you'd want to use -- `notifyOnPropsChange` seems to not work for unknown reasons.

**Comment by dai-shi** [comment]
You mean `notifyOnChangeProps`, right?
The "tracked" option might not work as expected with `atomWithQuery` by design.
ref: https://github.com/tannerlinsley/react-query/pull/1578

**Comment by garretteklof** [comment]
Perhaps a little off topic but is there a suggested pattern in place to create atoms based on a result from `atomWithQuery`? In my use case I'm retrieving a large object from an API (using React Query) and I'd like to then divvy this result into their own nested trees of atoms for more atomic usage across the app. Is this the way? Do I have to worry about orphan atoms?

**Comment by dai-shi** [comment]
@garretteklof This falls into #255 and we are working on #400. Please jump in and give us feedbacks there.

@Aslemammad This reminds me of something. We should support read-only atoms in the advanced recipe. We need to use `selectAtom` instead of `focusAtom` for read-only atoms. `splitAtom` works both read-only and writable (primitive-like) atoms.
