### ISSUE TITLE
value from atom is not update and component is not rendered (v0.15.3)

### ISSUE THREAD

**Issue by caltamiranob** [pmndrs/jotai#375]
Hi everybody, i hope you can help me with the following problem beacuse i don't know what i'm doing bad.

I have a "store.js" file where i have all my atoms for specific module:

```javascript
export const loading = atom(false);
export const document = atom(undefined);
export const loadDocument = atom(
    null,
    (_get, set, documentId) => {
        const fetch = async () => {
            try {
                set(loading, true);
                const response = await DocumentService.findById(documentId);
                log(response); //document is loaded ok
                set(document, response);
            } catch (error) {
                console.error(error);
            } finally {
                set(loading, false);
            }
        }
        fetch();
    }
);
```

In another file i have my component where use atoms, when this component load the the initial values from atom are: loading: false and document: undefined; next invoke to the loadDocument method (this method update the document state) in the useEffect hook, but my component continues showing "loading..." text, this happens because my _document state_ is not update and my component is not re-rendered. To make sure, i put a useEffect for _document state_, and this method just show in console _"document undefined"_. 

```javascript
import * as atoms from "./store";

export function ListPage() {
    const { documentId } = useParams(); //this value is get it from url
    const [loading, setLoading] = useAtom(atoms.loading);
    const [document] = useAtom(atoms.document);
    const [, loadDocument] = useAtom(atoms.loadDocument);

    useEffect(() => {
        loadDocument(documentId);
    }, []);

    useEffect(() => {
         log("document", document);
    }, [document]);

    return (
        <Provider>
            { loading && <h1>Loading...</h1>}
            { !loading && <h1>{document.name}</h1>}
       </Provider>
    )
}
```
When I changed the value of _document atom_ in the loadDocument method, my component should be re-rendered? is the right behavior? or I am doing wrong in my code?
Thanks for your support.

**Comment by dai-shi** [comment]
The code looks good and the behavior sounds weird.
Would you be able to create a codesandbox reproduction so that we can dig into it?
Thanks for your help.

**Comment by caltamiranob** [comment]
Hi @dai-shi, I share the sandbox:

https://codesandbox.io/s/test-jotai-async-method-41oyb

Thanks for your help.

**Comment by dai-shi** [comment]
Confirmed this is a bug in v0.15.3.

It works ok in v0.15.2.
https://codesandbox.io/s/test-jotai-async-method-forked-4z27y

**Comment by dai-shi** [comment]
#373 might be related. The root cause could be the same.

**Comment by caltamiranob** [comment]
Thanks @dai-shi, it works with v0.15.2.
Now, i have another problem but maybe is because i'm not understanding how jotai works. 
I have create a component "DocumentInfo", in this component read the "document" atom what was setted in the parent component (ListDocuments), but the "document" atom have the initial value (undefined). How call the document atom is incorrect? 

https://codesandbox.io/s/test-jotai-async-method-forked-ov1on

_ListDocument.js ->_
```javascript
import React, { useEffect } from "react";
import { useAtom, Provider } from "jotai";
import * as atoms from "./stores";
import { DocumentInfo } from "./DocumentInfo";

const ListDocuments = () => {
  const [loading, setLoading] = useAtom(atoms.loading);
  const [document, setDocument] = useAtom(atoms.document);
  const [, loadDocument] = useAtom(atoms.loadDocument);

  useEffect(() => {
    loadDocument("peru");
  }, []);

  useEffect(() => {
    console.log("document", document);
  }, [document]);

  return (
    <Provider>
      {loading && <h1>Loading</h1>}
      {/* {!loading && <h1>{document?.[0]?.name}</h1>} */}
      {!loading && <DocumentInfo />}
    </Provider>
  );
};

export default ListDocuments;
```

_DocumentInfo.js ->_
```javascript
import React, { useEffect } from "react";
import { useAtom } from "jotai";
import * as atoms from "./stores";

export const DocumentInfo = () => {
  const [document] = useAtom(atoms.document);

  useEffect(() => {
    console.log("document from DocumentInfo", document); //this print undefined
  }, [document]);

  return <h1>{document?.[0]?.name}</h1>;
};
```

Thanks for your help.

**Comment by dai-shi** [comment]
It's because you are using Provider incorrectly.
Provider will create a totally isolated state area in the subtree.
Either remove the Provider or place it closer to the root.
https://codesandbox.io/s/test-jotai-async-method-with-components-forked-ks9r1
