### ISSUE TITLE
Snaphot-based devtools

### ISSUE THREAD

**Issue by Thisen** [pmndrs/jotai#388]
Umbrella issue for snapshot-based devtools.

Things to consider/ideate:

- [x] Hooks for snapshots
- [ ] Babel plugin for adding debug labels
- [ ] Dedicated devtools?

Feel free to add ideas/thoughts.

**Comment by dai-shi** [comment]
Thanks for opening this up.

So, snapshot-based means it allows time traveling? The first question that comes to my mind is how to support non serializable values. Probably keeping snapshot array in JS memory.

FWIW, we could do something similar with catchAllAtom and useAtomDevtools for serializable values.

```js
const atom1 = atom(...)
const atom2= atom(...)

const allAtoms = [atom1, atom2]
const catchAllAtom = atom(
  (get) => allAtoms.map(get),
  (get, set, values) => {
    allAtoms.forEach((a, i) => {
      set(a, values[i])
    })
  }
)

const Component = () => {
  useAtomDevtoools(catchAllAtom)
```

**Comment by Thisen** [comment]
Closed, as babel plugin and dedicated devtools will be after v1. See #428  and #487
