### ISSUE TITLE
Jotai intro guide

### ISSUE THREAD

**Issue by panzerdp** [pmndrs/jotai#393]
@dai-shi Thanks for writing such a simple but flexible library!

I wrote an introductory guide to Jotai: https://dmitripavlutin.com/react-jotai-state-management/ 
If you're interested, you can add it to Readme.md.

Thank you, Dmitri.

**Comment by dai-shi** [comment]
@panzerdp Thanks for writing up the post! I already found it on Twitter and had a look.
If you are interested in contributing in documentation, you are more than welcome as that's something we need more work: #333 
Also, we have pmndrs discord server and #jotai channel there for chat-based discussion.

Closing this, but feel free to add follow up comments.

**Comment by dustinlacewell** [comment]
@panzerdp Great article. I think it could be improved if you emphasize how Jotai is different from useState. Their similarities are obvious, but it's not clear what differentiates them. Thanks for the write up!
