### ISSUE TITLE
`useAtomCallback` doesn't have types for 3-param signature

### ISSUE THREAD

**Issue by dwelle** [pmndrs/jotai#398]
```ts
const App = () => {
  useAtomCallback(useCallback((get, set, arg) => {}, [])); // <------ untyped
  return null;
};
```

sandbox: https://codesandbox.io/s/epic-voice-vgjhr?file=/src/App.tsx

**Comment by dai-shi** [comment]
Nice catch. That's similar to what you reported and we discussed about `setAtom` before. I'll make typing a bit looser likewise.
