### ISSUE TITLE
[Tips] How to persist a value with localStorage/AsyncStorage

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#4]
It's not supported by the lib itself, but here's an idea how to persist data.

```js
const strAtom = atom(localStorage.getItem('myKey') ?? 'foo')

const strAtomWithPersistence = atom(
  get => get(strAtom),
  (get, set, newStr) => {
    set(strAtom, newStr)
    localStorage.setItem('myKey', newStr)
  },
)
```

or

```js
const strAtom = atom('foo')

const persistStrAtom = atom(
  null,
  (get, set, action) => {
    if (action.type === 'init') {
      const str = localStorage.getItem('myKey')
      if (str !== null) {
        set(strAtom, str)
      }
    } else if (action.type === 'set') {
      set(strAtom, action.str)
      localStorage.setItem('myKey', str)
    }
  },
)
```

**Comment by camsloanftc** [comment]
Just a thought: these "tips" issues might serve well in an examples readme instead.

It was kind of a happy accident that I noticed these. I could see them getting buried eventually.

**Comment by dai-shi** [comment]
Agreed. We'd eventually move them to readme or a upcoming website.

**Comment by ghmeec** [comment]
RN example of data persistence will be appreciated

**Comment by dai-shi** [comment]
Something like this?
```js
const createPersistAtom = (anAtom, key, serialize, deserialize) => atom(
  null,
  async (get, set, action) => {
    if (action.type === 'load') {
      const str = await AsyncStorage.getItem(key)
      set(anAtom, deserialize(str)
    } else if (action.type === 'save') {
      const str = serialize(get(anAtom))
      await AsyncStorage.setItem(key, str)
    }
  },
)
```
Error handling omitted.

**Comment by italodeandra** [comment]
I'm having a problem with typing both atoms (the original and the persisted).

Can you check this codesandbox?
https://codesandbox.io/s/dreamy-frog-5zpbh?file=/src/App.tsx

What am I doing wrong?

On the persisted atom I'm using SetStateAction to mimic the native useState hook that accepts a function.

**Comment by dai-shi** [comment]
If you don't specify the type in L9, TS infers the atom as PrimitiveAtom.
But if you do like `atom<Person | null>(...)`, it is inferred as read-only atom.
So, it is correct.

I wish to improve atom() types to avoid such confusion. Not sure how..

**Comment by a-eid** [comment]
@dai-shi is `action.type` different btw `react` `react-native`

from you comments seems that react has `init` && `set` react native has `load` && `save` ? 
could you clarify please ?

**Comment by dai-shi** [comment]
@a-eid Nothing special. I just tried various patterns. Which do you think is better?

**Comment by a-eid** [comment]
@dai-shi they both are fine, I personally think `init` & `set` are more descriptive.

but to clarify they are the same actions names in `react` and `react-native` ?

checking the source code, it looks like they are the same for `react-native` & `react`. 

by the way your `use-context-selector` looks awesome 

thank you.

**Comment by dai-shi** [comment]
@a-eid Those action names are something I just defined and they have nothing to do with `react` or `react-native`. (Or, I misunderstood your question.)

**Comment by Maadtin** [comment]
> It's not supported by the lib itself, but here's an idea how to persist data.
> 
> ```js
> const strAtom = atom(localStorage.getItem('myKey') ?? 'foo')
> 
> const strAtomWithPersistence = atom(
>   get => get(strAtom),
>   (get, set, newStr) => {
>     set(strAtom, newStr)
>     localStorage.setItem('myKey', newStr)
>   },
> )
> ```
> 
> or
> 
> ```js
> const strAtom = atom('foo')
> 
> const persistStrAtom = atom(
>   null,
>   (get, set, action) => {
>     if (action.type === 'init') {
>       const str = localStorage.getItem('myKey')
>       if (str !== null) {
>         set(strAtom, str)
>       }
>     } else if (action.type === 'set') {
>       set(strAtom, action.str)
>       localStorage.setItem('myKey', str)
>     }
>   },
> )
> ```

Can you just asign the atom to itself instead of creating 2 different atoms? It's that "correct" ? thanks :)

**Comment by dai-shi** [comment]
@Maadtin good point.

```js
const langAtom = atom('es', (get, set, newLang) => {
    localStorage.setItem('lang', newLang);
    set(langAtom, newLang);
})
```

This works, but it's undocumented because typing in TS for this has a pitfall.
We have `atomWithReducer` in "jotai/utils", so this can be:

```js
const langAtom = atomWithReducer('es', (_prev, newLang) => {
  localStorage.setItem('lang', newLang)
  return newLang
})
```

The only concern is "reducer" typically indicates a pure function...

BTW, you don't want to `localStorage.getItem`, do you?

**Comment by dai-shi** [comment]
We don't need a derived atom and we can do it in useEffect too.

```js
const strAtom = atom('foo')

const Component = () => {
  const [str, setStr] = useAtom(strAtom)
  useEffect(() => {
    if (forTheFirstTimeOrWeWantToRefresh) {
      const savedStr = localStorage.getItem('myKey')
      if (savedStr !== null) {
        setStr(savedStr)
      }
    }
    if (weWantToSaveItForThisTime) {
      localStorage.setItem('myKey', str)
    }
  })
)
```

Cc @gsimone

**Comment by Maadtin** [comment]
> @Maadtin good point.
> 
> ```js
> const langAtom = atom('es', (get, set, newLang) => {
>     localStorage.setItem('lang', newLang);
>     set(langAtom, newLang);
> })
> ```
> 
> This works, but it's undocumented because typing in TS for this has a pitfall.
> We have `atomWithReducer` in "jotai/utils", so this can be:
> 
> ```js
> const langAtom = atomWithReducer('es', (_prev, newLang) => {
>   localStorage.setItem('lang', newLang)
>   return newLang
> })
> ```
> 
> The only concern is "reducer" typically indicates a pure function...
> 
> BTW, you don't want to `localStorage.getItem`, do you?

Yeah I forgot to Add localStorage.getItem  for when reloading the page, 😄  thanks for replying! and yeah I don't think Ill have problems since I don't use TS. :)

**Comment by dai-shi** [comment]
Hi, I added persistence to my simple todo example.
https://codesandbox.io/s/jotai-todos-ijyxm

I hope this pattern can be a general solution to persistence/serialization.

```tsx
const serializeAtom = atom<
  null,
  | { type: "serialize"; callback: (value: string) => void }
  | { type: "deserialize"; value: string }
>(null, (get, set, action) => {
  if (action.type === "serialize") {
    const obj = {
      todos: get(todosAtom).map(get)
    };
    action.callback(JSON.stringify(obj));
  } else if (action.type === "deserialize") {
    const obj = JSON.parse(action.value);
    // needs error handling and type checking
    set(
      todosAtom,
      obj.todos.map((todo: Todo) => atom(todo))
    );
  }
});

const Persist: React.FC = () => {
  const [, dispatch] = useAtom(serializeAtom);
  const save = () => {
    dispatch({
      type: "serialize",
      callback: (value) => {
        localStorage.setItem("serializedTodos", value);
      }
    });
  };
  const load = () => {
    const value = localStorage.getItem("serializedTodos");
    if (value) {
      dispatch({ type: "deserialize", value });
    }
  };
  return (
    <div>
      <button onClick={save}>Save to localStorage</button>
      <button onClick={load}>Load from localStorage</button>
    </div>
  );
};
```

**Comment by dai-shi** [comment]
https://github.com/pmndrs/jotai/issues/5#issuecomment-699922179
Another persistence example with atomFamily.

<overview>
<details>

```tsx
const serializeAtom = atom<
  null,
  | { type: "serialize"; callback: (value: string) => void }
  | { type: "deserialize"; value: string }
>(null, (get, set, action) => {
  if (action.type === "serialize") {
    const todos = get(todosAtom);
    const todoMap: Record<string, { title: string; completed: boolean }> = {};
    todos.forEach((id) => {
      todoMap[id] = get(todoAtomFamily({ id }));
    });
    const obj = {
      todos,
      todoMap,
      filter: get(filterAtom)
    };
    action.callback(JSON.stringify(obj));
  } else if (action.type === "deserialize") {
    const obj = JSON.parse(action.value);
    // needs error handling and type checking
    set(filterAtom, obj.filter);
    obj.todos.forEach((id: string) => {
      const todo = obj.todoMap[id];
      set(todoAtomFamily({ id, ...todo }), todo);
    });
    set(todosAtom, obj.todos);
  }
});

const Persist: React.FC = () => {
  const [, dispatch] = useAtom(serializeAtom);
  const save = () => {
    dispatch({
      type: "serialize",
      callback: (value) => {
        localStorage.setItem("serializedTodos", value);
      }
    });
  };
  const load = () => {
    const value = localStorage.getItem("serializedTodos");
    if (value) {
      dispatch({ type: "deserialize", value });
    }
  };
  return (
    <div>
      <button onClick={save}>Save to localStorage</button>
      <button onClick={load}>Load from localStorage</button>
    </div>
  );
};
```

</details>
</overview>

**Comment by ansh** [comment]
Is it better to do it using a reducer or a derived atom than using useEffect?

**Comment by dai-shi** [comment]
Note the discussion in this issue is a bit old. it's before we introduced `onMount`.

Using useEffect is just fine. If we define logic in atom, we have some benefits:
1. isolate logic outside react
2. make atoms reusable for different providers (also possible with custom hooks)
3. onMount works for dependency atoms
