### ISSUE TITLE
[Question] How do I get the next state value?

### ISSUE THREAD

**Issue by edmulraney** [pmndrs/jotai#406]
```
const [value, setValue] = useAtom(atom(1))

useEffect(() => {
  ...
  setValue(3)
  console.log(value) // === 1
  // how do I now get the latest value of the atom? 
})
```

**Comment by dai-shi** [comment]
On the next render, you would get the next value. This behavior is the same as `useState`.

```js
const [value, setValue] = useAtom(useMemo(() => atom(1), [])) // useMemo to get a stable reference

useEffect(() => {
  if (value === 1) { // to avoid infinite loop
    setValue(3)
  }
})

useEffect(() => {
  console.log(value) // first time "1", and then "3"
})
```

**Comment by edmulraney** [comment]
Is there anyway to provide a callback to get the next value? I need it
within the same calling function

**Comment by dai-shi** [comment]
> Is there anyway to provide a callback to get the next value? I need it within the same calling function

In this specific case you know the result is `3`, but it's not the case with derived atoms.
Updating atom values is an async process, which is handled by react scheduler, so in general it's technically impossible to get the next value in sync.

https://github.com/pmndrs/jotai/blob/master/docs/api/utils.md#useatomcallback
For special use cases, we have a `useAtomCallback` util, which is powerful but not very easy, and not certain if this works for your use case.

**Comment by edmulraney** [comment]
That's exactly my use case. Thank you! 

```
const stateCallback = useAtomCallback(
    useCallback((get, set, arg) => {
      const nextState = get(acid.state)
      return arg(nextState)
    }, [])
  )
```

**Comment by dai-shi** [comment]
That's good to hear.
Please note the use case of this util is not thoroughly tested / considered.

There is a hypothetical case it may not work as expected in Concurrent Mode in the future.
(It's a sort of edge case, if there's a derived read atom (both sync and async), and if stateCallback is invoked before react updates the state in its scheduler, it would return an old value.)
Technically impossible, but there might be a workaround on user end.

If anyone get an issue, please open a new issue. Closing this as resolved.

**Comment by dai-shi** [comment]
@edmulraney I actually would like to learn your use case, if you are still around.
To be honest, using `useAtomCallback` doesn't sound like a right solution, even if it's valid.
Wondered if we should make some guides around it and it would be helpful if you could provide a concrete use case. A codesandbox example would be perfect.

**Comment by tarngerine** [comment]
in a normal react use case i often will just mirror the value i need to access to a useRef, e.g. when I'm implementing a draggable element and i don't want to rebind event handlers every time i updated the x/y position, i'll do something like

```
// useDrag.ts hook, use inside a component that has its own tracked position
function useDrag(setPosition: (prev: Point) => void) {
const [offset, setOffset] = useState<Point>({x: 0, y:0})
const offsetRef = useRef<Point>()

useEffect(() => {
  offsetRef.current = offset
}, [offset]);

useEffect(() => {
  function onMouseMove(e: MouseEvent) {
    setOffset(prev => {x: prev.x + e.movementX, y: prev.y + e.movementY}) 
  }

  function onMouseUp() {
    // commit this value to a higher order component/atom setter that was passed down
    setPosition(prev => {x: prev.x + offsetRef.current.x, y: prev.y + offsetRef.current.y})
  }

  document.addEventListener('mousemove', onMouseMove)
  document.addEventListener('mouseup', onMouseUp)
  
  () => {
    document.removeEventListener('mousemove', onMouseMove)
    document.removeEventListener('mouseup', onMouseUp)
  }
}, [posRef, setPos]);
}
```

**Comment by tarngerine** [comment]
i guess this is not exactly the same bc im not accessing the ref in the same event handler, not sure this would even work, sorry!

**Comment by dai-shi** [comment]
@tarngerine Thanks for chiming in.
I think useRef+useEffect is more legit and less error-prone.

@edmulraney Do you think you can follow this pattern? or what would be the obstacles?

**Comment by edmulraney** [comment]
Hey @dai-shi I will revisit this soon and add some information around what I was trying.

**Comment by dai-shi** [comment]
Closing this as stale. We can reopen with a repro, or open a new one.
