### ISSUE TITLE
imperatively get an atom value

### ISSUE THREAD

**Issue by tarngerine** [pmndrs/jotai#410]
is this possible? e.g. from inside of a useeffect

usecase
- in a menu, when you select something from the list, we want to scroll to the item's positoin in the canvas
- the menu doesn't subscribe to the items themselves

```
useEffect(() => {
  window.scrollTo(itemsAtomFamily(selectedItemId).get().position)
}, [selectedItemId])
```

**Comment by tarngerine** [comment]
rationale here is performance, i dont want to subscribe to every item's atom from a sidebar and rerender the sidebar any time an item changes (they change frequently)

**Comment by tarngerine** [comment]
or actually even better: can fetch it from a function call like

```
function onClick() {
  window.scrollTo(itemsAtomFamily(selectedItemId).get().position)
}

<div onClick={onClick}>
```

**Comment by aulneau** [comment]
You should be able to use [useAtomCallback](https://github.com/pmndrs/jotai/blob/master/docs/api/utils.md#useatomcallback) for this.

**Comment by dai-shi** [comment]
Reading atom values imperatively, is still something yet to be fully supported. (I still don't know a good implementation to work in concurrent mode.)
It does work now at its best, and the api won't change hopefully.

You can use useAtomCallback as @aulneau suggested, or can do in a more straightforward way.

```js
const scrollToItemAtom = atom(
  null,
  (get, _set, id) => {
    window.scrollTo(get(itemsAtomFamily(id)).position)
  },
)

const Component = () => {
  const [, scrollToItem] = useAtom(scrollToItemAtom)
  return (
    <>
      {itemIds.map(id => <div onClick={() => scrollToItem(id)} />}
    </>
  )
}
```

So, you see the power of writable atom?

**Comment by tarngerine** [comment]
writable atom power:
![](https://upload.wikimedia.org/wikipedia/en/9/9f/Over_9000%21.png)

thank you!
