### ISSUE TITLE
atomFamily with atomWithDefault doesn't return WritableAtom

### ISSUE THREAD

**Issue by garrett-hopper** [pmndrs/jotai#413]
It appears the types are off here. If I create an `atomFamily` which returns `atomWithDefault` atoms, I'm not able to write to the atoms.

**Comment by dai-shi** [comment]
Sounds like a typing issue in `atomFamily`.
@Aslemammad you wanna look into it?

@garrett-hopper Would you help us by creating a small repro in codesandbox?

**Comment by garrett-hopper** [comment]
It looks like this isn't actually an issue.
I think my initializer was incorrect or perhaps I was missing the third type parameter on `atomFamily`. Or maybe I was just seeing ghosts. :shrug:
