### ISSUE TITLE
Error thrown in async write result in infinite loop

### ISSUE THREAD

**Issue by garrett-hopper** [pmndrs/jotai#414]
Trying to debug this, it looks like the `Promise` wrapped test error is constantly alternating being thrown by [core/useAtom.ts#L33](https://github.com/pmndrs/jotai/blob/fa983b2b4d39cc123df1fc6e8e49f6e81f0b8e90/src/core/useAtom.ts#L33) and some internal React code.

This results in constant `Rendering Test` messages being logged.
```jsx
import { atom, Provider, useAtom } from 'jotai';
import { Suspense } from "react";
import { render } from "react-dom";
import { ErrorBoundary } from "react-error-boundary";

const testAtom = atom(undefined, (async () => {
  throw new Error('test');
}));

render(<App />, document.getElementById("app"));

function App() {
  return (
    <Provider>
      <ErrorBoundary fallbackRender={({ error }) => { return (<p>{error.toString()}</p>); }}>
        <Suspense fallback={"Loading..."}>
          <Test />
        </Suspense>
      </ErrorBoundary>
    </Provider>
  );
}

function Test() {
  console.log('Rendering Test');
  const [_, write] = useAtom(testAtom);

  return (
    <button onClick={() => write()}>Test</button>
  );
}

```

**Comment by aulneau** [comment]
I've ran into this too, and it can be hard to debug. I think this will fix it:
```ts
const testAtom = atom(undefined, (async () => {
  await new Promise(resolve => resolve());
  throw new Error('test');
}));
```

Basically if you do an async atom that doesn't actually do anything async, it seems to break. Def not ideal, I wonder what can be done. @dai-shi what do you think?

**Comment by dai-shi** [comment]
Throwing a write promise is something I invented, and not like a de-facto yet.
So, it's subject to change in the future. So far, it's handy to suspend with write atoms.

I'm not sure if I understand the issue of OP. Oh, it's infinite loop. That's unexpected.
So, how can you make this to cause infinite loop? Does clicking the "Test" button once makes infinite loop?

---
There's one design issue. We could remove the write promise when error occurred, and return a original value. Yeah, that makes sense actually. Let me do it.

**Comment by garrett-hopper** [comment]
Yeah, a single click of `Test` results in infinite rendering calls.
Turning on `Pause on caught exceptions` shows that the `Promise` wrapped `Error` is bouncing between React and Jotai.

**Comment by garrett-hopper** [comment]
@dai-shi, testing with `https://pkg.csb.dev/pmndrs/jotai/commit/fb4fba1d/jotai`, it does indeed prevent the infinite loop, though the error ends up being thrown uncaught and is only logged to the console. It seems to me that it should be able to be caught by the `ErrorBoundary`.

**Comment by dai-shi** [comment]
> a single click of Test results in infinite rendering calls.

Hmm, I expected it would show Loading... forever. What would happen if you remove the ErrorBoundary?

Anyway, good to know that #415 fixes it.

> It seems to me that it should be able to be caught by the ErrorBoundary.

I originally thought so and implemented so. But, then realized that ErrorBoundary is for "render" errors. atom write is not "render" (while atom read is "render").

So, the idiom of this pattern is this:
```js
  const [_, write] = useAtom(testAtom);
  const safeWrite = async () => {
    try {
      await write();
    } catch (e) {
      // handle error
    }
  };
```

(But, I agree that there's an impedance mismatch, because we throw the write promise. So, this is still somewhat open for discussions.)

**Comment by garrett-hopper** [comment]
Yeah, it does show `Loading...` forever; the infinite loop is only seen in the console due to the `console.log('Rendering Test');`. (And I suppose my laptop fans spinning up. :thinking:)
Oh, that makes sense now. The write error would have to be stored, then it could trigger another render to throw it I suppose. (If I specifically wanted it to bubble up to the `ErrorBoundary`)
`try..catch` for writes does make sense as a requirement now.

**Comment by dai-shi** [comment]
OK, now got it. Because the write promise is no longer pending, React retries again and again.
So, I claim this is a bug in jotai and #415 is the proper fix.

Thanks for reporting and investigating!

**Comment by garrett-hopper** [comment]
@dai-shi, perhaps this should be a separate issue for discussion, but it seems like when a write function throws an error, it should be sent back to the caller so they can catch it and use something like [`useErrorHandler`](https://www.npmjs.com/package/react-error-boundary#useerrorhandlererror-error) from `react-error-boundary` to display it to the user. It seems like at the moment the error is consumed and sent straight to the console.

**Comment by garrett-hopper** [comment]
Oh, duh, I wasn't awaiting the returned promise. Nevermind; thanks for all your help!
