### ISSUE TITLE
Support primitive atoms with a Promise as the initial value.

### ISSUE THREAD

**Issue by mhcoffin** [pmndrs/jotai#430]
I think this would be a powerful feature. It would allow one to create an atom that is initially suspended, and then un-suspend it later, when data is available. See, for example,  a simple [subscription example](https://codesandbox.io/s/jotai-subscription-1-k416l). This was derived from something I was working in for firebase authentication. The same idea would work for firestore subscriptions. Dai-shi also mentioned that atomWithQuery() could be improved if this were supported. 

Work-arounds are possible using a combination of atoms and useEffect, but in my experience they're very tricky to get exactly right and they require quite a bit of code. 

In addition to the additional power, it seems like it might be better to implement this than try to write documentation explaining why it doesn't work. :-)

**Comment by dai-shi** [comment]
Thanks for opening this up. This is something I thought about too. Not sure if it can be implemented in a straightforward way. React Suspense contract is to wait until the promise is resolved, right? So, we need to return a new promise. I can try that.

I wonder if anyone has an idea for typing.

**Comment by dai-shi** [comment]
(Also wondering if this is possibly related with #426. In this case, it's a priority for me.)

**Comment by mhcoffin** [comment]
Accidentally closed this.

**Comment by dai-shi** [comment]
https://codesandbox.io/s/jotai-subscription-1-forked-ol4rv
This is with the build #431.

**Comment by dai-shi** [comment]
Oh my, the same issue can be reproduced with a normal async read atom.
https://codesandbox.io/s/winter-bash-rp2rr?file=/src/App.js
I think this is a bigger issue and not fixed yet by 8a2c510.

**Comment by dai-shi** [comment]
> the same issue can be reproduced with a normal async read atom.

let me create a new issue.
