### ISSUE TITLE
[Docs] Improve `atomFamily` typings to be obvious to use

### ISSUE THREAD

**Issue by RIP21** [pmndrs/jotai#436]
As per https://github.com/pmndrs/jotai/discussions/433#discussion-3327022

It's not currently 100% correct how `atomFamily` typings are working now especially if you want to explicitly pass generic arguments to it.

For instance:
```ts
export const profitLossEngineAtom = atomFamily<
  ProfitLossFamilyInitialize,
  ProfitLossEngineState,
  SetStateAction<ProfitLossEngineState>
>(
  ({ id }) => {
    const anAtom = atom({ id, queries: {}, queryResult: {} });
    anAtom.onMount = (setAtom) => {
      setAtom({ id, queries: {}, queryResult: {} });
    };
    return anAtom;
  },
  (a, b) => a.id === b.id
);
```

If you pass third argument to be just `ProfitLossEngineState` it will break typings for all the setters that would like to use a callback like `setAtomState(it => ({ ...it, queries: { ... }}))`
It's a bit counterintuitive especially since it used to work just fine before.

To understand the problem better and get reproduces etc. read the discussion above.

**Comment by dai-shi** [comment]
This is due to #392, which was breaking improvement, so it's technically not compatible with the previous types.

How can we make it more intuitive?

The alternative would be `atomFamily<Param, AtomType>`.
In your use case, it would be this:
```ts
export const profitLossEngineAtom = atomFamily<
  ProfitLossFamilyInitialize,
  PrimitiveAtom<ProfitLossEngineState>
>(
```

**Comment by RIP21** [comment]
@dai-shi I guess a bit more examples would do. Also, a nice approach is to put some examples into `jsdoc` above the typings for different overloads this way it will be a bit cleaner for which overload is for which use case.
This way it will evolve with the implementation. Maybe there is even some sort of tool to run the code in rust docs examples as Rust has :) But I'm unsure about anything like that, just an idea maybe there is smth like that available :) 

You may also generate docs right from the `jsdoc` in this case making sure it's all 100% working.
Another option is to keep all examples real and up to date is to set up
https://codesandbox.io/docs/ci
I guess it can then make sure that all the examples will work just fine with a new version. But I'm not 100% sure if there are such capabilities :) Anyway, more docs that are running well with the latest versions would be a solution :)

**Comment by dai-shi** [comment]
Okay, let's improve the doc in TS or add a TS section in atomFamily section.
My primary recommendation is to infer types from `atom()`. And, there's the issue in `atom()` typing. Anyway, would be good to fix both.

**Comment by RIP21** [comment]
Regarding interactive docs.
https://www.npmjs.com/package/@typescript/twoslash
Maybe this thing may help make examples interactive and always up to date.

**Comment by dai-shi** [comment]
Thanks for sharing.
We actually start using sandpack in our new pmndrs docs website. Still work in progress.

**Comment by HosseinAgha** [comment]
This took so much time to figure out.  
IMO, the docs should at least warn people who are trying to explicitly type the `atomFamily`.

**Comment by dai-shi** [comment]
@HosseinAgha Thanks for chiming in. I will add some notes in docs.

**Comment by dai-shi** [comment]
@HosseinAgha Would you review this? https://github.com/pmndrs/website/pull/65

**Comment by HosseinAgha** [comment]
Sure. I'll start right away.

**Comment by dai-shi** [comment]
https://github.com/pmndrs/website/pull/65#issuecomment-830792790
