### ISSUE TITLE
Atom snapshot

### ISSUE THREAD

**Issue by DynamicArray** [pmndrs/jotai#439]
In a writeable atom, I want to use the value of another existing atom. However, if I access it with the "get" param, my atom gets updated each time from there on in, which I don't want.

Is it possible to access a one-time, read-only snapshot of another atom, without creating a dependency on it?

**Comment by dai-shi** [comment]
So, something like reverse "atomWithDefault". There could be some patterns for it depending on requirements.

Here's one of patterns with onMount.
```js
const fooAtom = atom('foo')
const barAtom = atom(null)
const initBarAtom = atom(null, (get, set) => set(barAtom, get(fooAtom)))
barAtom.onMount = (initBar) => { initBar(null) }
const yourWritableAtom = atom(
  (get) => {
    get(initBarAtom) // to initialize, hmmm, this is tricky.
    return get(barAtom)
  },
  (get, set, arg) => {
    // ...
  }
}
```

I guess it would be easier if useEffect is acceptable to initialize.

**Comment by DynamicArray** [comment]
Thank you for the quick reply.

I was hoping to avoid useEffect and the 2nd render that would produce.

This is an array of data with a semi-shared set of values. Where a particular array value has not been set directly, it uses the shared values. But an array value set directly, must not take the shared values.

Initially, the whole array was an atom, but now I'm playing with a version that has an array of atoms (similar to the ToDos example) and that looks like the way to go.

**Comment by DynamicArray** [comment]
However, it would still be great - at some point - to be able to access the latest version of an atom, without creating a hook dependency.

**Comment by DynamicArray** [comment]
>get in read comes with dependency, and get in write comes without it.
Therein lies my problem. I'm (lazily, I know) relying on the dependency of gets in a read to update another atom, but not wanting all of those gets to be dependencies.

>invoke the update function
Perhaps that's what I need to do instead: force an update and use that as my place to make these changes.

**Comment by dai-shi** [comment]
We don't have any plan to change the core api, but there should be workarounds (may need to be less lazy), so we could discuss more with concrete use cases.

Closing this. Feel free to continue discussion here or open a new discussion.
