### ISSUE TITLE
devTools for atomFamily

### ISSUE THREAD

**Issue by naivefun** [pmndrs/jotai#449]
now useAtomDevtools seems only accept atom as param. how to use atomFamily with devTools?

**Comment by dai-shi** [comment]
Yes, useAtomDevtools only accepts one atom.

We are working on a new feature. #338 @Thisen is taking the lead.

Meanwhile, you can try a catchAllAtom workaround https://github.com/pmndrs/jotai/issues/388#issuecomment-808983607, but it would be hard to catch all atoms in atomFamily.

**Comment by dai-shi** [comment]
I'm hoping https://github.com/pmndrs/jotai/issues/428 would resolve this issue.

There might be another way to use `useAtomsSnapshot` and Redux DevTools Extension. 🤔

**Comment by dai-shi** [comment]
#575 is slightly related.

Would anyone be interested in improving devtools?

**Comment by LuckyPigeon** [comment]
@dai-shi 
Here's my feature summary for `useAtomFamilyDevtools` :
  - [ ] Subscribe to `AtomFamily` and log it if got any change
  - [ ] Subscribe to each `Atom` created by `AtomFamily` and log it if got any change
Did I understand it right?

**Comment by dai-shi** [comment]
#807 may solve atomFamily+PrimitiveAtom use case.

**Comment by LuckyPigeon** [comment]
We can simply add this in docs

**Comment by dai-shi** [comment]
You mean `useAtomFamilyDevtools`? Well, #807 will not work for read-only atoms.
That said, we can revisit it after #808.

In this issue, let's focus on docs to explain how to use devtools for atomFamily. cc @Aslemammad

**Comment by dai-shi** [comment]
https://github.com/pmndrs/jotai/releases/tag/v1.5.0 has a new `useAtomsDevtools`.
We hope it covers atomFamily use case.
Let me close this. For questions, please open a new discussion.

**Comment by jelling** [comment]
For anyone coming across this, `useAtomFamilyDevtools` does not exist.
