### ISSUE TITLE
how to access the value on the default store for a given atom

### ISSUE THREAD

**Issue by zcaudate** [pmndrs/jotai#473]
After an atom is created, I'd like to access it's value for within the default store (using it like valtio)

Where is the value being stored and how can I get access to it without going through the react lifecycle?

**Comment by dai-shi** [comment]
It's based on React context actually, so the value is store in context somehow. The only way to get it is `useAtom`. This is important as an atom value is not truly global in JS memory. If you would like to bridge react world and outside react, `useEffect` is a primary mean. Alternatively, atom has `onMount` which helps. Practically, you could use `jotai/valtio` for your use case.

**Comment by zcaudate** [comment]
okay, that makes sense. I will still need valtio then.

thanks!

**Comment by sandren** [comment]
> After an atom is created, I'd like to access it's value for within the default store (using it like valtio)

Jotai's `atomWithProxy` can cover your use case. The docs for it can be found here: https://docs.pmnd.rs/jotai/integrations/valtio

**Comment by zcaudate** [comment]
yep, I'm using it here: https://github.com/zcaudate/js-blessed.store-test/blob/master/src/js/react/store.js#L66
