### ISSUE TITLE
Bad setState() call when use atomWithQuery

### ISSUE THREAD

**Issue by DavoBR** [pmndrs/jotai#476]
i am facing with this error using atom with query

![image](https://user-images.githubusercontent.com/498724/118175253-de250d00-b3fd-11eb-91bf-400a584866c2.png)

it can be reproduced using the original sample with jotai 0.16.4

https://codesandbox.io/s/jotai-query-demo-forked-i28ug?file=/package.json

**Comment by dai-shi** [comment]
Thanks for reporting.
I think this is the issue we are aware in tests with recent wip changes.
My investigation so far indicates this is DEV-only problem (useDebugState), so production won't have any issues (but we can't see the warnings anyway.)

Just a confirmation, v0.16.3 doesn't show this warning, does it?

**Comment by DavoBR** [comment]
> Thanks for reporting.
> I think this is the issue we are aware in tests with recent wip changes.
> My investigation so far indicates this is DEV-only problem (useDebugState), so production won't have any issues (but we can't see the warnings anyway.)
> 
> Just a confirmation, v0.16.3 doesn't show this warning, does it?

thanks for reply, i tested with 0.16.3 and 0.16.2 and i get the same warning, but with 0.16.1 the warning is not showing, in the meantime i will be using this version

**Comment by dai-shi** [comment]
> thanks for reply, i tested with 0.16.3 and 0.16.2 and i get the same warning, but with 0.16.1 the warning is not showing, in the meantime i will be using this version

Oh, I see. Thanks for confirming. I'll investigate how we can fix it.

**Comment by dai-shi** [comment]
@DavoBR When you got time, would you try #477 build?
https://ci.codesandbox.io/status/pmndrs/jotai/pr/477/builds/130326
```bash
yarn add https://pkg.csb.dev/pmndrs/jotai/commit/0e99e9d7/jotai
```

**Comment by dai-shi** [comment]
Just confirmed this is solved. https://codesandbox.io/s/jotai-query-demo-forked-6nhdb
