### ISSUE TITLE
Browser support (IE11 supported?)

### ISSUE THREAD

**Issue by bricejar** [pmndrs/jotai#48]
On which browsers will jotai work ?

Is IE11 supported ?

**Comment by dai-shi** [comment]
Good question. Jotai intensively uses `Map`, `WeakMap` and `Symbol`. IE11 seems to support those, so it's expected to work. Can you confirm?

To use the CJS build:
```js
import { Provider, atom, useAtom } from 'jotai/index.cjs.js'
```

**Comment by edgesoft** [comment]
@bricejar https://github.com/pmndrs/jotai/blob/master/src/Provider.ts#L35

Here Proxy is used and that is not supported by IE11. However there are polyfills but they are mostly not very stable.

**Comment by dai-shi** [comment]
@edgesoft Oh, you are right. If it's the only blocking issue, I can probably change it to object getters. Polyfills should work fine in this case of simple proxy getters.

**Comment by edgesoft** [comment]
@dai-shi Thanks! I don't think it will be an issue since is not used extensively.

**Comment by dai-shi** [comment]
Let me close this. Please reopen if you need further discussion.

The current understanding of IE11 support is: It should work with proxy-polyfill.

**Comment by dai-shi** [comment]
Now, #162 removed proxies, it no longer requires proxy-polyfill.

**Comment by dai-shi** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
According to this, Map(iterable), Map.keys() and Map.entries() are not supported in IE11. We use those now.

Does anyone have access to IE11?

**Comment by sandren** [comment]
Would supporting IE11 compromise the Jotai bundle size for modern browsers? If so, it's not worth it at this point. [Even Microsoft doesn't support IE11 anymore](https://www.theverge.com/2020/8/17/21372487/microsoft-internet-explorer-11-support-end-365-legacy-edge).

**Comment by Thisen** [comment]
I don't think we should stress about supporting IE11, we're also using symbols which isn't supported in IE11.

**Comment by dai-shi** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set
I also noticed Set(iterator) and similar, which are used a lot.

> compromise the Jotai bundle size for modern browsers

So, seems like so.

> also using symbols

Yeah, but this one is easy. `Symbol = () => ({})`

---
So, concluding this:
- We don't officially support IE11.
- Map/Set/Symbol are blocking
  - (If one could polyfill them well, it might work.)
