### ISSUE TITLE
Updating an atom outside of useAtom hook

### ISSUE THREAD

**Issue by verekia** [pmndrs/jotai#480]
I believe the answer is probably going to be similar to #454, but worth checking :)

I am trying to update an atom outside of a component. For instance that can be in a `handleClick` function that is outside of a component to be reused between multiple components.

```tsx
const handleClick = () => {
  setAtom(myAtom, 'value') // <-- I want to do something like that
}

const ButtonA = () => <button onClick={handleClick} />

const ButtonB = () => <button onClick={handleClick} />
```

Is there any way to do this? If not, could this become possible in the future, or is there any workaround? Thank you.

As a side note, it is not possible in [Recoil either](https://github.com/facebookexperimental/Recoil/issues/289).

**Comment by dai-shi** [comment]
How about this?

```jsx
import { useUpdateAtom } from 'jotai/utils'

const useHandleClick = () => {
  const setAtom = useUpdateAtom(myAtom)
  return () => setAtom('value')
}

const ButtonA = () => <button onClick={useHandleClick()} />

const ButtonB = () => <button onClick={useHandleClick()} />
```

The fact is there's no such global thing. Atom values reside inside React. `myAtom` is just a config (atom definition). You can't determine which atom value you are updating, if you are outside React.

**Comment by dai-shi** [comment]
A workaround would be to use module state. We have two-way bindings. And, we have three options: `jotai/valtio`, `jotai/zustand`, and `jotai/redux`. (Hoping this comment doesn't confuse you.)

But, for your use case described in the first comment, it's not recommended.

**Comment by verekia** [comment]
Thank you for your quick answer!

I've got your example working in a [CodeSandbox](https://codesandbox.io/s/clever-darwin-buym0?file=/src/App.js).
It took me so long to (kind of) understand what's going on haha.

Isn't it against the rules of hook to execute the hook in the render function of the buttons ? (`onClick={useHandleClick()}`)

In the example it works, but in my app I am getting `Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.`, probably because I am conditionally rendering that button, and that hooks don't like kind of logic.

I'm impressed by the workaround, but it is probably a bit too tricky to use all over a codebase with peace of mind 😅.

**Comment by dai-shi** [comment]
It's just a shorthand for this:
```jsx
const ButtonA = () => {
  const handleClick = useHandleClick()
  return <button onClick={handleClick} />
}
```

So, nothing wrong.

Are you calling the function like `ButtonA()`, instead rendering like `<ButtonA />`?

Yeah, I agree to avoid too tricky things.

**Comment by verekia** [comment]
Good point, thank you for the explanation.
My codebase is not at a point where I can easily go back to test the issue in Jotai. I've switched to Zustand with no commit in between. We can close the issue, thank you very much for the quick answers :)
