### ISSUE TITLE
Code not compiled to ES5 after build

### ISSUE THREAD

**Issue by J-env** [pmndrs/jotai#497]
Code not compiled to ES5 after build.

I am using **next.js**.

There are arrow function const and for of statements in the code.
I compared the codes of other files, and there is no such situation.

// jotai lib
![image](https://user-images.githubusercontent.com/25259920/119617279-40d1cc00-be34-11eb-87af-16f6e6f3300e.png)

// other lib
![image](https://user-images.githubusercontent.com/25259920/119617647-9f974580-be34-11eb-82a5-98ee3e620208.png)

**Comment by Thisen** [comment]
Jotai uses [package exports](https://webpack.js.org/guides/package-exports/) in package.json, which makes it clear to bundlers like Webpack and Rollup what source code it can bundle. I assume you're using Chrome from the screenshots and Next.js knows it's serving the code to a modern browser, therefore it can utilize modern JS features.

Are you having any issues?

**Comment by J-env** [comment]
> Jotai uses [package exports](https://webpack.js.org/guides/package-exports/) in package.json, which makes it clear to bundlers like Webpack and Rollup what source code it can bundle. I assume you're using Chrome from the screenshots and Next.js knows it's serving the code to a modern browser, therefore it can utilize modern JS features.
> 
> Are you having any issues?

I set up browserslist. 

```
"browserslist": [
    ">15%",
    "last 12 versions",
    "Firefox ESR",
    "not ie < 10"
  ]
```

Compilation of other libraries is normal. It's weird.
I want to compile jotai into es5.

**Comment by Thisen** [comment]
I believe Next.js detects what browser you are in and serves code that can run in that browser. I advice you to try out your app in IE11.

**Comment by J-env** [comment]
> I believe Next.js detects what browser you are in and serves code that can run in that browser. I advice you to try out your app in IE11.

I have debugged. Syntax error, es6 cannot be recognized.
Mainly other libraries are normal.

![image](https://user-images.githubusercontent.com/25259920/119630403-81841200-be41-11eb-863e-f96fb3edc44a.png)
![image](https://user-images.githubusercontent.com/25259920/119630435-8648c600-be41-11eb-8fbf-db2b6767522e.png)

**Comment by Thisen** [comment]
What version of Node are you using?
What version of Next.js are you using?

**Comment by J-env** [comment]
> What version of Node are you using?
> What version of Next.js are you using?

```
"engines": {
    "node": ">=12.16.2",
    "npm": ">=6.14.4",
    "next": "^10.2.3"
  }
```

**Comment by Thisen** [comment]
Please try out the latest LTS of Node (I think it's 14.17.0) - If this doesn't solve your issue, please provide a Github repo with a reproduction.

**Comment by dai-shi** [comment]
@J-env 

> I want to compile jotai into es5.

jotai provides two bundles: commonjs in es5 for old browsers and module js for modern browsers.
nextjs would have used cjs before, but if not, you need to transpile module code into es5 by yourself.
See: https://github.com/pmndrs/jotai/issues/265#issuecomment-799784574

**Comment by J-env** [comment]
Thanks. Already resolved.

**Comment by Thisen** [comment]
Closed, since resolved.
