### ISSUE TITLE
jotai.surge.sh broken on safari?

### ISSUE THREAD

**Issue by stfnsr** [pmndrs/jotai#51]
I'm under the impression that the website is broken on Safari, at least with iOS 14 and macOS Safari 14.
I am not able to enter text in the input field - in iOS the keyboard pops up, but typing doesn't have any effect.
On Desktop, the field seems selected, but i get no cursor, and typing has no effect.

This seems to be caused by " * {user-select: none;}".
(On a related note, i also found it very irritating to be unable to select input text, especially when trying to paste stuff instead of typing on mobile)

**Comment by dai-shi** [comment]
Thanks for reporting. Confirmed the issue on Safari 13.
The examples in master branch is already fixed. Probably by #21 
We just need to re-deoploy it. cc: @drcmda

**Comment by dai-shi** [comment]
@stfnsr sorry for the delay. it's fixed now.
