### ISSUE TITLE
Facing an error with splitAtom version of todos example

### ISSUE THREAD

**Issue by tell-y** [pmndrs/jotai#510]
Hi,
I tried to use splitAtom() to learn it with the todos example.
Then I'm facing an error with a specific operation.

Representation code:
https://codesandbox.io/s/todos-splitatom-sample-ts-jh9mz

The specific operation:
https://user-images.githubusercontent.com/6883692/121356500-dd838600-c96b-11eb-9a09-b75caab9318c.mov

Maybe it's a bug so I just report It.
Thanks.

**Comment by dai-shi** [comment]
> We need to handle removing items from upstream (arrAtom).

This is already handled. So, the bug seems to be caused by a subtle timing issue. @Aslemammad is investigating it.
