### ISSUE TITLE
How to allow partial objects when updating

### ISSUE THREAD

**Issue by nahtnam** [pmndrs/jotai#52]
Hey,

I have an atom like this:

```
const test = atom({
  one: 'foo',
  two: 'bar',
  cache: {}
});
```

In my code I want to do the following:

```
setTest({
  cache: {
    test: true,
  },
});
```

Is this supported? Currently, you have to spread `...test` inside of the `setTest`, however, this does not deep merge all objects inside of `cache`

**Comment by dai-shi** [comment]
The core library doesn't support it directly. So, either you spread it (1) or use immer. See #11 for immer patterns. We may plan to add immer related helpers in another bundle.

(1)
```js
setTest(prev => ({
  ...prev,
  cache: {
    ...prev.cache,
    test: true,
  },
})
```

**Comment by dai-shi** [comment]
There is another issue #32

**Comment by nahtnam** [comment]
Thanks, this is perfect!
