### ISSUE TITLE
Can't get an async atom with default value in writable atom when update

### ISSUE THREAD

**Issue by SquirrelJimmy** [pmndrs/jotai#522]
I have some useages:
```ts
const read = atom(async (get) => {
   return await fetch(somethins)
})

const write = atom(null, (get, set, update) => {
  const something = get(read);
  // dosomething...
})
```
if `read` did't mounted when I used, it throw a error `Promise<pendding>`, if `read` had mounted, it's ok

**Comment by SquirrelJimmy** [comment]
`atomWithDefault` has same issue

**Comment by dai-shi** [comment]
Thanks for opening this.

I'm aware of this.

https://github.com/pmndrs/jotai/blob/00aaaf7678c68b7976d5bbd54ed639a6b57c763b/src/core/vanilla.ts#L411-L421

But, I'm note sure what we should do.
For now, it throws a promise, and you can catch it and retry.
This doesn't seem ideal. So, I decided to collect some feedback.

This is going to take some time, and your idea is welcomed.

----

In the mean time, you could try storing a promise value in the first atom, if it doesn't depend on other atoms.

**Comment by SquirrelJimmy** [comment]
> Thanks for opening this.
> 
> I'm aware of this.
> 
> https://github.com/pmndrs/jotai/blob/00aaaf7678c68b7976d5bbd54ed639a6b57c763b/src/core/vanilla.ts#L411-L421
> 
> But, I'm note sure what we should do.
> For now, it throws a promise, and you can catch it and retry.
> This doesn't seem ideal. So, I decided to collect some feedback.
> 
> This is going to take some time, and your idea is welcomed.
> 
> In the mean time, you could try storing a promise value in the first atom, if it doesn't depend on other atoms.

Thanks so much! Em... I will try it by storing a promise value, if you have some perfect idea, I will upgrade jotai

**Comment by dai-shi** [comment]
Please try #539 if it works for you.
https://ci.codesandbox.io/status/pmndrs/jotai/pr/539 has "Local install instruction" so that you can install with npm/yarn.

```ts
const read = atom(async (get) => {
   return await fetch(somethins)
})

const write = atom(null, async (get, set, update) => {
  const something = await get(read, true);
  // dosomething...
})
```

**Comment by SquirrelJimmy** [comment]
> Please try #539 if it works for you.
> https://ci.codesandbox.io/status/pmndrs/jotai/pr/539 has "Local install instruction" so that you can install with npm/yarn.
> 
> ```ts
> const read = atom(async (get) => {
>    return await fetch(somethins)
> })
> 
> const write = atom(null, async (get, set, update) => {
>   const something = await get(read, true);
>   // dosomething...
> })
> ```

Thank you ! it's what I need now !
