### ISSUE TITLE
useMount doesn't execute the unmount function when value updated

### ISSUE THREAD

**Issue by vasilenka** [pmndrs/jotai#538]
I'm trying to track when a value of an atom unmounted

From this snippet, I am expecting to see 'unmounting' logged on the console when I start typing on the input field, but there's nothing logged on the console

```javascript
import React from 'react';
import { useAtom, atom } from "jotai";

const queryAtom = atom("")
queryAtom.onMount = () => {
  return () => {
    console.log("unmounting")
  }
}

export default function App() {

  const [query, setQuery] = useAtom(queryAtom);

  return (
      <input
        type="text"
        value={query}
        onChange={(e) => setQuery(e.currentTarget.value)}
      />
  );
}

```

Does there's no re-render happened on the App, so no un-mount happened?

The weird thing is, It's working just fine a few days ago
So I am not sure what's happening here

Here's a sandbox link: https://codesandbox.io/s/dry-sky-3sigp?file=/src/App.js

**Comment by dai-shi** [comment]
Conceptually, mounting atom happen if  the atom is used with `useAtom` for the first time, unmounting is all `useAtom`s are no longer used.

So, with you code snippet, not showing "unmounting" is expected.

**Comment by vasilenka** [comment]
I see...
My mistake there for thinking it's the equivalent of useEffect

Thank you for clarifying!
