### ISSUE TITLE
Allow reducer updates to be optional

### ISSUE THREAD

**Issue by dwelle** [pmndrs/jotai#54]
The `dispatch` function of reducer atoms should support optional updates if the reducer defines the update as optional.

To detect this, Jotai could use the same pattern that React's `useReducer` does:

```ts
type ReducerWithoutAction<V> = (value: V) => V;
const reducerWithOptionalAction: ReducerWithoutAction<number> = (value, action?: boolean) => v;
```

Use case:

```ts
const sidebarAtom = atomWithReducer(true, (prev, update?: boolean) => {
	return update == null ? !prev : update
});

export default function App() {
	const [isSidebarVisible, toggleSidebar] = useAtom(sidebarAtom);

	return <button onClick={() => toggleSidebar()}>toggle</button>;
}
```

**Comment by dwelle** [comment]
sidenote: why wrap the types in tuples?

https://github.com/pmndrs/jotai/blob/af47162797d434835a5cd790874cbe1cee5f6f5f/src/useAtom.ts#L18-L20

**Comment by dai-shi** [comment]
> sidenote: why wrap the types in tuples?

Otherwise, it doesn't work. https://github.com/microsoft/TypeScript/issues/23182#issuecomment-379091887

**Comment by dai-shi** [comment]
Can you confirm if #55 solves your use case?
