### ISSUE TITLE
useResetAtom does not work on atomWithDefault

### ISSUE THREAD

**Issue by ahfarmer** [pmndrs/jotai#549]
`atomWithDefault` can be reset by sending the `REFRESH` symbol.
`atomWithReset` can be reset by sending the `RESET` symbol or with `useResetAtom`.

`useResetAtom` does not work on `atomWithDefault`.

Should we get rid of the `REFRESH` symbol, and instead use the `RESET` symbol everywhere including `atomWithDefault`? Then `useResetAtom` would work on `atomWithDefault`.

**Comment by dai-shi** [comment]
Yeah, I originally thought about using the same symbol. And, then thought it might be confusing.
Now, it sounds good to have a common hook. Though breaking, should we quickly release a new patch version, deprecating the previous one?

@LucaColonnello any comments?

**Comment by ahfarmer** [comment]
Wanted to throw out another idea: deprecate `atomWithReset` and make `atomWithDefault` able to take either `initalValue` or `() => initialValue`. Then it serves both purposes.

I think the concept of a dynamic default and resettability go hand-in-hand, so it makes sense to me that these should just be the same atom util.

**Comment by dai-shi** [comment]
API-wise, it's possible. However, implementation-wise, atomWithReset is only one atom internally, whereas atomWithDefault comes with two atoms. In other words, atomWtihReset can be more performance tuned.

**Comment by LucaColonnello** [comment]
Hey @dai-shi ,
Just reading this now!

Yeaah yesterday, even writing the docs, it felt weird having to explain REFRESH as a different thing than RESET. Also I'm implementing this in an app and it does not look great having to import the REFRESH const when you could have something like the useResetAtom do it for you.

I think a patch would be alright if we just released it yesterday!

**Comment by dai-shi** [comment]
Thanks for the comment. Just opened a PR #552.
