### ISSUE TITLE
atomFamily missing Typescript types for function setter

### ISSUE THREAD

**Issue by ahfarmer** [pmndrs/jotai#551]
With regular atoms, we can have function setters. It works great and the Typescript types are working:

```typescript
const updateAtom = useUpdateAtom(atomConfig)
...
updateAtom(prevValue => !prevValue);
```

The same functionality works with atomFamily, but the Typescript types for the function setter seem to be missing and we  get "Argument of type () => ... is not assignable to parameter of type ...". Here's a full example:

```typescript
import { atom, PrimitiveAtom } from "jotai";
import { atomFamily, useAtomValue, useUpdateAtom } from "jotai/utils";
import { useCallback } from "react";

const myAtomFamily = atomFamily<string, boolean | null, boolean | null>(
  () => atom<boolean | null>(false)
);

export default function App() {
  const atomValue = useAtomValue(myAtomFamily("meow"));
  const updateAtom = useUpdateAtom(myAtomFamily("meow"));

  const toggle = useCallback(() => {
    updateAtom((x) => !x);
  }, [updateAtom]);

  return (
    <div className="App">
      <button onClick={toggle}>Toggle</button>
      <p>Is on?: {atomValue ? "YES" : "NO"}</p>
    </div>
  );
}
```

Here's a screenshot of the TypeScript error:
![Screen Shot 2021-06-23 at 3 26 29 PM](https://user-images.githubusercontent.com/597825/123175882-63590400-d437-11eb-94e7-87a48ae0419c.png)

**Comment by dai-shi** [comment]
Does it work if you inter types?
```ts
const myAtomFamily = atomFamily(
  () => atom<boolean | null>(null) as PrimitiveAtom<boolean | null>
);
```

There must be a better typing along with #550. 🤔

**Comment by ahfarmer** [comment]
No, it doesn't work if I infer types. I edited my original post above to remove that type cast.

**Comment by dai-shi** [comment]
Is this issue only for non strict mode? Can you repro with strictNullChecks=true?

**Comment by ahfarmer** [comment]
This issue doesn't seem to be related to strictNullChecks=true.

Here is a self-contained repro, just run `yarn install` and then `yarn typecheck`. You can check the tsconfig has `"strictNullChecks": true`

[jotts-mini.zip](https://github.com/pmndrs/jotai/files/6710882/jotts-mini.zip)

**Comment by dai-shi** [comment]
@ahfarmer Thanks for the repro!

Here is the fix:

```ts
const myAtomFamily = atomFamily(() =>
  atom<boolean>(false)
);
```

Please give it a try.

If you want to explicitly annotate it. Try this:

```ts
const myAtomFamily = atomFamily<string, boolean, SetStateAction<boolean>>(() =  >
  atom<boolean>(false)                                                        
);                                                                            
```

**Comment by ahfarmer** [comment]
Ahhh, wonderful. Thank you! I'll go ahead and close this then.
