### ISSUE TITLE
Question: Optics-ts & focusAtom & useResetAtom

### ISSUE THREAD

**Issue by mostl33** [pmndrs/jotai#559]
Hi there,

first thanks to the Author(s) & contributors of Jotai 🙏.

I have a "best practice" Question :-).

If have a large state Object tree (imagine a page-by-page wizard style form app where different screens need access to the data entered in previous screens for calculation of sums etc.) which needs to be serializable (continue where you left off) and each screen of the wizard should have a "reset form" (only on the current page!) functionality.

Currently I am using optics-ts with jotai's "focusAtom" which works so far. Is there a good way to combine "atomWithReset/useResetAtom" and "focusAtom"? Or is there a better way to achieve the same kind of functionality (large state tree, use subtree, easy reset to initial values).

Thanks & best regards,

Jason

**Comment by dai-shi** [comment]
Hi, "best practice" in something very important for the community.
Hope everyone works on various things and create practices.

Combining atomWithReset and focusAtom would be possible for the root object (= entire tree).
But, doing so for sub trees would not be trivial. The implementation of atomWithReset is simple, so you might get some idea. atomWithDefault might be closer.

In summary, this is new field, so go ahead and keep up with it. Have fun. Create best practices.

That said, if you have a specific challenge, I'm happy to help. Maybe other people would be too. Please provide a small puzzle to solve.

**Comment by dai-shi** [comment]
While this can be seen as a doc issue, let me close this as it's not something small to solve. Please feel free to continue discussion here or open a new [discussion](https://github.com/pmndrs/jotai/discussions/new).
