### ISSUE TITLE
Question: Atom inside Atom

### ISSUE THREAD

**Issue by yoyeung** [pmndrs/jotai#563]
I was learning the tools and i try to reproduce the todo list app from to ToDo Example.
[https://codesandbox.io/s/elated-pond-2x95k?file=/src/App.js](https://codesandbox.io/s/elated-pond-2x95k?file=/src/App.js)

Here is the sample. 
I have a task list which is an array. And each task when create will become an atom and push it inside the list.
So that will become an Atom in side an atom array.

But for this case I implement a function to use a filter to remove the item by id.
Each item in the list is an atom. i cannot easily to access the attribute like id or detail.

Is there any way to get the atom info in useAtom update function?

For my current solution, I create another atom and use the write function as a kind of reducer to update the task list.
is the right way to handle it?

Thanks~

**Comment by dai-shi** [comment]
Yes, it looks like right solution. 👍

**Comment by yoyeung** [comment]
Should i use Atom.init to get the value? will have side effect?

**Comment by dai-shi** [comment]
No, `atom.init` should be an implementation deail, and you don't want to use it directly.

Sorry if I don't get your question correctly. Will you note your concern again?

**Comment by yoyeung** [comment]
i was thinking can we use the tools look like same as useState.
Maybe the difficulty when the atom inside the atom will happen.

create another atom to handle some modification for another atom is it a good idea?
It will become many atom with null value or get value from another atom.
So that mean if the application go bigger.
Will have a ton of customAtom as a reducer for another atom.

Not sure is it a good idea. Just want to share mine though.

```javascript
const customTaskAtom = atom(null, (get, set, action) => {
  if (action.type === "remove") {
    set(
      taskAtom,
      get(taskAtom).filter((task) => {
        return get(task).id !== action.id;
      })
    );
  }
});
```
vs
```javascript
const customTaskAtom = atom([], (value, get, set, action) => {
  if (action.type === "remove") {
      return value.filter((task) => {
        return get(task).id !== action.id;
      })
  }
});
```

**Comment by dai-shi** [comment]
`atomWithReducer` helps but not for atoms-in-atom scenario.
We might be able to expose `get` for the third argument. But, I'm afraid it's too confusing.

> Will have a ton of customAtom as a reducer for another atom.

That's also true for non atoms-in-atom scenario.

I'd expect you to create a wrapper function to organize atoms.

```js
const createAtom = (initialValue, reducer) => {
  const baseAtom = atom(initialValue)
  const derivedAtom = atom(
    (get) => get(baseAtom),
    (get, set, action) => set(baseAtom, reducer(get(baseAtom), get, set, action)),
  )
  return derivedAtom
}
```
