### ISSUE TITLE
useAtomsSnapshot ignores initialValues atoms

### ISSUE THREAD

**Issue by xbaun** [pmndrs/jotai#565]
The `useAtomsSnapshot` hook doesn't contain atoms from the `initialValues` of the `Provider` context. This could be solved by calling the state listener in [`createStoreForDevelopment()`](https://github.com/pmndrs/jotai/blob/cb418e3617e5601ea0de70f87318ac666e11721e/src/core/contexts.ts#L52-L92) after initializing the store:

```ts
  initialValues?.forEach(([atom]) => {
    stateListener(atom, true);
  })
```

I'm trying to debug the rehydrated initial atom states created by SSR and this would be really helpful.

**Comment by dai-shi** [comment]
Oh, nice catch.

This would be a fix:
```diff
diff --git a/src/core/contexts.ts b/src/core/contexts.ts
index 8585801..7f8c3fc 100644
--- a/src/core/contexts.ts
+++ b/src/core/contexts.ts
@@ -72,7 +72,7 @@ const createStoreForDevelopment = (
   ) => writeAtom(state, atom, update)
   const debugStore = {
     version: 0,
-    atoms: [] as Atom<unknown>[],
+    atoms: Array.from(initialValues || []).map(([a]) => a),
     state,
     listeners: new Set<() => void>(),
   }
```

@Thisen Can you confirm and fix?

**Comment by Thisen** [comment]
> Oh, nice catch.
> 
> This would be a fix:
> 
> ```diff
> diff --git a/src/core/contexts.ts b/src/core/contexts.ts
> index 8585801..7f8c3fc 100644
> --- a/src/core/contexts.ts
> +++ b/src/core/contexts.ts
> @@ -72,7 +72,7 @@ const createStoreForDevelopment = (
>    ) => writeAtom(state, atom, update)
>    const debugStore = {
>      version: 0,
> -    atoms: [] as Atom<unknown>[],
> +    atoms: Array.from(initialValues || []).map(([a]) => a),
>      state,
>      listeners: new Set<() => void>(),
>    }
> ```
> 
> @Thisen Can you confirm and fix?

Yup
