### ISSUE TITLE
Initialize atom with parameters and derived atoms

### ISSUE THREAD

**Issue by SandroMaglione** [pmndrs/jotai#576]
Hi,

I stumbled upon this usecase many times and I did not find a proper solution yet.

I am trying to initialize an atom with some extra parameters. For example, I get a list of `string` as props (using `getServerSideProps` of NextJs) and I want to initialize an atom from the list of `string`.
I tried to use `atomFamily`, for example:
```ts
const listAtom = atomFamily((listOfString: string[]) => /* Return atom */); 
const Page = (listOfString: string[]): ReactElement => {
  const [list, setList] = useAtom(listAtom(listOfString));
}
```
The problem then becomes creating derived atoms from the `listAtom`. I would like to access `listAtom` inside another atom, but I am required to specify every time the parameter.
```ts
const derived = atom((get) => get(listAtom) /* <- ERROR, missing parameter! */);
```

Is there another solution? Am I missing something?

**Comment by aulneau** [comment]
Hi there!

This is something I run into a lot and I can give how I typically deal with it.

First, we create an atom family that takes some unique key. I typically have a helper method to create a key based on params, such as the page and specific type of data this atom is meant for:

```ts
// create an atom family for "initial data"
const initialDataAtom = atomFamily((dataKey: string) => atom(null))
```

then in our next.js page, fetch data as usual:


```tsx
// in our page
export async function getServerSideProps(ctx: NextPageContext){
  const listOfStrings = await getMyListOfStrings();
  return {
    props : {
      listOfStrings
    }
  }
}
```
And in the same page, we want to use the `<Provider>` exported by jotai to set the initial value of our `initialDataAtom`, as such:
```tsx
// the next.js page component

const MyPage: NextPage = ({listOfStrings}) => {
  return <Provider initialValues={[
    [initialDataAtom(`my-unique-key`), listOfStrings] as const // we will set the initial value for our atom
  ]}>
    <OtherComponents />
  </Provider>
}
```
And now we can use it anywhere (that is a child of the provider)
```tsx
const derived = atom((get) => get(initialDataAtom(`my-unique-key`))); // now we have access to the data

const OtherComponents = () => {
  const listOfStrings = useAtomValue(initialDataAtom('my-unique-key'));
  const derivedValue = useAtomValue(derived);
}
```

**Comment by dai-shi** [comment]
Another approach would be to create an atom in components.
```jsx
const Component = ({ foo }) => {
  const fooAtom = useRef(atom(foo)).current // useRef to get stable reference
  // ...
}
```
This alone doesn't seem very useful, but if we share `fooAtom` with other components, they can use it.
There are several options for this.
1. prop passing
2. useContext
3. atoms in atom https://docs.pmnd.rs/jotai/guides/atoms-in-atom

They are a bit technical, so I won't deep dive now.
`atomFamily` is handy with global cache. One caveat is if you don't remove unused atoms from the cache, it will lead memory leaks.

**Comment by dai-shi** [comment]
> For example, I get a list of `string` as props (using `getServerSideProps` of NextJs)

@SandroMaglione For SSR, please try new `useHydrateAtoms` which may or may not cover your use case.

Let me close this as stale for now, and if anyone find bugs / questions, open new issues / discussions.
