### ISSUE TITLE
Docs CodeSandBox: Give explicit type to atom when used with useUpdateAtom

### ISSUE THREAD

**Issue by PuruVJ** [pmndrs/jotai#578]
In this CodeSandBox about useUpdateAtom, the setCount function has a TypeScript error, which arises due to TypeScript making a literal type from the `0` provided in the `atom(0)`. 
![image](https://user-images.githubusercontent.com/47742487/124551696-2ab22500-de50-11eb-8348-14fed1731efd.png)

I am not sure if this type of inference for numbers is by design or a bug in TypeScript.

But having this error in a Docs Sandbox can make the first time onlooker feel like this isn't ready, so I suggest the `atom(0)` be converted to `atom<number>(0)`

The final code is:

```tsx
import * as React from "react";
import { useRef } from "react";
import "./styles.css";
import { Provider, atom, useAtom } from "jotai";
import { useUpdateAtom } from "jotai/utils";

const countAtom = atom(0);

const Counter = () => {
  const [count] = useAtom(countAtom);
  return (
    <div>
      count: {count}
      (rendered: {++useRef(0).current})
    </div>
  );
};

const Controls = () => {
  const setCount = useUpdateAtom(countAtom);
  const inc = () => setCount((c) => c + 1);
  return (
    <div>
      <button onClick={inc}>+1</button>
      (rendered: {++useRef(0).current})
    </div>
  );
};

export default function App() {
  return (
    <Provider>
      <div className="App">
        <h1>Hello CodeSandbox</h1>
        <h2>Start editing to see some magic happen!</h2>
        <Counter />
        <Controls />
      </div>
    </Provider>
  );
}

```

**Comment by dai-shi** [comment]
Hm, `atom(0)` should be inferred as `number` primitive atom. If not, we should find the problem. I don't think it's a doc issue.

I bet you are not using `strict: true` (related #550)... hmmmm, can't repro.

https://codesandbox.io/s/relaxed-ramanujan-skuvd?file=/src/App.tsx is working. Would you try this?

**Comment by PuruVJ** [comment]
This is strange. The link you sent, there I'm getting no error.

But then I go to the sanbox linked under useUpdateAtom, open it in codesandbox URL, and it shows me this error again. I made no changes at all, this is how it is by default 

![image](https://user-images.githubusercontent.com/47742487/124561945-13793480-de5c-11eb-9dca-94a7ed0d1b36.png)

This the url https://codesandbox.io/s/react-typescript-forked-3q11k?from-embed

**Comment by dai-shi** [comment]
If you use the latest version (v1.1.2), it works.
We should update doc codesandboxes.

**Comment by PuruVJ** [comment]
Yeah, updating Jotai in Sandbox fixed it, the ones in docs have a weird version like cs:[hash] or something, had to click on Update deps button to fix

**Comment by dai-shi** [comment]
So, it was sort of a doc issue. Thanks for reporting!
