### ISSUE TITLE
selectAtom and shapeAtom should be the same, but aren't?

### ISSUE THREAD

**Issue by a6h-s** [pmndrs/jotai#579]
I've been playing with Jotai today for the first time. I found something I'm a bit confused about. 

In [this](https://codesandbox.io/s/reactsvgjotai4-s6u7n?file=/src/SvgShape.tsx) file, `selectAtom` isn't actually returning the same value as `shapeAtom` when it should be...?

I added this useEffect to that component: 

```
React.useEffect(() => {
    console.log(selected);
    console.log(shape);
});
```

And this is what I'm seeing in the console: 
![image](https://user-images.githubusercontent.com/26363886/124599948-85567b80-de66-11eb-86ad-dc44c0c84436.png)

I'm building a similar app, and stumbled upon this issue. Shouldn't these values be the same?

**Comment by dai-shi** [comment]
This is a unique coding pattern in jotai, called atom-in-atom.
`selectAtom` here (not to confuse with the one in `jotai/utils`) holds the atom config of `shapeAtom`, not the atom value of `shapeAtom`.

So, what you observed is correct.

See this for more info: https://docs.pmnd.rs/jotai/guides/atoms-in-atom

And, I agree this pattern is confusing. I'd say it's not for beginners, but this pattern is very powerful thanks to jotai's impl with weak maps (JS garbage collection).

**Comment by dai-shi** [comment]
Let me close this as answered. Feel free to continue discussions here.
