### ISSUE TITLE
When using the type "null" on a atom, the TypeScript understand that I want to use the "read" property instead of "initialValue"

### ISSUE THREAD

**Issue by italodeandra** [pmndrs/jotai#59]
But using `undefined` I get the right type `initialValue`.

That could be because `null` is an object and an object is a function. So the `NonFunction` helper mistakes null with a function.

![image](https://user-images.githubusercontent.com/19225266/93760669-c8fc3380-fc0c-11ea-9303-4fb4df751106.png)
![image](https://user-images.githubusercontent.com/19225266/93760733-e3cea800-fc0c-11ea-9e74-758d300a9ffe.png)

**Comment by dai-shi** [comment]
@italodeandra I assume you are not on the latest (v0.7.0) which no longer has `NonFunction`. cf. #53 
Can you confirm please?

**Comment by italodeandra** [comment]
I can confirm that it was outdated. I updated to latest (v0.7.0) but it's still the same typing.
Perhaps it's another reason?

I know that doesn't break anything. Now I'm just wondering if you consider that problem.

**Comment by dai-shi** [comment]
As we claim TypeScript friendliness, TS typing issue can be considered a problem.

https://codesandbox.io/s/fragrant-pine-wiggi?file=/src/App.tsx
I tried this, but can't reproduce the weird behavior. Is it only with the editor?

I'd appreciate if you could dig this in deep.

**Comment by italodeandra** [comment]
Hi @dai-shi,

It could be indeed my IDE's fault. I can't dig any deeper because it doesn't affect the code really. Is just how my IDE shows which property he thinks I'm filling there, if it is **initialValue** or **read** function.

I'm closing this for now but I'll keep an eye for this and will update here if I get to see anything. Now that I know the "TypeScript friendliness" we're aiming for I'll be happy to give any new insights.

Thank you for your amazing work.
