### ISSUE TITLE
benchmark utils like waitForAll

### ISSUE THREAD

**Issue by aulneau** [pmndrs/jotai#590]
In one of the apps I work on, I determined a performance drain coming from the use of `waitForAll`, I'd be curious to determine a way that we can test the performance of this helper and see how it performs when there are many atoms both in the waitForAll call, and many atoms that depend on this atom

**Comment by dai-shi** [comment]
Good catch. One thing I'm curious is if this is like a linear performance drop to the size of atoms. Or, more like infinite-like loop that could happen with fewer atoms.

**Comment by dai-shi** [comment]
cc @Thisen

**Comment by dai-shi** [comment]
This is not very actionable. If this is "very" slow type of issue, we need a repro. If it's a hypothetical concern, feel free to try benchmarking it.

**Comment by aulneau** [comment]
> This is not very actionable. If this is "very" slow type of issue, we need a repro. If it's a hypothetical concern, feel free to try benchmarking it.

Yeah -- I agree. It's a hard problem, as it was found to create issues in a larger, more complex app with many async atoms. It would take some time to properly reproduce the issue. Feel free to close if you prefer.

**Comment by dai-shi** [comment]
#663 might solve this. Let me close this for now.

(benchmark tools would be nice anyways, not only for waitForAll, but also for others. let's open a new issue when we work. ref #486)
