### ISSUE TITLE
AtomWithReset initial value overriden on useRestAtom call

### ISSUE THREAD

**Issue by Gungrave223** [pmndrs/jotai#591]
Not entirely sure if this is a bug or just lack in my understanding of how it's suppose to work...

Essentially the issue I'm running into is that I have a list of checkbox that's controlled by the values in the useResetAtom.

If I update the value of of the check box then call reset....the default value because the value of the first checkbox....

I create a [sandbox](https://codesandbox.io/s/jotai-userestatombug-bniwz?file=/src/App.js:380-392) to replicate the issue

To replicate....check a user....then check and uncheck `select all`... on uncheck of `select all` useResetAtom is call ... so no checkbox should be checked...however, the first box that was check remains checked.

**Comment by dai-shi** [comment]
The problem is the unexpected mutation of the atom value. Here's the fix.
```diff
-       selectedUsers.push(target.value);
+       selectedUsers = [...selectedUsers, target.value];
```

https://codesandbox.io/s/jotai-userestatombug-forked-dllkd?file=/src/App.js:1100-1156

**Comment by Gungrave223** [comment]
Gotcha... I see the issue... thanks for the quick response.
