### ISSUE TITLE
Once I import atomWithStorage I get 2 weird TS errors

### ISSUE THREAD

**Issue by 205g0** [pmndrs/jotai#604]
When adding `import { atomWithStorage } from 'jotai/utils'` (even with keeping it unused) I get this...

```
../../node_modules/.pnpm/jotai@1.2.1_react@17.0.2/node_modules/jotai/utils/atomWithObservable.d.ts(13,5): error TS1170: A computed property name in a type literal must refer to an expression whose type is a literal type or a 'unique symbol' type.
../../node_modules/.pnpm/jotai@1.2.1_react@17.0.2/node_modules/jotai/utils/atomWithObservable.d.ts(13,13): error TS2339: Property 'observable' does not exist on type 'SymbolConstructor'.
```

**Comment by dai-shi** [comment]
Thanks for reporting. I didn't realize this issue. Looks like it's using a type from redux in dev dependencies. Let me create a PR for a possible fix.

**Comment by dai-shi** [comment]
Please try #605, see the "Local install instructions" in the codesandbox build.
https://ci.codesandbox.io/status/pmndrs/jotai/pr/605

**Comment by 205g0** [comment]
Works like a charm, this atomWithStorage is btw my favorite feature, so buttersmooth haha 🙃

Thanks for your awesome work!
