### ISSUE TITLE
[Next.js] Error using useUpdateAtom

### ISSUE THREAD

**Issue by lishine** [pmndrs/jotai#61]
Using Next.js
Attached screenshot
The code is like this
```ts
import { atom, useAtom } from 'jotai'
import { useUpdateAtom } from 'jotai/utils'

const eventsAtom = atom<Events>([])

export const useCreateSSE = () => {
    let updateEvents = useUpdateAtom(eventsAtom)
}
```

Wrapping Component in _app with Provider
And then using this custom hook in some component

When I used useUpdateAtom code directly, just copied from the repo, it worked.

my tsconfig:
```json
{
    "compilerOptions": {
        "target": "es6",
        "lib": ["dom", "dom.iterable", "esnext"],
        "allowJs": true,
        "skipLibCheck": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "noEmit": true,
        "noImplicitAny": true,
        "strictNullChecks": true,
        "strictFunctionTypes": true,
        "strictPropertyInitialization": true,
        "noImplicitThis": true,
        "alwaysStrict": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "esModuleInterop": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "downlevelIteration": true,
        "baseUrl": ".",
        "allowSyntheticDefaultImports": true,
        "jsx": "preserve",
        "paths": {
            "~/*": ["./src/*"]
        }
    },
    "exclude": ["node_modules", "public", "not_used"],
    "include": ["next-env.d.ts", "src/**/*.ts", "src/**/*.tsx", "src/**/*.jsx", "src/**/*.js"]
}
```

![image](https://user-images.githubusercontent.com/6741645/93819110-faecb480-fc63-11ea-8d69-2dbf9b4498aa.png)

**Comment by lishine** [comment]
![image](https://user-images.githubusercontent.com/6741645/93819607-a0078d00-fc64-11ea-8792-e1ed6875b64f.png)

**Comment by lishine** [comment]
"react": "16.13.1"

**Comment by dai-shi** [comment]
So, I assume that esm doesn't work in nextjs server, maybe? Let me create the cjs build.

**Comment by lishine** [comment]
Ok, I added dev-dependency esm
And run NODE_OPTIONS='-r esm' next dev
And it works fine

Is it the way people import esm ?
I am using node 14.8. isn't es modules supported already?

**Comment by dai-shi** [comment]
Don't know. We need someone familiar with next...

**Comment by lishine** [comment]
OK, I run it with NODE_OPTIONS='-r esm'
Even didn't install any esm package
And it works fine
