### ISSUE TITLE
Update local state (useState) and atom at once on button-click - strange behavior

### ISSUE THREAD

**Issue by TheManFromEarth1** [pmndrs/jotai#614]
The component below outputs 3 div's.

Without updating the Atom, the component renders fine only once.

But when I try to change both - the local state with useState _(_setFolder_)_, as well as update the global Jotai state (_setDockBG_) - i get a weird behavior:

```
    ReactDOM.unstable_batchedUpdates(() => {
      setFolder((prevState) => !prevState) 
      setDockBG(!dockBG) // Switch between false/true - problem
    });
  };
```
The above way:
1. The useState is not updated anymore. Only the atom.
2. The component renders now three times, instead of once.

```
     setDockBG((dockBG) => true) // or
     setDockBG(true) 
```
The above way, I have to click 2 times so that both states change.

I thought maybe ReactDOM.unstable_batchedUpdates helps to force batch update of states but no.

Did I use a wrong way of switching/updating the jotai state?

Full component head
```
const Folder = (folders) => {
  const [folder, setFolder] = useState(false);
  const [dockBG, setDockBG] = useAtom(dockerAtom)

  const handleToggle = (e) => {
    e.preventDefault();
    e.stopPropagation();

    ReactDOM.unstable_batchedUpdates(() => {
      setFolder((prevState) => !prevState) 
      setDockBG(!dockBG) // problem
    });
  };

  const closeToggle = () => {
    ReactDOM.unstable_batchedUpdates(() => {
      setFolder(false);
      setDockBG(false);
    });
  };
```
store.js
```
export const dockerAtom = atom(
    false
)
```

If needed I can setup a codepen, but maybe it's a simple mistake on my part - I'm a beginner.

Specs: 
Next.js 11.0.1
"react": "^17.0.2",
jotai": "^0.15.0" or 1.2.2

**Comment by TheManFromEarth1** [comment]
The problem seems to be below.

The useState is rendered conditionally and messes the states up. 
If I remove the condition, only click is enough to update both states correctly.

```
 return (
    <>
       
        **{ folder == true &&**
          <div className="dockFolder backdrop-filter backdrop-blur-md">
            <FavoriteFolderExpanded folders={folders} closeToggle={closeToggle}/>
          </div>
        }
```

Will check regarding rendering problem.

**Comment by dai-shi** [comment]
https://codesandbox.io/s/hopeful-euler-bxsmg?file=/src/App.js

Here's a simple version to confirm it's working.
Hope you can reproduce the issue in a simplified way.
