### ISSUE TITLE
Initialize atom with function

### ISSUE THREAD

**Issue by aaronjensen** [pmndrs/jotai#615]
Hi, we have a situation where we want to store a function in an atom. The function is effectively a render prop value (it takes some arguments and returns a React Element). As it stands, passing a function to the `atom` constructor assumes that I am supplying a computed value function, which is not what I'm trying to do. 

Is there a way to do this or am I stuck putting the function in an object?

**Comment by dai-shi** [comment]
I knew this is the limitation in the API design from the beginning.

> am I stuck putting the function in an object?

So, yes. I'd do this.

---
As for `useState`, we could do `useState(() => (a) => a + 1)`, but we can't do this with `atom`, unfortunately.

**Comment by aaronjensen** [comment]
Okay, thank you for the clarification.
