### ISSUE TITLE
Bug? Derived atom value changes but useAtomValue not causing rerender 

### ISSUE THREAD

**Issue by tarngerine** [pmndrs/jotai#616]
sorry, i know this type of support is really annoying and difficult, but i occasionally have issues with dervied atoms not working properly and wanted to make sure to share an example when i could (in this case, a personal project instead of a client project :p )

I have a setup like so:

- `rings` atom
- `currentRingIdAtom`
- `currentRingAtom` -> derives from `rings` and `currentRingIdAtom`

when the app loads, i sync data from a remote source, and update `rings` atom, and the derived `currentRingAtom` function is re-running. however, my `useAtomValue` of that atom is not rerendering.

<img width="641" alt="image" src="https://user-images.githubusercontent.com/1629901/127095487-c52b9123-f5b9-4351-9b3e-c98cdd1afe15.png">

you can see "current ring useAtomValue updated" does not log again after the 2nd "derived atom for current ring" log, which is what i would expect.

i've spent a few hours, can't figure out why the derived atom function runs but the value doesn't update.  any guidance would be super appreciated, thank you!

---

Repro:

- go to https://codesandbox.io/s/github/tarngerine/blogring
- press [create blog], see new blog pop up
- open another tab of https://codesandbox.io/s/github/tarngerine/blogring

expected:
- see the new blog you created in the other tab
- derived atom runs AND useEffect in `Ring/index.tsx` reports via console log that the value is updated

actual:
- `Ring` component never updates after initial render with "old" data

**Comment by dai-shi** [comment]
Hi, thanks for reporting.
Looking at the code briefly didn't reveal any instant issues.
Would you please create a smaller reproduction with two or three atoms preferably without atomFamily?
Thanks for your help.

**Comment by tarngerine** [comment]
as with this type of bug im never able to repro in a controlled environment :( 

as a hacky fix, im adding a `useAtomValue(data.rings)` inside `Ring` component, which listens to the main `rings` atom, which is updating properly. this will mean `Ring` component has extra re-renders when other rings are updating, but it should be negligible


before (does not update)

```
export function Ring() {
  const ring = useAtomValue(currentRingAtom); // currentRing is a derived atom of data.rings and currentRingIdAtom

  return ...
```

after (updates properly)

```
export function Ring() {
  const rings = useAtomValue(data.rings);
  const id = useAtomValue(currentRingIdAtom);
  const ring = rings[id];

  return ...
```

**Comment by dai-shi** [comment]
> as with this type of bug im never able to repro in a controlled environment :(

So, we need to think a possible bug in our brain.
If one mutates atom object value, it doesn't cause re-renders.
In this case, `freezeAtom` might help to detect the mutation.

If there were a bug in somewhere (like in useMutableSource emulation), we would still need a repro in a controlled environment to investigate the bug. Hope someone could try to repro.

**Comment by TheEhsanSarshar** [comment]
@tarngerine can you make a simpler repo to reproduce the issue.

**Comment by dai-shi** [comment]
@TheEhsanSarshar 
@tarngerine said creating a smaller repro is not possible... I wish it could.

**Comment by dai-shi** [comment]
So, without a repro, we wouldn't be able to investigate.

@tarngerine My suggestion to debug is using `freezeAtom`. Let me know if the usage is unclear.

Closing this for now. We can continue discussion, and reopen with a repro.
