### ISSUE TITLE
jotai/query ignores `useErrorBoundary` property (`atomWithQueryWithoutSuspense`)

### ISSUE THREAD

**Issue by andreas-soroko** [pmndrs/jotai#621]
Seems like `jotai/query` ignores completely the `useErrorBoundary` property ( defaults = false ) from react-query options.

would be great if `jotai/query` would support this case too, currently it's no option for us to refactor everything to React.Suspense / ErrorBoundary components.
(we show loading spinner on buttons and don't want to change the complete component there)

example: https://codesandbox.io/s/jotai-query-hacker-news-forked-nnvus?file=/src/App.tsx

**Comment by dai-shi** [comment]
Yeah, `atomWithQuery` in `jotai/query` assumes suspense mode and it's the only mode supported now.

I just tried something if we can work around this in a simple manner, without a luck.

If you don't need suspense support, the code would be much smaller.
We can draft something like `atomWithQueryWithoutSuspense` but the function signature is different from `atomWithQuery`.

We discussed this before and decided this way as jotai is suspense first.
So, `atomWithQueryWithoutSuspense` won't be in `jotai/query`.
Might be good for a third party library.
cc @aulneau

**Comment by dai-shi** [comment]
I wonder if somebody is interested in developing a 3rd-party library for integrating jotai and RQ without suspense.

Or, preferably a recipe in docs. Yeah, that sounds good.

**Comment by andreas-soroko** [comment]
@dai-shi in generell, is there something like [useRecoilStateLoadable](https://recoiljs.org/docs/api-reference/core/useRecoilStateLoadable) in jotai? This would be quite helpful. 

(was experimenting a bit with async atoms and found this hook in recoil)

**Comment by dai-shi** [comment]
Unfortunately not, we decided to make it suspense-first for the future trend of React.
We put some workaround for non suspense usage: https://docs.pmnd.rs/jotai/guides/no-suspense

---
(A note to myself: It would be nice if https://github.com/pmndrs/jotai/issues/269#issuecomment-873563552 workaround worked. Might be related to #622 investigation.)

**Comment by dai-shi** [comment]
#672 is new effort. (`useErrorBoundary` will still be ignored, but it might cover your use case.)

**Comment by andreas-soroko** [comment]
updated from `1.2.2` to `1.3.4` and i am getting now this error

```
Uncaught ReferenceError: require is not defined
    at index.js:22
 ```
 
 
![image](https://user-images.githubusercontent.com/47380084/133143777-84c6aa07-b151-4a3d-bdeb-a11822500c94.png)


using `Vite` as build tool

**Comment by dai-shi** [comment]
@andreas-soroko Oh, my... Does it work with v1.3.3? Would you please open a new issue with a minimal reproduction? Does it fail without `jotai/query`? Thanks for your feedback!

**Comment by andreas-soroko** [comment]
Created a minimal example and noticed that the error does not occur, so had a look into what change compared to my project and I had to update vite itself from 2.1.3 to 2.5.7 ..

Now it's working and will test the change with `loadable` if I have some time for, thank you 👍🏼

**Comment by dai-shi** [comment]
@aulneau You might have some ideas to handle `useErrorBoundary`. (Maybe, just showing a message to suggest `lodable` when it's `true`, at least.)
