### ISSUE TITLE
atomWithProxy triggers infinite loop

### ISSUE THREAD

**Issue by israelidanny** [pmndrs/jotai#624]
When using `atomWithProxy` merely referencing any value from the state will cause an infinite loop. I created a minimal reproduction of the bug:
https://codesandbox.io/s/jotaivaltio-infinite-loop-yphdz?file=/src/App.js

It has a proxy atom and it uses it like so:
`const [atomState] = useAtom(proxyAtom);`

If you just print out something like `JSON.stringify(atomState)` everything is great, but the moment you do a simple change to `JSON.stringify(atomState.someNestedKey)` everything freezes in an infinite loop (even though the key exists and prints out successfully without being referenced directly.

**Comment by dai-shi** [comment]
If I don't misunderstand your example, you use async/suspense feature of valtio.

https://github.com/pmndrs/jotai/blob/2f142913e0af72fbfcf9c40cca1fed58c5dfa305/src/valtio/atomWithProxy.ts#L35
It's not currently supported due to typing issue.
But, I didn't know about the infinite loop.
Maybe, we can support the promise usage along with fixing the infinite loop.

**Comment by dai-shi** [comment]
I wish some contributors work on this, but it will require fairly deep understanding of jotai and valtio.

At least, our documentation should note about the limitation with promises.

**Comment by israelidanny** [comment]
Do I understand correctly that the typing issue is that once you set a state key as a promise, overwriting it would fail TypeScript checks because it expects a promise and not whatever promise returns?

**Comment by dai-shi** [comment]
Exactly.

**Comment by israelidanny** [comment]
I'd be interested to at least give it a small stab. Will report what, if anything, came out of it.

Off the top of your head: any guesses as to what could be triggering an infinite loop? We're not actually mutating the object but rather accessing a snapshot key, it's starange that merely accessing it would cause that.

**Comment by dai-shi** [comment]
If it doesn't touch the key, it will not throw a promise. so, that's probably why.

**Comment by dai-shi** [comment]
So, typing issue and infinite loop are probably different problems.

**Comment by israelidanny** [comment]
Alright, I'm giving it a stab now. Let's see if anything useful comes out of it :)

**Comment by israelidanny** [comment]
So, as far as I understand the following happens to cause the infinite loop:
1. `atomWithProxy` creates a snapshot of the proxy
2. The following logic executes and sets the prop to a getter that throws a promise: https://github.com/pmndrs/valtio/blob/master/src/vanilla.ts#L101-L110
3. The promise resolves
4. However, react instantly tries to render, hits the getter, gets an already resolved promise suspends for 0 milliseconds, re-renders, hits the getter, gets an already resolved promise, suspends for 0 milliseconds e.t.c
5. It never actually manages to get another version of the snapshot

**Comment by israelidanny** [comment]
The above is fixed in the following PR over at `valtio` and the test now passes:
https://github.com/pmndrs/valtio/pull/202

**Comment by dai-shi** [comment]
https://github.com/pmndrs/valtio/pull/202 is merged and v1.1.3 is published.

**Comment by israelidanny** [comment]
Amazing! I'm finishing advanced typings that will also fix the type problem and allow atomWithProxy to officially support promises in a few minutes :)

**Comment by israelidanny** [comment]
I think that this issue can be closed (infinite refresh bug fixed) and the types can be tracked in the PR, what do you think @dai-shi ?

**Comment by dai-shi** [comment]
Would you update valtio v1.1.3 in devDependencies in #625 and if it passes the test?

**Comment by dai-shi** [comment]
> Amazing! I'm finishing advanced typings that will also fix the type problem and allow atomWithProxy to officially support promises in a few minutes :)

AFAIR, it's not only technical issues, but design issues. proxies hold promises, but snapshot have resolved values. We can continue discussion in the PR.

**Comment by israelidanny** [comment]
Alright, moving my attention to the PR.
