### ISSUE TITLE
No .cjs version of utils avaliable

### ISSUE THREAD

**Issue by merisbahti** [pmndrs/jotai#63]
There’s a `index.cjs` file in the distribution, but no `utils.cjs`, is there any reason? I’m trying to debug an error with jest so I’m just wondering. Thanks!

**Comment by dai-shi** [comment]
Soon it will have. #62

**Comment by merisbahti** [comment]
awesome, thanks 🥳😅

**Comment by dai-shi** [comment]
https://github.com/pmndrs/jotai/pull/62#issuecomment-696438508
You could test it with the csb ci build, until it's merged and released.

**Comment by merisbahti** [comment]
Hey, I’m not sure I understand how to use it. I tried with a direct import like this: 

```
import { atomFamily } from 'jotai/utils.cjs' 
```

But I get the error that there’s no typings defined for it.

If I use 

```
import { atomFamily } from 'jotai/utils' 
```

I still get the same error as before, i.e. something similar to that code is not transpiled from `node_modules`.

How is this supposed to work?

Here’s my repo: https://github.com/merisbahti/jotai-optics

**Comment by dai-shi** [comment]
@merisbahti 

How about this?

```js
import { atomFamily } from 'jotai/utils.cjs.js'
```

**Comment by merisbahti** [comment]
Hey, I get the same error (no typings found for utils.cjs.js)

Hmm...
I was wondering why does

`import { atom } from ’jotai’`

work?

It seems like it just works is because in package.json you specify `main` as `index.cjs.js`.

**Comment by merisbahti** [comment]
As a workaround btw, I made this file:
```

declare module 'jotai/utils.cjs' {
  export * from 'jotai/utils'
}

```

https://github.com/merisbahti/jotai-optics/blob/master/src/external-types.d.ts

It’s alright.

**Comment by dai-shi** [comment]
> But I get the error that there’s no typings defined for it.

Sorry, I wasn't careful enough. So, it's the typescript error.
Your workaround seems good.

Alternatively, can we use this?
https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html

```ts
/// <reference path="node_modules/jotai/utils.d.ts" />
```

(never tried.

**Comment by merisbahti** [comment]
hmm, might work - but it feels like this would be rollups responsibility?
maybe we have missed something in the configuration?
