### ISSUE TITLE
waitForAll inside selector throws with a lot of atoms

### ISSUE THREAD

**Issue by fc1943s** [pmndrs/jotai#630]
https://codesandbox.io/s/hopeful-newton-0p6q3?file=/src/App.js

Running locally it starts throwing after 6225 atoms, on codesandbox 8000+.

I've also added a failing test in a fork.
https://github.com/fc1943s/jotai/commit/db74e3ccb01aced42a448c447741c852e40f8209

![image](https://user-images.githubusercontent.com/688618/127792904-26981f09-ab3b-4c33-94fd-9328988011a8.png)

**Comment by dai-shi** [comment]
@aulneau Is this similar to what you reported in #590?

**Comment by Thisen** [comment]
> @fc1943s great you made a failing test. would you like to dig more?
> This sounds like a hard issue, as it works with small number of atoms.
> 
> cc @Thisen can you also investigate?
> 
> 

Yes, I'll look into it.

**Comment by aulneau** [comment]
> @aulneau Is this similar to what you reported in #590?

I never experienced any issues with it throwing, but i don't think i ever got to that high of an atom count. perhaps they are related, at some level.

**Comment by fc1943s** [comment]
I made it work inside my app chunking the atoms before waitForAll

![image](https://user-images.githubusercontent.com/688618/127886210-ee980f60-2432-46a2-8457-19fe09d64743.png)

I'll try to understand the recursion in jotai and if needed, I add to the repro a javascript version of this chunking code.
