### ISSUE TITLE
useAtomValue with Atom contains Object or Array

### ISSUE THREAD

**Issue by meotimdihia** [pmndrs/jotai#631]
useAtomValue with Atom contains Object or Array.
```js
Type 'Record<string, string>' must have a '[Symbol.iterator]()' method that returns an iterator.
Property 'length' does not exist on type 'number'.
Type 'number' must have a '[Symbol.iterator]()' method that returns an iterator.
```
I got these bugs: 

![Code_2021-08-02_17-44-00](https://user-images.githubusercontent.com/300961/127849628-6b7e90f0-4e31-417e-b7b1-b793ddf1e307.png)

The code works fine if I replace `useAtomValue` with `useAtom`

**Comment by dai-shi** [comment]
Please try this:
```js
const coloredGeneres = useAtomValue(coloredGenresAtom)
```

**Comment by meotimdihia** [comment]
Sorry, I forgot it 😅. 
I close the issue.

**Comment by dai-shi** [comment]
👍 If you have a suggestion to improve docs, feel free to open a PR.
