### ISSUE TITLE
AtomFamily no way to separate key and init value?

### ISSUE THREAD

**Issue by philipaarseth** [pmndrs/jotai#638]
Maybe I'm missing something here, but it looks like atomFamily sets map key AND the atom value directly based from the param/ key and there's no way to pass a key and value separately. Yes, its not 100% 1:1 since you can do get calls and derivative logic.

from atomFamily.ts:50-52
``` ts
const newAtom = initializeAtom(param)
atoms.set(param, [newAtom, Date.now()])
return newAtom
```

So say I want to put an object in the atomFamily, I would need to have access to the entire object any time I want to access the atom. Doesn't this make atomFamily nearly pointless?

How I would expect it to work is that I can pass in say a string key and that would give me access to the object.

Alternatively if there's another way to create atoms dynamically that you can
1. iterate over (doing it now inelegantly by tracking string IDs in another atom)
2. access single atom by some ID/ key

**Comment by dai-shi** [comment]
> there's no way to pass a key and value separately.

How about this?
```js
const myFamily = atomFamily(
  (param) => atom(param.value),
  (a, b) => a.key === b.key
)
```


> Alternatively if there's another way to create atoms dynamically that you can

I prefer atoms-in-atom to atomFamily for most of my use cases: https://docs.pmnd.rs/jotai/guides/atoms-in-atom
(atomFamily requires use `remove` properly to avoid memory leaks.)

**Comment by philipaarseth** [comment]
Well this is part of the problem. 
You can take part of the param and make an atom, which means you can create a value that is smaller than the param, but never bigger. This means that I have to have the full param everywhere to access the value in the atomFamily.

But say I want my key to be completely unrelated to my atom value:
`const atomFamilyKey = "object-ID-1001"` as my key and 
``` ts
const objectValue = {
    key: value,
    secondKey: secondValue,
    ...
}
```

And access it somewhere like so
`const [object, setObject] = useAtom(objectFamily("object-ID-1001"))`
This way I can pass the id around as a prop and not the entire object wherever I need to access the atom.
The way it's implemented now seems kind of counterintuitive as if you're just talking about data access, if you already have the full object in the deeply nested component to be able to access the data, you already have more data than what you'd be looking to get from the atomFamily.


As for atoms in atom
Is there a way to access an atom inside another atom in a deeply nested component without either
A) passing the atom to the component as a prop 
`const Component = ({ atom1, atom2 }) => {`
B) first and also subscribing to the parent atom
``` ts
type objWithAtoms = { [key: string]: WritableAtom<type, type> }
const atomWithAtoms: objWithAtoms = useAtomValue(atomWithAtomsState)
const [atom, setAtom] = useAtom(objectWithAtoms["object-ID-1001"])
```

I guess an idea that could work (but I don't think is possible with the current implementation) is a useFocusAtom which I guess could just return null if the atom does not exist
`const [atom, setAtom] = useFocusAtom(atomWithAtomsState, (optic) => optic.prop("object-ID-1001"))`

**Comment by dai-shi** [comment]
A quick question:

> the ID-string as param

This sounds good in this case, but how would you know the object value for "object-ID-1001"? Can we assume there's a `Map<ObjectKey, ObjectValue>` or something?

**Comment by philipaarseth** [comment]
Do you mean before I initialise the atom or after?

In recoil you can define a type for the value and a value for the key/param
`function atomFamily<T, Parameter>({`

**Comment by dai-shi** [comment]
> Do you mean before I initialise the atom or after?

before. let me illustrate the idea in code.

```js
const params = {}
const myBaseFamily = atomFamily((strKey) => atom(params[key]))
const myFamily = (strKey, param) => {
  params[strKey] = param
  const anAtom = myBaseFamily(strKey)
  delete params[strKey]
  return anAtom
}
```




> In recoil you can define a type for the value and a type for the key/param
> `function atomFamily<T, Parameter>({`

We don't use that "key", and it returns `Parameter => RecoilState<T>`.
https://recoiljs.org/docs/api-reference/utils/atomFamily

tbh, I got lost. I wonder how recoil's atomFamily helps your use case.

would you be able to create a small codesandbox to play with?

**Comment by aulneau** [comment]
@philipaarseth to me it seems like you're using `atomFamily` as a way of accessing different keys in a given object, is that correct? If so, that seems different than the intended use case of `atomFamily`.

As @dai-shi requested, any real world examples of what you're attempting would be helpful in assisting you.

**Comment by philipaarseth** [comment]
Sorry for the late reply, just got back to this.

Reading that atomFamily was implemented like a weak map, I always just assumed that you would be able to pass in both a key and a value when initialising the atom. However when looking at the implementation in both recoil and jotai, it does not look like there is any way to pass a value along with the key when trying to initialise/ access an atom within an atomFamily. At first I assumed this was a mistake since maps are key: value pairs, but I guess that's just the approach that has been chosen.


My current approach (which worked fine until I started running into performance concerns) was simply to put the smaller objects into a big object in a react context and pass that down like so

```
const [bigObj, setBigObj] = useState({
    objectID1: {
      key1: value1,
      key2: value2,
    },
    object2: {}
    object3: {}
    ...
  })
```

This way I could get access to each of the smaller object through the big object, but as you can imagine, it causes re-renders like crazy as each time I need to update one small object, every component that subscribes to the big object re-renders.

Looking at alternative options, I think what I really need has nothing to do with atomFamily and maybe perhaps just implement useContextSelector instead.
https://github.com/dai-shi/use-context-selector

**Comment by philipaarseth** [comment]
Yes, but how would you access the small atom within a component completely skipping the big atom without passing the atom into the component?

I know I could for instance make an atom array [atom, atom, atom] then map that array and pass the atoms into the components, however for my use case that won't work as these containers are spread wildly throughout the app.

**Comment by dai-shi** [comment]
I mean `selectAtom` covers most use cases of `use-context-selector`.

```js
const bigAtom = atom({
  objectID1: {
    key1: value1,
    key2: value2,
  },
  objectID2: {}
  objectID3: {}
  ...
})

const Component = ({ objectId }) => {
  const [objectValue] = useAtom(selectAtom(bigAtom, useCallback(value => value[objectId], [objectId])))
  ...
}
```

**Comment by philipaarseth** [comment]
Would calling it like this `useAtom(selectAtom(bigAtom` let you solely subscribe to changes in the small atom and ignore all changes to bigAtom?

**Comment by dai-shi** [comment]
Yes, no, yes.

```js
const bigAtom = atom({
  objectID1: {
    key1: value1,
    key2: value2,
  },
  objectID2: {},
  objectID3: {}
  ...
})

const smallAtom = selectAtom(bitAtom, value => value.objectID1)
// will create something like the following.
const smallAtom = atom({
  key1: value1,
  key2: value2,
})
// but it's read-only. focusAtom will create a read-write atom.
```
