### ISSUE TITLE
Introduce `useAtom(atom, scope?)` and drop `atom.scope`

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#639]
https://github.com/pmndrs/jotai/issues/619#issuecomment-888037369
I realized that probably `atom.scope` was a bad abstraction.
We have really weird scope copying/validation in various utils, which is hard to maintain and increases bundle size.
The atom scope is only needed when we get a context, so having it in the second argument of `useAtom` seems the right way. We already do this for `useAtomCallback`, `useAtomsSnapshot`, and `useGotoAtomsSnapshot`.

[Migration Plan]
We simply drop `atom.scope` in TS, but have a fallback behavior in `useAtom` to avoid breaking change in JS (and we show the deprecation message).

**Comment by dai-shi** [comment]
@Thisen Would you review this please? I'd like to do this before #637.

**Comment by Thisen** [comment]
I think it's a good idea, but I think TS support is as important as JS (especially when we're TS oriented) - The types shouldn't break for our users, unless it's a major release. We need to have a better migration plan or cut a v2.

**Comment by dai-shi** [comment]
Let's mark TS type `@deprecated` so that it won't be a TS breaking change in core.
