### ISSUE TITLE
Feature Request: Add pause/skip to urql atomWithQuery

### ISSUE THREAD

**Issue by jrobber** [pmndrs/jotai#649]
**Description:**
When using atomWithQuery sometimes it is accessed, but we are not ready for the query yet.  It would be great if we could add the ability to pause (this is what urql calls it), or skip the query and updating the atom based on certain conditions.  More generically I think adding an optional "skip" check to Jotai could open up useful patterns.

**Use Cases:**
1. I'm using sessions instead of jwts and need to ping a server to see if there is a currently logged in user.  I have a userAuthAtom that has a "loading" property and a "userId".  Based on that userId I want to query for some data.  In this cause I'd like to pause the atomWithQuery until I have a userId.
2. It's common to setup a query, but not want to execute until a user performs an action (IE - Search).  In Urql this is done by using pause, and then manually firing the query.  If we use atomWithQuery we would based it on another atom, keywords.  Since we don't have keywords, but need the atoms setup we'll have to fire atomWithQuery at least once with an empty string.

**How it could work:**
1. Allow atomWithQuery to taken in a 3rd function, pause, that takes in get and returns a boolean.  If this function returns true then the query is skipped and the Atom is not updated.  I believe this option would best bridge into supporting `skip` as a jotai feature.
2. Add a pause property to the results of first function.  This option fits in best with how urql does things now.
3. Allow either of the functions passed to atomWithQuery to return null to indicate to not run the query.  I can't think of a good reason to do this over the others, but it's there in-case someone else does.

**Additional thoughts & Work arounds**
Both uses cases above could be done with some creative atom chaining and merging, or by isolating atomWithQuery with a manually updated atom(s) that it depends on.  The challenge with both of these options is that they force a lot of redundancy in managing my state flow.  I have to bridge from components and useEffect, into updating atoms, and duplicate certain atom data just so that it's isolated and doesn't trigger a query when it's not really ready, just partially ready.  I can alternatively break atoms into smaller pieces and then re-merge them together, but that's often more work than just changing "isReady": true on an atom and checking it.

**Comment by dai-shi** [comment]
Hey, thanks for the suggestion.

We had discussed about supporting "pause", and concluded it's not required: https://github.com/pmndrs/jotai/pull/463#discussion_r628814676

Some related issues: #622 #635

While we could revisit about supporting "pause" already available in urql,
the workaround for now shouldn't be that hard.

Can you try something like this?
```js
const queryAtom = atomWithQuery(...)
const isReadyAtom = atom(false)
const guardedQueryAtom = atom(
  (get) => get(isReadyAtom) ? get(queryAtom) : null
)
```

I'm not sure if I understand the use case fully, because "ping the server" sounds more like mutation. How would you do it with atomWithQuery?

**Comment by dai-shi** [comment]
> I'm requesting this feature because it makes for a significantly better API for developers.

That sounds fair. Thanks for clarifying.

Let me draft a PR supporting "pause" and see how it helps.

**Comment by dai-shi** [comment]
Would you please try if
https://ci.codesandbox.io/status/pmndrs/jotai/pr/655
solves your issue? See "Local Install Instructions"
