### ISSUE TITLE
Race conditions in rapidly updating async atoms

### ISSUE THREAD

**Issue by LXSMNSYC** [pmndrs/jotai#65]
@dai-shi's example sandbox: https://codesandbox.io/s/nextjs-with-jotai-async-pm0l8?file=/pages/_app.js

### Current Behavior
Clicking the button rapidly immediately opts-out of the fallback UI and shows a stale success state, then switches to the current state.

### Expected Behavior
Suspense should not opt-out of fallback until the current Promise state has been resolved.

**Comment by dai-shi** [comment]
Good point. Overall, async behavior is still not optimal. This one should be fixer sooner. I hope I can write a test first.
