### ISSUE TITLE
reexecuteQuery for jotai/urql

### ISSUE THREAD

**Issue by israelidanny** [pmndrs/jotai#666]
Do I understand correctly that there is no mechanism at all to reexecute a query in `jotai/urql`? In the regular `urql` hooks there is this method:
https://formidable.com/open-source/urql/docs/basics/react-preact/#reexecuting-queries

```
const Todos = ({ from, limit }) => {
  const [result, reexecuteQuery] = useQuery({
    query: TodosListQuery,
    variables: { from, limit },
  });

  const refresh = () => {
    // Refetch the query and skip the cache
    reexecuteQuery({ requestPolicy: 'network-only' });
  };
};
```

Not being able to reexecute queries seems like a rather big limitation.

**Comment by dai-shi** [comment]
I wasn't aware the reexecute feature. I don't know how I missed it. We have "refetch" feature in `jotai/query`. So, we should follow the pattern.

**Comment by dai-shi** [comment]
Actually, it doesn't work like `jotai/query`. 🤔

**Comment by israelidanny** [comment]
In urql it gets returned separately from the result object.

**Comment by israelidanny** [comment]
I'd be happy to contribute code if we can agree on a spec.
For now in my app I had to comment out Jotai and replace it with a pure
urql query for the specific place where I needed refetch.

So Im available to contribute

**Comment by dai-shi** [comment]
Please try if https://ci.codesandbox.io/status/pmndrs/jotai/pr/668 works.

**Comment by dai-shi** [comment]
> So Im available to contribute

Well, I should have asked for your help from the beginning. Next time.

I will merge #668 soon.

**Comment by israelidanny** [comment]
@dai-shi I'll test it today & let you know that it works!

**Comment by dai-shi** [comment]
Okay, I will wait. (I was about to cut a release.)

**Comment by dai-shi** [comment]
Well, I think we can release it, and if something goes wrong, we'll fix it ASAP.
