### ISSUE TITLE
is it possible to mutate state, without causing subscribed components to re-render ? 

### ISSUE THREAD

**Issue by a-eid** [pmndrs/jotai#67]
this is a very weird use-case but sometimes I wanna just update an atom without re-render ? 
is that possible ? if so how ?

**Comment by dai-shi** [comment]
Unofficial answer: If you mutate an atom value (object), it won't re-render. Same as useState.
Official answer: What would be the valid use case? If you want to mutate something useRef+useContext seems a better way.

**Comment by a-eid** [comment]
@dai-shi after thinking about it for a while, I thought I might not need it. 

thanks
