### ISSUE TITLE
`loadable` API for using async atoms without suspense

### ISSUE THREAD

**Issue by Pinpickle** [pmndrs/jotai#672]
Prior discussion: https://github.com/pmndrs/jotai/issues/269

Recoil has a `useRecoilValueLoadable` for bypassing suspense and returning a "loadable" object. This is useful in some cirumstances when suspense is not desired, and is also much easier than implementing it via the method recommended in the [Jotai docs](https://docs.pmnd.rs/jotai/guides/no-suspense).

<details>
  <summary>No-suspense code example</summary>

  ```
  const fetchResultAtom = atom({ loading: true, error: null, data: null })
  const runFetchAtom = atom(
    (get) => get(fetchResultAtom),
    (_get, set, url) => {
      const fetchData = async () => {
        set(fetchResultAtom, (prev) => ({ ...prev, loading: true }))
        try {
          const response = await fetch(url)
          const data = await response.json()
          set(fetchResultAtom, { loading: false, error: null, data })
        } catch (error) {
          set(fetchResultAtom, { loading: false, error, data: null })
        }
      }
      fetchData()
    }
  )
  runFetchAtom.onMount = (runFetch) => {
    runFetch('https://json.host.com')
  }

  const Component = () => {
    const [result] = useAtom(runFetchAtom)

    console.log(result) // { loading: ..., error: ..., data: ... }
    return <div>...</div>
  }
  ```
</details>

I'm proposing a read-only `loadable` util which returns an atom that converts an async atom into a sync atom, just like Recoil's loadable utils.

Depending on context, consumers may want errors to still be thrown or captured into the loadable object. There are two ways of handling this.

### 1. Separate `suspendable`/`loadable` APIs

```ts
const SUSPENDED = Symbol("jotai/atomSuspended");

type Loadable<T, TError = any> = { type: "loading" } | { type: "value", value: T } | { type: "error", value: TError };

// will still throw on error
const suspendable = <T>(atom<Promise<T> | T>) => T | SUSPENDED;

// will not throw on error
const loadable = <T>(atom<Promise<T> | T>) => Loadable<T>;
```

This has the advantage of calling a single function without parameters whether you want errors to be thrown or not. The `suspendable` type signature is also much simpler, as we don't need to be able to disambiguate between value and error types.

### 2. Param in the `loadable` function

```ts
function loadable<Value, Update>(
  atom: WritableAtom<Value, Update>
): WritableAtom<{ loading: true; data?: Value } | { data: Value } | { error: unknown }, Update>

function loadable<Value, Update>(
  atom: WritableAtom<Value, Update>,
  throwsError: boolean
): WritableAtom<{ loading: true; data?: Value } | { data: Value }, Update>

function loadable<Value>(
  atom: Atom<Value>
): Atom<{ loading: true; data?: Value } | { data: Value } | { error: unknown }>

function loadable<Value, Update>(
  atom: Atom<Value, Update>,
  throwsError: boolean
): Atom<{ loading: true; data?: Value } | { data: Value }>
```

This has the advantage of there only being one function. However, a flag with a default value means one option will be more convenient than another.

---

## Outstanding questions:

- Which API to choose?
- Should this support writable atoms in the first implementation? Or can that wait?

**Comment by dai-shi** [comment]
Thanks for opening this up.

> * Which API to choose?

I still believe most people want to avoid ErrorBoundary if they are not ready for Suspense.

I generally like symbols, so `suspendable` signature looks neat. But, what it gives for typing seems trivial.
```tsx
// with symbol
if (value === LoadingSymbol) {
 return <>Loading</>
}
return <>{value.text}</>

// with loadable object
if (value.loading) {
  return <>loading</>
}
return <>{value.data.text}</>
```
Or, am I missing something?

> * Should this support writable atoms in the first implementation? Or can that wait?

I thought it would be easy to implement for writable atoms, because it's just delegating.
However, I can actually change my mind. Because we can still use the original value for writing, we don't need to create writable atoms. It's cleaner in the implementation and the usage.
If one wants to create a custom hook, it requires an extra step.
```js
// with writable atom support
const useLoadableAtom = (anAtom) => useAtom(lodable(anAtom))

// without writable atom support
const useLodableAtom = (anAtom) => [
  useAtomValue(lodable(anAtom))
  useUpdateAtom(anAtom)
]
```
Not a big deal? I'm fine with only supporting `Atom<Value>`.

**Comment by dai-shi** [comment]
> I still believe most people want to avoid ErrorBoundary if they are not ready for Suspense.

Otherwise, we make `suspendable()` with `catchesErrorToo` option? Or, `catchable()`?

I wish we get some more feedback from someone.
Does recoil have `suspendable()` like feature?

**Comment by Pinpickle** [comment]
> Or, am I missing something?

I don't think you are, there really isn't _that_ much more typing with a loadable type API. It's just that in TS you'd need to do a check for errors even if you know your promise won't throw.

> I still believe most people want to avoid ErrorBoundary if they are not ready for Suspense.

The way I see it, if an atom throws (which may be due to a bug, not just a fetch failing for example), it'd be weird that the error wouldn't propagate to the component in the same way `useSelector` does in react-redux for example. Basically, as a developer, I'd expect errors to propagate all the way up the stack _unless_ I put an explicit catch in.

Loadables make sense when the expected error conditions are expected, like fetching data. Having them return errors in the event of bugs feels weird to me. 

Furthermore, error boundaries are an officially supported API recommended by React, suspense is still communicated as experimental by the React team.

> Does recoil have `suspendable()` like feature?

It doesn't, true!

**Comment by Pinpickle** [comment]
@dai-shi if you're still not convinced, I'm happy to go with a pure `loadable` approach.

It'd be pretty trivial to write my own util using loadable:

```
const suspendable = (anAtom) => {
  const loadableAtom = loadable(anAtom);

  if (anAtom.loading) {
    return SUSPENDED;
  }

  if (anAtom.error) {
    throw anAtom.error;
  }

  return anAtom.value;
}
```

**Comment by dai-shi** [comment]
> Furthermore, error boundaries are an officially supported API recommended by React, suspense is still communicated as experimental by the React team.

Yes, this is true.

> if you're still not convinced, I'm happy to go with a pure `loadable` approach.

Yeah, I feel like we should go with the pure `loadable`.

> It'd be pretty trivial to write my own util using loadable:

This looks nice! And, it's actually convincing that `loadable` is a good primitive. We can show this in the docs.

---

So, the signature will be:
```ts
function loadable<Value>(
  atom: Atom<Value>
): Atom<{ loading: true } | { loading: false; hasError: true; error: unknown } | { loading: false; hasError: false; data: Data }>
```

[typescript playgroud](https://www.typescriptlang.org/play?ssl=2&ssc=10&pln=3&pc=1#code/C4TwDgpgBAIghsOUC8UDeUBmB7bAuKAZ2ACcBLAOwHMoBfAKFEigBUV0oAbbOAE0qoFSAV2i0oAHw7c+AgpjidCEANxQAFnEIBREiWwkhJUWoh6DBYRQDWFbAHcKdSdJ79q8xcrWad5w1heqlC8CHAE8Ih09PQAxtgUxFjsABTABCwAlCgAfOj0UIVQZJhQaQB0Mu5U2WgFRQ3xidicEJXYVCkA5FUCXZn1heIQStAlZcDlvrr6JLWDDVBNhC1t3J1dZrNdADRQk1sGAw3Do-mLRcur7RuhiLv75Xdw5TjYx0UMDEA)

Hm, we could follow reocil's api: https://recoiljs.org/docs/api-reference/core/useRecoilValueLoadable

```ts
function loadable<Value>(
  atom: Atom<Value>
): Atom<{ state: 'loading' } | { state: 'hasError'; error: unknown } | { state: 'hasData'; data: Data }>
```

what do you think?

**Comment by Pinpickle** [comment]
> Hm, we could follow reocil's api: https://recoiljs.org/docs/api-reference/core/useRecoilValueLoadable

I think following Recoil's API here is a good idea, personally.

**Comment by dai-shi** [comment]
> I think following Recoil's API here is a good idea, personally.

cool.

We could make it closer, but it can't be really the same, so `{ state: 'loading' } | { state: 'hasError'; error: unknown } | { state: 'hasData'; data: Data }` would be good.

**Comment by aulneau** [comment]
This makes me so happy to see! I think this will enable a lot more usage from folks who maybe were hesitant due to suspense only support.

**Comment by dai-shi** [comment]
@Pinpickle Just checking if you are still around.

**Comment by Pinpickle** [comment]
@dai-shi I finally got a chance to take a crack at this, but ran into an issue with error edge cases. Could you take a look at https://github.com/pmndrs/jotai/pull/698 ?

**Comment by hantaogo** [comment]
How to use loadable? 
I got a ts(2339) error when access result.error or result.data.
my code:
``` ts
const AnTable = () => {
  const result = useAtomValue(loadable(atomUserList))
  let loading = true
  let hasError = false
  let error = null
  let hasData = false
  let data = null
  switch(result.state) {
    case 'loading':
      loading = true
    case 'hasError':
      loading = false
      hasError = true
      error = result.error // error: ts(2339)
    case 'hasData':
      loading = false
      hasData = true
      data = result['data'] // there is not error after replace result.data to result['data'] 
  }
  return (
    <Table
      columns={columns}
      dataSource={data || []}
      rowKey="id"
      size="middle"
      loading={loading}
    />
  )
}
```
so i made a function to do this:
``` ts
// utils.ts
import { Atom } from "jotai";
import { loadable, useAtomValue } from "jotai/utils";

export function useAtomValueLoadable<T>(atom: Atom<T>) {
  const result = useAtomValue(loadable(atom))
  let loading = true
  let hasError = false
  let error = null
  let hasData = false
  let data = null
  switch(result.state) {
    case 'loading':
      loading = true
    case 'hasError':
      loading = false
      hasError = true
      error = result['error']
    case 'hasData':
      loading = false
      hasData = true
      data = result['data']
  }
  return { loading, data, hasError, error }
}
```
then use like is, it's much simple.
``` ts
import { useAtomValueLoadable } from './utils'

const AnTable = () => {
  const result = useAtomValueLoadable(atomUserList)
  return (
    <Table
      columns={columns}
      dataSource={result.data || []}
      rowKey="id"
      size="middle"
      loading={result.loading}
    />
  )
}
```

**Comment by neckaros** [comment]
found this by chance but it's so great!! 💝

**Comment by dai-shi** [comment]
@Pinpickle Hope you get time for it. We have now docs in the same repo.

**Comment by Pinpickle** [comment]
@dai-shi I haven't forgotten this, just super busy at the moment. If this isn't done by the time I get some time to do so, I certainly will!

**Comment by jahglow** [comment]
@Pinpickle Maybe anytime soon???

**Comment by TwistedMinda** [comment]
@dai-shi Can't find any docs on loadable! It's available right?
It currently feels weird to have "No Suspense" separated from the "Async part", especially given the tricks inside it :D
I guess it's time to use the "Async" section of the docs to replace the good old "No Suspense" by the fresh loadable experience.

Async section would look like:

- kick-off: atomWithPending (async then normal, as many times as you want)
  - quick example with suspense
  - quick example with loadable, mention that it can be used the same way for any async atom
  - quick mention (+ link) to the atomWithAsyncStorage that uses the same concept

- full async methods
   - async get example (use word "async selector" somehow so reader can relate)
   - async write example (use word "action" somehow so reader can relate)
   - async get-write example (i can't even relate to this)

- common practices
  - suspense-everywhere
  - preloading (mention it fits well with atomWithAsyncStorage)

What u think?

**Comment by dai-shi** [comment]
> It's available right?

It's not yet available.

> It currently feels weird to have "No Suspense" separated from the "Async part"

I think it was written before we had `loadable`. So, I agree that it's (already) time to revisit.

> kick-off: atomWithPending

This is not what I would expect.
We want to educate async patterns in this order.
1. `atom(async (get) => ...)`
2. `atom(..., async (get, set, arg) => ...)`
3. `atom(new Promise(...))` and `set(new Promise(...))`
4. and finally ,`atom(infinitePending)` (infinitePending is `new Promise(() => {})`)

btw, I really appreciate your work on these.

**Comment by TwistedMinda** [comment]
Great, I'm totally okay with this order!
However, when will it be available officially ? Are there still problems with it ? 

When I tried it seemed to work like a charm!

Happy be able to help!

**Comment by dai-shi** [comment]
> However, when will it be available officially ?

Oops, I got it wrong. The `loadable` is available. It's just the docs that are not available.

**Comment by Bournegit** [comment]
Can loadable be used with an async writable atom?

**Comment by dai-shi** [comment]
`loadable` returns a read-only atom, so you need to derive it again.
```js
const baseAsyncWritableAtom = atom(...)
const readOnlyLoadableAtom = loadable(baseAsyncWritableAtom)
export const writableLoadableAtom = atom(
  (get) => get(readOnlyLoadableAtom),
  (_get, set, arg) => set(baseAsyncWritableAtom, arg)
)
```

**Comment by Bournegit** [comment]
My use case is I am loading async data and need to update it later on also and use loadable not suspense. Not sure if it is meant to be used that way. The problem here is I am not able to update the data again .For Example - If i update the data using RefreshControl.
I am getting this error - atom.write' is undefined

`import { atom,useAtom } from 'jotai';
import axios from 'axios';
import {loadable} from 'jotai/utils'


const fetchGroup = async () => {
return await axios({
        method: 'get',
        url: `/v1/groups`,
    }).then((response) => {
        return response.data;
    }).catch(function (error) {
     
        return {error:error}
    });;
}


const fetchGroupAtom= atom(
async (get) => {
    const response = await fetchGroup();
   return response;
  
});

const readOnlyLoadableAtom = loadable(fetchGroupAtom)
const writableLoadableAtom = atom(
  (get) => get(readOnlyLoadableAtom),
  async (_get, set, arg) =>{ 
      const response = await fetchGroup();
    set(fetchGroupAtom, response)

}
)

export const useGroup = () => {
    
    const [groups,updateGroups] = useAtom(writableLoadableAtom);
    
    return [groups,updateGroups];
  };`

**Comment by dai-shi** [comment]
`atomWithDefault` is to rescue.
```js
const fetchGroupAtom= atomWithDefault(async (get) => {
  const response = await fetchGroup();
  return response;
});
```

**Comment by Bournegit** [comment]
This worked. Yet to explore all the utils and use cases. Also explored how ### atomWithDefault works. 
Thank you.

**Comment by tikisailor** [comment]
> `atomWithDefault` is to rescue.
> 
> ```js
> const fetchGroupAtom= atomWithDefault(async (get) => {
>   const response = await fetchGroup();
>   return response;
> });
> ```

I am using this with an axios fetch function similar to the fetchGroup() above. When I update the writableLoadableAtom and the fetch fails it throws an error instead of setting the atom to hasError. If I catch the error within the fetch function (as in fetchGroup() above), writableLoadableAtom ends up with 'hasData' but data is undefined. Is there a way to make it update in a way that it doesn't throw but sets hasError?

**Comment by dai-shi** [comment]
Not sure if I follow 100%, but in general there would be two alternative approaches:
- store a promise itself in an atom instead of the resolved value
- do not use `loadable` and do similar things on your end

Hope it helps.

**Comment by tikisailor** [comment]
> Not sure if I follow 100%, but in general there would be two alternative approaches:
> 
> * store a promise itself in an atom instead of the resolved value
> * do not use `loadable` and do similar things on your end
> 
> Hope it helps.

Ok I found a workaround. Thanks for the prompt response.
