### ISSUE TITLE
can't update `atomWithDafault` by `set(RESET)`

### ISSUE THREAD

**Issue by SquirrelJimmy** [pmndrs/jotai#673]
some useage:
```ts
const someAtom = atomWithDafault(async (get) => return fetch('some things'));
// ...
const updateSomeThing useUpdateAtom(someAtom);
const handleUpdate = useCallback(() => {updateSomeThing(RESET)}, [updateSomeThing]);
```
It's nothing happend, the `async (get) => return fetch('some things')` not be invoke, What's more,
![image](https://user-images.githubusercontent.com/24666536/130402091-6c93973a-1cc0-4d34-acdf-de4addc38e66.png)

**Comment by dai-shi** [comment]
Isn't this because you never overwrite the default value?
`RESET` is to reset an overwritten value. It's not to "retry" or "rerun" the getter.

For "rerun" pattern, does this work for you?
```js
const fetchFunc = async () => 'some things'
const someAtom = atomWithDafault(fetchFunc)
const updateSomeThing = useUpdateAtom(someAtom)
const handleUpdate = useCallback(() => {updateSomeThing(fetchFunc())}, [updateSomeThing])
```

**Comment by SquirrelJimmy** [comment]
> Isn't this because you never overwrite the default value?
> `RESET` is to reset an overwritten value. It's not to "retry" or "rerun" the getter.
> 
> For "rerun" pattern, does this work for you?
> 
> ```js
> const fetchFunc = async () => 'some things'
> const someAtom = atomWithDafault(fetchFunc)
> const updateSomeThing = useUpdateAtom(someAtom)
> const handleUpdate = useCallback(() => {updateSomeThing(fetchFunc())}, [updateSomeThing])
> ```
what do I do if `fech` need some `params` that comes from some `atoms`? Like this
```
const someAtom = atomWithDafault(async (get) => {
   const params = get(someParamsAtom);
   return fetch('some things', params)
});
// ...
const updateSomeThing useUpdateAtom(someAtom);
const handleUpdate = useCallback(() => {updateSomeThing(RESET)}, [updateSomeThing]);
```

**Comment by dai-shi** [comment]
I would probably create another atom.

```js
const someBaseAtom = atomWithDafault(async (get) => {
   const params = get(someParamsAtom);
   return fetch('some things', params)
})
const someAtom = atom(
  (get) => get(someBaseAtom),
  (get, set) => {
    const params = get(someParamsAtom)
    set(someBaseAtom, fetch('some things', params))
  }
)

  // in component
  const refetch = useUpdateAtom(someAtom)
  const handleUpdate = refetch
```

We could make a creator to avoid repetition. I didn't do it for showing the pattern first.

This is basically mixing declarative fetch and imperative fetch, which is somewhat confusing.

I would rather recommend to focus on imperative pattern if possible.

```js
const someBaseAtom = atom(null)
const someAtom = atom(
  (get) => get(someBaseAtom),
  (get, set) => {
    const params = get(someParamsAtom)
    set(someBaseAtom, fetch('some things', params))
  }
)

  // in component
  const refetch = useUpdateAtom(someAtom)
  const handleUpdate = refetch
  useEffect(() => { refetch }, [refetch])
```

There are some techniques to improve this pattern, like `atomWithReducer` and `onMount`.

**Comment by dai-shi** [comment]
> I would rather recommend to focus on imperative pattern if possible.

The flip side is to focus on declarative pattern.

It's a bit tricky but you might like it.

```js
const retryAtom = atom(1)
const someBaseAtom = atom(async (get) => {
  get(retryAtom)
  const params = get(someParamsAtom);
  return fetch('some things', params)
})

  // in component
  const retry = useUpdateAtom(retryAtom)
  const handleUpdate = useCallback(() => retry((c) => c + 1), [retry])
```

**Comment by SquirrelJimmy** [comment]
> > I would rather recommend to focus on imperative pattern if possible.
> 
> The flip side is to focus on declarative pattern.
> 
> It's a bit tricky but you might like it.
> 
> ```js
> const retryAtom = atom(1)
> const someBaseAtom = atom(async (get) => {
>   get(retryAtom)
>   const params = get(someParamsAtom);
>   return fetch('some things', params)
> })
> 
>   // in component
>   const retry = useUpdateAtom(retryAtom)
>   const handleUpdate = useCallback(() => retry((c) => c + 1), [retry])
> ```

I have did this by anothore atom, like :
```ts
export function atomWithRefetch<Value>(getDefault: Read<Value>) {
  const overwrittenAtom = atom<Value | null>(null);
  const anAtom: WritableAtom<Value, undefined> = atom(
    (get) => {
      const overwritten = get(overwrittenAtom);
      if (overwritten !== null) {
        return overwritten;
      }
      return getDefault(get);
    },
    (get, set) => {
      const res = getDefault(get);
      if (res instanceof Promise) {
        res.then((v) => {
          set(overwrittenAtom, v);
        });
      } else {
        set(overwrittenAtom, res);
      }
    }
  );
  return anAtom;
}
```
Thank you, man! `atomWithDefault` is confusing me.
