### ISSUE TITLE
any idea why my test case fails?

### ISSUE THREAD

**Issue by chj-damon** [pmndrs/jotai#684]
```ts
type UserInfo = { name: string; age: number };

export const userInfoAtom = atom<UserInfo | null>(null);

export const fetchUserInfoAtom = atom(null, async (_, set) => {
  const userInfo = await new Promise<UserInfo>(resolve => {
    setTimeout(() => {
      resolve({ name: 'damon', age: 31 });
    }, 2000);
  });
  set(userInfoAtom, userInfo);
});
```

my test case is:
```ts
test('should get user info after 2000ms delay', async () => {
  const { result, waitForNextUpdate } = renderHook(() => useUpdateAtom(fetchUserInfoAtom));
  const { result: userInfo } = renderHook(() => useAtomValue(userInfoAtom));

  result.current();

  await waitForNextUpdate();

  expect(userInfo.current).not.toBeNull();
});
```

it would fail:
![图片](https://user-images.githubusercontent.com/4902684/131608773-b8122fa5-2d93-4f7d-abf5-c54203e7354c.png)

I have no idea why it doesn't work.

**Comment by chj-damon** [comment]
reproduce demo: https://codesandbox.io/s/kind-hofstadter-ncruj

**Comment by chj-damon** [comment]
I tried it in the browser, it works fine. I can get userinfo after 2s delay.

**Comment by dai-shi** [comment]
(quickly responding) Isn't it the same as https://github.com/pmndrs/jotai/issues/496#issuecomment-848349924?
> You need to create two hooks under the same Provider.

https://codesandbox.io/s/zealous-heyrovsky-w1u4t?file=/src/useOnBoardingService.test.tsx

**Comment by chj-damon** [comment]
it still fails even if I changed the code:

```ts
  test('should get user info after 2000ms delay', async () => {
    const { result, waitForNextUpdate } = renderHook(() => ({
      fetch: useUpdateAtom(fetchUserInfoAtom),
      value: useAtomValue(userInfoAtom),
    }));

    result.current.fetch();

    await waitForNextUpdate();

    expect(result.current.value).not.toBeNull();
  });
```

**Comment by dai-shi** [comment]
Looks like you for got to wrap with Provider?
```js
  const wrapper = ({ children }: any) => <Provider>{children}</Provider>;
```

**Comment by chj-damon** [comment]
no, still the same error even if I add wrapper to renderHook.

**Comment by dai-shi** [comment]
https://codesandbox.io/s/crimson-shadow-jtoeg?file=/src/countAtom.test.js
It looks like it can only wait up to 1000ms by default.

**Comment by chj-damon** [comment]
change the `timeout` config has no effect.
```ts
await waitForNextUpdate({ timeout: 5000 });
```

**Comment by chj-damon** [comment]
this is wired~ it works fine in the browser but it doesn't work in test, but I can confirm that async function without atom works fine with `react-hooks-testing-library`

**Comment by dai-shi** [comment]
> change the `timeout` config has no effect.
> 
> ```ts
> await waitForNextUpdate({ timeout: 5000 });
> ```

Nice. Updated the codesandbox.
https://codesandbox.io/s/crimson-shadow-jtoeg?file=/src/countAtom.test.js

**Comment by chj-damon** [comment]
Thanks for your help.
