### ISSUE TITLE
pass Getter to onMount: onMount(setAtom, get)

### ISSUE THREAD

**Issue by ahfarmer** [pmndrs/jotai#691]
This is such an amazing library that I am trying to move ALL of my state into Jotai. For data from the network I prefer to fetch data in the `atom.onMount` handler. This way it is always there right when I need it, and not before.

Unfortunately, some of my data can't be fetched in `onMount` because the fetch request needs to know something about the current state.

For instance, sometimes I have to use a different request path when the user is logged in vs. when they are logged out.

This is what I would love to do:

```javascript
const loggedInModeAtom = atom(false);

const feedDataAtom = atom(null);
feedDataAtom.onMount = (setAtom, get) => {
  const path = get(loggedInModeAtom) ? '/private-feed-data' : '/public-feed-data';
  fetch(path).then(response => {
    setAtom(response.data);
  });
}
```

I can't actually do that though, because onMount only passes `setAtom` - it doesn't pass `get`.  My workaround is to write a React component that fetches the data and puts it into the atom, but that isn't ideal.

Would it be possible to add `get` to onMount like this? `onMount(setAtom, get)`

**Comment by dai-shi** [comment]
To tell the truth, `onMount(get, set)` was something I originally tried and implemented. But then, it was complicated, and I noticed the API wasn't minimalistic. `onMount(setAtom)` was born after those considerations.

In jotai, we prefer creating derived atoms for almost everything. (and one of the library goals is to make derived atoms to work as lightweight as possible.)

So, in your case, you want another atom.

```js
const loggedInModeAtom = atom(false);

const feedDataAtom = atom(null);
const initFeedDataAtom = atom(null, (get, set) => {
  const path = get(loggedInModeAtom) ? '/private-feed-data' : '/public-feed-data';
  fetch(path).then(response => {
    set(feedDataAtom, response.data);
  });
};
initFeedDataAtom.onMount = (dispatch) => {
  dispatch();
};
```

There's a caveat here. Unless we use `initFeedDataAtom`, the `onMount` won't fire.

To make it more friendly without breaking the original API, here's a variant.

```js
const loggedInModeAtom = atom(false);

const INIT = Symbol(); // or anything that doesn't conflict with data.
const baseFeedDataAtom = atom(null); // this is hidden (not exported)
const feedDataAtom = atom(
  (get) => get(baseFeedDataAtom),
  (get, set, arg) => {
    if (arg === INIT) {
      const path = get(loggedInModeAtom) ? '/private-feed-data' : '/public-feed-data';
      fetch(path).then(response => {
        set(baseFeedDataAtom, response.data);
      });
    } else {
      set(baseFeedDataAtom, arg);
    }
  }
);
feedDataAtom.onMount = (dispatch) => {
  dispatch(INIT);
};
```

**Comment by ahfarmer** [comment]
That 2nd approach looks fantastic. Thank you! 👍

**Comment by dai-shi** [comment]
tbh, the `INIT` symbol idea is new. It just came up for this issue. (I used the first pattern in some places.)
