### ISSUE TITLE
useAtomMemo for recalculating derived values without a cache

### ISSUE THREAD

**Issue by ahfarmer** [pmndrs/jotai#693]
This is the problem I brought up in #690, but I think my description over there was complex and confusing.

I want to be able to write hooks that:
  * take parameters
  * conditionally fetch atom values
  * auto-update on changes to those atom values

## Naive Attempt (with crash)

Here I try to write a hook `useEventsForDevice` that conditionally returns one of two lists of events.

```javascript
const eventsByDeviceFamily = atomFamily(deviceUuid => {
  const a = atom(null);
  a.onMount = setAtom => {
    fetch(`/eventspath/${deviceUuid}`).then(response => {
      setAtom(response.events);
    });
  };
  return a;
});

// pretend these atoms also differ by deviceUuid
const liveEventsFamily = atomFamily(deviceUuid =>
  atom([{ timestamp: 103403000 }])
);

function useEventsForDevice(live, deviceUuid) {
  if (live) {
    return useAtomValue(liveEventsFamily(deviceUuid));
  }

  // very important that we not mount this atom and fetch
  // these past events while we are live
  return useAtomValue(allEventsFamily(deviceUuid));
}
```

Obviously the above code won't work because we get a React crash: "React has detected a change in the order of Hooks", because that second `useAtomValue` is only called sometimes.

## Can I use an atom?

No, the atom can't take my 'live' or 'deviceUuid' parameters.

## Can I use an atom family?

Yes, but then the result will be cached. That would look like this:

```javascript
atomFamily(
  ([live, deviceUuid]) =>
    atom(get =>
      live
        ? get(liveEventsFamily(deviceUuid))
        : get(allEventsFamily(deviceUuid))
    ),
  deepEqual
);
```

This is fine except that I really don't want to cache anything.

## Can I use useAtomCallback?

Sure, but then it will be async and it won't update in response to changes in upstream atoms.

## Ideal Interface: useAtomMemo

I think what I ideally want is this:

```javascript
function useEventsForDevice(live, deviceUuid) {
  return useAtomMemo(get => {
    if (live) {
      return get(liveEventsFamily(deviceUuid));
    }
    return get(allEventsFamily(deviceUuid));
  });
}
```

It should recalculate whenever any of my atoms or arguments change.

**Comment by dai-shi** [comment]
Okay, let me post the same idea as in #690.

```js
function useEventsForDevice(live, deviceUuid) {
  return useAtomValue(useMemo(atom(get => {
    if (live) {
      return get(liveEventsFamily(deviceUuid));
    }
    return get(allEventsFamily(deviceUuid));
  }), [live, deviceUuid]));
}
```

I use this pattern quite a lot, when atom depends on props.

I wonder if you use case additional requirement that is not covered by this pattern.

**Comment by ahfarmer** [comment]
Yes yes yes - I finally understand. You have an answer for everything! 👍
