### ISSUE TITLE
[Discussion] Async get function will not be waited for

### ISSUE THREAD

**Issue by jonaswre** [pmndrs/jotai#695]
I came across a bug

When you have a read only atom that does something async and you get that from Write Function of another atom the async part is not awaited. I've created a repo which reproduced the error.

The expected behavior would be when I press the "Fetch" Button it loads the HackerNews Story, but it throws an error and loads it on the 2nd click.

[Jotai_Async_Bug](https://github.com/jonaswre/Jotai_Async_Bug)

In the following File you can find the jotai code.
https://github.com/jonaswre/Jotai_Async_Bug/blob/c06b1ab9e49231a761a0875505a4479c083d89bc/src/jotai.ts

Thanks alot!

**Comment by jonaswre** [comment]
Maybe this is intended? 
I've realised that a warning is shown. I think that warning was supressed in my realworld example.

"Reading pending atom state in write operation. We throw a promise for now." 

What can i do to resolve it?

**Comment by jonaswre** [comment]
If I replace 

`export const fetchHNStoryAtom = atom(get => get(hnStoryAtom), (get, set) => {
    const fetchData = async () => {
        const _token = get(accessTokenAtom);
        const request = await fetch("https://hacker-news.firebaseio.com/v0/item/8863.json?print=pretty");

        const data = await request.json()
        set(hnStoryAtom, data)
    }
    fetchData();
})`

with

`export const fetchHNStoryAtom = atom(get => get(hnStoryAtom), (get, set) => {
    const fetchData = async () => {
        let _token;
        try {
            _token = get(accessTokenAtom);
        } catch (error) {
            await error
            _token = get(accessTokenAtom);
        }
        const request = await fetch("https://hacker-news.firebaseio.com/v0/item/8863.json?print=pretty");

        const data = await request.json()
        set(hnStoryAtom, data)
    }
    fetchData();
})`

the problem works. But is this a valid solution?

**Comment by jonaswre** [comment]
```
export const fetchHNStoryAtom = atom(get => get(hnStoryAtom), (get, set) => {
    const fetchData = async () => {
        let _token;
        _token = get(accessTokenAtom, true);

        const request = await fetch("https://hacker-news.firebaseio.com/v0/item/8863.json?print=pretty");

        const data = await request.json()
        set(hnStoryAtom, data)
    }
    fetchData();
})
```

Okay i've found the parameter, but can somebody explain what the parameter is for and why it's called unstable_promise.

What is unstable and what do I have to expect with the stability?

**Comment by dai-shi** [comment]
Thanks for opening this up.
Looks like you have good understanding now.

This is still an open problem. The `unstable_promise` would be a good solution, but it's still young and not yet a finalized API. That's why it's `unstable_` prefixed.

**Comment by dai-shi** [comment]
Related issues: #522 & #539

**Comment by jonaswre** [comment]
Thanks for your quick response. 

So it's prefixed unstable because the API might change not because the code is unreliable? 

And I couldn't find out from the related Issues what's causing the problem here. It seems like you found a solution. What's the reason not to default to is? And maybe an explainer should go into the aysnc part of the docs. Just so that people who get the warning have a chance to find something about it.

**Comment by dai-shi** [comment]
It's more about API design and TS issue, and docs issue. I don't think it's very easy to understand because everywhere else we don't see a promise on read thanks to Suspense.
This means, your first trial https://github.com/pmndrs/jotai/issues/695#issuecomment-915515939 is still valid and more consistent with Suspense. But, Suspense for this use case is still not finalized, so we hold it too.

If we want more options in the future, `{ promise: true }` might be better, but we even consider this as bundle size increase.
Finally, if you make it default, you would have to always type check if the result is a promise or not, even though you never use async at all.

Overall, I'm not yet confident.

**Comment by dai-shi** [comment]
I'll close this for now as we have nothing actionable now.
We actually want more feedback on `unstable_promise`.
For anyone, please leave comments here, and feel free to open [a new discussion](https://github.com/pmndrs/jotai/discussions/new).
