### ISSUE TITLE
[Question] Readable atom with parameter or Another way

### ISSUE THREAD

**Issue by imjuni** [pmndrs/jotai#707]
Thank for great works. 

I have some question, I develop custom calendar component.

Calendar component have selection map, for example:

```ts
// row are number of weekday, col are 7
const calendarSelectionMap: boolean[][] = [];
```

But, Calendar component don't know user selected month so dynamic generation array on render time.

```ts
// phase 01, create component
const [state, dispatch] = useReducerAtom(mainAtom, reducer);
const rowCount: number = calculateCalendarRowCount(userSelectedMonth);
const days = calculateCalendarDay(userSelectedMonth);

useLayoutEffect(() => {
// phase02 initialize component state
dispatch({ type: 'create-selection-map', rowCount })
}, [ state, dispatch ]);

// phase03 render dom: only example
return (
    {_.times(rowCount).map((rowId) => {
      <div>
          {_.times(7).map((colId) => <div selected={{state.selection[rowId][colId]}}>{days[rowId][colId]}</div>
      </div>
    })}
);
```

but I got exception phase03, react SSR executed phase01 -> 03 -> 02. 

I solve this problem that create wrapper function.

```ts
const onGetSelection = useCallback((rowId: number, colId: nubmer) => {
    try { 
       return state.selection[rowId][colId];
    } catch {
       return false;
   }
}, [state])
```

But I want use state value direct below,

```html
<div selected={{state.selection[rowId][colId]}}>{days[rowId][colId]}</div>
```

So, I Think that 

```ts
const readableAtom = atom(mainAtom, (get, param) => {
  const state = get(mainAtom); 

  try {
    return state.selection[param.rowId][param.colId];
  } catch {
    return false;
  } 
});
```

But I can't found readable atom with any parameter. I miss understood mechanism?

Thank you for kindness

**Comment by dai-shi** [comment]
From the last example, I'd say, you want to put param in an atom.
```js
const paramAom = atom()
const readableAtom = atom((get) => {
  const state = get(mainAtom)
  const param = get(paramId)
  try {
    return state.selection[param.rowId][param.colId];
  } catch {
    return false;
  } 
})
```

But, from the description about phase03, it seems like you can just early return if you don't have selection.
```jsx
  // phase03
  if (!state.selection) {
    return null
  }
  return ...
```

If you can create a small example in codesandbox, we should be able to help more easily.

**Comment by imjuni** [comment]
@dai-shi Hi, 

Thank you for your reply.

I create [codesandbox](https://codesandbox.io/s/react-jotai-calendar-example-1ckt3?file=/src/Calendar.tsx:1245-1586).

This is very simple calendar using by luxon.

Your answer is readableAtom parameter need create atom.

And I want change parameter, I have to use `setState` function, right?

Thank you.

**Comment by dai-shi** [comment]
Okay, thanks for the codesandbox example.
So, I'm a bit unsure if I understand your goal.
It seems `getSelection` does its good job as is.
So, is this only the question about SSR, or are there any improvements you want in CSR?

**Comment by imjuni** [comment]
@dai-shi 

Dear dai-shi, 

Thank you for kindness. 

1. Not related to SSR, only CSR (I think that SSR way find myself)
2. I want to know that jotai ideal way or efficient way

I fork another example code codesandbox: [codesandbox](https://codesandbox.io/s/react-simple-calendar-forked-utlw5?file=/src/Calendar.tsx)

But this example not work, because readable atom trigger rerender, so meet too-many rerender.

Thank you.

**Comment by dai-shi** [comment]
Hm, you can't call `writePosState` in render. Your previous `getSelection` looks better. Why do you want something like `getSelectionAtom`? Feels like I'm missing the goal here.

Sorry, if my `posAtom` suggestion was confusing. So far, your previous codesandbox looks good.

**Comment by imjuni** [comment]
@dai-shi 

Because I think that readable atom with parameter, looks like a writable atom.

```ts
const readableAtom = atom((get, by) => {
  const state = get(mainAtom)
  try {
    return state.selection[by.rowId][by.colId];
  } catch {
    return false;
  } 
})
```

But document and your answer is below,

```ts
const paramAom = atom()
const readableAtom = atom((get) => {
  const state = get(mainAtom)
  const param = get(paramId)
  try {
    return state.selection[param.rowId][param.colId];
  } catch {
    return false;
  } 
})
```

I think mutation of two atom that is not good way for this situation. Because render need getSelection. I think that move getSelection in atom file. I want to state management code in single file. 

Thank you.

**Comment by dai-shi** [comment]
Okay, let's step back and consider a simple case.

Suppose we have a list of todos:
```js
const todosAtom = atom([
  { id: 1, title: 'aaa' },
  { id: 2, title: 'bbb' },
  { id: 3, title: 'ccc' },
])
```

If you want an atom to read id=1 item:
```js
const todo1Atom = atom((get) => get(todosAtom).filter((todo) => todo.id === 1))
```

You can't create an arbitrary atom that holds a single item. What you can do is to create a function:
```js
const getTodoItemAtom = (id) => atom((get) => get(todosAtom).filter((todo) => todo.id === id))
```

But, if you are reading the entire todosAtom in your component, creating each todoItemAtom is just an overhead. So, just having a function makes more sense:

```js
const getTodoItem = (todos, id) => todos.filter((todo) => todo.id === id)
```

You can define such a function in your separate file with atom definitions (recommended).

Now, if you want to define such a function inside an atom definition, you could try this.
```js
const getTodoItemAtom = atom((get) => {
  const todos = get(todosAtom)
  const getTodoItem = (id) => todos.filter((todo) => todo.id === id)
  return getTodoItem
)
```

**Comment by imjuni** [comment]
@dai-shi 

Thank you for your answer.

Great! that is perfect solution for my case. I don't think that readable atom will be able to function.

Very helpful talk.

Maybe, I think your example `getTodoItemAtom` is add to primitives document it is great helpful content. 

Thank you!

**Comment by dai-shi** [comment]
> Maybe, I think your example getTodoItemAtom is add to primitives document it is great helpful content.

I wouldn't at this point, as it's not the primary recommendation. BUT, it might turn out to be something good with possibly other practice, so I will keep that in mind.

Let me leave another pattern with a custom hook, which may seem more idiomatic (not explicitly suggesting it, but just to expand our ideas):
```js
const useGetTodoItemAtom = () => {
  const [todos] = useAtom(todosAtom)
  const getTodoItem = (id) => todos.filter((todo) => todo.id === id)
  return getTodoItem
)
```

**Comment by Moizsohail** [comment]
Just leaving this here as an update. 
```
const getTodoItemAtom = (id) => atom((get) => get(todosAtom).filter((todo) => todo.id === id))
```
The above code is not a good idea. It causes infinite rendering error.
