### ISSUE TITLE
[Question] "Unsubscribed" dependencies in read function

### ISSUE THREAD

**Issue by frissonlabs** [pmndrs/jotai#708]
Is there a way to retrieve the latest value of an atom but not subscribe to it (make it a dependency) from another atom's read function?

I have a scenario where I have some reinitialization logic that needs to get called when a certain variable changes. I've modeled this with an atom that has the logic in the read function and the variable as a separate atom that is referenced using "get", so the logic executes every time this variable changes. However, this logic also needs the latest value from another atom, but should not execute when it changes. Ideally, I'm hoping to avoid using the write function since I'd like keep atoms that are depended on unaware of their dependents and, thus, not responsible for notifying their dependents when it's updated.

Is this possible?

**Comment by dai-shi** [comment]
The short answer is no. `get` is always reactive.
We have a hack of using ref, but I wouldn't recommend it in user space code.
Instead, there is `selectAtom` util. It accepts custom equality function, so I hope you can model your atoms using this.

>  avoid using the write function

If we use `write`, there can be another solution. Basically, `read` must be "pure", but `write` doesn't have such a limitation.
