### ISSUE TITLE
Upgrading from 1.3.3 to 1.3.4 gives worrying build-time warnings

### ISSUE THREAD

**Issue by tomhicks** [pmndrs/jotai#709]
I'm using jotai in a Next.js project, with nothing special in particular with the setup.

When I upgrade to 1.3.4 I get this in the build output, which seems reasonably important. My guess is that it's to do with the way the exports were changed to use wildcards?

Reverting back to 1.3.3 removes the warning.

```
warn  - ./node_modules/jotai/esm/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/jotai/esm/utils.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/jotai/esm/utils.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

**Comment by dai-shi** [comment]
Thanks for reporting. It sounds like so... Exports is hard...
Would you help me reproduce this? Any steps to follow?

**Comment by tomhicks** [comment]
hang on let me try to get a minimal repro

**Comment by tomhicks** [comment]
```
yarn create-next-app
yarn add jotai
```

```typescript
import {atom, useAtom} from "jotai"
const numberAtom = atom(5)

export default function Home() {
  const [value, setValue] = useAtom(numberAtom)

  React.useEffect(() => {
    setInterval(() => {
      setValue((old) => old + 1)
    }, 1000)
  }, [setValue])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        ... rest of the Home component here
```

`npm run dev`

```
warn  - ./node_modules/jotai/esm/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

**Comment by tomhicks** [comment]
^^ Essentially... use jotai 😂

**Comment by dai-shi** [comment]
Thanks for the steps. It's reproducible.
It has nothing to do with wildcards.

It seems the following code in `jotai/esm/index.js` causes the message.
```js
typeof require !== "undefined" ? require : (x) => {
  throw new Error('Dynamic require of "' + x + '" is not supported');
};
```

I don't think it's important. You can ignore for now.

I guess some of build tool updates caused this. 🤔

**Comment by dai-shi** [comment]
This seems to fix the issue.
```diff
diff --git a/package.json b/package.json
index d8b6b96..3d12b2e 100644
--- a/package.json
+++ b/package.json
@@ -137,7 +137,7 @@
     "benny": "^3.6.15",
     "concurrently": "^6.2.1",
     "downlevel-dts": "^0.7.0",
-    "esbuild": "^0.12.27",
+    "esbuild": "0.12.25",
     "eslint": "^7.32.0",
     "eslint-config-prettier": "^8.3.0",
     "eslint-import-resolver-alias": "^1.1.2",
```

https://github.com/evanw/esbuild/releases/tag/v0.12.26 changed something.
The new one seems to fail to eliminate dead code.

**Comment by tomhicks** [comment]
Interesting. As I understand it (my knowledge could be 5 years out of date though), exact calls to `require("some-literal-string")` can be statically analysed, so possibly the fact that here `require` is replaced might mean it can't do the same static analysis.

Is that `require = require ?? somethingElse` part a common pattern?

**Comment by prichodko** [comment]
FYI, this is also happening in Next.js, which doesn't use `esbuild`.

**Comment by sandren** [comment]
This is happening in Gatsby as well.

**Comment by Thisen** [comment]
Just to be clear, this is caused by the version of `esbuild` that builds `jotai`, it's not because of the consumers environment.

**Comment by israelidanny** [comment]
Can confirm, happening to me with next.js as well
