### ISSUE TITLE
[Question] Ways to work with derivatives for heavily nested data

### ISSUE THREAD

**Issue by s-apalon-b** [pmndrs/jotai#714]
Hey everyone,
I've got a question regarding working with derivatives for heavily nested data.

Let's imagine we have received data with such structure from our back-end:

```
[
    {
        "someProperty1": 1,
        "someProperty2": 2,

        "nestedCollection": [
            {
                "nestedProperty1": 1,
                "nestedProperty2": 2,
            },
            {
                "nestedProperty3": 3,
                "nestedProperty4": 4,
            },
        ],

        "someObj": {
            "nestedProperty1": {
                "moreNestedProperty1": 1,
                "moreNestedProperty2": 2,
            },
            "nestedProperty2": {
                "moreNestedProperty1": 1,
                "moreNestedProperty2": 2,
            },
        }
    },

    {
        "someProperty1": 3,
        "someProperty2": 4,

        "nestedCollection": [
            {
                "nestedProperty1": 1,
                "nestedProperty2": 2,
            },
            {
                "nestedProperty3": 3,
                "nestedProperty4": 4,
            },
        ],

        "someObj": {
            "nestedProperty1": {
                "moreNestedProperty1": 1,
                "moreNestedProperty2": 2,
            },
            "nestedProperty2": {
                "moreNestedProperty1": 1,
                "moreNestedProperty2": 2,
            },
        }
    },
]
```

Also we have atom with weight unit value, e.g. `const unitAtom = atom ('kilogram') ;`. It might be changed to pounds or milligrams.

Now let's assume that each of the nested properties (e.g. `someProperty1`, `nestedProperty2`, `moreNestedProperty1`, etc) is a kilogram and it might be consumed by any React component.

What would be the preferred way to create derivatives to read different nested props, which would take into account conversions to pounds or milligrams?

For example if unitAtom's value is changed to pounds all the derivatives should take this into consideration and return converted data from kilograms to pounds as well.

Regards!

P.S. Great work, guys 👍

**Comment by dai-shi** [comment]
If your single component reads all the nested data, you could simply create a derived atom to create a whole nested data with conversion. It will only re-evaluated when the unit is changed.

If your each component reads part of the nested data, you might want to convert in the render function.

There can be some misunderstanding of mine. You want to share how your components would use the atoms, and what is a pain.

**Comment by s-apalon-b** [comment]
Thanks for a quick response and sorry for my poor explanation.

Options of consuming data in components could be different, for example:
```
const { someProperty1, moreNestedProperty2  } = useAtomValue(derived1Atom);
```
or
```
const { nestedCollection, nestedProperty4  } = useAtomValue(derived2Atom);
```
Let's assume `derived2Atom` and `derived1Atom` are derivatives from `convertedDataAtom` described below.

My main idea now is to create one big atom with initial data and then make derived one where I'll track all unit changes and apply conversions to fields which should be changed. It would be great to keep all these conversions in one place.

Some pseudo-code as example:
```
const initialNestedDataAtom = atom({...});
const unitAtom = atom('kilogram');

const conversionsAwareDataAtom = atom(get => {
  const unit = get(unitAtom);
  const initialNestedData = get(initialNestedDataAtom);
  
  // apply conversions to all nested props
})
```

After that my components might be able to read only needed parts of the data from derived (convertible) atom and it always would be properly converted.

So the pain comes when I need to apply all these conversions. My data is nested collection and I'm struggling to keep code readable and I'm afraid to miss anything during the process of conversion. Maybe it would be easier to normalize it before converting or split it.

Could you give me a piece of advice how you'd do it please?

Hope it's clear now :)

Regards!

**Comment by dai-shi** [comment]
> ```js
> // apply conversions to all nested props
> ```

If I understand this correctly, this pain is not jotai specific, but pure js task to manipulate nested objects.
If that's the case, how about using immer? Or maybe some other fp-like libs that handle it.

> My data is nested collection and I'm struggling to keep code readable and I'm afraid to miss anything during the process of conversion. 

Would you be able to share some code that you think is not very readable and want to improve?

**Comment by s-apalon-b** [comment]
@dai-shi yep, you are right.
It seems I've managed to make it more readable by using some fp utils.

Thanks for you help and sorry for wasting your time!
