### ISSUE TITLE
Destructuring lost reference

### ISSUE THREAD

**Issue by eduardodallmannAmbev** [pmndrs/jotai#715]
All tests are the same thing, the difference is destructuring of result of renderHook

https://codesandbox.io/s/focused-glitter-9ixgx?file=/src/ok.test.ts

Is this issue related to Jotai? Or @testing-library/react-hooks?

**Comment by dai-shi** [comment]
I'm not super familiar with testing-library/react-hooks, but destructuring `current` doesn't seem correct. Does it work with `React.useState`?

**Comment by eduardodallmannAmbev** [comment]
Good question... Really `React.useState` not work too. But destructuring is correct, I add a new test on codesandbox with destructuring step by step. Thanks for help, I go open issue in testing-library/react-hooks
