### ISSUE TITLE
Get all key/value pairs from AtomFamily

### ISSUE THREAD

**Issue by KevinMusgrave** [pmndrs/jotai#722]
In one component, I'm adding key/value pairs to AtomFamily. In another component, I need to read all key/value pairs currently in that AtomFamily. Is there a way to do this?

**Comment by dai-shi** [comment]
I haven't thought about such use cases (it doesn't feel good practice), but yeah it can be useful in some cases.

Maybe something like this?
```diff
--- a/src/utils/atomFamily.ts
+++ b/src/utils/atomFamily.ts
@@ -6,6 +6,7 @@ type AtomFamily<Param, AtomType> = {
   (param: Param): AtomType
   remove(param: Param): void
   setShouldRemove(shouldRemove: ShouldRemove<Param> | null): void
+  keys(): IterableIterator<Param>
 }
 
 export function atomFamily<Param, Value, Update>(
@@ -74,5 +75,8 @@ export function atomFamily<Param, Value>(
       }
     }
   }
+
+  createAtom.keys = () => atoms.keys()
+
   return createAtom
 }
```

They are just keys, not entries. We want to call the function to get a value to make it sure that `shoudRemove` works.

**Comment by KevinMusgrave** [comment]
What's the best way to get all the values?

I can loop through the keys and grab the value from the ```atomFamily```.

```javascript
const output = {};
for (let k of family.keys()) {
  output[k] = family(k);
}
```

But I'm not sure how to use this in a component with a ```useAtomValue``` hook.

**Comment by dai-shi** [comment]
If you want to read all values in a single hook, you want to create a new derived atom.
```js
const familyValuesAtom = atom((get) => {
  const output = {};
  for (let k of family.keys()) {
    output[k] = family(k);
  }
  return output
})
```

However, this is not reactive to family.keys(). To make it reactive, you would need to keep keys in an atom, so that means `family.keys()` doesn't help much in this case.
If I were to deal this case, I'd prefer atoms-in-atom pattern. https://docs.pmnd.rs/jotai/guides/atoms-in-atom

Another hacky solution is to have a family version atom.
```js
const familyVersionAtom = atom(0)
const familyValuesAtom = atom((get) => {
  get(familyVersionAtom) // add dependency
  const output = {};
  for (let k of family.keys()) {
    output[k] = family(k);
  }
  return output
})
```
Whenever you create a new family item, increment the version.

My suggestion is to keep keys in another atom, if you would like to use atomFamily.

**Comment by KevinMusgrave** [comment]
Should I stick with atomFamily if I need to add/remove keys at runtime?

**Comment by dai-shi** [comment]
It's up to you as both work. I'd prefer atoms-in-atom pattern, because garbage collection should work. tbh, I never use atomFamily in my coding.

**Comment by KevinMusgrave** [comment]
Is there an example that shows how to add keys using the atoms-in-atoms pattern?

**Comment by dai-shi** [comment]
In the atoms-in-atom pattern, we don't have keys, atoms (configs) are keys.

Hope these help:
- https://docs.pmnd.rs/jotai/guides/atoms-in-atom#storing-an-array-of-atom-configs-in-atom
- https://github.com/pmndrs/jotai/tree/main/examples/todos

**Comment by KevinMusgrave** [comment]
Thanks for the help
