### ISSUE TITLE
Improve typing of Atom, so if value of Value, is a promise, it still typecheck

### ISSUE THREAD

**Issue by tychota** [pmndrs/jotai#725]
# Context

I'm writing a persistence helper for React Native that need the async / [suspense](https://docs.pmnd.rs/jotai/basics/async) parts to works.

The working version is roughly: https://gist.github.com/tychota/7d07d83f957b78a7c3f5ada263c4dd19

As you can see there is a `@ts-ignore` around line 23.

If we blindly trust TS and change this to https://gist.github.com/tychota/56da7d74c978a7c3dfbfdc29f0540768, then everything typecheck but there is a subtle race condition.

Eg if we do...

```ts
const accessToken = atomWithAsyncStorage('accessToken', null)
```

...the initial call are done without access token.

# Problem

![image](https://user-images.githubusercontent.com/13785185/134022493-2aa92499-cdad-479f-b02b-eeb90053ba6c.png)

The generated `d.ts` seems to forget the case where the Value is a Promise. I think of something like (!! untested !!):

```diff
export declare function atom<Value, Update>(read: Read<Value>, write: Write<Update>): WritableAtom<Value, Update>;
export declare function atom<Value, Update>(initialValue: Value, write: Write<Update>): [Value] extends [Function] ? never : WritableAtom<Value, Update> & WithInitialValue<Value>;
export declare function atom<Value>(read: Read<Value>): Atom<Value>;
export declare function atom<Value>(initialValue: Value): [Value] extends [Function] ? never : PrimitiveAtom<Value> & WithInitialValue<Value>;
-export declare function atom<Value extends unknown>(initialValue: Value): [Value] extends [Function] ? never : PrimitiveAtom<Value> & WithInitialValue<Value>;
+export declare function atom<Value extends unknown>(initialValue: Value): [Value] extends [Function] ? never : [Value] extends [Promise<infer U>]: PrimitiveAtom<U> & WithInitialValue<U> :  PrimitiveAtom<Value> & WithInitialValue<Value>;
```

# Solution

Do you agree with my understanding of the problem?

Would you be open to a PR fixing the typing?

**Comment by tychota** [comment]
Note, it is probably fixed by (draft) PR https://github.com/pmndrs/jotai/pull/713

**Comment by dai-shi** [comment]
Yeah, when I originally designed types, a promise as a value wasn't supported.
#713 is to address it as you see.
Can you try if it works for you?
See [codesandbox ci comment](https://github.com/pmndrs/jotai/pull/713#issuecomment-921009525) and click "here" in the comment. You will find "Local Install Instructions".

**Comment by tychota** [comment]
@dai-shi I would like but I'm lost with the new typing.

![image](https://user-images.githubusercontent.com/13785185/134147822-fcb27194-a902-4687-8a4b-565c1a43787e.png)

I try a bunched but I'm not sure exactly what to do.

Lets discuss here

## baseAtom

```diff
-const baseAtom: PrimitiveAtom<T> = atom<T>(getInitialValue());
+const baseAtom = atom<Promise<T>>(getInitialValue());
```

But now there is an error on onMount

![image](https://user-images.githubusercontent.com/13785185/134148687-cb302855-41ee-4d86-9f90-38f8fdb1d2b2.png)

## derivedAtom

I've tried blindly something like 

![image](https://user-images.githubusercontent.com/13785185/134148835-76fdeb25-8e79-4ada-b8c8-037b5fbb1fc6.png)

but looks just like I'm trying to program by coincidence :)

**Comment by dai-shi** [comment]
```ts
const baseAtom = atom<Promise<T>>(getInitialValue());
```
This means read-only atom, which is not what you meant.

There are several options.
```ts
const baseAtom = atom(getInitialValue()); // maybe this is easier
const baseAtom: PrimitiveAtom<T | Promise<T>> = atom(getInitialValue()); // in case you want Non Promise type
const baseAtom = atom<Promise<T>, SetStateAction<Promise<T>>, void>(getInitialValue()); // this is full annotation
```

**Comment by dai-shi** [comment]
https://user-images.githubusercontent.com/13785185/134148835-76fdeb25-8e79-4ada-b8c8-037b5fbb1fc6.png

Maybe something like this.
```js
const derivedAtom = atom<T | Promise<T>, Update<T>, void>(...)
```

I would be nice if we have an example in codesandbox to work with.

**Comment by tychota** [comment]
Thank for all this, I will do a minimal example in codesandbox.

**Comment by tychota** [comment]
@dai-shi here you are https://codesandbox.io/s/happy-goldwasser-y7hy1

**Comment by dai-shi** [comment]
Here you go: https://codesandbox.io/s/jolly-cerf-vwfh7?file=/src/utils/atomWithAsyncStorage.ts

> ```ts
> const baseAtom = atom<X, SetStateAction<X>, void>(getInitialValue()); // this is full annotation
> ```

☝️ That was my bad. The correct on is this. 👇 

```ts
const baseAtom = atom<X>(getInitialValue()); // this is a primitive atom
```

In your case, you want `T | Promise<T>`, because you use both types.

**Comment by dai-shi** [comment]
@tychota Hi, #713 is improved. Would you try it again?

**Comment by tychota** [comment]
Hi, thanks for the updated sandbox.

What would you like me to test? I looked at the PR ans have seen that now the third parameter default to `void` (but we should use `Promise<void>`, right ? ) and that now an atom is `Atom<T | Promise<T>>` by default.

**Comment by dai-shi** [comment]
If you have a project using jotai, I would like to know how it works with the PR. Basically, we want to be confident about merging the PR.

**Comment by tychota** [comment]
Will do later today.
