### ISSUE TITLE
import from 'jotail/utils' throwing an error

### ISSUE THREAD

**Issue by Kerumen** [pmndrs/jotai#73]
```ts
import { useUpdateAtom } from 'jotai/utils'
```

I'm using Next.js and when I try to import from `jotai/utils` it's throwing this error:

<img width="981" alt="Screenshot 2020-09-30 at 16 30 24" src="https://user-images.githubusercontent.com/5436545/94699116-44ab5e00-033a-11eb-9ccc-b85abb83eefa.png">

**Comment by dai-shi** [comment]
Hi, does this help?

```js
import { useUpdateAtom } from 'jotai/utils.cjs.js'
```

We may need to reconsider dist file names for node server environment..

**Comment by Kerumen** [comment]
@dai-shi Yes but then I have the following TS error:

```
Could not find a declaration file for module 'jotai/utils.cjs'.
```

**Comment by dai-shi** [comment]
Oh,,, right. I wonder how other libs solve this bundling issue...

**Comment by Kerumen** [comment]
Why don't you expose everything from the main entry point?

**Comment by dai-shi** [comment]
Because I want to explicitly split utils out of core. We took the same approach as zustand.
I'll make a small PR and would like you to see if it works. One moment.
