### ISSUE TITLE
Possible bug with atom derived from variable sized splitted atom

### ISSUE THREAD

**Issue by s-apalon-b** [pmndrs/jotai#736]
The following warning appears in console if derivative was created from variable sized splitted atom:
```splitAtom: array index out of bounds, returning undefined warning in console.```

Here is sandbox https://codesandbox.io/s/client-splitatom-derivative-5uir4

To reproduce the issue just start clicking on the button and check out console.

**Comment by dai-shi** [comment]
Looking at the code in store.js,
```js
export const collectionAtom = atom([]);
export const collectionAtomsAtom = splitAtom(collectionAtom);

export const derivativeAtom = atom((get) =>
  get(collectionAtomsAtom).map(
    (ca) => get(ca) + Math.round(Math.random() * 150)
  )
);
```

I would expect it's valid. The warning is added to detect possible bugs. I'm not sure if it's a real bug that should/could be solved, or if it's the expected behavior.
@Aslemammad Would you please investigate it?

**Comment by Aslemammad** [comment]
Sure! I'll do.

**Comment by dai-shi** [comment]
@Aslemammad If you have a chance, feel free to investigate it.

**Comment by Aslemammad** [comment]
sure, it's in my TODO list after useAtomDevtools.

**Comment by Aslemammad** [comment]
I'll work on this tommorrow!

**Comment by dai-shi** [comment]
@Aslemammad I just remembered that @Thisen made a failing test https://github.com/pmndrs/jotai/compare/split-atom-out-of-bounds, which might help your investigation.
