### ISSUE TITLE
Using jotai/utils in v1.3.6 on Next.js app (webpack 5) causes errors in build

### ISSUE THREAD

**Issue by tomhicks** [pmndrs/jotai#743]
`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './utils' is not defined by "exports" in /Users/tomhicks/Developer/orbital/webapp/node_modules/jotai/package.json`

Sorry for the pretty vague report.

Here's the extent of my investigation:

## 1.3.3
👍 no build errors 👍 

## 1.3.4 onwards
```
warn  - ./node_modules/jotai/esm/index.js - Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

then later on

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './utils' is not defined by "exports"
```

This stops the app from rendering. I reported the first error a while back, and it didn't seem to prevent the app from rendering, so I'm a bit confused as to why it now won't render, even on 1.3.4, where before it seemed to render fine despite the warnings.

I don't think anything else in the build chain has changed (e.g. babel) so I might be misremembering the fact that it rendered on 1.3.4 before.

**Comment by dai-shi** [comment]
Thanks. This is helpful. https://github.com/pmndrs/zustand/issues/576 is reported too.

So, this is not the error from Node, but from webpack 5.
Then, my guess is webpack 5 doesn't support "exports" subpath `*` wildcard. Oh, my. 🤦‍♂️ 
@barelyhuman how do you think we can confirm?

**Comment by barelyhuman** [comment]
I'll setup dummy projects, and I guess we can't trust CSB with this since it works in a next project there and the same happened for react-ts

**Comment by barelyhuman** [comment]
@tomhicks 
I'd like to know what version of node you are using and if it's possilble to reproduce this issue on one of the following versions 
v12.20.0,  v14.13.0

Thanks

**Comment by tomhicks** [comment]
I'm using v12.18.3. Let me try on 14...

**Comment by barelyhuman** [comment]
> I'm using v12.18.3. Let me try on 14...
You could try v12.20 if you don't want to move up to 14 

 I need the confirmation since I'm on 16 and on an M1, can't build lower versions..

**Comment by tomhicks** [comment]
Can confirm all is good on 14.13, 12.20 and 16.

**Comment by dai-shi** [comment]
@tomhicks Thanks!
Could you try #745 codesandbox build with v12.18.3 and how it complains or not?

**Comment by tomhicks** [comment]
Sorry to be a bit dim, but I'm unsure what to do to try the 745 codesandbox build! I've never used it before and I'm not sure what it's for or what I'm supposed to do.

**Comment by barelyhuman** [comment]
@tomhicks 
We want you to rollback to 12.18 
and try to use the below package to see if it warns you about unsupported version 

```
yarn add https://pkg.csb.dev/pmndrs/jotai/commit/731da603/jotai
npm i https://pkg.csb.dev/pmndrs/jotai/commit/731da603/jotai
```

**Comment by dai-shi** [comment]
oops, sorry! Please go to: https://github.com/pmndrs/jotai/pull/745#issuecomment-931065012

<img width="666" alt="image" src="https://user-images.githubusercontent.com/490574/135458289-0b24b213-c381-43c3-8006-9817b0b86e46.png">

☝️ Click "here" link

<img width="998" alt="image" src="https://user-images.githubusercontent.com/490574/135458438-bf426aa1-81a2-4809-97ac-4d51a561f483.png">

☝️ Scroll down in the right most pane.

<img width="379" alt="image" src="https://user-images.githubusercontent.com/490574/135458542-959f77ce-aeea-45d8-b3a6-f95558e25dbf.png">
☝️ The "Local Install Instructions" is what you need.

**Comment by tomhicks** [comment]
So...

```
nvm use 12.18
npm i https://pkg.csb.dev/pmndrs/jotai/commit/731da603/jotai
npm run dev
```
❌ Error
```
error - Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './utils' is not defined by "exports" in /Users/tomhicks/Developer/orbital/webapp/node_modules/jotai/package.json
```

---

```
nvm use 16
npm i https://pkg.csb.dev/pmndrs/jotai/commit/731da603/jotai
npm run dev
```
✅

---

```
nvm use 12.18
npm i jotai@1.3.3
npm run dev
```
✅

---

```
nvm use 16
npm i jotai@1.3.6
npm run dev
```
✅

---

```
nvm use 14
npm i jotai@1.3.6
npm run dev
```
✅

**Comment by dai-shi** [comment]
Thanks!!! and, that's unfortunate for me..

**Comment by tomhicks** [comment]
I guess imposing a specific node version isn't a good choice for a library author?!

Anything else I can do to help, please let me know.

I'm a huge fan and advocate for jotai - hope that helps!

**Comment by dai-shi** [comment]
Yeah, I feel like I should revert the wildcard exports for now. That's really unfortunate.
I don't know if it's really a bad choice, which could really happen and sometimes unavoidable, but the problem of this one is not easy to notice.

**Comment by barelyhuman** [comment]
Cool, no more touching package.json 😂

**Comment by tomhicks** [comment]
![image](https://user-images.githubusercontent.com/3647830/135471224-ca2ddb9d-afe3-47c6-bb26-458461e258dc.png)
