### ISSUE TITLE
Is there any way that I can get the atom name?

### ISSUE THREAD

**Issue by chj-damon** [pmndrs/jotai#744]
I defined an atom like this:
```ts
const countAtom = atom(0);
```

I want to get the atom name, which in the example is `countAtom`, to show some info. But what I get is not the exact name I want.
![image](https://user-images.githubusercontent.com/4902684/135384033-93628cbe-b282-446e-b51c-ee7223af8024.png)

**Comment by dai-shi** [comment]
I don't think it's possible at JS level.
At the current best, we provide a babel plugin to attach debugLabel.
https://docs.pmnd.rs/jotai/api/babel

**Comment by chj-damon** [comment]
nice! Thanks for your help. I should read the doc more carefully.
