### ISSUE TITLE
Chain of async dependencies with immediate resolution causes infinite loop

### ISSUE THREAD

**Issue by Pinpickle** [pmndrs/jotai#751]
This ones a bit weird, here's the reproduction: https://codesandbox.io/s/jotai-crashing-suspend-bug-vsr2b

Basically, it's possible to construct a series of atoms that creates an infinite loop.

```js
const asyncAtom = atom(async () => {
  await new Promise((resolve) => setTimeout(resolve, 2000));

  return null;
});
const derivedAtom1 = atom(async (get) => {
  // Uncomment this line to stop crashing
  // await new Promise((resolve) => setTimeout(resolve, 10));
  return get(asyncAtom);
});

const derivedAtom2 = atom(async (get) => {
  return get(derivedAtom1);
});
```

Calling `useAtom(derivedAtom2)` will cause the infinite loop.

From what I can tell, the derived atoms have to be async, but they have to resolve immediately. This is happening in an app I'm working on at the moment.

The linked codesandbox includes the fix in #747, so it's different to #742

**Comment by dai-shi** [comment]
okay, one issue after another.. Thanks for the reproduction!
Do you think you can create a failing test?
Let me merge #747 as it's good and to tackle this new one.

**Comment by dai-shi** [comment]
Pinpickle seems busy. I'm looking into it.
Just found, it works with v0.16.1. https://codesandbox.io/s/jotai-crashing-suspend-bug-forked-fdxii
Maybe not very helpful, but it's something.
