### ISSUE TITLE
How rehydrate atom?

### ISSUE THREAD

**Issue by eduardodallmann** [pmndrs/jotai#756]
I am creating an external component (will be in another package), when using it, the dev passes props.
Inside the component I want to use atoms to not use prop drilling.
How to rehydrate atom when the prop changes? Should I use another utils from jotai that i dont see?

Simulation of what I would like
https://codesandbox.io/s/prop-to-atom-b7y85

**Comment by dai-shi** [comment]
The first option is useEffect. How does it accomplish your issue?
https://codesandbox.io/s/prop-to-atom-forked-087sh

If it's another package, having a scoped Provider may fit.
If they don't fulfill the needs, combining with useHydrateAtoms might help.

**Comment by eduardodallmann** [comment]
useEffect solves my problem, but the component has too many props, I dont like to use useUpdateAtom for each atom and then set the prop on the atom in useEffect.

That would be good, or something like that
```
useHydrateAtoms([
[atomProp1, propExternal1],
[atomProp2, propExternal2],
[atomProp3, propExternal3],
//.....
], {observeChanges: true});
```

**Comment by dai-shi** [comment]
You could create a custom hook.
```js
const useUpdateAllAtoms = (tuples) => {
  const updateAllAtoms = useUpdateAtom(useMemo(() => atom(null, (get, set, tuples) => {
    tuples.forEach(([atom, value]) => { set(atom, value) }
  }), []))
  useEffect(() => { updateAllAtoms(tuples) }, [updateAllAtoms, tuples])
}

// in component
  useUpdateAllAtoms(useMemo(() => [
    [atomProp1, propExternal1],
    [atomProp2, propExternal2],
    [atomProp3, propExternal3],
  ], [...])
```

**Comment by eduardodallmann** [comment]
This is a great idea. I will try to use this here. Thanks for your help.
