### ISSUE TITLE
Recursive AST atoms [Question]

### ISSUE THREAD

**Issue by loganvolkers** [pmndrs/jotai#783]
At SaaSquatch we build a lot of AST editors libraries that edit a homogeneous tree of AST nodes of arbitrary depth. Jotai seems to be a good fit for a lot of the state management use cases, but I'm looking for some guidance on the best way of dealing with recursion.

<details>
<summary>Example JSON for an HTML AST</summary>
```json
{
    "start": 0,
    "end": 108,
    "type": "Fragment",
    "children": [
      {
        "start": 0,
        "end": 15,
        "type": "Element",
        "name": "!DOCTYPE",
        "attributes": [
          {
            "start": 10,
            "end": 14,
            "type": "Attribute",
            "name": "html",
            "value": true
          }
        ],
        "children": []
      },
      {
        "start": 15,
        "end": 16,
        "type": "Text",
        "raw": "\n",
        "data": "\n"
      },
      {
        "start": 16,
        "end": 108,
        "type": "Element",
        "name": "html",
        "attributes": [],
        "children": [
          {
            "start": 22,
            "end": 24,
            "type": "Text",
            "raw": "\n\n",
            "data": "\n\n"
          },
          {
            "start": 24,
            "end": 99,
            "type": "Element",
            "name": "body",
            "attributes": [],
            "children": [
              {
                "start": 30,
                "end": 35,
                "type": "Text",
                "raw": "\n    ",
                "data": "\n    "
              },
              {
                "start": 35,
                "end": 60,
                "type": "Element",
                "name": "h1",
                "attributes": [],
                "children": [
                  {
                    "start": 39,
                    "end": 55,
                    "type": "Text",
                    "raw": "My First Heading",
                    "data": "My First Heading"
                  }
                ]
              },
              {
                "start": 60,
                "end": 65,
                "type": "Text",
                "raw": "\n    ",
                "data": "\n    "
              },
              {
                "start": 65,
                "end": 91,
                "type": "Element",
                "name": "p",
                "attributes": [],
                "children": [
                  {
                    "start": 68,
                    "end": 87,
                    "type": "Text",
                    "raw": "My first paragraph.",
                    "data": "My first paragraph."
                  }
                ]
              },
              {
                "start": 91,
                "end": 92,
                "type": "Text",
                "raw": "\n",
                "data": "\n"
              }
            ]
          },
          {
            "start": 99,
            "end": 101,
            "type": "Text",
            "raw": "\n\n",
            "data": "\n\n"
          }
        ]
      }
    ]
}
```
</details>

## Option 1 - Build and pass atoms

My current approach is based on the [large objects guide](https://jotai.pmnd.rs/docs/advanced-recipes/large-objects). Each node is a React component that is responsible for creating and memoizing sub-atoms.

```js
function NodeEditorPassDown({ nodeAtom }) {
  const childrenAtom = useMemo(
    () => atom((get) => get(nodeAtom)?.children ?? []),
    [nodeAtom]
  );
  const childrenAtomsAtom = splitAtom(childrenAtom);
  const [childrenAtoms] = useAtom(childrenAtomsAtom);
  const [node] = useAtom(nodeAtom);
  return (
    <div>
      Type: {node.type}
      <hr />
      {childrenAtoms.map((a) => (
        <NodeEditorPassDown nodeAtom={a} key={a} />
      ))}
    </div>
  );
}
```

## Option 2 - Using scope / provider

I haven't been able to figure out if this is a good idea or not. The idea is to simplify working on nested editors, since they should be able to know about atoms in their context. The idea here is that other things can connect into the sub-atom state, without having to touch the React hooks.

My big unanswered questions are:
 - Is this an abuse of `Provider`?
 - Is React's Context a better fit?
 - Is there a way of scoping an atom's `get` method to read from a different store?
 - Is there another way of scoping and connecting stores?

Here's a **non-working** example that's trying to demonstrate the scoping/context idea.
```js
const NodeScope = Symbol();

const rootAtom = atom(root);
const scopeAtom = atom(rootAtom);

function NodeEditorScopeAware() {
  const nodeAtom = useAtom(scopeAtom, NodeScope);
  if (!nodeAtom) throw new Error("Scope missing");
  const childrenAtom = useMemo(
    () => atom((get) => get(nodeAtom)?.children ?? []),
    [nodeAtom]
  );
  const childrenAtomsAtom = splitAtom(childrenAtom);
  const [childrenAtoms] = useAtom(childrenAtomsAtom);
  const node = useAtom(nodeAtom);
  return (
    <>
      Type: {node.type}
      {childrenAtoms.map((a) => (
        <Provider scope={NodeScope} initialValues={[[scopeAtom, a]]}>
          <NodeEditorScopeAware />
        </Provider>
      ))}
    </>
  );
}
const Component = () => {
  return (
    <Provider scope={NodeScope}>
      <NodeEditor />
    </Provider>
  );
};
```

**Comment by dai-shi** [comment]
Yeah, this is still a field we don't have specific recommendations. Happy to have you on board.

First of all, option 1 is good as written in a guide. I'm not very satisfied with it either because it doesn't feel like jotai's way, and technically splitAtom is super performant. (Don't get it wrong. It should work great. My perspective is from the library implementation.)

Quoting your questions:

> * Is this an abuse of `Provider`?

Using nested Providers is a valid pattern, which can be said underrated.
So, it looks like a good approach, if it works.
Whether you need `scope` is questionable. (The provider scope is basically creating a new React Context. Is it what you would do with pure React Context?)

> * Is React's Context a better fit?

Jotai is absolutely developed on top of Context. Basically, all Context features are available in jotai.
So, if you can solve your use case with React Context, that's good.
You can keep using pure React Context, or we can try improving it with jotai atoms.

> * Is there a way of scoping an atom's `get` method to read from a different store?

I'm not sure if I understand the goal. So, you want to avoid reading a node that is not in the children?

> * Is there another way of scoping and connecting stores?

I would explore [atoms-in-atom](https://jotai.pmnd.rs/docs/guides/atoms-in-atom) pattern.

**Comment by loganvolkers** [comment]
> what's the goal of option 2 that can't be accomplished by option 1?

Option 1 is working, but the boilerplate is a bit cumbersome.

Option 2 would be about reducing prop drilling by being able to access your "in scope" node atom as a statically referenceable constant. It's about simplifying and making the node atom tree (do we say molecule?) statically defined instead of created dynamically.

This is possible for the global scoped atoms. This is possible for node scoped atoms. But if you need to connect these two molecules, you need hooks to allow recursion.

**Comment by dai-shi** [comment]
> Option 2 would be about reducing prop drilling by being able to access your "in scope" node atom as a statically referenceable constant.

Then, I'm pretty sure one good solution is: `<Provider initialValues={...}>`.
It's like what you wanted to do with "scope", but with "atom-in-atom" pattern.

**Comment by dai-shi** [comment]
> The problem with `Provider` is that it creates a new store

Oh, you are absolutely right. I was missing that. Then, Provider `scope` might come and play.

**Comment by loganvolkers** [comment]
Nice!

I'll play around with the API a bit, but I think this does a good job of removing boilerplate, decoupling components and allowing recursion. Hopefully it's also efficient.

**Comment by loganvolkers** [comment]
Thanks for your help!

**Comment by dai-shi** [comment]
Good to hear!

This is probably the first time to see the real Provider `scope` use case other than the library use case.

**Comment by loganvolkers** [comment]
Solved this with a new library https://github.com/saasquatch/jotai-molecules

There are a lot of tests and examples. Thanks for the help @dai-shi in figuring out how to create non-global atoms in some good ways.

**Comment by dai-shi** [comment]
It looks very nice!!

> Molecule scopes can be interconnected

You did it! ❤️ 

cc: @aulneau may find this interesting.
