### ISSUE TITLE
Cannot use 'in' operator to search for 'scope' in undefined

### ISSUE THREAD

**Issue by ASgmbv** [pmndrs/jotai#801]
Hi, I faced the following error:

<img width="697" alt="Screen Shot 2021-10-25 at 8 59 26 PM" src="https://user-images.githubusercontent.com/38725027/138720090-f7c5d510-58b7-42ee-b484-59dc2612faea.png">

<img width="632" alt="Screen Shot 2021-10-25 at 8 54 40 PM" src="https://user-images.githubusercontent.com/38725027/138719513-713e5c60-dd48-4564-be04-8f7297a1031b.png">

I am new to the library but it seems like a bug.

**Comment by dai-shi** [comment]
Unfortunately, v1.5.0 doesn't change the behavior. So, closing this as wontfix. Please use the workaround.
