### ISSUE TITLE
Improve docs for atomWithStorage and persistence

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#805]
https://github.com/pmndrs/jotai/pull/394#issuecomment-953346219 @jrobber 

- docs/guides/persistence.mdx should explain more about best practices with `atomWithStorage`
- `atomWithStorage` docs should explain how to use non default storage like sessionStorage and AsyncStorage
- `atomWithStorage` docs should explain how to use non JSON.parse/stringify serializer
- `atomWithStorage` docs should explain how to type atoms
- document options like `delayInit` https://github.com/pmndrs/jotai/issues/780#issuecomment-944729651
- document how to do validations and type guards

**Comment by ryandi-tiket** [comment]
`delayInit` moved from atomWithStorage option to `createJSONStorage` option? Will it be a backwards compatible change?

**Comment by dai-shi** [comment]
No, no. `delayInit` stays there. It's just `createJSONStorage` takes an option and transfers the option. It's just a syntax sugar to avoid `{ ...createJSONStorage(...), delayInit: true }`, which you said less ergonomic.

**Comment by TwistedMinda** [comment]
@dai-shi There are a few linked subjects already:
- the loadable stuff and the "no suspense" stuff
- the atomWithStorage utils stuff
- the atomWithPending stuff
- the persistence stuff
- the async stuff

I'm trying to organize that part and they're already a few issues about it.
In this issue, what's remaining to be done? It seems mostly good!
Especially the atomWithStorage examples. The persistence part has also been reworked recently.

Maybe we could close this one?

**Comment by dai-shi** [comment]
@TwistedMinda Can you check all bullet points in OP are covered?

**Comment by TwistedMinda** [comment]
@dai-shi yep to me it's kinda all good. Except the type guards which I don't know what are these :p

**Comment by dai-shi** [comment]
> document how to do validations and type guards

This is to create a custom storage and make it type safe.
Usually, if you deserialize from string-based storage, you don't have types. Type guard is a runtime solution to make it type safe (just throw if unexpected...)
For now, nobody requested this, so let's leave it and revisit in the future.

**Comment by dai-shi** [comment]
> * `atomWithStorage` docs should explain how to use non default storage like sessionStorage and AsyncStorage

Looks like sessionStorage is missing? #1220

**Comment by TwistedMinda** [comment]
@dai-shi Indeed, i'll take care of this

**Comment by Nziranziza** [comment]
I am using typescript and this is the error I get `'delayInit' does not exist in type 'AsyncStorage<string | null | undefined>'`
