### ISSUE TITLE
unable to resolve `react-dom` when used with react-native ?

### ISSUE THREAD

**Issue by a-eid** [pmndrs/jotai#81]
![Screen Shot 2020-10-03 at 1 39 16 PM](https://user-images.githubusercontent.com/19273413/94990633-eec6f800-057d-11eb-9a0c-fe8fd8ee84b6.png)

it seem to be an issue with `use-context-select` @dai-shi .

**Comment by dai-shi** [comment]
Oh!!! The single bundle doesn't work for RN... Thanks for reporting!

**Comment by a-eid** [comment]
no problem, I hope this gets resolved soon, I really like the library, 
thank you!

**Comment by a-eid** [comment]
I have another project working with `^0.7.2`, but now even if I install that version it doesn't work for some reason.
I'm not sure I understand why.

**Comment by dai-shi** [comment]
If you lock the use-context-selector version to v1.1.4, it would work.

**Comment by a-eid** [comment]
thank you. @dai-shi

**Comment by a-eid** [comment]
probably not a good idea, but I edited `yarn.lock` to lock the `use-context-selector` version.
if you want -with you instruction- I can work on a PR to fix this issue. 

thank you.

**Comment by dai-shi** [comment]
Thanks. The dependency version is already fixed in the latest version.

Anyway, I will fix it soon.
https://github.com/dai-shi/use-context-selector/pull/26 This should be it. I'd just release it and make a PR here in jotai.
