### ISSUE TITLE
devtools: useAtomsDevtools

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#811]
I was hoping #796 (and #807) would be a nice debugging tool and possibly fix #449, which turned out it's not a silver bullet.

So, here's a new idea. `useAtomsDevtools`.
We already have `useAtomDevtools` which is an atomic debugging tool using Redux DevTools Ext. (We'd like to improve it with #808.)
`useAtomsDevtools` is a catch-all version of it. It still uses Redux DevTools Ext, and it might cover some use cases that #428 would cover.

`useAtomsDevtools` will show all atoms in store (= Provider), as a single source in Redux DevTools Ext. It might be too many, but will see.

Implementation-wise, it will be similar to what we have in `useAtomsSnapshot` and `useGotoAtomsSnapshot`, and of course what we did in `useAtomDevtools`.

Time traveling is a bit of challenge, because we need to keep all snapshots locally while sending it to Redux Devtools Ext. It requires some string keys of the snapshots.

**Comment by Aslemammad** [comment]
Let me work on it now!
