### ISSUE TITLE
Prevent write-only component from unnecessary re-rendering

### ISSUE THREAD

**Issue by Newbie012** [pmndrs/jotai#814]
I decided to move from recoil to jotai. Surprisingly the transition was smooth, but there's one last thing that I couldn't figure out.

According to the [documentation](https://github.com/pmndrs/jotai#write-only-atoms) the way of using write-only atoms is as follows:

```
const [, multiply] = useAtom(multiplyCountAtom)
```

Which technically is just omitting the actual state. The thing is, it gets re-rendered whenever the value of the atom changes. In recoil, I had [useRecoilState](https://recoiljs.org/docs/api-reference/core/useRecoilState).

I made a small [codesandbox](https://codesandbox.io/s/jotai-demo-forked-3jeum?file=/src/App.js) that illustrates the re-renders.

**Comment by Newbie012** [comment]
I'm sorry. I haven't seen [useUpdateAtom](https://jotai.pmnd.rs/docs/api/utils#use-update-atom). I suggest it should be mentioned instead of the example in README.md

**Comment by dai-shi** [comment]
For `multiplyCountAtom`, it's unlikely that its value changes, so the example in README doesn't have extra re-renders.
