### ISSUE TITLE
Derive value on the fly based on dynamic input.

### ISSUE THREAD

**Issue by laclance** [pmndrs/jotai#816]
I'm trying to create a global function to get users currency based on atom config but I am not sure of the best way to do it. Below is a simplified example of what I have at the moment but of course because it uses a hook it becomes a problem in certain circumstances like conditional rendering:

```
const currencyAtom = atom({ symbol: '$' });

const convertPriceToCurrencyAtom = (value: number) => {
    return atom(get(currencyAtom).symbol + value.toFixed(2));
}

const Component = ({ items: Item[] }) => {(
    <div>
        {items.map(item => <span>{item.name}: useAtomValue(convertPriceToCurrencyAtom(item.price))</span>)}
    </div>
)}
```

Is there a best practice within Jotai or should I create a custom hook like below?

```
const usePriceToCurrency = () => {
  const currency = useAtomValue(currencyAtom);
  return (value: number) => currency.symbol + value.toFixed(2);
};
```

**Comment by dai-shi** [comment]
Your custom hook looks just fine.
Alternatively, you can create an atom that returns a function.
```js
const priceToCurrencyAtom = atom((get) => {
  const currency = get(currencyAtom);
  return (value: number) => currencyAtom.symbol + value.toFixed(2);
});
```

But, if I were to do this, I would instead try to avoid to use such a function from the ground. Maybe, it depends on your requirement.

**Comment by Thisen** [comment]
Closing, seems like @dai-shi answered the question. @laclance, feel free to open a discussion, if you have more questions.
