### ISSUE TITLE
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

### ISSUE THREAD

**Issue by Dfurb87** [pmndrs/jotai#828]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
# Happens at runtime, so is not related to any `brew` commands.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Initiate a VPN connection that previously worked on macOS before Monterey/12.

### What happened (include all command output)?

When initiating a connection with strongSwan the installation of virtual IPs fails with something like this:

```
Created TUN device: utun1
interface utun1 appeared
virtual IP 10.0.10.2 did not appear on utun1
installing virtual IP 10.0.10.2 failed
```

More information can be found in https://github.com/strongswan/strongswan/issues/707.

### What did you expect to happen?

The virtual IP should be detected on the created TUN device. But that doesn't happen because macOS 12 doesn't produce the required kernel event(s).

[This patch](https://github.com/Homebrew/homebrew-core/files/7503555/macos-12-tun-fix.txt) works around the issue by setting an MTU on the TUN device, which produces the kernel event required to detect the virtual IP. Note that it is not the actual patch in our repository, but instead applies to the 5.9.4 tarball (i.e. it patches two generated files instead of their source file). I'd have created a PR but I wasn't sure how to go about this for such patches.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install strongswan
# configure a connection and initiate it
```

__Originally posted by @tobiasbrunner in https://github.com/Homebrew/homebrew-core/issues/89022__

**Comment by y-shevchenko** [comment]
> ### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output
> ```shell
> # Happens at runtime, so is not related to any `brew` commands.
> ```
> 
> * [x]  I ran `brew update` and am still able to reproduce my issue.
> * [x]  I have resolved all warnings from `brew doctor` and that did not fix my problem.
> 
> ### What were you trying to do (and why)?
> Initiate a VPN connection that previously worked on macOS before Monterey/12.
> 
> ### What happened (include all command output)?
> When initiating a connection with strongSwan the installation of virtual IPs fails with something like this:
> 
> ```
> Created TUN device: utun1
> interface utun1 appeared
> virtual IP 10.0.10.2 did not appear on utun1
> installing virtual IP 10.0.10.2 failed
> ```
> 
> More information can be found in [strongswan/strongswan#707](https://github.com/strongswan/strongswan/issues/707).
> 
> ### What did you expect to happen?
> The virtual IP should be detected on the created TUN device. But that doesn't happen because macOS 12 doesn't produce the required kernel event(s).
> 
> [This patch](https://github.com/Homebrew/homebrew-core/files/7503555/macos-12-tun-fix.txt) works around the issue by setting an MTU on the TUN device, which produces the kernel event required to detect the virtual IP. Note that it is not the actual patch in our repository, but instead applies to the 5.9.4 tarball (i.e. it patches two generated files instead of their source file). I'd have created a PR but I wasn't sure how to go about this for such patches.
> 
> ### Step-by-step reproduction instructions (by running `brew` commands)
> ```shell
> brew install strongswan
> # configure a connection and initiate it
> ```
> 
> **Originally posted by @tobiasbrunner in [Homebrew/homebrew-core#89022](https://github.com/Homebrew/homebrew-core/issues/89022)**

How do I install this patch?

**Comment by Thisen** [comment]
No idea what this has to do with Jotai, closing it.
