### ISSUE TITLE
Is there any way that I can redo async read on atom?

### ISSUE THREAD

**Issue by chj-damon** [pmndrs/jotai#829]
```ts
function mockFetch(): Promise<number> {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(22);
    }, 3000);
  });
}

export const dashboardAtom = atom(async () => {
  const result = await mockFetch();
  return result;
});
```
in my page:
```tsx
<Suspense key={refreshKey} fallback={<Loading />}
    <Dashboard />
</Suspense>

function Dashboard() {
    const dashboard = useAtomValue(dashboardAtom);
    return (<div>{dashboard}</div>);
}
```

my page will suspend when the promise read is not done. 
If I change the refreshKey, the Suspense will be unmount and re-mount again, so the <Dashboard> component will be a new element. but the question is, dashboardAtom will not run again so the Suspense will not work as the first time.

what should I do to make it work, I hope that when I change the refreshKey, my page should suspend, dashboardAtom should request the promise data again.

**Comment by dai-shi** [comment]
all atom (async or sync, derived or not) values are store in a provider store. So, unmounting an intermediate component (`<Suspense>` or whatever) doesn't clear the values.

If you want to clear the store, you might want to put `key` to a provider:
```jsx
<Provider key={refreshKey}>
  <Suspense fallback={<Loading />}
      <Dashboard />
  </Suspense>
</Provider>
```

But, this may not be what you want, depending on your requirement.
