### ISSUE TITLE
async initial value

### ISSUE THREAD

**Issue by Sylvenas** [pmndrs/jotai#834]
Suppose I need to randomize a number and display it, but the number must be in the range [min,max], so how should I initialize my `numAtom`?

``` js
function randomNum(min, max) {
  return Math.floor(Math.random() * (max - min)) + min;
}

const numAtom = atom(
  // TODO //
)

const Number = ({ min, Max }) => {
  const [num, setNum] = useAtom(numAtom)
  return <span>{num}</span>
}
```

**Comment by dai-shi** [comment]
Can you elaborate the use case a bit?
A canonical answer is `num` shouldn't be changed for each render. (`read` must be pure.)
So, the first thing in mind is:
```js
const Number = ({ min, max }) => {
  const [num, setNum] = useAtom(numAtom)
  useEffect(() => {
    setNum(randomNum(min, max))
  }, [setNum, min, max])
  return <span>{num}</span>
}
```

**Comment by Sylvenas** [comment]
What I need to achieve is that when rendering for the first time, I must render the number in the correct range. However, at this time, the initial value of `numAtom` can only be a fixed value, because it is initialized in advance outside the `Number `component

**Comment by dai-shi** [comment]
Here's one solution:
```js
const numAtom = atom(null)
const Number = ({ min, max }) => {
  const [num, setNum] = useAtom(numAtom)
  const numToRender = useMemo(() => num === null ? randomNum(min, max) : num, [num, min, max])
  useEffect(() => {
    setNum(numToRender)
  }, [setNum, numToRender])
  return <span>{numToRender}</span>
}
```
Alternatively, you can create an atom in render, but that will then require a way to share the created atom. For example, the atom-in-atom pattern would be like this:
```js
const numAtomAtom = atom(null)
const Number = ({ min, max }) => {
  const setNumAtom = useAtomUpdate(numAtomAtom)
  const numAtom = useMemo(() => atom(randomNum(min, max)), [min, max])
  const [num, setNum] = useAtom(numAtom)
  useEffect(() => {
    setNumAtom(numAtom)
  }, [setNumAtom, numAtom])
  return <span>{num}</span>
}
```

**Comment by Sylvenas** [comment]
Thanks for your help, the first option is clearer and easier to understand, I will use it and this issues can be closed.

**Comment by dai-shi** [comment]
Yeah, the second one doesn't make much sense in this specific case. Closing.
