### ISSUE TITLE
splitAtom - creation/deletion of individual split atoms

### ISSUE THREAD

**Issue by Froskk** [pmndrs/jotai#836]
Hello. Firstly I'll write out my use case, I may be going about it the wrong way.

I have a todo list, items are first populated from a server request. Each item is fairly complex. I want to be able to add/remove items, and later save the entire list back to the server.

I have tried using splitAtom to create an atom for each item.
Specifically, as I retrieve the inital list of items from a server, I have a custom hook that creates the split atom:

```ts
export const useCreateSplitAtom = <Value extends Record<string, unknown>>(initialValue: Value[]) => {
  const [configAtom] = useState(() => atom(initialValue));
  const [listAtomsAtom] = useState(() => splitAtom(configAtom));

  return [...useAtom(listAtomsAtom)] as const;
};
```

I also modified the splitAtom utility to allow other payload types, specifically insert and remove:

```ts
// ...existing splitAtom impl...
const write = (get: Getter, set: Setter, payload: SplitItemSetterPayload<ItemAtom>) => {
        if (payload.type === 'remove') {
          console.log('payload:', payload.atom);
          const index = get(splittedAtom).indexOf(payload.atom);
          if (index >= 0) {
            const prev = get(arrAtom);
            const next = [...prev.slice(0, index), ...prev.slice(index + 1)];
            set(arrAtom as WritableAtom<Item[], Item[]>, next);
          }
        }

        if (payload.type === 'move') {
          const prev = get(arrAtom);

          const next = [...prev];
          const [removed] = next.splice(payload.from, 1);
          next.splice(payload.to, 0, removed);

          set(arrAtom as WritableAtom<Item[], Item[]>, next);
        }

        if (payload.type === 'insert') {
          const prev = get(arrAtom);
          // If payload.index > prev.length, splice will append the item to the end of the array by default
          console.log({ payload, prev });
          const templateAtom =
            payload.index < 0 ? prev[0] : payload.index > prev.length - 1 ? prev[prev.length - 1] : prev[payload.index];
          const next = prev.splice(payload.index, 0, templateAtom);

          set(arrAtom as WritableAtom<Item[], Item[]>, next);
        }
      };
      const splittedAtom = isWritable(arrAtom) ? atom(read, write) : atom(read);
      return splittedAtom;
```

When adding/deleting an item, I hit the `console.warn('splitAtom: array index out of bounds, returning undefined', atom);` error.

Does splitAtom allow dynamically creating/deleting items? Am I on the right track?

Despite hitting this warning, removing an item does work, however upon insertion my entire splitAtomsAtom returns an empty array

**Comment by dai-shi** [comment]
Hi, it sounds like you are on the right track, and it's a nice idea to add `insert` and `move`.
It's an unresolved issue, or an unresolvable limitation.
#736 is probably related. cc @Aslemammad 

I know it might work, even with the warning. the warning is to tell that we are accessing out of bounds and returning undefined which is proper JS behavior.
This is probably a timing issue, but I haven't had time to look into further.
There's probably room for improvement in `splitAtom` implementation. It may require some understanding how jotai works, but you are welcome to dig into it.

**Comment by Froskk** [comment]
In fact it was an implementation error on my end: `const next = prev.splice(payload.index, 0, templateAtom);` does not return the spliced array. My bad! 

I no longer hit the `out of bounds` error on insertion, only deletion, so it seems everything is working as it should

**Comment by Froskk** [comment]
I hope it is not a problem to write here about my issues without spending too many hours debugging them.
I seem to have found an issue where my insertion logic is correct (see first image, `item 0` is the newly created item) however the read values from `useAtom` or `useSliceAtom` seem to get overwritten in some way.
![Developer Tools — Planner — http___localhost_3000_mission-planner_edit_org=a event=a mission=a 12_11_2021 16_03_19](https://user-images.githubusercontent.com/37559715/141498936-9b81b60c-ca84-4d72-bb4c-ac8c294a223b.png)

https://user-images.githubusercontent.com/37559715/141499002-c6d91ab9-a753-4e7e-8b3b-573e6e15bd5e.mp4

So inside of the splitAtom logic, the array is `set` with the correct data as seen in DevTools, but the data that is being used in my rows (results of `useSliceAtom` in the row, `useAtom` in the unstyled block of text at the bottom) seems inconsistent. The atom id from `atom.toString()` is correct, and unique, and that value is used as the React `key` for each row. It also happens when using my `move` update method. I will try to create a minimal codesandbox soon

**Comment by Froskk** [comment]
https://codesandbox.io/s/adoring-tree-q6sl8?file=/src/App.tsx

At this point I believe I'm doing something wrong regarding React keys, atom ID's and the whole nature of re-ordering data, but here is a reproduction. My small tweaks to `splitAtom` are found in jotai-fork/splitAtom, the utils file in there is just internals that splitAtom depended up, copied directly from jotai's source.

**Comment by dai-shi** [comment]
Before looking into it, may I confirm the current status? So, you don't have any issue with the released splitAtom, and you are trying to add "insert" feature in your fork which doesn't work as expected, something like that?

**Comment by Froskk** [comment]
Yes, that is correct. Apologies for not being more clear. Both new methods I have added, `move` and `insert`, call `set` with the correct updated array of atoms. However, `useAtom` and `useSliceAtom` called with the splitAtom do not seem to update correctly

**Comment by dai-shi** [comment]
Looked at the codesandbox. Yeah, it can probably be a potential bug. But, I'm not so sure.

**Comment by dai-shi** [comment]
@Thisen If you get a deeper understanding of `splitAtom`, you should be able to help on this. This would be a nice enhancement. As I said somewhere, I'm not very confident if the current `splitAtom` implementation is ideal, so you can try to re-implement. It's challenging. We have a fairly good set of tests, and of course you can add more tests.
