### ISSUE TITLE
Question about different ways to access atom data

### ISSUE THREAD

**Issue by csantos-nydig** [pmndrs/jotai#840]
I'm amazed by this library. it's so simple to use!

As I'm getting familiarized with this library, I'd like to know what should be the right approach to read deep level of an atom, like this one:
```
import { atom } from 'jotai';
import { useUpdateAtom } from 'jotai/utils';

export const modalAtom = atom({
  open: false,
  ids: {
    title: 'titleId',
    body: 'body'
  }
});

const useModal = () => useAtom(modalAtom);
```

I've multiple approaches, but I can't really identify which one is the right way to do it (most performant)

```
const useIds = () => useModal().ids;
```
or
```
const ids = atom(get => get(modalAtom).ids);
const useIds = () => useAtom(ids);
```
or
```
const ids = selectAtom(modalAtom, (modal) => modal.ids);
const useIds = () => useAtom(ids);
```

**Comment by dai-shi** [comment]
> I'm amazed by this library. it's so simple to use!

yay!

> I've multiple approaches, but I can't really identify which one is the right way to do it (most performant)

Thanks for asking. I think this kind of things are worth documenting, docs or tutorial.

> ```js
> const useIds = () => useModal().ids;
> ```

This is not recommended. It will extra re-render if only `open` changes.

> ```js
> const ids = atom(get => get(modalAtom).ids);
> const useIds = () => useAtom(ids);
> ```

This is recommended. Jotai way. `ids` should be defined outside in this case, which is recommended.
In case you want to inline the atom definition, use `useMemo`.
```js
const useIds = () => useAtom(useMemo(() => atom((get) => get(modalAtom).ids), []));
```

> ```js
> const ids = selectAtom(modalAtom, (modal) => modal.ids);
> const useIds = () => useAtom(ids);
> ```

This works. Performance-wise, it's basically the same as the previous one.
Again, defining `ids` outside is recommended.
In case you want to inline it, here's the pattern.
```js
const useIds = () => useAtom(selectAtom(
  modalAtom,
  useCallback((modal) => modal.ids, [])
));
```

**Comment by csantos-nydig** [comment]
Thanks for the quick reply and the detailed explanation! you saved me a lot of re-renderings! (I was gonna do `const useIds = () => useModal().ids;`)

Please feel free to close this one, or keep it open as "documentation".

Thanks again

**Comment by dai-shi** [comment]
Closing this, but documentation is something we should focus on. cc @sandren @aulneau @Thisen @Aslemammad
