### ISSUE TITLE
Using a "setter" in an async read function on first use?

### ISSUE THREAD

**Issue by cyphercider** [pmndrs/jotai#853]
Thanks for your continued work on jotai - this library is amazing!

I am trying to create a hooks library that returns a complex object.  The object requires some initialization before it can be first used, and I'm wondering if there's a way to use async getters to make this setup really transparent to the library user.  Would something like this be possible:

```ts
const InnerAtom = atom<ComplexObject>(null as any)

const ConsumableAtom = atom(async (get, set) => {
  const existing = get(InnerAtom)

  if (!existing) {
    const instance = new ComplexObject()
    await instance.doSomeInit()
    set(InnerAtom, instance)   // <----  Missing need is this setter function being available in the "getter"
  }

 return instance
})

export function useSlickLibrary() {
  return useAtom(ConsumableAtom)[0]
}
```

**Comment by dai-shi** [comment]
The read function has to be "pure".

If it's really for the first mount, `onMount` may help. Otherwise, `useEffect`.
In your case `useEffect` would be good.

```ts
const InnerAtom = atom<ComplexObject | null>(null)

const ConsumableAtom = atom(async (get) => {
  const existing = get(InnerAtom)
  if (!existing) {
    const instance = new ComplexObject()
    await instance.doSomeInit()
  }
  return instance
}, (get, set, instance) => {
  const existing = get(InnerAtom)
  if (!existing) {
    set(InnerAtom, instance)
  }  
})

export function useSlickLibrary() {
  const [instance, dispatch] = useAtom(ConsumableAtom)
  useEffect(() => {
    dispatch(inistance)
  })
  return instance
}
```

Alternatively, `atomWithDefault` in `jotai/utils` may work for some similar use cases.

**Comment by dai-shi** [comment]
Although different, #834 is a similar discussion.

**Comment by cyphercider** [comment]
@dai-shi this works well, thank you!
