### ISSUE TITLE
Add more type tests

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#860]
where do we start?

**Comment by Thisen** [comment]
@dai-shi I think we should look into the core API (atom and useAtom) and then atomFamily, as we had some issues with the deprecated types. From there, we can fan out and split it into chunks.

We should probably also start adding type tests to new APIs.

What do you think?

**Comment by dai-shi** [comment]
To be honest, I'm curious how the tests look like. So, if you start something small, that will be super helpful.

**Comment by Thisen** [comment]
We already have some here:
https://github.com/pmndrs/jotai/blob/main/tests/types.test.tsx

**Comment by dai-shi** [comment]
Oh, yes, then what do you mean by "we should look into the core API (atom and useAtom)"?

**Comment by Aslemammad** [comment]
@Thisen It'd be good if we can close this! feel free to re-open! I guess we have `tsc --noEmit` for type check, so this is not something so urgent! (I'm not against type tests)
