### ISSUE TITLE
I'm not sure whether jotai should as peerdependencies?

### ISSUE THREAD

**Issue by Fiv5** [pmndrs/jotai#863]
Same like react-redux.

**Comment by Thisen** [comment]
Can you elaborate more about your use case?

Two answers comes to mind based on different use cases:

- Using Jotai for an application:
  - It should be a part of your `peerDependencies`.

- Using Jotai for a library:
  - If you are developing a library, where you expect the user of your library to also use Jotai, it should be a peer dependency.
  
If this doesn't answer your question, do elaborate on your use case. 👍🏼

**Comment by a-eid** [comment]
> Using Jotai for an application:
> 
> * It should be a `dependency`.

**Comment by Thisen** [comment]
> > Using Jotai for an application:
> > 
> > * It should be a `dependency`.

Major typo from my side! Thanks for pointing it out. Updated my comment.

**Comment by Fiv5** [comment]
> * If you are developing a library, where you expect the user of your library to also use Jotai, it should be a part of your `peerDependencies`

Thanks! I will use jotai to develop my library.
