### ISSUE TITLE
Write to a store without `useAtom`

### ISSUE THREAD

**Issue by mfbx9da4** [pmndrs/jotai#864]
Often I just want to set the state without using a hook e.g. 

```
export const foo = atom(0)

function Component() {
  return <Button onClick={() => foo.set(1)} />
 }
 ```
 
 Can I use `foo.write(...` to do something similar?

**Comment by dai-shi** [comment]
No, because `foo` doesn't have values. [An example](https://twitter.com/dai_shi/status/1447892237753278466). The atom definition is reusable.

See also #861.

**Comment by mfbx9da4** [comment]
Hmm i see
