### ISSUE TITLE
trigger -> https://github.com/opencontainers/image-spec/pull/809/files#r667082904

### ISSUE THREAD

**Issue by Dfurb87** [pmndrs/jotai#868]
trigger -> https://github.com/opencontainers/image-spec/pull/809/files#r667082904

discoveries:
- https://github.com/opencontainers/image-spec/pull/711
- https://github.com/opencontainers/image-spec/pull/492
- https://github.com/opencontainers/umoci/blob/07fa845e5b068dee64dcbf391b456a564a6fcfa6/oci/config/convert/runtime.go#L32-L42

I think this section of conversion of `Config.labels` to some `annotations` is not actually use in the wild.
Lets just remove it

__Originally posted by @vbatts in https://github.com/opencontainers/image-spec/issues/864__

**Comment by Thisen** [comment]
Closing.
