### ISSUE TITLE
when to use jotai and when to use zustand?

### ISSUE THREAD

**Issue by ManuRodgers** [pmndrs/jotai#876]

**Comment by dai-shi** [comment]
If you want to use module state outside React, zustand and valtio.
If you want a replacement for useState+useContext, jotai.

A module state is a singleton, but jotai's atoms are not.
Ref: https://twitter.com/dai_shi/status/1447892237753278466

That said, zustand and valtio can use context optionally, and jotai might be going to have an _experimental_ feature #861.

**Comment by ManuRodgers** [comment]
thanks mate
