### ISSUE TITLE
Improve core tests

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#88]
Core tests are the followings:

```
tests/async.test.tsx
tests/basic.test.tsx
tests/dependency.test.tsx
tests/error.test.tsx
tests/items.test.tsx
```

I need someone to help advice if it's ok or if there's room for improvement. I followed the same pattern as in zustand, but I'm not quite sure if testing with `findByText` is a good/desired way (instead of using `expect`.)

**Comment by LuckyPigeon** [comment]
@dai-shi 
Test with `findByText` is good in our case, since we have using asynchronous in our case and `findByText` is also do with asynchronous and promise. Then search the content shows within 1 second by default.
And for the testcase improvement, I'm still reviewing the code.

**Comment by dai-shi** [comment]
We need more async tests. Basic ones are still missing. ref: #148

**Comment by dai-shi** [comment]
Two points to improve our tests.

1) use single `waitFor` wrapping multiple `getTextBy`s instead of multiple `findByText`s.
ex. https://github.com/pmndrs/jotai/pull/170/files#diff-9b93a57f63999f35f29dafb87113a31d78f31f63e01db59c772f60b309c7fe6eR31-R34

2) use jest.fn and toHaveBeenCalledTimes instead of naive counters (`readCount` and `updateCount`)
ex. https://github.com/pmndrs/jotai/pull/188/files#diff-1a2f0b70991659205d97a3598aa6492bc1356e60d2f0334737218f2120b577ffR89-R90

**Comment by LuckyPigeon** [comment]
@dai-shi 
Thanks for the tips!

**Comment by dai-shi** [comment]
@Aslemammad As you got familiar with the first one in https://github.com/pmndrs/jotai/issues/88#issuecomment-725329174, please feel free to go ahead and open a PR.

**Comment by Aslemammad** [comment]
@dai-shi Sure, I'm gonna work on it, thanks for the suggestion.

**Comment by Aslemammad** [comment]
@dai-shi I improved core tests( except dependency & error), but I don't see anything to improve in these two files for now, right?

**Comment by dai-shi** [comment]
@Aslemammad Thanks so much for all your work.
Now, as you got familiar with current core tests, do you see any missing tests, or improve them including restructure from scratch?

**Comment by Aslemammad** [comment]
@dai-shi I'll take a look at the other tests, If I found something, I'll share. But I think core tests work is done now, better to close this issue, how do you think?

**Comment by dai-shi** [comment]
Good idea. Please open new issue or PR for any improvements.
