### ISSUE TITLE
Synchronize atomWithStorage across tabs with "storage" event

### ISSUE THREAD

**Issue by fzembow** [pmndrs/jotai#882]
I've noticed that using `atomWithStorage` util, across two tabs of the same origin, with the same key, does not synchronize the values.

Synchronization would be relatively simple to implement by listening to the [storage event](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event) on the window and updating the atom's value if the localStorage changes at the same key.

Of course, we'd need to take care that two tabs do not notify one another in a loop with these events (the recipient tab of the event should only update the in-memory state and not write to localStorage).

What do you think? I'd be happy to take a stab at implementation.

**Comment by dai-shi** [comment]
atomWithStorage takes custom storage option. would you try to implement what you want with it? looking at atomWithHash implementation might help.

**Comment by fzembow** [comment]
@dai-shi I'll try that out. I'll make a gist and then you can decide whether it's a change that should be added to the project or not.

Perhaps there are too many implementation details here to warrant placing it in the main project (such as what should the equality function be, since any JSON object can be stored in localStorage, and some folks might want deep or shallow comparison).

However, from a user point of view, I think the cross-tab synchronization would be beneficial and perhaps even expected -- after all, if the state in one tab got out of sync, and then the user reloaded the tab, the data would be refreshed

Ps. I love this library - thank you for all your work on it. I always reach for it for quick projects and prototypes!

**Comment by fzembow** [comment]
That's straightforward enough to implement as a custom storage! See below.

```ts
/**
 * LocalStorage-based atom persistence,
 * with the added benefit that updates are
 * synchronized between tabs
 */
const getSyncedLocalStorage = <Value>() => ({
  getItem: (key: string) => {
    return JSON.parse(localStorage.getItem(key) || '');
  },

  setItem: (key: string, value: Value) => {
    localStorage.setItem(key, JSON.stringify(value));
  },

  subscribe: (key: string, callback: (value: Value) => void) => {
    const storageEventCallback = (e: StorageEvent) => {
      if (e.key === key && e.newValue) {
        callback(JSON.parse(e.newValue));
      }
    };
    window.addEventListener('storage', storageEventCallback);
    return () => {
      window.removeEventListener('storage', storageEventCallback);
    };
  },
});
```

Let me know if you'd like me to make a PR to include this as a util: we'd need to change the `StringStorage` and `AsyncStringStorage` types to allow for a "subscribe" as well, since effectively you can subscribe to localStorage changes (just like you do for the implementation of the hash storage).

**Comment by dai-shi** [comment]
Can this be a default behavior for localStorage? (I don't want to add too many different features.)
@sandren What do you think?

---
> we'd need to change the StringStorage and AsyncStringStorage types to allow for a "subscribe" as well

I'd change createJSONStorage to accept options in the second argument like `subscribe` and `delayInit`.

(ah, I found a bug in `createJSONStorage`... `setItem` doesn't return a promise on async.)

**Comment by sandren** [comment]
> Can this be a default behavior for localStorage? (I don't want to add too many different features.) @sandren What do you think?

I think this would be a very helpful default behavior for most users. Those that don't want it (or want an alternate implementation) can always provide a custom storage. 😀

**Comment by dai-shi** [comment]
Cool. Let's do that.
@Thisen seems to work on it.
