### ISSUE TITLE
React Refresh Babel plugin causes unexpected behaviour in atoms returned from functions

### ISSUE THREAD

**Issue by worldeggplant** [pmndrs/jotai#891]
I was pulling my hair out when trying to get `atomWithStorage` to work (with Expo's SecureStore in a React Native context).
The issue I was having was that no matter which atom I updated, all `atomWithStorage` atoms would receive the same value – that of the first atom created.
The occurrence started at a (seemingly) random time at first, but after creating a completely blank project I was able to boil it down to being the fault of the React Refresh Babel plugin (which of course needed the Metro cache to be cleared before jumping into effect, which was why it popped up at a random time – after a reboot of my laptop 😵‍💫).

Disabling `plugin-react-refresh` or `jotai/babel/preset` in the babel config and then restarting Metro bundler with `--reset-cache` fixes the issue.

[Reproducible example (using plugin-react-refresh)](https://codesandbox.io/s/react-with-custom-babel-config-forked-311h6?file=/src/App.js)

[Working example (using plugin-debug-label)](
https://codesandbox.io/s/react-with-custom-babel-config-forked-28cbf?file=/src/App.js)

Click the buttons in the examples above to demonstrate the behavior and look at the console to see the output of `useAtomsSnapshot()`.

In essence, updating the state of any atom that is returned from a function (countAtom2 or countAtom3 in the example) will result in both receiving the same state (and debugLabel).

**Comment by dai-shi** [comment]
@Thisen ?

**Comment by Thisen** [comment]
@worldeggplant thanks for the issue and reproduction, this is definitely a bug in the Babel plugin. 

I'll look into it.
