### ISSUE TITLE
[docs] links is 404 page in /docs/api/utils.mdx

### ISSUE THREAD

**Issue by birdview-HongKi** [pmndrs/jotai#902]
Links of [/docs/api/utils.mdx](https://github.com/pmndrs/jotai/blob/main/docs/api/utils.mdx)  is 404 page.

maybe adding '.mdx' to all links will solve it.

When i search by regex (`\[.+\]\(\.\..+\)`). only /docs/api/utils.mdx file issues.

May i write Pull Request this issue?

**Comment by dai-shi** [comment]
Thanks. Please go ahead.

**Comment by dai-shi** [comment]
Oh, wait. You mean the link in github?
That will be addressed later. For now, please see https://jotai.org.

**Comment by birdview-HongKi** [comment]
@dai-shi Oh! You didn't need it! Thanks for the feedback!

I will close this issue!
