### ISSUE TITLE
Improve debugging docs

### ISSUE THREAD

**Issue by Aslemammad** [pmndrs/jotai#903]
> Daishi: we would need to improve https://jotai.org/docs/guides/debugging, which can be a separate PR. it needs much improvement. it has to be a "guide" which isn't currently.

Suggestions & Ideas are welcome!

**Comment by dai-shi** [comment]
This will be addressed after useAtomsDevtools is released. I mean we can start working on it from now.

First question: What will be the first option for the debugging tool?
1. React DevTools with `<Provider>`
2. Redux DevTools Ext with `useAtomsDevtools`
3. (unlikely but) Redux DevToolsExt with `useAtomDevtools`

How are these two different in terms of debugging experience?

**Comment by LuckyPigeon** [comment]
@dai-shi @Aslemammad 
I think introduce `atomic-devtools` is also a good idea, since it builds natively for jotai.

**Comment by dai-shi** [comment]
I think it's not ready. They need to update the tool (see #918) and we need to improve some apis (see #911).

**Comment by Aslemammad** [comment]
Let's close as we improved the debugging docs!
