### ISSUE TITLE
[Question] Is there any way to call the setter of Atom by the state change of dependent Atom?

### ISSUE THREAD

**Issue by Kourin1996** [pmndrs/jotai#908]
I'm trying to find the way to update atom state by the change of the other atoms.

Let me explain why I need this function first. I'm implementing a view of a list where each record in the list has a type and some fields. There is a selector to switch types in the view and only records with the selected type will be displayed in the list. In addition, the records will be filtered by selected `status`. Now, I have two statuses defined by atom: `type` and `status`. But `status` is restricted by `type` and the set of `status` depends on the selected `type`.

```jsx
type OrderType = 'adhoc' | 'scheduled'
type OrderStatus = 'pending' | 'ordered' | 'completed'
const orderTypeToOrderStatus = {
   adhoc: ['ordered', 'completed'], // when type is 'adhoc', 'pending' can't be selected
   scheduled: ['pending', 'ordered', 'completed']
}
```

For that reason, I want to check `status` is still valid when `type` changed and update `status` if it's invalid. To implement that, I let the setter of `type` atom update `status` currently.

```jsx
const _orderTypeAtom = atom<OrderType>('adhoc') // display adhoc data on mount
const orderTypeAtom = atom(
    (get) => get(_orderTypeAtom),
    (get, set, newValue) => {
        set(_orderTypeAtom, newValue)
        set(orderStatusAtom, get(orderStatusAtom)) // call update function to make sure status is valid
    }
)

const _orderStatusAtom = atom<OrderStatus>('ordered')
const orderStatusAtom = atom(
    (get) => get(_orderStatusAtom),
    (get, set, newValue) => {
        const currentOrderType = get(orderTypeAtom)
        if(orderTypeToOrderStatus[currentOrderType].includes(newValue)) {
            // valid status
            set(_orderStatusAtom, newValue)
            return
        }
        // set default value because of invalid value
        set(_orderStatusAtom, orderTypeToOrderStatus[currentOrderType][0])
})
```

To be honest, I don't want the `type` atom to depend on `status` atom. Ideally, `status` atom should detect the change of `type` and change its own state in this case.

I would appreciate it if you could tell me the best practices. Thank you for your help!

**Comment by dai-shi** [comment]
In general, we don't provide a way to change state based on other state change. This is because there's a delay in React, and such a pattern is not recommended. If it's truly required, `useEffect` is the current solution.

Now, in your use case, there are two options: a) validated derived atom, and b) set two atoms in one write function.
a) may or may not work in some use cases. b) is more or less what you are doing now.

### a) validated derived atom

```ts
const orderTypeAtom = atom<OrderType>('adhoc') // display adhoc data on mount

const _orderStatusAtom = atom<OrderStatus>('ordered')
const orderStatusAtom = atom(
  (get) => {
    const currentOrderType = get(orderTypeAtom)
    const storedOrderStatus = get(_orderStatusAtom)
    if(orderTypeToOrderStatus[currentOrderType].includes(storedOrderStatus)) {
      return storedOrderStatus
    }
    return orderTypeToOrderStatus[currentOrderType][0] // default status when invalid
  },
  (_get, set, newValue) => {
    set(_orderStatusAtom, newValue)
  }
)
```

### b) set two atoms in one write function

```ts
const _orderTypeAtom = atom<OrderType>('adhoc') // display adhoc data on mount
const orderTypeAtom = atom(
  (get) => get(_orderTypeAtom),
  (get, set, newValue) => {
    set(_orderTypeAtom, newValue)
    // make sure status is valid
    const currentOrderStatus = get(orderStatusAtom)
    if(!orderTypeToOrderStatus[newValue].includes(currentOrderStatus)) {
      set(orderStatusAtom, orderTypeToOrderStatus[newValue][0])
    }
  }
)

const orderStatusAtom = atom<OrderStatus>('ordered')
```

**Comment by Kourin1996** [comment]
Understood. I see the reason why you're not providing such a feature. 

Thank you for your quick reply and detailed information. I appreciate it.
