### ISSUE TITLE
AtomWithStorage doesn't have a 'remove' possibility

### ISSUE THREAD

**Issue by justinhandley** [pmndrs/jotai#930]
I can't figure out how to remove an item from asyncstorage with the AtomwithStorage.

Would it be possible to either have a remove argument we could pass in, or if you pass in null it could call remove internally?

I store user's auth token in async storage, I want to clear it on log out - can I achieve that with AtomWithStorage?

**Comment by dai-shi** [comment]
Good and valid point. To be consistent with `atomWithReset` and `atomWithDefault`, we can use `RESET` symbol (unless it's too confusing.)
A small concern is adding `removeItem` to SyncStorage type is a breaking change, but I lean to it, because zustand https://github.com/pmndrs/zustand/pull/598 does the same. Maybe we follow the same migration path.

I can work on it.

**Comment by dai-shi** [comment]
@justinhandley Would you please try #934 ?

https://ci.codesandbox.io/status/pmndrs/jotai/pr/934
☝️ Find "Local Install Instructions"

**Comment by justinhandley** [comment]
So, on first attempt I'm getting this.

[Thu Jan 06 2022 14:04:27.572]  ERROR    ReferenceError: Can't find variable: localStorage
[Thu Jan 06 2022 14:04:27.572]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by dai-shi** [comment]
So, you are using React Native, right?

We are missing clear docs for RN usage. (contributions welcome!)

It has to be like this for non-default storage other than localStorage:
```js
import { atomWithStorage, createJSONStorage } from 'jotai/utils'

const storage = createJSONStorage(() => AsyncStorage)
const fooAtom = atomWithStorage('foo', null, storage)
```
refs:
https://github.com/pmndrs/jotai/discussions/921#discussioncomment-1892700
https://github.com/pmndrs/jotai/issues/780
https://github.com/pmndrs/jotai/issues/805

**Comment by justinhandley** [comment]
Thanks @dai-shi - I'm not sure why, but with the experimental version I never got it working, but with it merged into the main branch it is now working absolutely perfectly.  Really appreciate it.
