### ISSUE TITLE
Optional comparator function for getter values

### ISSUE THREAD

**Issue by pc-erin** [pmndrs/jotai#935]
I have a primitive and derived atom that contain x and y coordinates.

```typescript
const mouseViewportPositionAtom = atom(initialState)

const mouseGridPositionAtom = atom((get) => {
  const mouseViewportPosition = get(mouseViewportPositionAtom)

  return {
    x: mouseViewportPosition.x + 10,
    y: mouseViewportPosition.y + 10
  }
})
```

The problem is that if a component `useAtom`s `mouseGridPositionAtom`, it will always re-render any time it is checked for freshness (like if it's parent re-renders).

This seems to be because the return value of `mouseGridPositionAtom`s getter is always referentially different because it returns an object.

Is there a way to tell an atom how to know when it's return value is the same as last time? Referential equality works fine for primitive values, but if you need to store/derive anything more complex in objects it results in re-renders even when the property values haven't changed.

There is a [similar issue for recoil](https://github.com/facebookexperimental/Recoil/issues/1416). I was wondering if Jotai has a way around this.

EDIT: [Example codesandbox](https://codesandbox.io/s/react-typescript-forked-sjs3f?file=/src/App.tsx)

**Comment by dai-shi** [comment]
Hm, no, it shouldn't return a new value unless you change `mouseViewportPositionAtom` value.
Can you try to create a codesandbox?

Note that my huge motivation of developing jotai and some other libraries to eliminate the need for memoization (of selectors, not components) and custom equality function. Everything in jotai is build with referential equality and it should work for 99% use cases. (`selectAtom` is an escape hatch with custom comparator.)

**Comment by dai-shi** [comment]
> EDIT: [Example codesandbox](https://codesandbox.io/s/react-typescript-forked-sjs3f?file=/src/App.tsx)

Thanks.
You want to check this: https://codesandbox.io/s/react-typescript-forked-hp16t

**Comment by pc-erin** [comment]
So that re-render is coming from React, not from a change in the value returned by `useAtom`?

Btw, how does the derived value get cached? Is the atom doing it's own deep equals, or just not re-running the getter at all if the atoms it depends on haven't changed?

**Comment by dai-shi** [comment]
> So that re-render is coming from React, not from a change in the value returned by `useAtom`?

Right. You can try removing `useAtom` entirely, and still see `renders++` increases.

> Btw, how does the derived value get cached?

It keeps the last value, i.e., the cache size is `1`.

> Is the atom doing it's own deep equals, or just not re-running the getter at all if the atoms it depends on haven't changed?

The latter: Not re-running the read function at all if dependencies haven't changed.

**Comment by pc-erin** [comment]
Thank you! I have a much better understanding of how both Jotai and React work now.

I had been under the impression that React does not re-run a component unless it's state or props change, but that does not seem to be true unless you wrap it with `React.memo`.

It also makes me realize my first example was not representative of my real question.

In [this codesandbox](https://codesandbox.io/s/react-typescript-forked-ybpih?file=/src/App.tsx) `SubComponent` re-renders whenever the button is clicked because a new object has been written to `mouseViewportPositionAtom`. Is there any way for `mouseViewportPositionAtom` to recognize that it is getting the same coordinates set each time even though the object reference is new?

Is there a recommended way to handle this when using Atom-type state management systems? A lot of my "atoms" are objects because my apps often have multiple pieces of data that only make sense to read/write as one unit.

**Comment by dai-shi** [comment]
Basically, you want to make things more atomic **if** re-rendering is a real issue for you.
So, instead of:
```js
const initialState = { x: 0, y: 0 };
const mouseViewportPositionAtom = atom(initialState);
```
you could do this:
```js
const initialX = 0;
const initialY = 0;
const mouseViewportXAtom = atom(initialX);
const mouseViewportYAtom = atom(initialY);
```

> A lot of my "atoms" are objects because my apps often have multiple pieces of data that only make sense to read/write as one unit.

If you want to keep the atom as an object, you can create intermediate derived atoms.
👉 https://codesandbox.io/s/react-typescript-forked-f26zd?file=/src/App.tsx
Internal atoms should be hidden in a small scope (like function scope or module scope).

But, again, this might be over optimization depending on your app use case.

**Comment by pc-erin** [comment]
That seems like it could quickly get unwieldy for large objects or if you have a lot of atoms that need custom equality functions.

I checked out the [`selectAtom`](https://jotai.org/docs/utils/select-atom) utility you mentioned earlier and I think it might be the simplest way to deal with my situation.

Leaving my solution here in case it helps anyone else with a similar issue:

```typescript
const mouseViewportPositionAtom = atom(initialState);

const suppressedRefreshMouseViewportPositionAtom = selectAtom(
  mouseViewportPositionAtom,
  identity,
  arePointsEqual
);
```

[Working example](https://codesandbox.io/s/react-typescript-forked-c1iz7?file=/src/App.tsx)

It would be even more convenient if it was possible to pass the equality checker into `atom` itself, but this is the next best solution I think.

**Comment by dai-shi** [comment]
Yeah, that's why we provide `selectAtom` as an escape hatch, even though it's against our philosophy.

Closing this as we don't plan to change the core and the next best solution is our solution.

**Comment by pc-erin** [comment]
Fair enough. I appreciate your help, and it turns out this library is so extensible I can make exactly what I wanted by composing the atom and utility functions.

```typescript
function memoizedAtom<Value>(
  initialState: Value,
  equalityFn: (a: Value, b: Value) => boolean
) {
  const writeAtom = atom(initialState);

  const readAtom = selectAtom(writeAtom, identity, equalityFn);

  return atom(
    (get) => get(readAtom),
    (get, set, update: SetStateAction<Value>) => set(writeAtom, update)
  );
}

const initialState: Point = { x: 0, y: 0 };

const mouseViewportPositionAtom = memoizedAtom(initialState, arePointsEqual);

const mouseGridPositionAtom = atom((get) => {
  const { x, y } = get(mouseViewportPositionAtom);

  return {
    x: x + 10,
    y: y + 10
  };
});
```

[Working example](https://codesandbox.io/s/react-typescript-forked-cysm9?file=/src/App.tsx) in case anyone wants to do something similar.

That version has no excess re-renders, and has almost the same simplicity as creating a regular atom. It only works for primitive atoms, but I think that's what matters since primitive atoms must always sit at the top of the atom graph (as far as I understand) and derived atoms don't update if their dependencies don't.

**Comment by dai-shi** [comment]
> so extensible I can make exactly what I wanted by composing atoms and utility functions.

Yes! It's the jotai mental model.
