### ISSUE TITLE
[jotai/xstate] Allow updating of machine options once initialized.

### ISSUE THREAD

**Issue by jtmthf** [pmndrs/jotai#938]
A nice feature that `@xstate/react` has is that `useMachine` allows the options of a machine to updated once initialized. The example from their documentation demonstrates this using `react-router`

```tsx
import { machine } from './machine';
import { useMachine } from '@xstate/react';
import { useHistory } from 'react-router';

const Component = () => {
  const history = useHistory();

  const [state, send] = useMachine(machine, {
    actions: {
      goToOtherPage: () => {
        history.push('/other-page');
      }
    }
  });

  return null;
};
```

> If you use this technique, any references you use inside goToOtherPage will be kept up to date each render. That means you don't need to worry about stale references.

Currently I don't believe this to be possible with `jotai/xstate` as once a machine atom is initialized, the machine nor the options can be updated.

Ideally it'd be possible to do something similar to below where the options of an already running machine can be updated.

```tsx
import { machine } from './machine';
import { historyAtom } from './historyAtom';
import { useMachine } from '@xstate/react';
import { useHistory } from 'react-router';
import { useAtom } from 'jotai';
import { atomWithMachine } from 'jotai/xstate';

const machineAtom = atomWithMachine(machine, (get) => {
  const history = get(historyAtom);

  return {
    actions: {
      goToOtherPage: () => {
	    history.push('/other-page');
	  }
    }
  }
});

const Component = () => {
  const [state, send] = useAtom(machineAtom);

  return null;
};
```

What's tricky about this implementation is that xstate doesn't expose a native API to update the options of service and in `@xstate/react` relies on direct mutation of the machine to accomplish this behavior.

**Comment by dai-shi** [comment]
Ah, interesting. Basically we want to support what `@xstate/react`, but it sounds difficult in this case. Do you have any idea for the implementation?

A workaround what I have in mind is to mutate a function in `historyAtom`. But, it's too hacky and not a recommended pattern. Doesn't work correctly in concurrent rendering.

**Comment by hoetmaaiers** [comment]
Very interested in updating the machine after initialisation. Any updates or new thoughts about this?

**Comment by dai-shi** [comment]
> xstate doesn't expose a native API to update the options of service

Unless it's resolved upstream, we probably can't do appropriate fixes.

**Comment by dai-shi** [comment]
useInterpret is from `@xstate/react`. We need an API exposed from `xstate`, because atoms are conceptually framework agnostic. I didn't investigate this, OP tells so.

**Comment by Leechael** [comment]
I'm meet similar scenario here, and here is my approach (I share a simple memo here for discuss).

1. Put dependencies in machine context.
2. Add an action names 'updateDependencies` which for update context for that values tracking by atoms.
3. Write `useMachineDepdenciesUpdateEffect` and call it somewhere.

```typescript
const aMachineAtom = atomWithMachine((get) => {
  return createMachine(
    {
      context: {
        wsInstance: get(wsInstanceAtom),
      },
      initial: 'INITIAL',
      states: {
        INITIAL: {
          on: {
            '': [
              {target: 'RED', cond: 'isRed'},
              {target: 'GREEN', cond: 'isGreen'},
            ],
          },
        },
        RED: {
          on: {
            updateDependents: {
              target: 'INITIAL',
              actions: ['updateDependents'],
            },
          },
        },
        GREEN: {},
      },
    },
    {
      actions: {
        updateDependents: assign({
          wsInstance: (_, {wsInstance}) => wsInstance,
        }),
      },
      guards: {
        isRed: (context) => context.isRed,
        isGreen: (context) => context.isGreen,
      },
    }
  )
})

const useMachineDependenciesUpdateEffect = () => {
  const send = useUpdateAtom(aMachineAtom)
  const wsInstance = useAtomValue(wsInstanceAtom)
  useEffect(() => {
    send({
      type: 'updateDependents',
      wsInstance: wsInstance,
    })
  }, [send, wsInstance])
}
```

**Comment by dai-shi** [comment]
> What's tricky about this implementation is that xstate doesn't expose a native API to update the options of service and in `@xstate/react` relies on direct mutation of the machine to accomplish this behavior.

Are anyone experienced enough about how `@xstate/react` implements it?

**Comment by Leechael** [comment]
> Are anyone experienced enough about how `@xstate/react` implements it?

I take a quick look through the source code of `useInterpret`, it stop the service and re-create an new one (using `withConfig` then `interpret`). I'm not sure is it acceptable?

**Comment by dai-shi** [comment]
> is it acceptable?

Possibly. Sounds like a workaround. I'm not confident enough if we can keep up with xstate changes in the future. It would be nice if xstate exposes such an API.

If creating a new machine is acceptable, we can do atom-in-atom in jotai.

**Comment by jahglow** [comment]
> I'm meet similar scenario here, and here is my approach (I share a simple memo here for discuss).
> 
> 1. Put dependencies in machine context.
> 2. Add an action names 'updateDependencies` which for update context for that values tracking by atoms.
> 3. Write `useMachineDepdenciesUpdateEffect` and call it somewhere.
> 
> ```ts
> const aMachineAtom = atomWithMachine((get) => {
>   return createMachine(
>     {
>       context: {
>         wsInstance: get(wsInstanceAtom),
>       },
>       initial: 'INITIAL',
>       states: {
>         INITIAL: {
>           on: {
>             '': [
>               {target: 'RED', cond: 'isRed'},
>               {target: 'GREEN', cond: 'isGreen'},
>             ],
>           },
>         },
>         RED: {
>           on: {
>             updateDependents: {
>               target: 'INITIAL',
>               actions: ['updateDependents'],
>             },
>           },
>         },
>         GREEN: {},
>       },
>     },
>     {
>       actions: {
>         updateDependents: assign({
>           wsInstance: (_, {wsInstance}) => wsInstance,
>         }),
>       },
>       guards: {
>         isRed: (context) => context.isRed,
>         isGreen: (context) => context.isGreen,
>       },
>     }
>   )
> })
> 
> const useMachineDependenciesUpdateEffect = () => {
>   const send = useUpdateAtom(aMachineAtom)
>   const wsInstance = useAtomValue(wsInstanceAtom)
>   useEffect(() => {
>     send({
>       type: 'updateDependents',
>       wsInstance: wsInstance,
>     })
>   }, [send, wsInstance])
> }
> ```
> 
> This approach may associate to how you design your state machine and practice in real-world.

This is basically what I came to do, but I call it an INITIALIZE event цру I need to pass xstate methods applicable and available only in react-lifecycle, e.g. react-navigation aware method, or when a machine is used in similar scenario but it needs a modifier boolean to differentiate what behavior is necessary for this very workflow. Using many atoms preconfigured at start makes code not reusable because code already references an atom and in react-native world with react-navigation where screens are as flat as possible, passing an atom through context or props is something not trivial. So yeah, any initialize event is a worthy thing.

**Comment by dai-shi** [comment]
Moved to https://github.com/jotaijs/jotai-xstate/issues/3
