### ISSUE TITLE
Mount and unmount functions are not paired if an atom is only used in write

### ISSUE THREAD

**Issue by xbaun** [pmndrs/jotai#942]
Hi,

I noticed that when an atom (A) is invoked by a getter from another atoms (B) setter, then the unmount function of (A) is not getting invoked when (B) is unmounted. The Atom (A) is not mounted before and therefore has no dependents. As far as I debugged into this, it seems that atom (B) is not correctly tracking its dependencies in the `writeGetter`.

Here is a minimal working example of the issue: https://codesandbox.io/s/elated-frost-x8dlh?file=/src/App.tsx

```ts
const aAtom = atom("A");
aAtom.onMount = (set) => {
  console.log("mount->A");
  return () => {
    console.log("unmount->A");
  };
};

const bAtom = atom("B", (get, set) => {
  get(aAtom);
});
bAtom.onMount = (set) => {
  console.log("mount->B");
  return () => {
    console.log("unmount->B");
  };
};
```

The output is
```
mount->B 
mount->A 
unmount->B 
```
but I would expect
```
mount->B 
mount->A 
unmount->A 
unmount->B 
```

**Comment by dai-shi** [comment]
Oh, this is such an edge case that is not covered currently.
So, we don't track dependencies on `write` by design.
If we use `aAtom` in `bAtom`'s write function, we need to mount it anyway, but then there's no chance to unmount (unless there are other usage).
I don't know if this is fixable without adding write dependencies, which would be too much and make it less performant.)

The workaround for now is to make `bAtom` depends on `aAtom` explicitly.
https://codesandbox.io/s/fervent-orla-7e3ob

**Comment by xbaun** [comment]
Thanks for your quick answer. I did the same thing to ensure that the atom gets unmounted.

I stumbled across this when I noticed that a remote subscription in the `onMount` function was not cleaned up and the atom remained mounted. The proposed workaround would mean, that I always have to explicitly depend on every atom that is used in a write function, even if it is not used in the read function, because it is not obvious if there are transitive dependencies to other atoms with an `onMount` function.

Perhaps the existing dependency tracking could be extended to use a ref count to determine if an atom read or write function is accessing other atoms through a `Getter`, whereby a `writeGetter` immediately decrements the ref count after the invocation of the write function. Therefore it would be ensured that the unmount function is getting called.

**Comment by dai-shi** [comment]
> immediately decrements the ref count after the invocation of the write function.

That sounds reasonable. In this case, with the current architecture, it may not fire `onMount` in writeGetter. Yeah, that might be how it works. Now, I think `mount->A` shouldn't happen. 🤔 

Let me reopen this.

**Comment by dai-shi** [comment]
I labeled this as `bug` for now. We may end up with this being a known limitation.

**Comment by dai-shi** [comment]
Note:
> So, we don't track dependencies on `write` by design.

This design won't change. So, the first approach is NOT to invoke `onMount` for `aAtom` in [this](https://github.com/pmndrs/jotai/issues/942#issue-1097238902) case.

**Comment by dai-shi** [comment]
#961 should have a fix.
Please try: https://ci.codesandbox.io/status/pmndrs/jotai/pr/961
