### ISSUE TITLE
[Regression Bug] Updated atom value not propagated to component

### ISSUE THREAD

**Issue by xbaun** [pmndrs/jotai#947]
I am using an atom (A) to control if an atom (B) should return the value of an atom (C) otherwise a default value is returned.  See the example below: https://codesandbox.io/s/dark-http-bsili?file=/src/App.tsx

```ts
const aAtom = atom<any>(false);
aAtom.debugLabel = "aAtom";
aAtom.onMount = (set) => {
    console.log("onMount: aAtom");
    setTimeout(() => {
        set(true);
    }, 1000);
};

const cAtom = atom<any>(1);
cAtom.debugLabel = "cAtom";
cAtom.onMount = (set) => {
    console.log("onMount: cAtom");
    set(2);
};

const bAtom = atom<any>((get) => {
    const a = get(aAtom);
    console.log("a=", a);
    if (a) {
        return get(cAtom);
    }
    return 1;
});
bAtom.debugLabel = "bAtom";

```

The problem is, that the changed value of atom (C) is never propagated to the invoking component through `useAtom`. The error occurs when there is no externally triggered rendering within the calling component, which re-evaluates the `useAtom` hook. I think, there is somewhere a `flushPending` missing. I tried to figure out what could be a possible fix, but I did not found any good solution. 

Affects version `1.5.0`.  Worked with ~~`1.4.2`~~ `1.4.9`.

----

BTW:  I think the `useEffect` call at https://github.com/pmndrs/jotai/blob/main/src/core/useAtom.ts#L103-L105 should pass its dependencies. If so, a forced rendering has no effect anymore on the bug above.

```ts
  useEffect(() => {
    store[COMMIT_ATOM](atom, version)
  }, [store, atom, version]);
```

**Comment by dai-shi** [comment]
Thanks for reporting. I think we miss tests to cover this...

> Affects version `1.5.0`. Worked with `1.4.2`.

This almost indicates, this is a bug. Note: it works with `1.4.9` too.

**Comment by xbaun** [comment]
I updated the version in the bug description.

**Comment by smashercosmo** [comment]
Hm... I think I also stumbled upon this bug, but for me the last working version is 1.4.6

**Comment by dai-shi** [comment]
Are you sure? That sounds like a different bug. Thanks for reporting anyway.
I'm currently working hard on issue.

**Comment by smashercosmo** [comment]
Yeah, maybe different bug, but same behaviour: updated atom value is not reflected in a component. Works in 1.4.6, doesn't work in all other versions > 1.4.6. I'll try to create reproduction sandbox.

**Comment by xbaun-mms** [comment]
Couldn't test it with my application because it breaks currently because of #967. But as far es I can see it, the test is working and increasing delays also works perfectly.

**Comment by dai-shi** [comment]
https://ci.codesandbox.io/status/pmndrs/jotai/pr/960/builds/208261 is new build.

**Comment by dai-shi** [comment]
> doesn't fix

**Comment by dai-shi** [comment]
#960 should fix this.
Please try: https://ci.codesandbox.io/status/pmndrs/jotai/pr/960
