### ISSUE TITLE
[Next.js @ jotai 1.5.1] `atomWithStorage` : localStorage is not defined 

### ISSUE THREAD

**Issue by comingAlive** [pmndrs/jotai#949]
```
import { useAtom } from "jotai";
import { atomWithStorage } from "jotai/utils";

const counterAtom = atomWithStorage("counter", 0);

export default function HomePage() {
  const [c] = useAtom(counterAtom);
  return <div>{c}</div>;
}
```

<=1.5.0 working as expected.

**Comment by dai-shi** [comment]
Oops! Will make a fix soon. Thanks for reporting.

**Comment by dai-shi** [comment]
Can you try #951 to see if it really fixes the issue?
https://ci.codesandbox.io/status/pmndrs/jotai/pr/951
☝️ See "Local Install Instructions"

**Comment by comingAlive** [comment]
It does. Amazing library btw :) Thank you for your work.

**Comment by dai-shi** [comment]
https://github.com/pmndrs/jotai/releases/tag/v1.5.2 is released with the fix.
