### ISSUE TITLE
can't find variable: localstorage in react native

### ISSUE THREAD

**Issue by Stackerr** [pmndrs/jotai#953]
hello, my project run by jotai.
a few days ago, we got an error about below message.

![image](https://user-images.githubusercontent.com/16572803/149069370-01e33c30-1229-4c88-9517-d3ea1e8c2745.png)
how can we do for deal with this error?
we ran react-native by 0.64.1

**Comment by sandren** [comment]
This is a bug in v1.5.1 as reported [here](https://github.com/pmndrs/jotai/issues/949#issue-1098775854).

If you could, please downgrade to v1.5.0 until the next release is issued. 🙂

**Comment by Stackerr** [comment]
![image](https://user-images.githubusercontent.com/16572803/149088350-34fbea5c-a099-41a3-ac7d-4b449201ad5f.png)

i downgraded jotai module, but localstorage error happend. 
why occur an error above images? 

it seems like to happen an error on jotai/utils. 
please check this

and always thank you for support this

**Comment by dai-shi** [comment]
Sorry for the inconvenience.
Published a new release: https://github.com/pmndrs/jotai/releases/tag/v1.5.2

**Comment by dai-shi** [comment]
Oops, this looks like a different issue.

**Comment by dai-shi** [comment]
My bad. It is fixed.

**Comment by Stackerr** [comment]
thank you this issue is fixed
