### ISSUE TITLE
Prevent suspending atomWithQuery when keepPreviousData is true

### ISSUE THREAD

**Issue by alexski-perry** [pmndrs/jotai#957]
I think this has been brought up before in #374, but it seems that setting `keepPreviousData` to true on `atomWithQuery` doesn't prevent suspending, which I believe should be the intended behaviour. 

For instance in [this example](https://codesandbox.io/s/atomwithquery-keeppreviousdata-yowuv), whenever the query key changes, the list jumps to and from the loading state. I don't think this should be the case with `keepPreviousData` set to true.

**Comment by dai-shi** [comment]
Sounds reasonable. It can suspend at the first time, right?

Hope @aulneau comes up with a solution.

**Comment by alexski-perry** [comment]
Yes it should suspend the first time, unless `initialData` is set or initial data is supplied using `queryClient.setQueryData` or `queryClient.prefetchQuery`.

**Comment by TwistedMinda** [comment]
@alexski-perry It feels like your example works just great!
It's actually an impressive demo of how lovely react-query is :p 

Simple workflow that shows it works:
- type "red" (it will load)
- erase everything
- type "red" again (it will not load)

and just to be sure, repeat with another color.
Maybe I missed something?

**Comment by TwistedMinda** [comment]
@alexski-perry Oh, yes indeed, my bad! Thanks for the explanation
I don't know how I came up with that interpretation. Because what I was describing (your 1st example's behaviour) is actually the exact behaviour of just "suspend: true"

Thanks for the demo!
