### ISSUE TITLE
[docs] wrong variable used in doc, https://jotai.org/docs/integrations/immer#atom-with-immer 

### ISSUE THREAD

**Issue by lgh06** [pmndrs/jotai#962]
It seems that, the `setCountAtom` should be corrected to `countAtom`,  or line 27 should add something else ? I am not sure.

Doc site: https://jotai.org/docs/integrations/immer#atom-with-immer 
Source:  https://github.com/pmndrs/jotai/blame/49c7b813cceac5eab4d208f7f710c598bc834bd9/docs/integrations/immer.mdx#L34

**Comment by dai-shi** [comment]
seems like a bug in docs. should be `countAtom`. would you like to send a PR?

**Comment by lgh06** [comment]
I will try today.
