### ISSUE TITLE
freezeAtom usage is unclear

### ISSUE THREAD

**Issue by LuckyPigeon** [pmndrs/jotai#963]
## Description

I use `freezeAtom` & `freezeAtomCreator` with `useAtom` , and set the new value to test if it can change. And it did change! Does I understand it wrong? Or does `freezeAtom` not work well?

## Reproduce the bug

```typescript
import { atom, useAtom, Provider } from 'jotai'
import { freezeAtom } from 'jotai/utils'

const countAtom = atom({count:0});

const Increment = () => {
  const freezeCount = freezeAtom(countAtom);
  const [freezeObj, setFreezeObj] = useAtom(freezeCount);
  const inc = () => setFreezeObj({
    ...freezeObj,
    count: freezeObj.count+1
  });
  return (
    <div>
      <button onClick={inc}>+1</button>
      count: {freezeObj.count}
    </div>
  )
}

export default function App() {
  return (
    <Provider>
      <div className="App">
        <Increment />
      </div>
    </Provider>
  );
}
``` 

## Log 

Should be 0
![image](https://user-images.githubusercontent.com/32315294/149557228-0d3566fd-cade-4b89-a221-631994f16d51.png)

**Comment by dai-shi** [comment]
```js
  {
    ...freezeObj,
    count: freezeObj.count+1
  }
```
☝️ That is a valid usage. What `freezeAtom` prevents is this usage. 👇 
```js
  freezeObj.count++
```

**Comment by LuckyPigeon** [comment]
Thanks for the explanation!

**Comment by dai-shi** [comment]
Doesn't `freezeObj.count++` prevent to update the count property value?
There's no magic behind its usage, if you want to freeze atom value (object), this is the tool.

I think I heard that recoil freezes everything. jotai does it selectively by developers.

**Comment by dai-shi** [comment]
By the way, I hope after this discussion, we have ideas to improve docs.

**Comment by LuckyPigeon** [comment]
`freezeObj` works well and prevent user from directly mutating objects. And I found the main reason cause my confusion. When a `freezeAtom` being used, then the `baseAtom` will also be frozen!

**Comment by dai-shi** [comment]
`freezeObj` doesn't (deep-)copy objects. It behaves unexpectedly if we copy. BUT, now I understand this is confusing.

**Comment by LuckyPigeon** [comment]
And I think we can improved docs by examples with three points mentioned.

1. `freezeAtom` will be activated by `useAtom` or `get` utility in other `atom`s
2. When a `freezeAtom` being activated, `baseAtom` will be frozen as well.
3. Developers can still mutate object by using `updateValue` utility in `useAtom` or `set` utility in other `atom`s.

**Comment by dai-shi** [comment]
(And I hope you can work on docs. 😄 )

**Comment by LuckyPigeon** [comment]
Sure! Working on it!

**Comment by LuckyPigeon** [comment]
@dai-shi 
Is it a good idea to add a feature like `freezeAtom(initValue, atomFn)` or `atom(read, write, type)`? An utility function that can provide freeze atom every time, create a state safe environment, if developer wishes.

**Comment by LuckyPigeon** [comment]
For example,
```typescript
const anAtom = freezeAtom(0, atom);
// or
const storageAtom = freezeAtom({'darkmode': true}, atomWithStorage);
// or
const freezeBaseAtom = atom(read, write, type="freeze");
```

**Comment by dai-shi** [comment]
> `freezeAtom(initValue, atomFn)`

It's what `freezeAtomCreator` is trying to solve. We don't know if `atomFn` requires `initialValue`.
There might be some better ways, so suggestions are welcome.

> or `atom(read, write, type)`?

I'm strongly against changing the core. All these things should be add-on features.

**Comment by LuckyPigeon** [comment]
We can check if `initialValue` is an object type or non-object type or none type, then decide to assign value or not.
This can save lots of lines.
At least, add it in [Custom useAtom Hooks](https://jotai.org/docs/advanced-recipes/custom-useatom-hooks) might help.

**Comment by dai-shi** [comment]
Note that `freezeAtomCreator` works for non-object values as no-op.

**Comment by Aslemammad** [comment]
This issue helped improve the docs, so the goal was met and the docs are less unclear after this issue! let's close it! Feel free to re-open it!
