### ISSUE TITLE
"useAtomsDevtools/useAtomsSnapshot can only be used in dev mode" error in CRA v5

### ISSUE THREAD

**Issue by TimoWilhelm** [pmndrs/jotai#965]
Awesome Project!

When trying to use `useAtomsDevtools` in my application right now with a basic create-react-app boilerplate (react-scripts 5.0.0) I'm getting the following error:
```
Uncaught Error: useAtomsSnapshot can only be used in dev mode.
    at useAtomsDevtools (devtools.js:148:1)
    at AtomsDevtools (index.tsx:13:1)
```

The single atom `useAtomDevtools` works without any issues and I'm able to see the values in the redux dev tools.

I cannot reproduce this on codesandbox, so I assumed I had some wrong environment variables, but I made sure I'm not running in production mode and all other debugging feature in react dev tools work correctly.

I'm using atoms providerless. My setup is Win 11 Node v16.13.1.

Do you have any idea what might be going wrong?

**Comment by dai-shi** [comment]
Hmm, maybe CRA v5 doesn't set `process.env.NODE_ENV`?
Ah, they probably have it, but not `process`.
Now, this is complicated... Thanks for reporting.
Meanwhile, would you try if CRA v4 works at least?

**Comment by TimoWilhelm** [comment]
It does indeed seem to work with react-scripts@4.0.3. I'm currently stuck on v5 for webpack 5 compatability. It's not a dealbreaker, just something that would be nice to have.

**Comment by dai-shi** [comment]
Sure. We will do that. This requires quite a bit of work, so expect to take some time.

If we have `process` defined as object, it should work. Like in webpack 5:
```js
  plugins: [
    new webpack.DefinePlugin({
      'process': JSON.stringify({}),
      'process.env.NODE_ENV': JSON.stringify('development'),
    }),
  ],
```

**Comment by dai-shi** [comment]
#968 is to address this issue.

**Comment by dai-shi** [comment]
Please try #968 build:
https://ci.codesandbox.io/status/pmndrs/jotai/pr/968
Find "Local Install Instructions" ☝️

**Comment by TimoWilhelm** [comment]
I tried the [#968](https://github.com/pmndrs/jotai/pull/968) build and it seems to be wroking as expected 👍 I was able to use the Redux devtools and got no errors  in the console.

**Comment by dai-shi** [comment]
Cool. There's no ETA, but we hope to have it in the next minor release.

**Comment by dai-shi** [comment]
btw, the error message is not correct...
It should be: "useAtomsDevtools can only be used in dev mode"

**Comment by violabg** [comment]
I have tested #968 and is working, could you release so we can use it on the current version.

**Comment by dai-shi** [comment]
It will be v1.6.0, but there are some tasks moving forward and it still takes some time.
Meanwhile, please keep using #968 build.

**Comment by challengy1** [comment]
This is just a comment. When I made my test environment with 'Vite' instead of Create-React-App 5, I faced the same issue mentioned by Mr. TimoWilhelm. As you may know, Vite does not use Webpack. It uses ESBuild inside. I hope you can take this finding into consideration.

**Comment by dai-shi** [comment]
Our hope is that #968 improves the vite DX.
Would you help on it? I'm not sure how to let vite use ESM build instead of CJS.

**Comment by challengy1** [comment]
I wonder if I can contribute but I would like to do my best. I will look around to seek where I can start from. Would you let me know which module provide environment variable for compiler ?

**Comment by dai-shi** [comment]
If you build code:
```bash
git clone https://github.com/pmndrs/jotai.git
cd jotai
git switch feat/build/env
yarn
yarn build
```

There's `dist` directory.
For example, `dist/index.js` is CJS and `dist/esm/index.js` is ESM.

CJS uses `NODE_ENV`:
```bash
$ grep NODE_ENV dist/index.js | head -1
  if (process.env.NODE_ENV !== "production") {
```

ESM uses `import.meta`:
```bash
$ grep import.meta dist/esm/index.js | head -1
  if ((import.meta.env && import.meta.env.MODE) !== "production") {
```

This `import.meta.env.MODE` is vite's convention. So, I want vite to use ESM instead of CJS. But, it seems like vite picks CJS at the moment.

**Comment by challengy1** [comment]
I will try to find some time tomorrow. Thanks for you swift action.

**Comment by challengy1** [comment]
I would like to share some findings I obtained so far. (before digging into the way you mentioned.)
The version of the jotai with which I made some experiments was 1.5.3 available in npm.
I put some console.log lines as follows:

```
function App() {
  const [count, setCount] = useAtom(countAtom);
  const handler = () => {
    setCount(() => count + 1);
  };
  console.log('MODE: ' + import.meta.env.MODE);
  console.log('DEV:  ' + import.meta.env.DEV);
  console.log('PROD: ' + import.meta.env.PROD);
  const checkEnv1 = import.meta.env && import.meta.env.MODE !== 'production';
  console.log('CHECH: ' + checkEnv1);
  return (
    <AtomsDevtools>
      <div>
        <button onClick={handler}>INCREMENT</button>
        <h1>{count}</h1>
      </div>
    </AtomsDevtools>
  );
}
```
and the result was as follows...
```
[vite] connecting...
client.ts:52 [vite] connected.
App.tsx:17 MODE: development
App.tsx:18 DEV:  true
App.tsx:19 PROD: false
App.tsx:21 CHECH: true
```
From this result, it seems to me vite uses ESM instead of CJS.

In Jotai 1.5.3, node_modules/jotai/**esm**/index.js checks environment as follows:
```
if (typeof process === "object" && process.env.NODE_ENV !== "production" && process.env.NODE_ENV !== "test") {
    useDebugState(scopeContainerRef.current);
  }
```
This will be changed as you modified recently as follows:
```
if ((import.meta.env && import.meta.env.MODE) !== "production") {
    stateListeners = /* @__PURE__ */ new Set();
    mountedAtoms = /* @__PURE__ */ new Set();
  }
```

BTW, it might be as follows, though...
```
import.meta.env && ( import.meta.env.MODE !== "production")
```
instead of
```
(import.meta.env && import.meta.env.MODE) !== "production"
```
This is just a minor thing.

I will dig into it a bit more with the latest status I have just cloned.

Have a nice day.

BR,
Challengy1

**Comment by dai-shi** [comment]
Thanks for investigating!

> From this result, it seems to me vite uses ESM instead of CJS.

Okay, maybe it's my misunderstanding. vite uses ESM correctly then.

I just need someone to confirm #968 work as expected (=import.meta.env.MODE works in vite).
https://ci.codesandbox.io/status/pmndrs/jotai/pr/968

> (import.meta.env && import.meta.env.MODE) !== "production"

This is intentional. if `env` is undefined, we assume it's development mode.

**Comment by dai-shi** [comment]
> I just need someone to confirm https://github.com/pmndrs/jotai/pull/968 work as expected

confirmed.

**Comment by challengy1** [comment]
Thank you so much for your swift action. I have just confirmed Jotai 1.6 useAtomsDevtools does work on the React environment created with Vite.
