### ISSUE TITLE
Confusion regarding the setter function for atoms; expected `set` to receive the atom's `Value` type instead of its `Update` type

### ISSUE THREAD

**Issue by geoyws** [pmndrs/jotai#97]
Hi everyone, really appreciate the work done on jotai.

I've been spending hours today trying to understand why `set` wouldn't accept my atom's `Value` type but instead accepts the `Update` type. Codesandbox [here](https://codesandbox.io/s/react-typescript-forked-reijr?file=/src/App.tsx).

Can anyone enlighten me?

```TypeScript
import { atom } from "jotai";

export interface Person {
  name: string;
  age: number;
}

export interface Action<T> {
  type: string;
  payload: T;
}

export const personAtom = atom<Person, Action<any>>(
  () => ({
    name: "Joe",
    age: 55
  }),
  (get, set, update) => {
    const newPerson = {
      name: "Jon",
      age: 65,
      [update.type]: update.payload
    };
    set(personAtom, newPerson);
    //              ~~~~~~~~~
    // TypeScript error here ^
    // but why am I setting personAtom with an update value?
    // shouldn't it be the real value? i.e. Person?
  }
);
```

**Comment by merisbahti** [comment]
There's an utility called `atomWithReducer` that would be helpful here....

See here:
```typescript
import { atomWithReducer } from "jotai/utils";

export interface Person {
  name: string;
  age: number;
}

export type Action<key extends keyof Person> = {
  type: key;
  payload: Person[key];
};

export const personAtom = atomWithReducer<Person, Action<"name" | "age">>(
  {
    name: "Joe",
    age: 55
  },
  (state, action: Action<"name" | "age">) => ({
    ...state,
    [action.type]: action.payload
  })
);
``` 
https://codesandbox.io/s/react-typescript-forked-yg70b?file=/src/App.tsx:0-414

I'd suggest that route, or maybe inspect the type declaration for `atomWithReducer`.

**Comment by dai-shi** [comment]
Yeah, it's called something like context sensitive functions, and it's the behavior of typescript. It can't be helped.

If you split atoms, it should work as you expect.
```js
const primitivePersonAtom = atom<Person>(
  {
    name: "Joe",
    age: 55
  }
);

export const personAtom = atom<Person, Action<any>>(
  (get) => get(primitivePersonAtom),
  (get, set, update) => {
    const newPerson = {
      name: "Jon",
      age: 65,
      [update.type]: update.payload
    };
    set(primitivePersonAtom, newPerson);
  }
);
```

Or, use `atomWithReducer` as @merisbahti suggested. (Thanks!)

**Comment by geoyws** [comment]
Thanks @dai-shi !

@merisbahti Unfortunately `atomWithReducer` doesn't grant me access to `get` and `set` :(

**Comment by dai-shi** [comment]
`atomWithReducer` should work fine if it's working with just one atom.

Please let us know how you solve it anyway. 💪

**Comment by dai-shi** [comment]
Closing this. Feel free to reopen for further discussion.
