### ISSUE TITLE
Feature request for atomWithBroadcast util

### ISSUE THREAD

**Issue by thachp** [pmndrs/jotai#982]
A  way to share atoms between browser tabs and frames, similar to atomWithStorage.

See https://github.com/pubkey/broadcast-channel 
and  https://hookstate.js.org/docs/extensions-broadcasted.

```javascript
import { useAtom } from 'jotai'
import { atomWithBroadcast } from 'jotai/utils'

const darkModeAtom = atomWithBroadcast ('darkMode', false)

const Page = () => {
  const [darkMode, setDarkMode] = useAtom(darkModeAtom)

  return (
    <>
      <h1>Welcome to {darkMode ? 'dark' : 'light'} mode!</h1>
      <button onClick={() => setDarkMode(!darkMode)}>toggle theme</button>
    </>
  )
}
```

**Comment by dai-shi** [comment]
This works without localStorage (or any other storage), right?
Then, we can't implement on top of atomWithStorage. It would be a new util.

I wonder if this should be in `jotai/utils` or in a third-party library. Maybe, an advanced recipe would fit well based on `broadcast-channel` (instead of native method).

---
Implementation-wise, I also wonder how we could pull the initial value. 🤔

**Comment by dai-shi** [comment]
Would anyone be interested in creating an advanced recipe for a start?

**Comment by dryrainbow** [comment]
Hello, I'm interested in implementing it, or just in writing an example in documentation with the recipe for using library with broadcast-channel

**Comment by dai-shi** [comment]
@dryrainbow Why won't you try creating a codesandbox example and an advanced recipe in docs? Happy to review.

**Comment by dai-shi** [comment]
Note that we already have a plan to add sync feature in for localStorage #882. For IndexDB, we could do the same with `atomWithStorage`.
What's not possible with `atomWithStorage` is pure BroadcastChannel without storage.

**Comment by dai-shi** [comment]
Now #1004 is merged and released, what's remaining is `atomWithBroadcast` (with native method or boradcast-channel library) to be in "advanced-recipes" in docs. Would anyone be interested?

**Comment by dai-shi** [comment]
wip #1111

**Comment by dai-shi** [comment]
#1111 is merged.
