### ISSUE TITLE
[docs] put simplified core code in docs

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#983]
Looks like people like them:
https://twitter.com/dai_shi/status/1484835169475653634
https://twitter.com/dai_shi/status/1485434083778117632

Maybe we put them in docs somehow?

## First one

<img width="300" alt="How Jotai Works" src="https://user-images.githubusercontent.com/490574/150774272-4cdb2b5c-6021-43e1-9efd-6e0e182e9273.png">

https://codesandbox.io/s/zealous-field-z2xk6?file=/src/App.js

## Second one

<img width="300" alt="How Jotai Works (long version)" src="https://user-images.githubusercontent.com/490574/150774368-55980398-ac47-47b7-8ead-7e13fa60d259.png">

https://codesandbox.io/s/affectionate-chandrasekhar-nuxms?file=/src/App.js

**Comment by AjaxSolutions** [comment]
Is the simplified core code intended just for learning how Jotai works or could it be used in production?

**Comment by astahmer** [comment]
I don't know if that's the right place to ask but if this kind of tweets gets in the docs, maybe some of these could be integrated (or mentionned ?) too ?

jotai diagrams:
https://twitter.com/dai_shi/status/1384532412521009168

jotai comparisons with valtio/zustand:
https://twitter.com/dai_shi/status/1381252474682535938

Decision Tree to Choose a Global State Library
https://twitter.com/dai_shi/status/1348257768130560008

zustand vs. jotai:
https://twitter.com/dai_shi/status/1372909917011542027
https://twitter.com/dai_shi/status/1477593623156105217

internal weakmap implementation animation diagram:
https://twitter.com/dai_shi/status/1346770792797802496

`jotai-jsx`
https://github.com/dai-shi/jotai-jsx
https://twitter.com/dai_shi/status/1421676705106718725
https://twitter.com/dai_shi/status/1412790409646903301

benchmark vs recoil
https://twitter.com/dai_shi/status/1480083292884172801

converting from recoil + example with r3f
https://twitter.com/dai_shi/status/1477430821900648449

`jotai-game` 
https://github.com/dai-shi/jotai-game
https://twitter.com/dai_shi/status/1483825915813855239
https://twitter.com/dai_shi/status/1483992971121143809

react memo approach using jotai
https://twitter.com/dai_shi/status/1468875799327817730

7GUIs challenge
https://twitter.com/dai_shi/status/1433804219828490241

**Comment by dai-shi** [comment]
@AjaxSolutions

> Is the simplified core code intended just for learning how Jotai works or could it be used in production?

It's intended for learning purpose, but I made it properly as much as possible, so if the implemented feature is enough, it can probably be used for real use cases.

**Comment by dai-shi** [comment]
@astahmer



> I don't know if that's the right place to ask but if this kind of tweets gets in the docs, maybe some of these could be integrated (or mentionned ?) too ?

Wow, you collected them well. I'm happy to see if someone works on organizing them and open a PR for docs. (maybe links with small notes work?)
