### ISSUE TITLE
Infered types when using useHydrateAtoms

### ISSUE THREAD

**Issue by yemi** [pmndrs/jotai#990]
Hi,

Thanks for creating this elegant way of managing state, it's opened so many architectural doors for us to explore!

**Goal**
It would be really nice if the atoms passed to `useHydrateAtoms` could have their types inferred and checked against.

**Current situation**
This will compile perfectly fine:
```js
const volumeAtom = atom(100);
useHydrateAtoms([[volumeAtom, 'not-an-integer']]);
```

**Question**
Is it possible to infer the type of the atoms provided to `useHydrateAtoms`?

**Comment by dai-shi** [comment]
I thought about the issue when introducing `initialValues` prop in `Provider`. `useHydrateAtoms` takes the same signature from it.

Now, the solution I have in mind is instead of supporting it in the API, we use a helper function.

Something like this:
```js
const atomValues = new Map()
const setAtomValue = <Value>(anAtom: Atom<Value>, value: Value) => {
  atomValues.set(anAtom, value)
}
```

**Comment by yemi** [comment]
What if there's multiple atoms, would it be possible to use typescript's tuple-types in order to get the types then?

**Comment by yemi** [comment]
Initially I was thinking that typescript tuple-types could be a potential solution, but when playing with them I realized that they wouldn't support generic members, i.e. [Atom<Value>, Value] so that wouldn't work, your solution did work, thank you!
