### ISSUE TITLE
LocalStorage not defined - React Native

### ISSUE THREAD

**Issue by tomyates** [pmndrs/jotai#994]
Hi,
I'm using version v1.5.3, but in React Native I'm still getting an error about local storage:

```
import {AsyncStorage} from '@react-native-async-storage/async-storage';
import {atomWithStorage} from 'jotai/utils';

export const emailStrAtom = atomWithStorage('string', undefined, AsyncStorage);
```

Error:

<img width="300" alt="Screenshot 2022-02-01 at 12 00 24" src="https://user-images.githubusercontent.com/785769/151964865-088682e7-ddae-4e76-aa2e-0097f0844786.png">

Any idea what I'm doing wrong?
Thank you.

**Comment by dai-shi** [comment]
Hmm, I wonder if anybody has experienced this in previous versions.
Not sure how it's happening. Would you be able to try if this reproduces in Expo Snack?
Thanks for reporting.

**Comment by tomyates** [comment]
Hi, 
I fixed this, I was an idiot. User error.
Import should have been:

`import AsyncStorage from '@react-native-async-storage/async-storage'
