### ISSUE TITLE
Support Generic Arguments in atomFamily

### ISSUE THREAD

**Issue by seanaye** [pmndrs/jotai#997]
I am trying to return slightly different types for atomFamily based on the parameter given as the id as follows

```ts
export enum Registry {
  EditableOnKeyDown = "editable-on-keydown",
  EditorOnChange = "editor-on-change",
  ChangedNodes = "changed-nodes",
}

type Signature = {
  [Registry.ChangedNodes]: Generator<NodeEntry<Text>>;
  [Registry.EditableOnKeyDown]: KeyboardEvent<HTMLDivElement>;
  [Registry.EditorOnChange]: Array<Descendant>;
};

type EventType<T extends Registry> = T extends keyof Signature
  ? Signature[T]
  : never;

export const registryFamily = atomFamily(function <T extends Registry>(registryId: T): Atom<MiddlewareRegistry<EventType<T>>> {
  const registry = new MiddlewareRegistry<EventType<T>>(
    // cleanup function for when the registry becomes emptied
    () => {
      registryFamily.remove(registryId);
    }
  );

  return atom(registry);
});

const a = registryFamily(Registry.EditableOnKeyDown)

```
This gives

<img width="2253" alt="Screen Shot 2022-02-04 at 2 58 46 PM" src="https://user-images.githubusercontent.com/24496822/152595064-f262c21d-c069-4bc9-b5f6-12c436454777.png">

It appears that atomFamily does not support the generic constraint for initializing. It would be great if this was possible

**Comment by dai-shi** [comment]
Hmm, I don't think it's even possible, because `registoryFamily` has to be a concrete type.

CodeSandbox: https://codesandbox.io/s/compassionate-frog-npg8q?file=/src/App.tsx

**Comment by seanaye** [comment]
If the constructor function is split out then there is no issue with the types when making a single atom. It is only when wrapped within the atom family that there is a type error

https://codesandbox.io/s/distracted-carson-24por?file=/src/App.tsx:774-841

**Comment by dai-shi** [comment]
Ah, so you don't mean to make `registryFamily` generic, but just resolve the type error with `atomFamily(makeRegistry)`?

A workaround would be this:
```ts
export const registryFamilyAlternative = atomFamily((registryId: Registry) => makeRegistry(registryId));
```
I don't know if there's a better solution.

**Comment by seanaye** [comment]
Ideally `registryFamily` would be generic and would work with type constraints. If this not possible then we can close the issue

**Comment by dai-shi** [comment]
oops, my misunderstanding.

okay, I'm not sure if `registerFamily` can be generic because it's not just a function.

It has a following type:
https://github.com/pmndrs/jotai/blob/fb3f906e010cc469019fe3da8102b4a58a1fc1c2/src/utils/atomFamily.ts#L5-L9

So, what you could work around is to assert types:
```ts
export const registryFamilyOrig = atomFamily(makeRegistry as any) as {
  <T extends Registry>(param: T): Atom<MiddlewareRegistry<EventType<T>>>
  remove<T extends Registry>(param: T): void
  setShouldRemove<T extends Registry>(shouldRemove: ((createdAt: number, param: T) => boolean) | null): void
};
```

hm, does it  work if we have a wrapper function? needs TS wizard.

**Comment by seanaye** [comment]
This is a great workaround. Thank you!

**Comment by TwistedMinda** [comment]
@seanaye Can you confirm that your issue is resolved? By marking the accepted answer if that's the case.
Or maybe you guys are waiting for a TS wizard to come to the rescue ?

@dai-shi Should something like this be documented in a "Atom Family" subsection of the main Typescript section (kinda basic at the moment) ?
I'm not sure I understood well the use-case tho, may need more explanation if you want me to doc it.

**Comment by dai-shi** [comment]
> maybe you guys are waiting for a TS wizard to come to the rescue ?

Yeah, that's correct. However, I feel like closing this, because even if we have a solution, I expect it will be hacky.

> Should something like this be documented

I don't think this is typical/recommended usage, so no idea to document it at this moment.
